### ISSUE TITLE
Feature request: Mylar

### ISSUE THREAD

**Issue by Hellowlol** [Hellowlol/HTPC-Manager#10]
blindpet commented a day ago

Gotcha, just needed to do a refresh and it works now. Any plans for Mylar or Headphones support?

**Comment by Hellowlol** [comment]
@blindpet I'm gonna finish the open pr regarding headphones. I have no eta.

**Comment by edru** [comment]
Commenting because I would like Mylar support added.

Posted this on reddit.com/r/usenet and a couple people upvoted wanting Mylar as well.

http://www.reddit.com/r/usenet/comments/2vgtta/htpcmanager_w_sonarr_sickrage_and_headphones/

**Comment by Hellowlol** [comment]
So that might be the reason why unique visitors/clones have sky rocketed.. Thanks, kinda forcing my hand here.. :p

**Comment by edru** [comment]
Wasnt trying that all. Only 4 people actually upvoted Mylar, so not too many of us.

**Comment by Hellowlol** [comment]
I was just kidding. I'll keep it in mind.

**Comment by Hellowlol** [comment]
Accecpted @edru @blindpet no ETA tho

**Comment by edru** [comment]
nice! thanks!

**Comment by Hellowlol** [comment]
https://github.com/Hellowlol/HTPC-Manager/tree/mylar It's just a initial commit, not working at all :p

**Comment by Hellowlol** [comment]
This is gonna take some longer time as there are bugs in mylar api

**Comment by edru** [comment]
Thanks for giving it a go!

**Comment by Hellowlol** [comment]
I'm really sorry for being so slow, according to Mylar api docs stuff there are some api commands di t don't even exist. My plan was to do the last push and merge yesterday, but I have to fix more stuff in the api first

**Comment by edru** [comment]
Ahh no worries man. Cant really build something if what you need to build
on top of is broken.

**Comment by KaHooli** [comment]
+1 for Mylar support, but understand the issues you are having with this.

**Comment by Hellowlol** [comment]
I dont think im gonna do any thing to the api,. Ill rather just clean it up and merged it as it is.

**Comment by Hellowlol** [comment]
@edru @KaHooli  @blindpet I just added mylar, it hasnt been teste that much so let me know if there are any bugs.

**Comment by Hellowlol** [comment]
I just remember that some of the api calls that i have used does not exist in the in mylar atm, Ill send a pr regarding that tomorrow.

**Comment by Hellowlol** [comment]
You can us this branch until it gets merged: https://github.com/Hellowlol/mylar/tree/missingapistuff

**Comment by blindpet** [comment]
Which features are in this repo?

Best,

Mike Andreasen

Psychology MA, MSc

**Comment by Hellowlol** [comment]
Nothing spesial, just added some to Mylar app to make it usable with htpc manager.

**Comment by Hellowlol** [comment]
Gonna reopen this until the required changed as merged in Mylar.

**Comment by Hellowlol** [comment]
@edru @KaHooli @blindpet My pr has been merged in both the development and master branch. Please use one of those.

**Comment by 40wattrange** [comment]
From the actual true mylar source?

**Comment by Hellowlol** [comment]
yeah
