### ISSUE TITLE
Change order of "other apps"

### ISSUE THREAD

**Issue by kooimens** [Hellowlol/HTPC-Manager#100]
This would be useful as almost everything is changeable now, except for these links. If it's too hard to build it the way the menu order is built, a field to number each custom app link could be an option (like the maraschino project did).

**Comment by wmariz** [comment]
It's easy to code it, but I don't know how to make this work well on the interface.

Any ideas?

**Comment by Hellowlol** [comment]
What about if the list is just sortable and on save its serialized to the db? So in the settings page?

**Comment by wmariz** [comment]
You mean changing the order on settings page only? I think it's ok, but is not integrated as the others.

**Comment by Hellowlol** [comment]
I agree, but I couldn't find a better place to do it.

**Comment by wmariz** [comment]
https://github.com/Hellowlol/HTPC-Manager/pull/102
