### ISSUE TITLE
CouchPotato takes a long time to load

### ISSUE THREAD

**Issue by thejrose1984** [Hellowlol/HTPC-Manager#103]
The other modules load almost instantly, but CouchPotato takes a while. Not sure if it has to do with the fact there's a large library (doubtful because then Plex would also take a long time to load). Checked the logs and didn't find any messages.

**Comment by Hellowlol** [comment]
The entire js is one large hack so I don't know if I can get it any better without rewriting the entire thing. That isn't likely. How long did it take?

**Comment by madclicker** [comment]
All the js is just a hack job. I rewriting now and seeing significant speed and stability increases.

**Comment by Hellowlol** [comment]
Using js or your static vars?

**Comment by madclicker** [comment]
Static html. I'm also restructuring that. Just because js can create html on the fly doesn't make it the right way to do it.

I even remember @styxit mentioning it.

**Comment by styxit** [comment]
True, i wanted to use some js templating like [handlebarsjs](http://handlebarsjs.com)

**Comment by Hellowlol** [comment]
Well I don't like your static vars I'll rather have slow or atleast use mako. Handlebars has similar syntax.

Imo the best solution would be to split monster js so you can get rid of the duck typing

**Comment by thejrose1984** [comment]
@Hellowlol anywhere from 30 seconds to a minute and can sometimes crash the browser

**Comment by Hellowlol** [comment]
How many movies? Is it difference between the browsers?

**Comment by thejrose1984** [comment]
1000+
Tried in Chrome and Native browser on my Galaxy S5 - same response time
Also tried Chrome and Firefox from Mac OS X

**Comment by Hellowlol** [comment]
Ok, seems strange. I'm gonna double check my movies number later. I'm not sure if all of them are in cp. btw can you check the devolopment checkbox inside cp and see if it gets better?

**Comment by Hellowlol** [comment]
- [ ] limit load

**Comment by thejrose1984** [comment]
What do you mean @Hellowlol ?

**Comment by Hellowlol** [comment]
I mean limit how many items are loaded. Like kodi and plex has.

The easiest way to speed up the cp module is not not have a manager folder setup in cp. 

Say you have 50 wanted and 1000 in your library the co module will try to fetch 1050 images...

**Comment by thejrose1984** [comment]
Okay, but to play devil's advocate here...why doesn't CouchPotato load items the same way Plex does in HTPC-Manager? I know if I go through CP directly, it looks a small chunk at a time so I don't wait for the 1300 some odd items to load all at once...

**Comment by Hellowlol** [comment]
Well you have to ask the original author about that ;) that's why I want to limit it. 

I prefer loading all items at once but as I hate the scrolling but it isn't a other way to really speed this up. Even if I rewrite the js, the images load time will be huge.

**Comment by Hellowlol** [comment]
Just some numbers so i dont forget:
tested from remote location via nginx proxy

xhr done with 352 movies takes 3,5 sec

total requests is 946, total load time is 34 sec (all images etc)

**Comment by Hellowlol** [comment]
Closing this as the js is fast enough.

On the same computer as htpc manager:
985 requests in 5,28 sec with a empty cache (chrome) including every image etc.
