### ISSUE TITLE
Duplication in Plex module / add option to select included libraries

### ISSUE THREAD

**Issue by raysguy** [Hellowlol/HTPC-Manager#104]
In Plex I have a number of libraries set up customised to the viewing preferences of individual users.  There's quite a bit of overlap where libraries include the same shows/movies.  The result is that my Plex module in HTPC-Manager is a mess as it has lots of duplicate items.

It'd be great if there was a way to prevent these duplicates appearing.  I'm guessing the best solution would an option in the Plex settings to select which libraries should be included so that the libraries created for other users can be excluded.  I don't have any coding knowledge myself so I don't know how easy that would be to include, but it would be a great feature if possible.  Thanks.

**Comment by Hellowlol** [comment]
If you just want dupes removed that would be a easy fix. If you want to choose what to exclude I need to start digging in the api, I have no idea what it returns.

**Comment by raysguy** [comment]
Hi, thanks for the quick reply.  I'd be happy just having the dupes removed because at least then I'd be able to see everything I have in one place.

I've got a few small issues I wanted to ask about too please but I'm new to github so I'm not sure if I need to move them to a new issue.  Basically on the Dashboard the "Latest Movies" section loads correctly but the "Latest TV Shows" remains blank (no placeholder or anything), and within the Plex module of Manager the thumbnails for movies/shows are rather low resolution, whereas those in the CouchPotato area are crisp and sharp.  Also the Spaceship theme doesn't load correctly, it just produces a totally unformatted page (tested on Chrome and Safari with same result). Don't know if these are known issues or something specific to me but thought I'd bring them up.  I'm running a fully updated master2 build on OS X 10.10.3, python 2.7.9 if that info helps. 

Thanks for the awesome work you're doing on Manager.  Really great fork you've created here which has let me do away with multiple other management software I was using before.

**Comment by Hellowlol** [comment]
@raysguy Please make a new issue regarding the bug etc. I dont want that mixed up with feature requests.

**Comment by Hellowlol** [comment]
Module in dash:I see that it sometimes complains about a variable that i changed yesterday, that might be the reason. Ill fix this.

Themes: I just added every theme i found as bootstrap 2 is getting old, i have not tested every theme, please add that to the themes issue.

Images: I dont know why there is a diff in quality, the code is the same, ill look into this.

**Comment by Hellowlol** [comment]
@raysguy the dupication should now be fixed, can you update and confirm?

**Comment by raysguy** [comment]
I've updated and duplication is now fixed in the Movies tab within the Plex page, however duplication still exists on the TV tab.

**Comment by Hellowlol** [comment]
Ah crap I only tested movies..

**Comment by Hellowlol** [comment]
Closing this as ignore sections is added.
