### ISSUE TITLE
Request - option to add Search tab to menu bar

### ISSUE THREAD

**Issue by raysguy** [Hellowlol/HTPC-Manager#106]
Hi, I have a small request based on something I just noticed.  I love being able to do a quick search via the search bar, but sometimes I want to be more specific and target certain categories.  I realised there's no way to do this without first performing a search to bring up the search page or manually going to ip:port/search.  I know I could add a custom link to ip:port/search but it would then be buried under the "Other" section.  It'd be awesome if a checkbox could be added within the Newznab settings to toggle a "Search" menu bar item that can be moved and arranged with the others.

I guess an alternative (and possibly cleaner) solution would be if a category dropdown could be added to the search box when a Newznab provider is specified just as it is on the actual search page.  I have no idea how difficult that would be to implement though.

**Comment by Hellowlol** [comment]
This would be major pita as the seach bar is used in a lot of modules not just newznab search.

**Comment by raysguy** [comment]
Ah, I see.  Maybe just adding the option for a Search menubar item would be the simplest route then.

**Comment by Hellowlol** [comment]
Yeah, that's would easy fix

**Comment by raysguy** [comment]
Hi, just tried this after the latest changes but it isn't working for me.  The option to rename it has no effect - just shows as Newznab on the nav bar.  When I click on that link it just takes me to ip:port/nzbsearch/ which shows the "An error has occurred" message.  Nothing in console errors except same one as yesterday which I think you said wasn't related.  Same result in both Safari and Chrome.

**Comment by Hellowlol** [comment]
Yeah, sorry about that it doesn't use the same logic as the rest of the modules.
