### ISSUE TITLE
SSL Error with fork

### ISSUE THREAD

**Issue by JJmax** [Hellowlol/HTPC-Manager#109]
I'm trying to access this awesome fork via SSL and for some reason it will not accept the cert while the main clone does along with CouchPotato and Sonarr as well. The cert was made with directions from Sonarr. I also made new certs via different methods and made different kinds but it was the same result. Any help is appreciated greatly. I really want to use this fork and my searching and attempts have yielded zero results. I'm sure I'm probably doing something wrong, but I've installed every single package I could find too and it didn't help.

The pastebin below is two vanilla clones from the main and the fork. All I did was configure the SSL on each one with the same cert/location and I get the error. If you need anything at all please let me know. Keep up the awesome work!

http://pastebin.com/xi5qJkmc

**Comment by Hellowlol** [comment]
Hi!
Have you tried with the certs that generated for you? 
By enabling ssl and not provide a path for it HTPC manager will make them for you. Does that work? 

What are the cert details?

**Comment by JJmax** [comment]
I saw that function in the code, and read about it, but I didn't see where in the interface I was able to do it. I'm sure I'm being an idiot and missing it cause I've been at it a long time. That would make it a lot easier and would definitely work. 

I just made a cert for my domain at the site the wiki for Sonarr said to go to then get the tumbprint/make a .pfx.

**Comment by Hellowlol** [comment]
Well, I totally get why you didn't know where to do it. :p Try deleting the cert and key and reboot htpc manager

I know nothing about ssl so I have no idea what a pfx is...

**Comment by JJmax** [comment]
I have. I don't see an option. Tried both Firefox and Chrome. Is it under another tab besides general maybe. Screen included

![generaltab](https://cloud.githubusercontent.com/assets/11706293/6886019/ac2004e8-d5fd-11e4-8170-9b387e5fba29.png)

**Comment by Hellowlol** [comment]
Just check use ssl, save then reboot.

**Comment by JJmax** [comment]
Nothing. It's just ticked now. Tried restarting twice and refreshing page.

**Comment by JJmax** [comment]
Is there maybe a dependency I'm missing. I've installed simplejson, psutil, pil, pyopenssl, c++, easy install, and few others I can't think of right now.

**Comment by Hellowlol** [comment]
OpenSSL is needed.

**Comment by JJmax** [comment]
I have it installed for Python. Should I install it for Server 2012 too

**Comment by JJmax** [comment]
Ok well I don't know if it didn't install right or what. I cloned the git and even installed C++ 2008 or whatever it was when it gave an error. 

You bringing up OpenSSL made me want to try a different way using pip -m install and it worked! Thank you so much for your patience and all your help! You're amazing!! I knew I was being an idiot. 

There was still an error, but it connected finally unlike before. It's one of the errors I was receiving before when I was trying with the clone that was configured fully.

Error in HTTPServer.tick
Traceback (most recent call last):
  File "C:\HTPCman\HTPC-Manager-master2\libs\cherrypy\wsgiserver\wsgiserver2.py"
, line 1837, in start
    self.tick()
  File "C:\HTPCman\HTPC-Manager-master2\libs\cherrypy\wsgiserver\wsgiserver2.py"
, line 1902, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "C:\HTPCman\HTPC-Manager-master2\libs\cherrypy\wsgiserver\ssl_builtin.py"
, line 52, in wrap
    keyfile=self.private_key, ssl_version=ssl.PROTOCOL_SSLv23)
  File "C:\Python27\Lib\ssl.py", line 891, in wrap_socket
    ciphers=ciphers)
  File "C:\Python27\Lib\ssl.py", line 566, in __init__
    self.do_handshake()
  File "C:\Python27\Lib\ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:581)

**Comment by Hellowlol** [comment]
check the userdata folder, can you see any .cert and key there? If it is delete them and try again

**Comment by JJmax** [comment]
That did the trick. I really do appreciate it a lot. Thanks for talking it out with me to get it working. You happen to have a BTC address by any chance?

**Comment by Hellowlol** [comment]
I'm happy to help. I'm glad it got sorted out. I'll add some stuff to the wiki.

No, I don't have a btc address but thanks for the consideration.

If you still feel like donating I'm sure kodi, sr, cp, sonarr etc would be happy to take your hard earned $$ off your hands ;)
