### ISSUE TITLE
Search bar doesn't do anything

### ISSUE THREAD

**Issue by thejrose1984** [Hellowlol/HTPC-Manager#111]
![screen shot 2015-03-29 at 8 58 13 pm](https://cloud.githubusercontent.com/assets/7573083/6888794/5e2c085a-d656-11e4-8b97-03dcaf615754.png)

Since I have a fairly large library, it is helpful to search, but noticed that when I try to query something and press the enter key, nothing happens and the logs don't show anything being wrong. Any ideas?

**Comment by Hellowlol** [comment]
Search for what where? Start htpc manager with loglevel debug and post the log.

**Comment by thejrose1984** [comment]
Branch = Master2
Commit hash = N'A; can't find
Your operating system and python version = Mac OS 10.8.5 / Python 2.7
What did you do? Try to search for a movie
What happened? Nothing
What did you expect to happen? Search modules for media based on query input
If its a visual bug, screenshot or it didnt happen!
What browser, including version = Latest version of Google Chrome (happens in all browsers)
Link to a copy/paste of your logfile with clear debug info of the error on PASTEBIN = Log doesn't show any information

**Comment by Hellowlol** [comment]
When your search what module  do you have open?

**Comment by thejrose1984** [comment]
None - at the dashboard

**Comment by Hellowlol** [comment]
Have you set any newznab?

**Comment by Hellowlol** [comment]
Closing this as issue creator hasn't responded.
