### ISSUE TITLE
Plex Controls don't work

### ISSUE THREAD

**Issue by thejrose1984** [Hellowlol/HTPC-Manager#112]
Can't start streaming or control media from connected Plex server. Below is the log entries when I try:

2015-03-29 21:02:37	modules.plex	ERROR	Unable to play + item + on player 192.168.1.10
2015-03-29 21:00:07	modules.plex	ERROR	Unable to control Plex with action: play

Any ideas how to troubleshoot further?

**Comment by Hellowlol** [comment]
What player is there on that computer?

**Comment by thejrose1984** [comment]
You can close this issue for now as I don't focus on the Plex module being a very integral part of my setup. I'll do some more testing later on when I have time.

**Comment by Hellowlol** [comment]
Ok? The controls should work. For some reason I needed to update pms and reboot the computer.

**Comment by thejrose1984** [comment]
Don't forget to I run PMS from FreeNAS which is a few versions behind. Mind you I could update to the latest version, but recent attempts to do so ends up breaking the plugin and/or jail :)

**Comment by Hellowlol** [comment]
Ok, but the commands are sent to pht. Try rebooting that computer.

**Comment by thejrose1984** [comment]
That could be why. Not sure if Plex running from Roku is considered Plex Home Theater or not. That might be why it doesn't work.
