### ISSUE TITLE
Headphones Fails Test

### ISSUE THREAD

**Issue by yungfras** [Hellowlol/HTPC-Manager#115]
I'm checking the log and there is nothing in the log to show why headphones won't sync. I press test and it turns red.

**Comment by Hellowlol** [comment]
Does the module still work? 

Have you started htpc manager with 
 debug as explained in the issue guidelines?

**Comment by yungfras** [comment]
I did this...

How to enable detailed logs

Shutdown HTPC-Manager
Start Htpc.py --loglevel debug (Do NOT start with --debug)
Start HTPC-Manager and wait for error to occure again

**Comment by yungfras** [comment]
I cleared the log and pressed test on Headphones in the settings and this is what i get 


Date
Module
Level
Message
2015-04-01 18:42:18	modules.plex	INFO	GDM: No servers discovered
2015-04-01 18:42:17	modules.plex	INFO	Sending discovery message: M-SEARCH * HTTP/1.0
2015-04-01 18:42:11	modules.plex	INFO	GDM: No servers discovered
2015-04-01 18:42:10	modules.plex	INFO	Sending discovery message: M-SEARCH * HTTP/1.0

**Comment by yungfras** [comment]
I'm closing this. It started working thanks for your quick response and help and thanks for going easy on me as I'm still new to this. Not computers per say but the online lingo in regards to technology.
