### ISSUE TITLE
smartmontools error

### ISSUE THREAD

**Issue by yungfras** [Hellowlol/HTPC-Manager#116]
It keeps saying smart on tools is not installed or smartctl is not in the system path but I can run smartctl from anywhere in cmd prompt. Any ideas?

**Comment by Hellowlol** [comment]
Hi! Please read the issue guidelines next time :) you say nothing about os, Python version ? There is no logs, so this will be guess. This is the checklist for smart:

Have you enabled smart in computer settings?
Is smartmontools installed?
Can you type smartctl Im cmd? 
Have you started htpc manager with administrator privileges?

**Comment by yungfras** [comment]
Python 2.7 OS 8.1 Pro WMC
Smart is installed. I got it from here https://www.smartmontools.org/
I can type smartctl -h in cmd and get the help list.
I have no idea how in enable smart in computer settings and as far as Have you started htpc manager with administrator privileges? Does that mean have I setup a user name and password?

**Comment by yungfras** [comment]
here is what the log says when i try to refresh S.M.A.R.T. from the dashboard:

2015-04-01 19:52:58	cherrypy.error.27892200	ERROR	[01/Apr/2015:19:52:58] HTTP Traceback (most recent call last):
2015-04-01 19:52:40	cherrypy.error.27892200	ERROR	[01/Apr/2015:19:52:40] HTTP Traceback (most recent call last):

**Comment by yungfras** [comment]
and here is the output from GSmart Control:
smartctl 5.43 2012-06-30 r3573 [i686-w64-mingw32-win8(64)] (sf-5.43-1)
Copyright (C) 2002-12 by Bruce Allen, http://smartmontools.sourceforge.net

=== START OF INFORMATION SECTION ===
Model Family:     Western Digital Caviar Blue Serial ATA
Device Model:     WDC WD3200AAJS-65B4A0
Serial Number:    WD-WCAT10723050
LU WWN Device Id: 5 0014ee 100ef07dd
Firmware Version: 01.03A01
User Capacity:    320,072,933,376 bytes [320 GB]
Sector Size:      512 bytes logical/physical
Device is:        In smartctl database [for details use: -P show]
ATA Version is:   8
ATA Standard is:  Exact ATA specification draft version not indicated
Local Time is:    Wed Apr 01 19:58:23 2015 CDT
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

General SMART Values:
Offline data collection status:  (0x84)	Offline data collection activity
					was suspended by an interrupting command from host.
					Auto Offline Data Collection: Enabled.
Self-test execution status:      (   0)	The previous self-test routine completed
					without error or no self-test has ever 
					been run.
Total time to complete Offline 
data collection: 		( 5760) seconds.
Offline data collection
capabilities: 			 (0x7b) SMART execute Offline immediate.
					Auto Offline data collection on/off support.
					Suspend Offline collection upon new
					command.
					Offline surface scan supported.
					Self-test supported.
					Conveyance Self-test supported.
					Selective Self-test supported.
SMART capabilities:            (0x0003)	Saves SMART data before entering
					power-saving mode.
					Supports SMART auto save timer.
Error logging capability:        (0x01)	Error logging supported.
					General Purpose Logging supported.
Short self-test routine 
recommended polling time: 	 (   2) minutes.
Extended self-test routine
recommended polling time: 	 (  70) minutes.
Conveyance self-test routine
recommended polling time: 	 (   5) minutes.
SCT capabilities: 	       (0x303f)	SCT Status supported.
					SCT Error Recovery Control supported.
					SCT Feature Control supported.
					SCT Data Table supported.

SMART Attributes Data Structure revision number: 16
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  1 Raw_Read_Error_Rate     0x002f   200   200   051    Pre-fail  Always       -       0
  3 Spin_Up_Time            0x0027   155   151   021    Pre-fail  Always       -       3216
  4 Start_Stop_Count        0x0032   094   094   000    Old_age   Always       -       6251
  5 Reallocated_Sector_Ct   0x0033   200   200   140    Pre-fail  Always       -       0
  7 Seek_Error_Rate         0x002e   200   200   000    Old_age   Always       -       0
  9 Power_On_Hours          0x0032   071   071   000    Old_age   Always       -       21209
 10 Spin_Retry_Count        0x0032   100   100   000    Old_age   Always       -       0
 11 Calibration_Retry_Count 0x0032   100   100   000    Old_age   Always       -       0
 12 Power_Cycle_Count       0x0032   100   100   000    Old_age   Always       -       549
192 Power-Off_Retract_Count 0x0032   200   200   000    Old_age   Always       -       211
193 Load_Cycle_Count        0x0032   198   198   000    Old_age   Always       -       6248
194 Temperature_Celsius     0x0022   105   084   000    Old_age   Always       -       38
196 Reallocated_Event_Count 0x0032   199   199   000    Old_age   Always       -       1
197 Current_Pending_Sector  0x0032   200   200   000    Old_age   Always       -       0
198 Offline_Uncorrectable   0x0030   200   200   000    Old_age   Offline      -       0
199 UDMA_CRC_Error_Count    0x0032   200   200   000    Old_age   Always       -       0
200 Multi_Zone_Error_Rate   0x0008   200   200   000    Old_age   Offline      -       0

SMART Error Log Version: 1
No Errors Logged

SMART Self-test log structure revision number 1
No self-tests have been logged.  [To run self-tests, use: smartctl -t]


SMART Selective self-test log data structure revision number 1
 SPAN  MIN_LBA  MAX_LBA  CURRENT_TEST_STATUS
    1        0        0  Not_testing
    2        0        0  Not_testing
    3        0        0  Not_testing
    4        0        0  Not_testing
    5        0        0  Not_testing
Selective self-test flags (0x0):
  After scanning selected spans, do NOT read-scan remainder of disk.
If Selective self-test is pending on power-up, resume after 0 minute delay.

**Comment by yungfras** [comment]
The only thing I haven't done from your checklist is start htpc manager with administrator privileges I guess. i install htpc manager using this guide http://www.htpcguides.com/install-htpc-manager-windows/

**Comment by wmariz** [comment]
Try to create a bat file like
<pre><code>C:
cd \HTCP_DIR
python htpc.py
</code></pre>
Right click on it and select Run as Administrator

**Comment by yungfras** [comment]
Ok, I did that. it opened a cmd window and closed it quickly and the bat file disappeared.

**Comment by wmariz** [comment]
Have you changed HTCP_DIR to the actual htpc directory? Python directory is set in path? How do you normally run HTPC Manager?

Try to add a line with 'pause' (without quotes) so you can see the output.

**Comment by yungfras** [comment]
I ran cd 
c:\HTPCManager
python htpc.py
yes python is installed on path an I installed HTPC as a service using nssm install HTPCManager from this guide...http://www.htpcguides.com/install-htpc-manager-windows/ so it runs automatically.

**Comment by wmariz** [comment]
Probably it is not running because the service is already using the http port.

Can you paste the output from the bat file?

You can also try to disable the service and run the bat, or disable windows UAC and restart computer.

**Comment by yungfras** [comment]
windows UAC is already disabled. I'm gonna disable the service and run the bat again

**Comment by yungfras** [comment]
After the 10 uninstall, reboot, and reinstall it finally works. thanks for all your help and patience guys.

**Comment by wmariz** [comment]
Another note for future reference: The Smartmon directory need to be added to system enviroment variable path, if you add it just on the user enviroment, the exe cannot be found in scenarios like running as administrator or as a service, because on both situations, a new enviroment is created.

**Comment by yungfras** [comment]
Thanks again. I would have been lost without you guys.
