### ISSUE TITLE
Add features to Sonarr module

### ISSUE THREAD

**Issue by thejrose1984** [Hellowlol/HTPC-Manager#117]
Any chance you can show the path to DroneFactory folder when you choose to scan? For some reason (and this is a Sonarr issue, not with HTPC-Manager) I have to regularly choose between the main scan folder and the "tv" subfolder that my download client tends to make.

I would like to see the default set in Sonarr so, on the off chance, I have to choose the "tv" subfolder, I won't have to try and remember the full path.

**Comment by Hellowlol** [comment]
Dosnt DroneFactory process all files and folders inside DroneFactory?

**Comment by thejrose1984** [comment]
Yes and no. Sometimes Sabnzb and/or Transmission creates sub-folders that make it hard for files to import automatically, hence why a drone folder can be set. The problem is that sometimes the drone folder is needed and sometimes it isn't in Sonarr.

**Comment by Hellowlol** [comment]
I cant find a api command to retrive the current dronefactory folder. Im gonna close this, feel free to reopen if they do it it.
