### ISSUE TITLE
Synology install

### ISSUE THREAD

**Issue by thejrose1984** [Hellowlol/HTPC-Manager#122]
Manually installed this port of HTPC-Manager on a Synology box to see if I can get better performance compared to FreeNAS. Any experience with an install on this platform?

**Comment by Hellowlol** [comment]
Sorry, i have no experience regarding synology or freenas. What type of performance do you think of?

**Comment by Hellowlol** [comment]
I guess your best bet is to ask for a custom package like headphones has. Atm my fork is available on unraid and freenas (with some manually hacks) nas.

**Comment by thejrose1984** [comment]
No worries, I've been tinkering with porting your code to my Synolgoy box as opposed to running it on the same FreeNAS box that houses the other components (e.g. Sonarr, CP, and Headphones). Once I sort things out, I'll update the Wiki with porting to Synology NAS so people can use your version of HTPC (which happens to be a favorite of mine). Cheers!

**Comment by Hellowlol** [comment]
Thanks!

**Comment by thejrose1984** [comment]
So good news and bad news...I was able to manually install your fork of HTPC Manager to a Synology DS413. The problem, and this is why I moved my media server to FreeNAS, is that the hardware in the unit causes unusual behavior that may not appear in other Synology NAS units with different CPU architecture. Not sure it is worth rewriting this web app to fit Synology's model.

**Comment by Hellowlol** [comment]
Thanks for taking the time to test this! What unexpected behavior did occur? (nice to know if anybody has issues) The app will not be rewritten to just support Synologys. The strange part is that this is just normal python, there are several other common python app that uses the same webserver etc (sickbeard, sabnzbd comes to mind)

**Comment by thejrose1984** [comment]
I'll go through the setup again and do a Wiki page and put in the observed issues there.

**Comment by Hellowlol** [comment]
Wiki is fine, i dont have time now.

**Comment by thejrose1984** [comment]
Wiki created

**Comment by Hellowlol** [comment]
Thanks!
