### ISSUE TITLE
Username and password for Plex

### ISSUE THREAD

**Issue by brendann993** [Hellowlol/HTPC-Manager#124]
Maybe I'm just being stupid but I can't seem to figure out what username and password to use in the plex module. I have tried MyPlex login. Plex home username and pin and test fails. What am I missing?

**Comment by Hellowlol** [comment]
It should be myplex login info. It's only required if plex home is activated.

**Comment by brendann993** [comment]
Yea plex home is active. I will continue to try now I know for sure it's the MyPlex login.

**Comment by Hellowlol** [comment]
Verify the login on the site and see the issue guidelines if you don't get it working.

**Comment by brendann993** [comment]
Hmmm so, I changed my password and the. Set it back. I also then chose the "Force Update" option in setting of HTPC manager. I then noticed I was using "localhost" instead of a IP address. So changed it and now it's working. Does it not work with "localhost" or was it something else?

**Comment by Hellowlol** [comment]
Honestly, I don't know. I have never had anything else then the ip as its inserted when pms is discovered.

I'm happy you got it sorted atleast :)
