### ISSUE TITLE
CP Link Error

### ISSUE THREAD

**Issue by ohbarnes** [Hellowlol/HTPC-Manager#13]
I am seeing an issue with the below link:

/usr/local/htpcmanager/share/HTPC-Manager/interfaces/default/html/couchpotato.html

> href="**${webinterface}**" target="_blank" title="Open original Couchpotato interface">${settings.get('couchpotato_name', 'CouchPotato')}

In HTPC clicking opens new tab "**about:blank**"

If I change it to the following it works fine:

> href=**"http://192.168.1.3:5050**" target="_blank" title="Open original Couchpotato interface">${settings.get('couchpotato_name', 'CouchPotato')}

Great job on this fork by the way - loving it...

**Comment by Hellowlol** [comment]
Thanks. What browser are you using?

**Comment by Hellowlol** [comment]
Nvm, found the error. It's two :: in webinteface. I'll fix it later today. I don't have access to my computer now

**Comment by Hellowlol** [comment]
Fixed
