### ISSUE TITLE
Add Season Folder option

### ISSUE THREAD

**Issue by evilspectre** [Hellowlol/HTPC-Manager#133]
When adding a series via Sonarr it defaults to season folder off. Would be nice to have the option to enable that either globally or on a per series basis

**Comment by Hellowlol** [comment]
I just assumed it would add season folders by default. Who wants all episodes inside a folder.., :O dies this really require a option or can we just add that by default?

**Comment by evilspectre** [comment]
I am perfectly fine with defaulting to season folders. All the episodes in one folder is gross, but people like options :)

**Comment by raysguy** [comment]
Just to throw my two cents in, I'm one of the odd ones who actually doesn't use season folders as I've had problems with them in the past. So if they are to become the default an option would be nice ;)

**Comment by Hellowlol** [comment]
Ok, I'll add a option for that and while I'm at it I'll add a option regarding specials

**Comment by Hellowlol** [comment]
Should be added with the latest commit
