### ISSUE TITLE
Plex not working

### ISSUE THREAD

**Issue by elRadix** [Hellowlol/HTPC-Manager#14]
It scans the plex servers and populates the data automatically but when I test it, it gives an error
I also entered the correct username/password

modules.plex	ERROR	Unable to fetch currently playing information! Exception: HTTP Error 401: Unauthorized

**Comment by Hellowlol** [comment]
This is when you click the test button?

**Comment by elRadix** [comment]
yes, the test button is red

**Comment by Hellowlol** [comment]
Oki. I forgot to check that after plex home support was added. Thanks for reporting the issue. I'll fix it.

**Comment by elRadix** [comment]
great, let me know when its done ;-)

**Comment by Hellowlol** [comment]
But to be clear everything else works? You can find the shows, see what playing and so on?

**Comment by elRadix** [comment]
no, there is no connection with plex so no tv/movies in the dashboard, adding the server is possible but it cant retrieve anything

I have 2 plex servers (Synology and Mac) both are reported in the admin interface but there is no connection possible
```Date
	
Module
	
Level
	
Message
2015-01-08 13:12:07	modules.plex	ERROR	Unable to fetch currently playing information! Exception: HTTP Error 401: Unauthorized
2015-01-08 13:12:06	modules.plex	ERROR	Unable to fetch all shows! Exception: HTTP Error 401: Unauthorized
2015-01-08 13:12:03	modules.plex	ERROR	Unable to fetch all movies! Exception: HTTP Error 401: Unauthorized
2015-01-08 13:11:44	modules.plex	INFO	GDM: Servers discovered: 3
2015-01-08 13:11:43	modules.plex	INFO	Sending discovery message: M-SEARCH * HTTP/1.0
2015-01-08 13:02:56	modules.plex	ERROR	Unable to contact Plex via http://192.168.1.16:32400 

```

**Comment by Hellowlol** [comment]
Do you use plex home? It works fine here, both with and without u/p

**Comment by elRadix** [comment]
no, I am using plex media server, why Home ? does it not work plex media server

**Comment by Hellowlol** [comment]
Plex home is a new feature in plex media server. You wrote it happen in the dashboard does the module it self work?

**Comment by elRadix** [comment]
I have home actived in the plex media server, but no no connection, test button remains red, see error logs above

2015-01-08 13:02:56	modules.plex	ERROR	Unable to contact Plex via http://192.168.1.16:32400

**Comment by Hellowlol** [comment]
I have a hard time finding out why this doesn't work for you since it works here. Can you test styxits version and see if plex works there?

**Comment by elRadix** [comment]
Just tested with the styxits version, plex worked immediately was able to see movies/tvshows, yours seems broken somehow strange.

**Comment by Hellowlol** [comment]
Can you update and try again?

**Comment by elRadix** [comment]
it works now, thank you for your quick support !!!!!!

**Comment by Hellowlol** [comment]
iPhone debugging few!

**Comment by thejrose1984** [comment]
Having this issue on a fresh install of HTPC Manager. Verified PMS is running without issue.

**Comment by Hellowlol** [comment]
Make a new issue with logs, if you have ssl enabled you need to set it to prefered.

**Comment by thejrose1984** [comment]
Default setting for secured connections is preferred on my setup

**Comment by Hellowlol** [comment]
Ok, make a new issue with logs then and ill take a look. It works fine here :)

**Comment by bakman2** [comment]
I see the content of my local library, is it supposed to work with shared libraries as well ?

**Comment by Hellowlol** [comment]
I don't know, I have never tested it (no one shares there library with me)

**Comment by Hellowlol** [comment]
Is shared lib listed in /sections ?
