### ISSUE TITLE
Plex Movie/Shows Grab doesn't work

### ISSUE THREAD

**Issue by damiantje99** [Hellowlol/HTPC-Manager#142]
Title describes problem. 

The Plex module is working, because its shows me when someone is watching a movie or show.
But it doesn't show any movies or shows. The error I see in the log is:

Failed to update section 1 on Plex: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0x0311E990>)

And

Failed to update section 2 on Plex: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0x03245C60>)

I think its because Plex isn't working with localhost:32400 but only with localhost:32400/web.

Can you help me out?

Kind Regards

**Comment by MaartenMol96** [comment]
I have the same problem, the test buttons says it's working. When someone is watching on Plex I can see that. But there are no library items showing in HTPC Manager. And when I hit the Update All Sections button I get the following error:

Failed to update section 13 on Plex: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0x01E2D5F8>)

**Comment by Hellowlol** [comment]
Hi! Thanks for reporting this.

Plex works fine here. 
Have you set anything in hide watched and/or ignore section? 
Have you set a username and password?
Is plex home actived in plex?

**Comment by Hellowlol** [comment]
@damiantje99 @MaartenMol96 The missing tvshows and movies should work with the lastest update. Sorry about that.

Please respond to my questions above regarding the 401

**Comment by MaartenMol96** [comment]
@Hellowlol we have not set any of the ignore settings, we have set the correct credentiuals and we use Plex Home!

**Comment by raysguy** [comment]
Plex is working perfectly here with and without Home credentials.  Also I'm happily using the section filters which work without issue thanks.

**Comment by Hellowlol** [comment]
@MaartenMol96 Did the last update solve the issue regarding tvshows and movies not showing up? Have you change myplex password while htpc-manager was turned on?

**Comment by Hellowlol** [comment]
@raysguy thanks!

**Comment by MaartenMol96** [comment]
@Hellowlol Just updated! Working like a charm now! Love it! thank you for the fast response ;)

**Comment by Hellowlol** [comment]
Np, happy to help :)

**Comment by MaartenMol96** [comment]
@Hellowlol one other question: It only shows 50 of my movies and tv shows. Can this value be changed? I have like 600+ movies and 100+ tv shows ;)

**Comment by damiantje99** [comment]
Thanks, its also working here! Thanks for the fast respone, Appreciate it!

**Comment by Hellowlol** [comment]
Just scroll down and you will see the rest. (just incase you wasnt aware). 
If you want to change this your self you need to edit https://github.com/Hellowlol/HTPC-Manager/blob/master2/interfaces/default/js/plex.js#L7

You need to do the same for tvload etc.

I noticed kodi was set to 75 and there isnt any search feature like kodi has. How many do you want to have by default?

**Comment by MaartenMol96** [comment]
@Hellowlol No nvm it, just was slow. I guess 600+ movies is a lot to take in ;)
