### ISSUE TITLE
Possible Sickrage improvements

### ISSUE THREAD

**Issue by Hellowlol** [Hellowlol/HTPC-Manager#146]
- [ ] Edit show modal (needs to be added to the api)
- [ ] Status bar like sonarr has (needs to be added to api)

**Comment by thejrose1984** [comment]
Also perhaps have shows be listed alpabetically the way it does in SR (e.g. The Big Bang Theory will be sorted under B, not T)

**Comment by Hellowlol** [comment]
I can do that

**Comment by thejrose1984** [comment]
And showing shows sorted A-Z by default as opposed to Z-A?

**Comment by Hellowlol** [comment]
Isn't it sorted from A to Z today? I was sure it was. Anyway I'm working on some filter stuff.

**Comment by Hellowlol** [comment]
@thejrose1984 the sorting is fixed in a branch in working on.
