### ISSUE TITLE
Cant add movies in Couchpotato

### ISSUE THREAD

**Issue by cirkator** [Hellowlol/HTPC-Manager#15]
Hi, i have a problem adding movies with the CouchPotato module. I have set everything up right, when i enter CPs IP, Port, Username and Password, HTPCManager can fetch the API-Key.
I can view my CP Library and Wanted List. When i want to add a movie and i search for e.g. Spiderman, i can see all available spiderman movies, i click on one and get the detailed view, there i select my desired quality in CP and when i click on "add" nothing is happening. When i click on "imdb" i get to the appropriate imdb site. When i click "close" nothing is happening. The detailed view window is just sitting there....

The Log message in HTPCManager doesnt tell me much unfortunately.

2015-01-09 23:29:29    cherrypy.error.47296388534416    ERROR    [09/Jan/2015:23:29:29] HTTP Traceback (most recent call last):

In CP´s log i get this:

01-09 23:25:19  INFO [hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?y=&t=spiderman, data: []
01-09 23:25:19  INFO [hpotato.core.plugins.base] Opening url: get http://api.themoviedb.org/3/search/movie?api_key=xxx&search_type=ngram&query=spiderman, data: []
01-09 23:25:19  INFO [hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/search/spiderman/?limit=5, data: []
01-09 23:25:19  INFO [ie.providers.info.omdbapi] Found: Spiderman (1990)
01-09 23:25:19  INFO [hpotato.core.plugins.base] Opening url: get http://api.themoviedb.org/3/movie/557?api_key=xxx&append_to_response=alternative_titles, data: []
01-09 23:25:20  INFO [hpotato.core.plugins.base] Opening url: get http://api.themoviedb.org/3/movie/68658?api_key=xxx&append_to_response=alternative_titles, data: []
01-09 23:25:21  INFO [hpotato.core.plugins.base] Opening url: get http://api.themoviedb.org/3/movie/315635?api_key=xxx&append_to_response=alternative_titles, data: []
01-09 23:25:22  INFO [providers.info.themoviedb] Found: [u'Spider-Man (2002)', u'Spiderman (1990)', u'Spider-Man (2017)']
01-09 23:26:39  INFO [ie.providers.info.omdbapi] Found: Spiderman (1990)
01-09 23:26:39  INFO [providers.info.themoviedb] Found: [u'Spider-Man (2002)', u'Spiderman (1990)', u'Spider-Man (2017)']

I tried it with Chrome and Firefox, same behaviour.
I am running HTPCManager and Couchpotato on unRAID with Usercreated Dockers. I am using Hellowlol´s branch of HTPCManager.
I can add series in Sonarr, add torrents in deluge and add nzbs in nzbget just fine. Its only CP that is giving me troubles. All mentioned are running as dockers.

Any help would be appreciated Smile

Edit: The timestamps in the logs dont add up, but thats because i tried it often. The logmessages are appearing at the same time.

**Comment by Hellowlol** [comment]
Can you update to the latest version and test again?

**Comment by cirkator** [comment]
Hello, thanks for looking into it. 
I just updated but unfortunately nothing has changed. I still cant click on either "add" nor "close" and i am getting the same errormessage :(

**Comment by Hellowlol** [comment]
Delete browser cache :)

**Comment by cirkator** [comment]
Haha, what a noob move of mine. 
Good News!!!
I deleted my browser cache and have now successfully added a movie. It immediately got downloaded as well, so all is good!

Thanks for this quick fix, i know why i love opensource developers so much. Your dedication is highly appreciated!

**Comment by Hellowlol** [comment]
It's a common mistake! Your not the first and wount be the last :D thanks for reporting the issue.

**Comment by cirkator** [comment]
Thanks for fixing it! :)
