### ISSUE TITLE
µTorrent not loading

### ISSUE THREAD

**Issue by damiantje99** [Hellowlol/HTPC-Manager#150]
Since yesterday I have the problem that HTPC won't load the torrents that are currently downloading with µTorrent. The error I get in the log is: 

HTTP Traceback (most recent call last), this is comming from the module cherrypy.error.43114320. 

After a reboot it will work again, but it will stop at some random time.

Do you have any solution?

Kind Regards

**Comment by Hellowlol** [comment]
Sorry i have no idea what could have caused that. The utorrent module lacks logging so it would only be guesses. Ill add some debug logs later. 

What uTorrent version are you using?

**Comment by damiantje99** [comment]
We'll have to do with it, its better than nothing right?

Currently im using µTorrent 3.4.3 (build 40097). It's the latest version. 
When i'm opening the µTorrent on HTPC I see the loading icon. It just keeps spinning and then the error in the log appears. In µTorrent self I can see the downloading torrents. 

Im not sure if i'm doing it wrong, but the only thing that appears in my browser is: An error occured.

**Comment by Hellowlol** [comment]
Thank you :)

If you go to http://htpcmanagerip:hptcmanagerport/utorrent/torrents . Is there a error message there? If it is can you paste it here.

**Comment by damiantje99** [comment]
I get this error:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

**Comment by Hellowlol** [comment]
I just pushed a branch with with some logging added to uTorrent. Can you test again and paste the error you get?

You can change to that branch in the settings. Choose utorrent-addlogs in the branch dropdown. Click save, click force update.

Or download it manually:

https://github.com/Hellowlol/HTPC-Manager/tree/utorrent-addlogs

**Comment by Hellowlol** [comment]
@damiantje99  have you tested the branch i mentioned?

**Comment by damiantje99** [comment]
I didn't have any time to test, im on my way home now, ill test it then and will let you know. Sorry for the late response.

**Comment by damiantje99** [comment]
Currently im not getting any error's. Im not sure if it is fixed or not. I'm letting you know if I get an error and what the error is. If I don't get the error within two days, you can mark this issue as fixed!

**Comment by Hellowlol** [comment]
@damiantje99 you should switch back to the master2 branch. 

I have merged the one your using and added some small improvements to the utorrent module.

**Comment by damiantje99** [comment]
Alright! I think the problem is fixed now! Thanks for the support!

**Comment by Hellowlol** [comment]
:)
