### ISSUE TITLE
Visual bugs

### ISSUE THREAD

**Issue by Hellowlol** [Hellowlol/HTPC-Manager#155]
- [ ] Fix line-height 26 px on other in nav bar.

**Comment by thatbritguy** [comment]
Think this can be closed.  Was fixed in 67d53fe38f444b2d5deb1e98a4fb02b6b9e70f17 :+1:

**Comment by rkorn86** [comment]
nope it was not :-1: 
See last item in list above. ![Custom Module](http://i.imgur.com/qSW7XmT.png)
Ive already created PR for it: https://github.com/Hellowlol/HTPC-Manager/pull/173
