### ISSUE TITLE
Multiple Samsung TV remote on main menu

### ISSUE THREAD

**Issue by elRadix** [Hellowlol/HTPC-Manager#16]
I would like to ask feature to show multiple tv remove on the main menu so I could manage multiple TVs in my home.

**Comment by Hellowlol** [comment]
I'm not gonna add more remotes on the same screen but I could have a dropdown like the xbmc modules have. Would that work for you?

**Comment by elRadix** [comment]
yes sure, happy with a dropdown approach - more cleaner

**Comment by Hellowlol** [comment]
Great, I have no eta tho.

**Comment by elRadix** [comment]
sure, no rush ;-) enjoy yr day!

**Comment by Hellowlol** [comment]
@elRadix Can you test this branch? https://github.com/Hellowlol/HTPC-Manager/tree/sremote
I only have one tv to test with.

**Comment by Hellowlol** [comment]
@elRadix Have you had a change to test the mention branch?

**Comment by Hellowlol** [comment]
Feel free to reopen the issue once the feature is tested:)
