### ISSUE TITLE
Latest Plex Server update breaks Music section

### ISSUE THREAD

**Issue by raysguy** [Hellowlol/HTPC-Manager#161]
Plex pushed an update to their server software this week (0.9.12.0) which was mainly focussed on overhauling the music side of things.  This seems to have broken the Plex Music tab in HTPC - clicking on tab results in "Error connecting to Plex" message.  If I already have music playing it still shows up in the Now Playing section but the controls don't work.

**Comment by Hellowlol** [comment]
Thanks! i dont use plex for music so i would never had noticed

**Comment by Hellowlol** [comment]
Should be fixed. Can you confirm?

**Comment by thatbritguy** [comment]
Checked it out last night and music now loads correctly. Thanks for fixing it so fast! :)
