### ISSUE TITLE
Headphone title link not going to Headphones

### ISSUE THREAD

**Issue by KaHooli** [Hellowlol/HTPC-Manager#165]
When I go to my HTPC-Manager install at http://192.168.41.2:7000/headphones/ , and click on the title (which I have named Music), it takes me to http://192.168.41.2:7000/headphones/%3Cfunction%20_build_url%20at%200x00000000024C7828%3E instead of http://192.168.41.2:8181/ .
The information is loading correctly at http://192.168.41.2:7000/headphones/ from Headphones, so it doesn't appear to be an issue with my settings.

**Comment by Hellowlol** [comment]
Can you update and verify that it works now?

**Comment by Hellowlol** [comment]
Closing this as it should work.

**Comment by KaHooli** [comment]
Confirmed, all working now.  Thanks :smile:

**Comment by Hellowlol** [comment]
Happy to help!
