### ISSUE TITLE
Mylar bugs - lots of hidden text visable and blank Action buttons

### ISSUE THREAD

**Issue by KaHooli** [Hellowlol/HTPC-Manager#167]
Thanks for adding Mylar support.

Just thought I'd give a heads up that there is at least one bug.  I get lots of formatting text below the "Comics" tab and above the release info.  Also, the buttons under "Action" are blank.

Sorry for the size of this screen shot...
![htpc-mgr_mylar](https://cloud.githubusercontent.com/assets/665634/7626833/9eab82d2-fa52-11e4-9b9b-da795267e917.png)

**Comment by Hellowlol** [comment]
It's a easy fix the text, is just something I used for debugging. I'm sorry for merging such a raw module but I have been dragging my feet for months.. If I did do it now it would never have happened.

**Comment by Hellowlol** [comment]
Should be fixed in the latest update.

**Comment by KaHooli** [comment]
Confirmed fixed :+1: 
The extra text is missing and the Action buttons have their icons on them.  Thanks :grinning:

**Comment by Hellowlol** [comment]
Thanks for confirming.
