### ISSUE TITLE
Mylar: comic file download link

### ISSUE THREAD

**Issue by KaHooli** [Hellowlol/HTPC-Manager#168]
It would be great if you could link some text with each comic, maybe the title, to the download link for the comic book file.  This link is supplied in Mylar as the green circle next to each title, but not sure if this is available via the API.

As I use HTPC Manager from my iPad to regularly monitor my server, this would make it easier to add a comic to my comic book reader.

**Comment by Hellowlol** [comment]
That isn't available in the api :(. I'll try to add this, don't t hold your breathe.

**Comment by Hellowlol** [comment]
@evilhero I need to add some stuff to mylar api. What branch should i checkout from?

**Comment by evilhero** [comment]
Development is the branch to always use for PR's. I'll try and merge within a day of the request too (just depends on when I can get to a machine).

**Comment by Hellowlol** [comment]
@KaHooli Ill do you request when/if https://github.com/evilhero/mylar/pull/1017 gets merged.

**Comment by Hellowlol** [comment]
@KaHooli Its done, until its merged you need to use the pr i sent to mylar

**Comment by KaHooli** [comment]
Thanks @Hellowlol & @evilhero :+1: 
It seems to be working.  Very much appreciated :grinning:

**Comment by KaHooli** [comment]
Tested earlier on my PC, but when tested under Safari on my iPad & iPhone (iOS 8.3), it wants to download a 30 byte file called DownloadIssue.
![image](https://cloud.githubusercontent.com/assets/665634/7669831/72d13384-fccb-11e4-9305-76c806efc181.jpg)

**Comment by Hellowlol** [comment]
Shit, this is just HTML 5.. I'm not sure it's supported I'll see if I can find a work around.

**Comment by Hellowlol** [comment]
This happen cus Apple think the user is a retard that needs to be protected from him self... 
Anyway you need a app that can handle downloads, i tried with downloads lite. Find the file, rename the file to the correct ext. choose open with, select your comic app (i used iComix)
