### ISSUE TITLE
Users have more permissions than wanted

### ISSUE THREAD

**Issue by camjac251** [Hellowlol/HTPC-Manager#17]
I'd like to give users access to viewing Sonarr, Couchpotato, Sabnzbd, etc, but not actually altering anything. Or atleast not being able to restart/shutdown the service, delete movies/episodes, etc.

I'd like to give them access to add their own stuff but thats about it

**Comment by Hellowlol** [comment]
Thanks for your interest in my fork. I think i can add that type of feature, but i have to check. However it  will not be a priority. I what about a user like guest/kid or something?

**Comment by CamJGaming** [comment]
Requiring login though. Like they can view things but cannot change or add anything

**Comment by Hellowlol** [comment]
Ok. Let me see what i can do.

**Comment by Hellowlol** [comment]
Request accepted. Just to be clear you want a user where they can't to shit, like add movies, search for missing episodes, pause torrents/ nzb, change speed, restart stuff and so on? This require a change to every single function in every module (trivial change) do I wanna make sure i get this right as I ain't doing this twice :p

**Comment by Hellowlol** [comment]
@CamJGaming Since this is your request i would like to have some assistance with testing this feature.
Can you test every button in every module that you use in this branch? https://github.com/Hellowlol/HTPC-Manager/tree/addnewuser

**Comment by Hellowlol** [comment]
Feel free to reopen once the feature is tested.

**Comment by kooimens** [comment]
I can't re-open the issue. Don't know what happened to the dash, but it's really fucked up atm:D.
![1](https://cloud.githubusercontent.com/assets/3150962/6112987/3c671814-b094-11e4-8102-7cadc7f35b75.jpg)

**Comment by Hellowlol** [comment]
fuck dash. i dont think i have done anything related to that. Does the other stuff work?

**Comment by Hellowlol** [comment]
@kooimens have you had the chance to test the modules?

**Comment by kooimens** [comment]
I will give it a try tomorrow!

**Comment by kooimens** [comment]
Modules tested: sabnzbd, sickrage, couch, plex, newznab search. All tests done with restricted user.

Dash plex: movies = empty? rest is ok
dash couch, sickrage, sab = ok. 

Sabnzbd, deleting from history not possible = ok.
user can add nzb's.

Sickrage, user can search/add shows.
user can not delete shows.
user can search for episodes.

Couchpotato, can search/add movies.
Not able to delete movie.

Don't know what's really the purpose of this branche, but I don't care testing some shit:D

**Comment by Hellowlol** [comment]
Then I made the login system/ user control the idea was to protect Htpc managers settings aswell as the app it self. This pr is for a even more restricted user where only basic commands are allowed. Like search, add etc but not delete, restart shutdown change speed etc

**Comment by kooimens** [comment]
I get it!

**Comment by henkjanvries** [comment]
ive tried this branch, but i don't have restrictions in couch potato. I can still remove movies etc.

am i doing something wrong?

**Comment by Hellowlol** [comment]
Have you added a restrictwd user and logged in?

**Comment by henkjanvries** [comment]
its working now, this branch is only behind. anyway to get it up to latest branch?

**Comment by Hellowlol** [comment]
Yeah, you have to merge master2 branch into this one. 

Im not gonna do it until the feature is done and that gonna take some time, unless @CamJGaming or someone else test every link as i have asked. 

Im not gonna do anything until its done as it just loads of work and i personally dont have use for this.

**Comment by Hellowlol** [comment]
@henkjanvries try this one https://github.com/Hellowlol/HTPC-Manager/tree/tempaddnewusr

**Comment by henkjanvries** [comment]
ive got this running in your master2 branch. i changed the setting yesterday for the user role.
Thanks!
This works for me, and my users.

**Comment by Hellowlol** [comment]
Please report any issue so this get merged with master2

**Comment by henkjanvries** [comment]
like ive said in another issue thread, ive set a lot of permissions my self. based on the master2 branch.
it would be good to have functions greyed or invisible when not having correct role.

**Comment by CamJGaming** [comment]
Sorry for not replying. I forgot that I made this thread. What can I test?

**Comment by CamJGaming** [comment]
Wanted to clarify my original post. I'd like to give users access to adding movies, shows, etc, viewing downloads, and grabbed movies, but no access to deleting, changing, or restarting/shutting down services.

**Comment by Hellowlol** [comment]
That should be fixed in every module but sonar and headphones. Check the tempaddnewusr branch.

**Comment by CamJGaming** [comment]
I tried the tempaddnewusr branch. With both restricted user and user, it gives me the option to delete movies from couchpotato still.

**Comment by Hellowlol** [comment]
That shouldnt be possible for a restricted user, thanks for reporting that. There are several actins in cp that would be restricted that arnt (added after the the branch was made). Have you tried the other modules!

**Comment by CamJGaming** [comment]
Yeah, in nzbget, with restricted and user, I can change the speed limit. So restricted user is the new user for adding and viewing?

**Comment by Hellowlol** [comment]
The idea

restriced user: Add stuff, see stuff
user: Access to everything in the modules
admin: Access to everything

**Comment by CamJGaming** [comment]
I will test restricted more and get back to you.

**Comment by Hellowlol** [comment]
CP delete works fine, it does not delete with a restriced user.

**Comment by CamJGaming** [comment]
Could the ui element be deleted though? CP seems fine with restricted.

**Comment by Hellowlol** [comment]
No

**Comment by Hellowlol** [comment]
@evilspectre I noticed you removed the ability to delete shows from cp. Is this because other ppl are using htpc manager? You can test https://github.com/Hellowlol/HTPC-Manager/tree/tempaddnewusr witch reduces access so they can only add stuff etc.

**Comment by evilspectre** [comment]
@Hellowlol Did not even notice that branch. Yes, I am using HTPC Manager as a front end for other users to add movies and tv shows then watch them on Plex. Got tired of family/friends asking me to add their show for them.

**Comment by Hellowlol** [comment]
@evilspectre Remember to change the users to restricted user or it will not work :), let me know if you find any bugs (users have access to more then they should). I think all of then should be ok except from sonarr.

restriced user: Add stuff, see stuff
user: Access to everything in the modules, delete, change speed reboot/shutdown modules
admin: Access to everything (htpc managers settings etc)

**Comment by nockstarr** [comment]
I would like to help out  to get this done:) 
Is "tempaddnewusr" still the active branche?

**Comment by Hellowlol** [comment]
I wouldn't call it active :p but yea that's the one. I'll merge master2 into it in a couple of days.

**Comment by nockstarr** [comment]
This is my view of the restricted user:

SAB:
add nzb "working" however getting the warning in SAB "Empty NZB file" 
can view
can not alter settings or content

CP:
can view
can add movies
can not alter settings, content or shutdown/restart/update

Sonarr:
can view only history, nothing showing up in calander and Tv Shows
can add tv shows
can not alter settings, content or shutdown/restart/update

Plex:
can not connet in general even with the master2 branche.

HTPC Manager:
can view as expected, can also view logs, not delete
can check for update
can not alter settings, content or shutdown/restart/

To me the restricted user function looks ready to merge.

**Comment by Hellowlol** [comment]
Plex works in the master2 branch, I use it everyday. It does not support ssl and if Plex home is activated you need to enter username and password

**Comment by nockstarr** [comment]
Good to know, at this time I can not turn off plex ssl for testing :/

**Comment by Hellowlol** [comment]
You can set it to preferred to allow both http and https

**Comment by Hellowlol** [comment]
@nockstarr @kooimens  Can you test this branch? https://github.com/Hellowlol/HTPC-Manager/tree/newuser_role
Its up todate with master. It you think its ok, ill merge it.

**Comment by nockstarr** [comment]
sab:
Can view, alter, delete
CP:
Can add, delete, view
Can not restart/shutdown
Sonarr:
Can delete,add, view
Can not restart/shutdown
Plex: 
Can view, update library 

Ready to merge, og god jul :)

I suppose this is only a test for "user" role, and not "restrictive user" role? Just to be clear.

**Comment by Hellowlol** [comment]
I wanted to test both user and restricted user. I could use some suggestions regarding the auth levels. The idea is that restriced user should be allowed  to add, search for stuff, while a user should be able to do pretty much everything except for settings, kill processes, shut down htpc manager add users, delete logs. And prob mure stuff I don't remember :p God Jul ja!

**Comment by nockstarr** [comment]
How I see it:
admin: 
Can do everything
Power user (user):
Can do everything except:
Alter or access to general settings (htpc settings, and moduels)
Delete logs
Restart/shutdown (only htpc)

I'm happy with how "user" is now.

Restrictive user:
Can only view modules, add tv-shows, movies, nzb's,(torrents?)

Optional auth structure:
Admin: admin
Power user: Everything except alter/view htpc settings and log.
User: View, add
Guest: Only view

Probably a bit to much auth levels:P

**Comment by nockstarr** [comment]
Just a thought, is it possible to make it so yo can choose which modules to share with the new user?

**Comment by Hellowlol** [comment]
I'm sure it is but I have no idea how.

**Comment by Torkiliuz** [comment]
This is a lucky find for me, I was struggling with getting my personal version updated, as I have been running a "restricted" version for a while with most of the UI hidden. I'll get my users to test it out and will report back if something is broken.

**Comment by Hellowlol** [comment]
@torkiliuz it's already merged into the master2 branch so it's enoght to just run that. Remember that you have to change the users access rights.

**Comment by Torkiliuz** [comment]
@Hellowlol Yes, I'm trying out that version now :) So far it blocks the same things my version did, although I set it up without the UI elements even showing ;) Before I did a "hard" modification by changing it in the html-files, but it worked okay for what I have it set up for.

**Comment by camjac251** [comment]
Could a new role be added to allow view only of modules with no access to add/change/edit?
