### ISSUE TITLE
Random FreeNAS Q&A?

### ISSUE THREAD

**Issue by thejrose1984** [Hellowlol/HTPC-Manager#175]
(1) Fails to restart properly (can initialize a restart, but have to SSH into the jail and manually start HTPC Manager
(2a) Installing in a fresh FreeNAS jail seems better, but not sure which init script included in the code will allow properly daemonize HTPC
(2b) Will making www user/group owner be an issue?

**Comment by Hellowlol** [comment]
Hi!

I would love to help you with your questions, im afraid it would be off no use. 
Im a windows guy..

Just a quick question regarding 1: does the styxit version restart correctly?
2: none if them I believe

**Comment by thejrose1984** [comment]
Windows guy?! GASP! All joking aside, no a big deal. I made another Wiki page for anyone interested in the manual approach and bypassing FreeNAS plugins altogether.

**Comment by Hellowlol** [comment]
@thejrose1984 If you send a pr for a working rc script for freenas ill merge it :)
