### ISSUE TITLE
Unable to connect to qbittorrent with version 3.2.0

### ISSUE THREAD

**Issue by three80** [Hellowlol/HTPC-Manager#176]
I am able to connect to local qbittorrent but not qbittorrent-nox on my server (headless).

Relevant info:

Branch: master2
Commit hash: 7d1d749dae2b8b32326f1decb4bf96ea554ac379
OS: linux mint ( Linux version 3.16.0-31-generic (buildd@toyol) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #43~14.04.1-Ubuntu SMP Tue Mar 10 20:13:38 UTC 2015)
Python: Python 2.7.6

What I did:      tried to connect to qbittorrent-nox on remote (local) server
What happened:    the busy indicator showed but nothing else
What did I expect to happen:   it to show me list of downloads/queues in qbittorrent

Browser:  Chrome Version 42.0.2311.152 (64-bit) and Firefox 38

Log: http://pastebin.com/fVZkSxMD

Log says error 404 but its the address I put in my browser, with same user/pw and it connects.

![selection_012](https://cloud.githubusercontent.com/assets/7866777/7720368/4a68330e-fe81-11e4-96c9-91e5359b50b1.png)

![selection_011](https://cloud.githubusercontent.com/assets/7866777/7720377/57c4a71c-fe81-11e4-82a3-c6789b285541.png)

![selection_013](https://cloud.githubusercontent.com/assets/7866777/7720392/8f2ccc98-fe81-11e4-8318-6a46b1f21154.png)

Setting in HTPC-Manager Http:// before local address but I have tried without and get same results.

**Comment by Hellowlol** [comment]
Yeah, I also notice that. Couldn't get global download limit HTTP Error 403: Forbidden. Seems strange.

Can you post a img of your qbittorrent settings (in htpc manager)?

**Comment by three80** [comment]
added images a minute ago to first post.

**Comment by Hellowlol** [comment]
what qbt version is this?

**Comment by three80** [comment]
qBittorrent v3.2.0 (Web UI)

Also here is log without http:// in qbittorrent settings if it makes a difference: http://pastebin.com/dQPZzFzy

**Comment by Hellowlol** [comment]
Can you update htpc manager wipe the log and then post the new log here? When you go to the webui in qbittorrent nox, what are the realm?

**Comment by three80** [comment]
What do you mean realm?

domain? just  localdomain

**Comment by three80** [comment]
Shutdown
git pull
Restart

new log: http://pastebin.com/AUYVPs7K

**Comment by Hellowlol** [comment]
Oh, sorry. Can you take a screenshot of the login (where you enter username and password to qbittorrent.)

**Comment by three80** [comment]
Also updated above if it helps.

**Comment by Hellowlol** [comment]
Ah crap, i notice they have updated the api in 3.2.0. Im still using a old version on my desktop. What version are you desktop qbittorrent?

**Comment by Hellowlol** [comment]
https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation
New docs :https://gist.github.com/pmzqla/7e5733dbecfc50ee4ecd#file-web-api-documentation

**Comment by three80** [comment]
desktop is 3.1.8

**Comment by Hellowlol** [comment]
Well there we have it then. Until i have time to fix  this you will need to downgrade :)

**Comment by three80** [comment]
Well I can wait, this work of yours has eliminated many bookmarks for me.  I can live with using just one extra.  Thanks for the work.  It's a really great thing to have.

**Comment by Hellowlol** [comment]
Im glad you like it, i working om some improvements regarding nzbget and sabnzbd but as soon as thats finished ill start rewriting the qbittorrent module

**Comment by Hellowlol** [comment]
@three80 I got some spare time this weekend so ill start on this. Initially i wanted to just drop support for older versions, but loads of private torrent sites have whitelist/blacklist so ill support both.

**Comment by Hellowlol** [comment]
@three80 Closing this as it should work now.

**Comment by three80** [comment]
Yup, it's working.  Thanks.

**Comment by Hellowlol** [comment]
Thanks for confirming.
