### ISSUE TITLE
A multitude of sins, lol

### ISSUE THREAD

**Issue by sparklyballs** [Hellowlol/HTPC-Manager#18]
Running commit a52df7a077, in docker from smdion over on unraid forum because i was toying with the idea of moving from sickbeard over to sonarr and styxit doesn't support it yet.

anyways, this is what i've found so far, kodi test fails, save kodi settings say save failed, yet latest movies, music, shows etc in kodi show on dashboard.
![screen shot 2015-01-24 at 03 32 16](https://cloud.githubusercontent.com/assets/4343808/5886000/20a7a250-a37a-11e4-969c-66f828922e8a.png)

![screen shot 2015-01-24 at 03 32 24](https://cloud.githubusercontent.com/assets/4343808/5886001/265ec854-a37a-11e4-8388-280652c2b160.png)

![screen shot 2015-01-24 at 03 32 38](https://cloud.githubusercontent.com/assets/4343808/5886003/2a6b1b50-a37a-11e4-8504-cc7246135835.png)

Sickbeard module / dashboard settings. 

Sickbeard passes test and appears in top menu, next aired does not appear on dashboard, try to save more options than just sickbeard on dash and different options to what i've chosen are checked in the list.

![screen shot 2015-01-24 at 03 29 12](https://cloud.githubusercontent.com/assets/4343808/5886019/70f22d52-a37a-11e4-80fa-0c79042f45f7.png)

![screen shot 2015-01-24 at 03 30 26](https://cloud.githubusercontent.com/assets/4343808/5886021/85e57f48-a37a-11e4-8ded-3f7fb039996c.png)

![screen shot 2015-01-24 at 03 31 20](https://cloud.githubusercontent.com/assets/4343808/5886022/96a2225a-a37a-11e4-9ce3-652f4a995d2a.png)

^^^ list i saved 

![screen shot 2015-01-24 at 03 31 32](https://cloud.githubusercontent.com/assets/4343808/5886025/bb2764d2-a37a-11e4-88bf-998bac1de4df.png)

^^^^ settings after refreshing page , see sickrage has been checked when i didn't select it in save.

**Comment by Hellowlol** [comment]
Thanks! I'll look into it.

**Comment by Hellowlol** [comment]
Are you using the latest kodi? Grabbing labels for (Mac address) is kinda buggy so that might be the reason.

**Comment by sparklyballs** [comment]
using 14.0 final. (helix)

**Comment by Hellowlol** [comment]
I think i have fixed your issues now, can you test?

**Comment by sparklyballs** [comment]
little later, have 4 year old mini typhoon to cater to, lol

**Comment by Hellowlol** [comment]
@sparklyballs Can I close this issue?

**Comment by Hellowlol** [comment]
Assumed fixed, let me know if this issue should persist
