### ISSUE TITLE
Watched Status for episodes

### ISSUE THREAD

**Issue by GTunney** [Hellowlol/HTPC-Manager#184]
Would it be possible to have it so HTPC-Manager displays watched status for individual episodes. It currently does this for shows but not episodes.

**Comment by Hellowlol** [comment]
in the kodi module?

**Comment by GTunney** [comment]
Sorry yes.

**Comment by Hellowlol** [comment]
Ill see if the api returns seen count, if it does ill add it.

**Comment by madclicker** [comment]
You can get it with 'playcount'.

**Comment by Hellowlol** [comment]
sweet, ill add it then.

**Comment by thatbritguy** [comment]
It'd be great if this was possible with the Plex module too :)

**Comment by Hellowlol** [comment]
@raysguy Ok, ill see if the api supports it. Ill add it if it does

**Comment by thatbritguy** [comment]
Thanks :)

**Comment by Hellowlol** [comment]
Should be ok now.

**Comment by GTunney** [comment]
Not too sure if something has changed but this appears to have vanished from my HTPC Manager now. Did the changes get reverted?

**Comment by Hellowlol** [comment]
Nope, there are some changes to the js. Have you tried refreshing browser cache? (if its on a iphone etc you might need to clear all data in safari settings.)

**Comment by GTunney** [comment]
My bad lol
