### ISSUE TITLE
Change the Latest TV Shows to Latest Episodes on Dash

### ISSUE THREAD

**Issue by GTunney** [Hellowlol/HTPC-Manager#187]
The latest tv shows on the dashboard seems better suited to be latest episodes with it detailing the episode number. Here are a few changes which i think would make it better.

Change from Latest TV shows to Latest Episodes - Also change show thumbail to episode thumbnail if available.

OR

Keep as Latest Shows and set to display shows only and not invidivual episodes. If you download more then one episode of the same it just keeps scrolling through the same art.

Hope you understand :-)

**Comment by Hellowlol** [comment]
I think it got it.

You want me to rename the "label" latest tvshow to latest episode and just use thumbnail if available?

**Comment by GTunney** [comment]
Yes Latest Episodes. I think it would suit the dash module more.

**Comment by GTunney** [comment]
I managed to do this quickly on my machine by changing the episode.fanart to episode.thumbnail in dash.js tested it on 4 different themes. Altbhough not too sure what action it takes if thumbnail not available as I have art for everything.

**Comment by Hellowlol** [comment]
You can do it like this:

```
var imgp;
if (episode.thumbnail) {
    imgp = episode.thumbnail;
} else {
   imgp = episode.fanart
}

var src = WEBDIR + "kodi/GetThumb?h=240&w=430&thumb="+encodeURIComponent(imgp)

```

**Comment by GTunney** [comment]
Closing as now implemented.
