### ISSUE TITLE
NZBGet doesn't work with latest commit

### ISSUE THREAD

**Issue by 15bitgames** [Hellowlol/HTPC-Manager#188]
Just updated to the latest commit and noticed that NZBGet now doesn't show the current queue but will show the history.  I'm using SSL on my nzbget instance and here are my settings.  I couldn't see anything in the log unfortunately.

IP: localhost
Port: 6790
Basepath: /
User: xenogia
Pwd: ***
Use SSL: (ticked).

**Comment by Hellowlol** [comment]
Hi! Thanks for reporting this. 

Can you provide the following info and provide a full debug log:

Branch
Commit hash
Your operating system and python version
What did you do?
What happened?
What did you expect to happen?
If it's a visual bug, screenshot or it didn't happen!
Which browser, including version
If it's regarding a module what version/commit are the program
Link to a copy/paste of your logfile with clear debug info of the error on PASTEBIN

**Comment by Hellowlol** [comment]
As you can see in https://github.com/Hellowlol/HTPC-Manager/blob/master2/modules/nzbget.py#L188 a exception should be raised if there is a problem. If you cant see it see start htpc manager with --loglevel debug

**Comment by 15bitgames** [comment]
Master2 Branch
83235c750cae58854aab4dd179e8f58aa1ed80d1 Commit Hash (latest HTPC update) - Said it was 11 commits behind
Ubuntu 14.04 (x64) with Python 2.7.6

Updated GIT from "check for updates" under HTPC Manager

Then went to to my NZBGet and then noticed there was no queue - but history is still there.  There are no entries in NZBget queue or download speed notifications.

Note: The messages are staying up-to-date under "Warning" Nzbget tab option though.

I expected it to show my current 22 entries in queue under NZBGet.

Using Firefox 38.0.1

Debug log attached below (nothing to show nzbget issues)

EDIT: Sorry i'll check it with --loglevel debug now.

**Comment by 15bitgames** [comment]
Here is the debug log - can't see any issue.
http://pastebin.com/4GW8TfVn

**Comment by 15bitgames** [comment]
My apologies I had to restart NZBGet after the HTPC GIT update.  I'll close the issue.  Sorry for the inconvenience.

**Comment by Hellowlol** [comment]
Np. Glad it got sorted.
