### ISSUE TITLE
"An error occured" when trying to click on newznab in menu

### ISSUE THREAD

**Issue by 15bitgames** [Hellowlol/HTPC-Manager#189]
Using Ubuntu 14.04/Python 2.7.4 with the latest commit (83235c750cae58854aab4dd179e8f58aa1ed80d1) of HTPC Manager under the master2 branch.

Newznab option doesn't work no matter what provider I use, it just comes up with a blank screen with the black text "An error occured" appearing.

Here is the debug log, but it doesn't show much.

http://pastebin.com/iaEwFvVB

**Comment by Hellowlol** [comment]
What did you do? Did you search on anything or click the newznab in the menu?

**Comment by Hellowlol** [comment]
I know that happens if you click the link in the menu. Nzb search is getting some improvements https://github.com/Hellowlol/HTPC-Manager/issues/54

**Comment by 15bitgames** [comment]
Just clicked the newznab button at the top and it went straight to "an
error occured"

**Comment by Hellowlol** [comment]
Ok, that doesn't work :D

**Comment by 15bitgames** [comment]
Is there a way to get to the functionality or is it just currently disabled?

**Comment by Hellowlol** [comment]
Its already fixed in a feature request I'm working on. For now you just have to search on something to get to that page

**Comment by Hellowlol** [comment]
Fixed in https://github.com/Hellowlol/HTPC-Manager/tree/impnewznab I just have some cleanup left

**Comment by 15bitgames** [comment]
Excellent, thank you so much :)

**Comment by Hellowlol** [comment]
Fixed, please let me know if you find any bugs in the newznab module :)

**Comment by 15bitgames** [comment]
Just a quick note. NZBGeek has a weird thing where its requires a much longer timeout compared to most NZB apis.  I had to do this NZB MegaSearch.  Here is the error I get occasionally with NZBGeek.

Failed to fetch results HTTPSConnectionPool(host='api.nzbgeek.info', port=443): Read timed out. (read timeout=60)

**Comment by Hellowlol** [comment]
Having a api that takes more then 60 sec to respond is just... They should fix the api..

**Comment by 15bitgames** [comment]
I know. Nzbgeek is dreadfully slow.
