### ISSUE TITLE
[Feature Request] Add more options to Deluge (add torrent from link, etc.)

### ISSUE THREAD

**Issue by coach0742** [Hellowlol/HTPC-Manager#19]
I wanted to start an issue here for adding torrents to deluge. I will be starting work on it today, it should be fairly easy but I wanted a place to track it and ask for advice/help :) I was going to do it on styxit's repo, but he's not much for adding other people's work anymore.  
  
I will work on adding torrents from a link first and if I have any success, I'll try to figure out how to upload a .torrent file (don't hold your breath on this one...)

**Comment by Hellowlol** [comment]
Thats awesome, let me know if you need any help. Check out https://github.com/Hellowlol/HTPC-Manager/blob/master2/modules/deluge.py#L110 that is what is used to send a link to deluge for torrent search

**Comment by coach0742** [comment]
Thanks for the pointer. I'll definitely look at that. I'm sure I'll need help, it's just a matter of time. Sometimes I have to just sit at stare at it for a few hours before I decide what I need to do haha.

**Comment by Hellowlol** [comment]
Regarding the add a local torrent take a look on how I did that for transmission and use add_torrent_file(filename, filedump, options)

**Comment by Hellowlol** [comment]
@coach0742 is this something your still working on?

**Comment by coach0742** [comment]
I've decided I'm terrible at python, and more importantly, I'm not patient enough to troubleshoot my issues. I don't think I'll be working on this anymore.

**Comment by Hellowlol** [comment]
Ok, need a hand?

**Comment by Hellowlol** [comment]
@coach0742 Is this something you still want?

**Comment by ordinarygulp** [comment]
This would be awesome! As a fellow user of Deluge, I feel like there's not much support for it in this project. Would mainly like to see the downloads in the dashboard :)

**Comment by Hellowlol** [comment]
@d2dyno Can you specify what you want to be able to do with the deluge module? Regarding downloads on the dashboard are you thinking about something like we have done for qbittorrent?

**Comment by ordinarygulp** [comment]
I don't use qbittorrent, so I am not sure what has been done for it. The screenshot on the main Git page, has what looks like (I'm supposing qbittorrent) downloads and torrents widgets. It'd be nice to get those for Deluge as well.

**Comment by Hellowlol** [comment]
Ok. It's pretty simple. It just shows 5 downloads. I can do that, but I have no eta I got some other stuff I want to finish first.

**Comment by ordinarygulp** [comment]
Sweet, sounds good! :)

**Comment by coach0742** [comment]
@Hellowlol Crap, I completely forgot about this. It is absolutely something I still want. I know I could move over to another client like qbittorrent or transmission, but Deluge is still the only client that does everything I want it to.  

I would like to take another stab at writing it myself, but I'm afraid I'm quite terrible at python and don't really know what I'm doing.

**Comment by Hellowlol** [comment]
Then we are two :P

**Comment by Hellowlol** [comment]
Let me know if you need any help. I'll work on deluge on on the dash

**Comment by Hellowlol** [comment]
@coach0742 I got time to work on this in a couple of weeks, if your aren't done by then I'll add upload torrent, pause/start all and change speed.

**Comment by Hellowlol** [comment]
@coach0742 @d2dyno Its better late then never. Added add url, magnet and local torrent to deluge, set speed limit up and down and pause resume all. Please give it a spin and close this request if this is what you wanted
