### ISSUE TITLE
HTPC manager kodi mysql issues

### ISSUE THREAD

**Issue by GTunney** [Hellowlol/HTPC-Manager#190]
If Kodi is running via a Mysql database HTPC Manager will only connect to the main kodi install.

Example: My main kodi install is in my living room, the database is shared via mysql as per the kodi wiki, If I add another Kodi install (master bedroom) to HTPC it will not connect or display anything when selected via the drop down.

**Comment by Hellowlol** [comment]
My setup is MySQL so I'm 100% sure it supports it. Check your kodi setting on the master bedroom.

**Comment by GTunney** [comment]
I'm on absolute noob, firewall was playing havoc. Sorry for wasting your time.

**Comment by Hellowlol** [comment]
No worries :)

**Comment by GTunney** [comment]
Do both kodi's need to be running 24/7, seems to crash if one isn't available?
Living room is on 24/7 but master is only switched on as and when needed.

**Comment by Hellowlol** [comment]
I dont think so no, please make a proper bug report. See https://github.com/Hellowlol/HTPC-Manager#so-you-found-a-bug-great

**Comment by GTunney** [comment]
I think it's the timeout, If I select Master bedroom and it's not available it seems to get stuck for a few mins then switches over to living room.
