### ISSUE TITLE
Bug - Send to nzbget button not working

### ISSUE THREAD

**Issue by thatbritguy** [Hellowlol/HTPC-Manager#193]
Happens in all recent builds on both safari and chrome.  When clicking the send to nzb button on search results the success notification appears but nothing ever downloads.  Each time nzbget generates the following warnings:

[5/28/2015, 3:22:46 PM] Deleting file /Volumes/Data/nzbget/Watched/Temp Name.nzb.queued
[5/28/2015, 3:22:46 PM] Skipping duplicate Temp Name, found in history with success status
[5/28/2015, 3:22:46 PM] Adding collection Temp Name.nzb to queue

Seems that HTPC Manager uses the same temp name each time so nzbget is flagging as a dupe.

**Comment by Hellowlol** [comment]
I believe this is related to dupe check in nzbget settings. I'll see if I can't find another solution (search from newznab returns the name and if name is omitted generate a random number (for manually passed URL)

**Comment by Hellowlol** [comment]
Should be fixed in the lasted commit
