### ISSUE TITLE
NZBGet Warning duplicates

### ISSUE THREAD

**Issue by wesleyegbertsen** [Hellowlol/HTPC-Manager#194]
When on NZBGet page when switching from Active to Warnings tab than back to Active and again to Warnings. It gets duplicate entries. It keeps doing this when switching tabs. It seems it getting the warnings and forgetting to clear the old warnings.

**Comment by Hellowlol** [comment]
Thanks!

**Comment by Hellowlol** [comment]
I'll fix this today. NZBget is gonna get some love after version 15 is released.

**Comment by thatbritguy** [comment]
V15 is already out :)

**Comment by Hellowlol** [comment]
That's great! I thought I just checked it. Thanks for the tip
