### ISSUE TITLE
Upgrade to Bootstrap 3.3.4

### ISSUE THREAD

**Issue by Hellowlol** [Hellowlol/HTPC-Manager#196]
- [ ] restructure folders to support templates

**Comment by Dahlgren** [comment]
Anything in particular you want help with? Here's the official migration guide http://getbootstrap.com/migration/. There's a couple of scripts to automate the process such as https://github.com/yaph/b2tob3

**Comment by madclicker** [comment]
Nothing  is going to help with that snakey js html. I started this a few 
times and it's a nightmare.

**Comment by Dahlgren** [comment]
It works quite good on the js templating switching out column definitions, buttons and image classes at least. Navigation bar needs to reworked a bit and the settings form doesn't have the correct form structure. I have only tried the Sonarr and the CouchPotato but they worked good with just some minor tweaks.

**Comment by Hellowlol** [comment]
I tried bs2tob3  it works fairly well but there is still loads to do. I have been working on the nav bar and the settings page, the problem is that they are removed some of the classes that we are using atm and im no designer... it is pita.

Im not really sure i see the benefit by upgrading, unless someone want to make new themes or templates there isnt really any reason to upgrade.

If you want to do this yourself, feel free! ;)

**Comment by thatbritguy** [comment]
For what it’s worth I’m in the process of creating a set of themes for Bootstrap 2.3.2 which give the whole appearance a cleaner and sleeker look and I’ve been designing them based on the look of Bootstrap 3.  Hoping to have between 10-15 themes when I’m done.

**Comment by Hellowlol** [comment]
@raysguy I have been holding off because of that, but i didnt see any branch on github so assumed you have stopped.

**Comment by thatbritguy** [comment]
Yeah the branch on there got messy when pulling latest updates from your master2 branch so I ended up deleting it and have been working on it on a local branch.  Bought Tower 2 and find it pretty good now I’m used to it.  Going to need to pick your brain at some point though on a couple of issues I’ve run into.

**Comment by Hellowlol** [comment]
Dont bother keeping up with the changes that are merged. Just work on the themes, ill fix/update it when i merge it :)

Np, give me a shout if you need any assistance.

**Comment by Dahlgren** [comment]
Awesome, fixing the themes is probably the biggest hurdle to overcome!

**Comment by thatbritguy** [comment]
Cool thanks. Main issue I'm having is trying to figure out how to manipulate the drop down boxes (.form-inline I think) as they won't respect my border/border-radius/font settings. Spent hours trying to figure it out to no avail. 

Other sticking point is trying to theme the check boxes in settings. Want to be able to update those for high resolution displays.

**Comment by Hellowlol** [comment]
push a branch to github, open for issues on your fork and well take it from there. I dont want to cutter this issue
