### ISSUE TITLE
HTPC Manager can't connect to Plex when new SSL feature is enabled

### ISSUE THREAD

**Issue by thatbritguy** [Hellowlol/HTPC-Manager#198]
Plex launched an update to their media server today giving all servers a trusted SSL certificate.  There are now three server settings for a secured connection - Required, Preferred and Disabled.  If this option is set to Required HTPC Manager can't connect to it. Logs show this error: 

`Unable to fetch currently playing information! Exception: ''`

**Comment by Hellowlol** [comment]
There isnt a ssl option at all.

**Comment by Dahlgren** [comment]
If using a direct IP to the host the SSL certificate will also be invalid. Not sure if GDM uses their new generated DNS names that allows for proper SSL. Maybe have an option to ignore invalid SSL when using direct IP?

**Comment by Hellowlol** [comment]
Would be alot simpler if the users just checked preferred... :P, i see no benefit by running pms with ssl. If you want access to pms outside your network. You can login to the site and manage it from there. (where there already is ssl)

**Comment by thatbritguy** [comment]
Lol yeah that's true. I can never get SSL to work for anything for some reason even though I paid for trusted certificates.  Sonarr, nzbget, Couch Potato all refuse to work when I attempt to use SSL.

**Comment by Hellowlol** [comment]
@raysguy You should check your settings then. CP works fine with certs here. Htpc-Manager aswell.

**Comment by Hellowlol** [comment]
Im gonna close this, if a user wants ssl he will have to use preferred. If plex should remove this option ill add support for ssl. It isnt worth the development time.
