### ISSUE TITLE
Sickbeard/sickrage issues

### ISSUE THREAD

**Issue by kooimens** [Hellowlol/HTPC-Manager#20]
I'm using sickrage for my tv downloads. When using styxit/HTPC-Manager I can use the sickbeard module to make use of my sickrage setup. This works perfect. You have got a seperate sickrage module which works, but with one downside. I have added The Blacklist. Next Aired is 2015-02-01. Which is showed in the 'tv shows' tab as 'next ep'. However, the 'Next Aired' tab says 'No future/missing episodes found'. Any ideas? 

What is the difference between your sickbeard module and the one from styxit? Because with the of styxit i got my sickrage setup connected, but with yours it fails.

**Comment by kooimens** [comment]
The Next Aired on dash is showing the next episode, so that's great!

One other question. Is it right that your branche is more stable than the one of styxit? It's loading much faster when i'm using it as reverse proxy through apache2.

**Comment by Hellowlol** [comment]
I wouldnt call it that. But there are some improvementents in mine

**Comment by Hellowlol** [comment]
Regarding the differance, add with tv rage id in addition to tvdbid, manual postprocess and some more that I don't remeber.. I'll look into the black list thing

**Comment by Hellowlol** [comment]
Well The Blacklist works fine here, its listed as it should,  both on the next aired tab in the module and in the dash. If you go to http://yourip:port/sickrage/GetNextAired is something returned there?

**Comment by kooimens** [comment]
That's weird. If I try http://yourip:port/sickrage/GetNextAired or even http://yourip:port/sickrage/home/GetNextAired it returns me to the home screen of sickrage

**Comment by Hellowlol** [comment]
Just to be clear its the ip and port to htpc-manager not sickrage!

**Comment by kooimens** [comment]
I'm sorry, I was thinking of a sickrage api call. If I try ip:8085/htpc/sickrage/GetNextAired (htpc is my webroot) it asks to open or save GetNextAired.json

**Comment by Hellowlol** [comment]
Is this via your reverse proxy? Can you try directly against Htpc manager? What briwser are you using?

**Comment by Hellowlol** [comment]
Can you start htpc manager with --loglevel debug and upload the log to pastebin?

**Comment by kooimens** [comment]
I'm on IE 11. Initially, but switching to Firefox gives the same problem. I'm trying it directly to HTPC manager (not through the proxy), but with the webroot enabled.

With the webroot disabled, I got the same. IE ask me to open or save the GetNetAired.json. 
Firefox returns:
`{"message": "", "data": {"later": [], "missed": [], "today": [], "soon": [{"paused": 0, "episode": 9, "network": "NBC", "airdate": "2015-02-01", "quality": "HD", "show_name": "The Blacklist", "ep_name": "Luther Braxton (1)", "tvdbid": 266189, "airs": "Sunday 9:00 PM", "weekday": 7, "season": 2, "indexerid": 266189, "ep_plot": "When the elusive Reddington is arrested and taken to a secret detention facility Liz and the task force set out to save Red before he disappears forever. Meanwhile, Red encounters Luther Braxton at the detention facility, a thief that he shares a complicated history with.", "show_status": "Continuing"}, {"paused": 0, "episode": 10, "network": "NBC", "airdate": "2015-02-05", "quality": "HD", "show_name": "The Blacklist", "ep_name": "Luther Braxton: Conclusion (2)", "tvdbid": 266189, "airs": "Thursday 9:00 PM", "weekday": 4, "season": 2, "indexerid": 266189, "ep_plot": "As chaos ensues at the Factory leaving the fate of Red and the task force unknown, FBI boss Cooper struggles to rescue his team from the detention facility. Meanwhile, it\u2019s a race against time to stop Luther Braxton from attaining confidential information.", "show_status": "Continuing"}]}, "result": "success"}`

**Comment by Hellowlol** [comment]
Okei if you check the same page if firefox does the the blacklist show up in the in all the tabs/dash?

**Comment by kooimens** [comment]
No, same thing as in IE. Two next aired on my dash (the second appeared tonight). The Sickrage module shows the next epsiode under the 'Next ep' (maybe this should be Next Episode, btw? Space enough) header within the "TV Shows" tab. But under showname (Next Aired tab) it says No future/missing episodes found

**Comment by kooimens** [comment]
The same on my mobile device (Safari browser)

**Comment by Hellowlol** [comment]
![image](https://cloud.githubusercontent.com/assets/1214134/5968672/93636e06-a81a-11e4-92b3-df6c7262be74.png)

![image](https://cloud.githubusercontent.com/assets/1214134/5968679/a885a5c4-a81a-11e4-8ed6-055aa7bb0d0e.png)

Works fine here. As you can see the info is retured from the server. Can you try directly against htpc manager and delete the cache? I have no idea why this doesnt work.

**Comment by Hellowlol** [comment]
I choose the Next ep since thats the one that its listed in show list inside sickrage. I wanted something familiar to the user

**Comment by kooimens** [comment]
Sickrage is using a 'Coming Episodes' tab. Maybe, that's better?

I added 2 Broke girls. No next episodes show up, nor in tv shows tab, nor in next aired tab. However, on my dash I can see them all? (three of them, 2 blacklist, 1 '2 broke girls'). I removed the blacklist and added it again and the result is even worse. Even no 'next ep' under the tv shows tab anymore.

I will try with a clean clone of the master.

**Comment by kooimens** [comment]
Done, no change. I can't see what's going wrong here.

**Comment by kooimens** [comment]
I enabled the sickbeard module to work with my sickrage setup and that is working fine.

**Comment by Hellowlol** [comment]
Is there any errors in the console log in the browser? Wtf is going on...

**Comment by Hellowlol** [comment]
Can you try this branch? https://github.com/Hellowlol/HTPC-Manager/pull/23 i think im a retard..

**Comment by kooimens** [comment]
Same result, unfortunately... :(

**Comment by Hellowlol** [comment]
Sure your cleared your cache?

**Comment by kooimens** [comment]
I cloned that branch in a new folder and ran it on a different port. HTPC-Manager created a new folder userdata in it. Of course, I removed cookies as well.

**Comment by Hellowlol** [comment]
Ctrl f5 would be enough. Mate I don't how to fix this..

**Comment by Hellowlol** [comment]
I know this would be a pita but I need a list off all your shows to I can add them to try to recreate the problem

**Comment by kooimens** [comment]
![shows](https://cloud.githubusercontent.com/assets/3150962/5977669/37612140-a89a-11e4-9c45-7020fd3f7097.jpg)

Is this enough? Btw, thanks for taking so much time to dig into this weird shit!

**Comment by Hellowlol** [comment]
Yeah, that would do.

**Comment by Hellowlol** [comment]
Can you update and try again?

**Comment by kooimens** [comment]
Yeah! It's fixed. Great job!
