### ISSUE TITLE
Change Suggested Text Color In Config Fields

### ISSUE THREAD

**Issue by brando56894** [Hellowlol/HTPC-Manager#201]
Not really an issue, more of a request, but would it be possible to change the suggested text color to something other than black or gray? I just spent about 15 minutes going through my logs, modifying stuff and wondering why htpc manager kept trying to connect to 192.168.1.100:/sickrage even though I (thought I) had the port number specified in the Port field. Turns out I was just looking at the suggested text and not the text that I had written. It tends to be quite confusing, at least for me.

**Comment by Hellowlol** [comment]
The placeholder text can look like values, especially on dark themes like slate, i want them grey, but ill see if i cant make em so grey you cant do wrong :P

**Comment by madclicker** [comment]
Just do away with the placeholders and put the info in the desc field. I did the placeholder before I realized what confusion it would create.

**Comment by Hellowlol** [comment]
I like them! :P But agree it isnt the first time someone has reported this.
@brando56894 what theme are you using?

**Comment by Hellowlol** [comment]
Hows your app coming along btw?

**Comment by madclicker** [comment]
Still on the Android learning curve. I believe this is the future of the HTPC.

**Comment by Hellowlol** [comment]
Im gonna buy it when it gets released :D

**Comment by madclicker** [comment]
So far I luv Android. I remember years ago talk about Linux on appliances and it didn't show up until Google did it. It finally grew up from a toy.

**Comment by Hellowlol** [comment]
Im a IOS user myself (except from a shitty tab, worst thing samsung ever made. (first 4g tab)), i think i was unlucky when i bought my s4. All the battery was drained within 3 hours. Feel free to chip in if your tired of writing classes! ;)

**Comment by madclicker** [comment]
LOL, not programming in Java.

**Comment by Hellowlol** [comment]
What programming language are you writing in?

**Comment by madclicker** [comment]
Python
Of course.

**Comment by madclicker** [comment]
You should come with me. It might get really good,

**Comment by Hellowlol** [comment]
To the dark side? No way. ;)

The reason that i dont use android, (the shitty tab is never used) and i want to be able to access the stuff on a computer aswell.

I do appreciate the offer tho :)

**Comment by madclicker** [comment]
Can't blame the OS for the hardware!

I think we're talking apples and oranges here.

I've never used any android toy phones or tablets; never will. 

The Android I'm talking about is all grown up. You do know the android kernel is linux? 

The TV box I just got has Android 4.4.2, 4 core cpu, 8 core gpu and plays 2160p! Delivered for $50! Also came with a Minix A2 AirMouse.

Burns only 10 watts max.

As far as accessing the stuff on the box, It's rooted and a few free apps give it nearly full linux capability. I have root ssh and sftp access. 

With PyTunes the box will be a complete HTPC.

**Comment by Hellowlol** [comment]
Decent hardware/features for the price!

**Comment by Hellowlol** [comment]
https://github.com/Hellowlol/HTPC-Manager/issues/229#issuecomment-115756928

**Comment by Hellowlol** [comment]
Closing this a placeholders are removed.
