### ISSUE TITLE
[Bug] Plex setting doesn't exclude specified libraries

### ISSUE THREAD

**Issue by ordinarygulp** [Hellowlol/HTPC-Manager#208]
On the Plex setting page, I try to exclude libraries (let's say "Home Videos"). However, those libraries' videos still appear in the program. I also tried the "Hide homemovies" option, but still nothing. All supposedly excluded libraries appear in this program. Running latest master2.

**Comment by Hellowlol** [comment]
@raysguy do you also have this issue?

**Comment by thatbritguy** [comment]
This works for me fine. Have got multiple libraries excluded and they work without issue.

**Comment by Hellowlol** [comment]
@d2dyno What have you tested? can you list the section titles and the one that you have excluded? Please read https://github.com/Hellowlol/HTPC-Manager#so-you-found-a-bug-great
