### ISSUE TITLE
Couchpotato History date 

### ISSUE THREAD

**Issue by kooimens** [Hellowlol/HTPC-Manager#21]
The couchpotato module shows a weird Histroy date for every event: NaN-NaN-NaN NaN:NaN

**Comment by Hellowlol** [comment]
Thanks for reporting the issue. I have no idea why that happens. It it still like that?

**Comment by kooimens** [comment]
Yes it is.

**Comment by Hellowlol** [comment]
Is cp installed on a windows computer?

**Comment by kooimens** [comment]
No, i'm running Ubuntu Server 14.04. With the latest version of CP

**Comment by Hellowlol** [comment]
Fixed in the last commit

**Comment by kooimens** [comment]
Tried you commit. It's not yet totally fixed. I get "2015-00-24 14:47" for a snatched movie. 00 should be 01 (month). At least much better than the weird shit before:D

**Comment by Hellowlol** [comment]
thanks!

**Comment by kooimens** [comment]
That last commit did it;) Tested, and working like it should!
