### ISSUE TITLE
Sonarr plugin not working

### ISSUE THREAD

**Issue by thejrose1984** [Hellowlol/HTPC-Manager#212]
Apparently my instance of HTPC Manager was 14 versions behind. After a successful update, I noticed Sonarr data was not showing up.

All I see is a single line with value "undefined/undefined"

No errors in the logs. Please fix.

**Comment by Hellowlol** [comment]
Its working fine here. There hasn't been any changes to the sonarr module as far as i can remember. Clear browser cache, if it still dont work: read the issue guidelines.

**Comment by thejrose1984** [comment]
Resolved when applying updates to FreeNAS OS and rebooting. Please note restarting HTPC Manager as well as the jail containing it did not resolve issue.

**Comment by Hellowlol** [comment]
Good to know. Thanks.
