### ISSUE TITLE
Bug - Settings page won't load

### ISSUE THREAD

**Issue by thatbritguy** [Hellowlol/HTPC-Manager#215]
Hi, in the latest master2 branch the settings page no longer loads.  When trying to navigate to that page I get a 500 Internal Server Error.  Same thing happens in both latest Safari and Chrome on Mac.  Tried on two different computers.

Here are the logs I  was able to pull.  All the errors points at the info module object being unable to find an attribute for "get_users".

http://pastebin.com/HTLCx3xn

**Comment by Hellowlol** [comment]
What psutil version and os? I haven't changed anything.

**Comment by thatbritguy** [comment]
Disregard this - after a few restarts and re-logins of htpc it's now working fine on both computers. Not sure what the issue was but seems to have fixed itself.

**Comment by Hellowlol** [comment]
Good :)
