### ISSUE TITLE
Synology install

### ISSUE THREAD

**Issue by brendann993** [Hellowlol/HTPC-Manager#216]
Hey guys, Wasn't sure where to put this. I Have compiled a htpcmanager-custom package for synology NAS. I have tested it on my server using this fork of HTPC-Manager(the reason I built the package) but no guarantee it will work for all or not break something so it is provided as is. It will ask you for git url on install so you can choose any fork you like. the spk and the source is [available here](https://github.com/brendann993/spksrc/releases/tag/1)

restarting by gui, and git updates appear to be working.

**Comment by brendann993** [comment]
and I just noticed someone already raised a pr to spksrc for a similar package so I probably wont bother :)

**Comment by Hellowlol** [comment]
Hi! Thank you for your time and effort I really appreciate it :). I'll use your link if the merge drags out.

**Comment by thejrose1984** [comment]
Good to know @brendann993 and you're correct that there's no guarantee because Synology NAS units can be fickle at times :)
