### ISSUE TITLE
Getting error: AttributeError: 'Process' object has no attribute 'get_memory_info'

### ISSUE THREAD

**Issue by paulgfrey** [Hellowlol/HTPC-Manager#217]
When enable psutils invoked, processes are not listed and this error "AttributeError: 'Process' object has no attribute 'get_memory_info'" is being logged.
Tried updating pip and psutils but both say they are already up to date.

**Comment by Hellowlol** [comment]
Please read: https://github.com/Hellowlol/HTPC-Manager#so-you-found-a-bug-great

**Comment by Hellowlol** [comment]
I see there is a new psutil version. They have deprecated get_memory_info. Downgrade psutil until this is fixed

**Comment by Hellowlol** [comment]
@paulgfrey All users need to upgrade psutil now.
