### ISSUE TITLE
Stats module, processes no longer work in latest update

### ISSUE THREAD

**Issue by coach0742** [Hellowlol/HTPC-Manager#219]
[LOG](http://pastebin.com/xtESFTQw): lines 1008-1022 have pertinent information.  

Branch: Master2
Python: 2.7.6
Commit HASH: 9c7a5daf3dc7f587ca76ab42dfd4ec00d360b632
Using psutil 3.0.1

Processes tab no longer shows any data. Opening the tab shows a blank page and enters an error into the log.  

Using Chrome Browser version Version 44.0.2403.54 beta

**Comment by Hellowlol** [comment]
The log is removed, but in short you need to upgrade to psutil 3.0.1

**Comment by coach0742** [comment]
Fixed the link for the log. I am updated to 3.0.1 as well.

**Comment by Hellowlol** [comment]
All good? I knew this update would make some issues. Been waiting for it :P But i cant bother to support every api from 0.7 to 3.0

**Comment by coach0742** [comment]
Nope, I think you missed my last comment. Updated link for log.  

I'm getting an attribute error.   

There is more in the log at the designated lines, but the main error is 

AttributeError: 'module' object has no attribute 'proc_name'

**Comment by Hellowlol** [comment]
what os are you using?

**Comment by coach0742** [comment]
It's running on Ubuntu server 14.04.2.

**Comment by Hellowlol** [comment]
Aw, crap that might be some windows only shit then. Oh well. After you have upgraded to psutil 3.0.1 can delete the log, then reboot. go to the stats module then post a new log?

**Comment by coach0742** [comment]
Sorry, you must have missed that in my first comment too. I am fully upgraded to psutil 3.0.1.

**Comment by Hellowlol** [comment]
Nope, check the version number in the log line 941 psutil version 2.1.3. Try a new shell or reboot the computer. I'd had to close the shell after i upgraded for it to work. Lets give it a try

**Comment by coach0742** [comment]
I've rebooted the computer several times since I upgraded. I don't understand how it could still be using an old version of psutil. I used pip, and everything shows 3.0.1 now.

It shows up perfectly when I import psutil on my own.

```
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.__version__
'3.0.1'
>>> 
```

**Comment by coach0742** [comment]
I rebooted again, same errors, same problem.

**Comment by Hellowlol** [comment]
wtf. can you uninstall psutil with pip then install it again? after you start htpc-manager again can you still see the import of 2.1.3?

**Comment by coach0742** [comment]
I'll try uninstalling and installing again.  

Yes, it still showed it importing 2.1.3 after the last reboot and starting htpc-manager.

**Comment by Hellowlol** [comment]
you didnt install old psutil with apt-get or something?

**Comment by coach0742** [comment]
Haha, we were looking way too high on the log. Look at the timestamp for that import of 2.1.3. It was earlier today before I upgraded. I deleted the log and I'll post a new one with _only_ this startup on it.  

It is still showing the same attribute error though.

**Comment by Hellowlol** [comment]
I saw the time, just i just figured it was the time difference :P

**Comment by coach0742** [comment]
[new log](http://pastebin.com/7Fem5dc3)  

Ok, this is strange. It doesn't show it importing psutil at all now.

Am I missing something? I don't understand what's going on now.

**Comment by coach0742** [comment]
I just completely deleted htpc-manager from my server, uninstall psutil, reinstalled both, restarted, and started it up. Even before enabling the stats module, I'm getting that attribute error. I'm going to try it in a fresh virtual machine as well, but I don't think it's a problem on my end.

**Comment by Hellowlol** [comment]
I just pushed a update, can you try that one? post a new log if it doesnt work.

**Comment by coach0742** [comment]
Perfect. Works great now.  

Thanks for your help!

**Comment by Hellowlol** [comment]
Good :)
