### ISSUE TITLE
Newznab search is showing nzbget icon although it is not enabled

### ISSUE THREAD

**Issue by kooimens** [Hellowlol/HTPC-Manager#22]
The newznab module should not show a 'send nzb to nzbget' if nzbget is not enabled.

**Comment by Hellowlol** [comment]
It intended for it to be like that but I agree, it should be like torrent search

**Comment by Hellowlol** [comment]
Thanks for testing it, I don't notice everything.

**Comment by kooimens** [comment]
I will, no problem! To be honest, I like your branch more than that from styxit. Your branch don't hang on refreshes for some seconds if I hit F5 for example or if I am behind a reverse proxy. I think I should test the headphones commits with your branch.

**Comment by Hellowlol** [comment]
Well your welcome to contribute. :), The developments seems to have stopped and merges was way to  slow, that why i stopped after 72 prs

**Comment by Hellowlol** [comment]
Fixed in the last commit

**Comment by kooimens** [comment]
Pulled the last commit, can confirm it's fixed. Thanks a lot! And yeah, you're delivering a lot of great work so the merges should be a lot faster. Most of the time just a one click on the button;) I will stick to your branch now, definitely!
