### ISSUE TITLE
Loading couchpotato module freezes entire program, requires restart

### ISSUE THREAD

**Issue by coach0742** [Hellowlol/HTPC-Manager#220]
[LOG](http://pastebin.com/fpYtAFfN) only pasted relevant information.

Branch: Master2
Python: 2.7.6
Commit HASH: 9c7a5da
Using Chrome Browser version Version 44.0.2403.54 beta

After opening the couchpotato page, it will start loading for a moment, and then I am not able to go to any other modules, load any more tabs. The entire thing freezes up. HTPC-Manager requires a restart to use it again.

**Comment by Hellowlol** [comment]
Is that the entire log? Seems to work fine here :(

**Comment by Hellowlol** [comment]
Have you verified that cp is running?

**Comment by coach0742** [comment]
Yes, I am positive that couchpotato is running. Like I said, it will load up my wanted movies, and suggestions. Then it freezes and doesn't do anything else. The log stops here because htpc-manager no longer does anything.

**Comment by coach0742** [comment]
Nevermind, if I leave it trying to load for about 20 mins, it starts working again. This only happens the first time I load the module after starting htpc-manager.  

It has to be something on my end. 

Thanks

**Comment by Hellowlol** [comment]
Im not really sure, sometimes cp is really slow, but it hasnt happen for me for 1-2 months. Are you using windows?
