### ISSUE TITLE
vnstat wrong date?

### ISSUE THREAD

**Issue by coach0742** [Hellowlol/HTPC-Manager#221]
To be honest, I'm not even sure if this is a problem with Htpc-Manager or vnstat.  

However, every time I install vnstat and enable the module, no matter what OS I use. The date in the graphs is always exactly one month off.  

I'm not sure what to put in this issue as there are no errors in the log files.  

![screenshot 2015-06-23 at 6 05 37 pm](https://cloud.githubusercontent.com/assets/1206702/8320124/0a0e47da-19d4-11e5-87c5-c776d2700e6c.png)

Here's a screenshot of what I mean. The area in question is the "day" graph in the upper middle

**Comment by Hellowlol** [comment]
This probably my bad. Can go to vnstat/dumpdb and parse the content to pastebin. It's the month off everywhere is just "last 30 days"

**Comment by Hellowlol** [comment]
I think the error is in https://github.com/Hellowlol/HTPC-Manager/blob/master2/interfaces/default/js/vnstat.js#L52 I believe I should have set + 1 there as months are zerobased indexed

**Comment by Hellowlol** [comment]
@coach0742 Can you update (rememeber to force browser cache) then try again?

**Comment by coach0742** [comment]
Well, it's closer.. ish haha.  

![screenshot 2015-06-24 at 12 30 50 am](https://cloud.githubusercontent.com/assets/1206702/8323968/6bd948be-1a08-11e5-9c09-4786821e04a4.png)

It now counts down today to last month.

**Comment by Hellowlol** [comment]
Crap, well when was data used? can you go to vnstat/dumpdb and paste the content to pastebin?

**Comment by Hellowlol** [comment]
Seems right i my head, its suppose to show the usage the last 30 days. just as the last 24 hours and  12 months do :) Edit I see the way the data is displayed is not consisted.

**Comment by Hellowlol** [comment]
@smdion I'm pinging you since you requested the module. Are the dates off for you too? What direction do you want to read the chart?

**Comment by Hellowlol** [comment]
My assumption regarding hours was wrong. Hours.hour does not follow the same setup as the months, days. (Where id 0 always is current month/day and it includes the date in the json response.) instead it follows current hour. So say you download a huge file at 1700 hours that would have id 17 (or 16 depending on the "tick")

**Comment by Hellowlol** [comment]
Nice setup btw ;)

**Comment by coach0742** [comment]
/r/homeserver?

**Comment by Hellowlol** [comment]
Yeah.

**Comment by Hellowlol** [comment]
Can you update verify that its fixed?

**Comment by coach0742** [comment]
Its still not fixed for me. I'll post a screenshot in a second. Now the graph starts on 5/31 and has today as the 7th.

**Comment by Hellowlol** [comment]
Ok, its works fine here. Make sure you have cleared your browser cache. and go to http://ip:port/vnstat/dumpdb grab the output and post it on pastebin to i can recreate your problems with your data.

**Comment by Hellowlol** [comment]
ah, fuck i can see that the tables are off, i havnt even checked them...charts are ok tho

**Comment by Hellowlol** [comment]
@coach0742 Im closing this as it should be fixed now. If you still having issues you need to http://ip:port/vnstat/dumpdb and save the response to a gist/pastebin
