### ISSUE TITLE
Backup/Restore Feature?

### ISSUE THREAD

**Issue by thejrose1984** [Hellowlol/HTPC-Manager#222]
Had to do some heavy snapshot restores and other high level maintenance on my FreeNAS and noticed HTPC stopped working and needed a reinstall. Any chance you can add an option to export/import settings to a file?

**Comment by Hellowlol** [comment]
Everything is in the db, so you can just copy that over to the new install and you should be good to go. Isnt that enough or did you have some thing in mind?

**Comment by thejrose1984** [comment]
You mean a SQL dump from SQLite?

**Comment by Hellowlol** [comment]
No inside the htpc manager folder there is a folder called userdata, inside that folder is database.db. Just copy that file :)

**Comment by thejrose1984** [comment]
Gotcha - I'll make a cron job/script from the FreeNAS to handle this then.
