### ISSUE TITLE
Unable to contact Plex (#14)

### ISSUE THREAD

**Issue by thejrose1984** [Hellowlol/HTPC-Manager#223]
Branch = master2
OS = FreeNAS / FreeBSD
Python = 2.7.9
Event = fresh install of HTPC and could not connect to Plex
Expected result = connect to Plex
Issue is not browser specific (tested in Google Chrome and IE10)
Secure Connection set to Preferred
Reboots of HTPC and PMS have been done and did not fix issue
http://pastebin.com/SAuuZpGw

**Comment by Hellowlol** [comment]
Is that  the full log? Is this a debug log? Set logging to debug in the settings page, restart htpc manager, then download the entire log from the logpage. You need to check your settings see 2015-06-24 08:56:26     modules.plex    ERROR   Unable to fetch all movies! Exception: HTTP Error 401: Unauthorized. Are you using plex home?

**Comment by Hellowlol** [comment]
There are also alot of other connection errors as ip and port is missing from sonarr settings fx

**Comment by thejrose1984** [comment]
Yes, that is the full debug log from a relatively fresh HTPC manager install. Plex was the only thing that was setup at the time. The issue appears to have fixed itself as no steps were taken.
