### ISSUE TITLE
Connecting to SickRage

### ISSUE THREAD

**Issue by EZarnosky** [Hellowlol/HTPC-Manager#224]
My sysem have HTPC Manager and SickRage installed locally with a Nginx reverse proxy set up. I have I am connecting to HTPC Manager with SickRage set up like:

<pre>
Enabled: Checked
Menu name: TV
IP/HOST: localhost
Port: 8081
Basepath: /backend/tv
API key: (copied from SickRage but omitted from this post)
Use SSL: Unchecked
Reverse proxy link: http://localhost:8008/backend/tv
</pre>

When i test the configuration it fails. In the logs it shows this:

<pre>
modules.sickrage    ERROR   Unable to contact sickrage via http://localhost:8081/backend/tvapi/********************************/?cmd=sb.ping
</pre>

HTPC Manager does nto place a / at the end of the path - it should be http://localhost:8081/backend/tv/api. I fixed the test failure by adding the / to the end of the basepath in the setting (Basepath: /backend/tv/).

But all that does not resolve the underlying issue. When i open the SickRage page it is stuck loading the shows. When I look at the logs I see this:

<pre>
modules.sickrage    ERROR   http://localhost:8081/backendtv/api/********************************/?cmd=future
</pre>

 As you can see from the log it is changing the path from http://localhost:8081/backend/tv/ to http://localhost:8081/backendtv/.

**Comment by Hellowlol** [comment]
You have a unnormal basepath. Ill fix this later today until that, you can use any basepath that doesn't contain / as its auto removed to help formatting the basepath correctly. Fx /tv/ or tv will work fine :)

**Comment by EZarnosky** [comment]
I know, I am just being 'organized' with my structure on my webserver. all the frontend stuff gets a url right off the hostname. All the backend stuff is nested in the /backend/ path.

Thanks

**Comment by Hellowlol** [comment]
Fixed in the latest commit.

**Comment by EZarnosky** [comment]
andI just finished editing my nginx settings... damn your fast

**Comment by Hellowlol** [comment]
Yeah, but did it from my phone :P it was a easy fix. I did forgot about the test button, im gonna fix that now.

**Comment by Hellowlol** [comment]
I cant see there is any wrong with the ping now, can you test it again please?

**Comment by EZarnosky** [comment]
I think it was old data, sickrage is fine since I swithced it to the /tv. I will try switching to the /backend/tv shortly.
