### ISSUE TITLE
Installing smartmontools on Raspberry/Banana Pi (Debian Wheezy)

### ISSUE THREAD

**Issue by EZarnosky** [Hellowlol/HTPC-Manager#227]
I thought I would share how to get the smartmontools installed on a Debian Wheezy since there are no guides out there. You would think it would be easy, but Debian Wheezy apt repo has version 5.41, HTPC Manager requires 5.42+.

After completely hosing my linux install trying to use the version on the Debian Jessie repo, I flashed the sd card from a backup and dug a little deeper into the backport repos.

Debian warns that the backport servers house experimental and possibly unstable versions of packages. However I did get smartmontools to install with no problems to my raspberry.

when logged in as a root user run the following command (you can simply copy and paste into your favorite ssh terminal).
1. We add the backport repo - this creates a file that can be deleted later if you want (not required)
   
   <pre>echo "deb http://http.debian.net/debian wheezy-backports main" > /etc/apt/sources.list.d/wheezy-backports.list</pre>
2. We add a preferences file so that the backport server is only ever used when it specified in the command line - this creates a file that can be deleted later if you want (not required)
   
   <pre>echo "Package: *\nPin: release n=wheezy-backports\nPin-Priority: -1" > /etc/apt/preferences.d/wheezy-backports.pref</pre>
3. Update the repo list, then install smartmontools (the -t wheezy-backports specifies to use the backports version, same label as in the preferences file we created)
   
   <pre>apt-get update && apt-get install -t wheezy-backports smartmontools -y</pre>

My system shows that smartmontools 6.3 is installed.

After that you just need to restart your HTPC Manager install and enable the S.M.A.R.T. otion in the Computer Stats setting. Provided you have smartctl in your path (see: http://www.troubleshooters.com/linux/prepostpath.htm for directions on that).

**Comment by Hellowlol** [comment]
Awesome thanks! Would you mind adding that to the wiki?

**Comment by EZarnosky** [comment]
sorry, i was being brain dead. yeah, gimme a couple minutes.

**Comment by EZarnosky** [comment]
Wiki page added

**Comment by Hellowlol** [comment]
ty

**Comment by EZarnosky** [comment]
np, i figure I gotta create some good will. I plan to submit a fair number of feature requests once I get my new download station build stable.

**Comment by Hellowlol** [comment]
Your +1 now atleast. :D
