### ISSUE TITLE
Sonarr not updating

### ISSUE THREAD

**Issue by stempleton** [Hellowlol/HTPC-Manager#229]
Sonarr api settings are correct and I get a green check when testing but going to that section the page will not upload and just spins. I also can't search for anything.

**Comment by Hellowlol** [comment]
Hi! Thanks for reporting this. 

Can you read the issue guidelines and update your post?

**Comment by stempleton** [comment]
Sure.

Branch: Master2
not sure where to find commit hash
Operating System: Windows 8.1, python v2.7
Browser: Chrome 43
When clicking on Sonarr section no information populates. It just sits there trying to load. Searching brings up no results either.
Log file: https://www.dropbox.com/s/s2k1k6yn879h3lg/htpcmanager-2.txt?dl=0

**Comment by Hellowlol** [comment]
You have forgot to set a port mate. :)

**Comment by stempleton** [comment]
That's so weird. It was showing 8989 in the Sonarr settings and I made no changes to make it stop working, but I just manually added the port again and it's now working...weird. Thanks for the help though!

**Comment by Hellowlol** [comment]
I'm happy to help :)
