### ISSUE TITLE
Warning message in HTPC Manager Log

### ISSUE THREAD

**Issue by EZarnosky** [Hellowlol/HTPC-Manager#230]
Error message:

<pre>
htpc.updater    WARNING error: The requested URL returned error: 403 while accessing https://github.com/Hellowlol/HTPC-Manager.git/info/refs
</pre>

When you visit https://github.com/Hellowlol/HTPC-Manager.git/info/refs you see the message:

<pre>
Please upgrade your git client.
GitHub.com no longer supports git over dumb-http: https://github.com/blog/809-git-dumb-http-transport-to-be-turned-off-in-90-days
</pre>

Seems that Github does not like your git requests one of the functions are making.

**Comment by Hellowlol** [comment]
I don't see that in my log. Have you tried updating git?

**Comment by EZarnosky** [comment]
I believe that was me trying to force an update. I'll try to recreate the error again.

**Comment by Hellowlol** [comment]
Full log debug log please :)

**Comment by EZarnosky** [comment]
i just spent about 20 minutes trying to recreate it, no such luck. Could there be a alternate update link that used if the primary is unreachable.

I will start up htpc in debug mode and leave it that way for the time being. should it occur again I'll have a detailed log for you.

**Comment by EZarnosky** [comment]
I just looked at my SickRage Logs... I was getting the same error

<pre>
CHECKVERSION :: git fetch origin returned : error: Couldn't resolve host 'github.com' while accessing https://github.com/SiCKRAGETV/SickRage.git/info/refs
</pre>

Looks like GitHub was having issues...
