### ISSUE TITLE
vnStat interface filter not working

### ISSUE THREAD

**Issue by EZarnosky** [Hellowlol/HTPC-Manager#231]
I have multiple interfaces on my linux system, bot really only want to see stats on one - eth0. In the interface box I have manually entered eth0m but I still see tunl0 (another interface) in the vnStat view

**Comment by Hellowlol** [comment]
This is intended. The interface is just for the speed nothing else, if you wish to filter more you can edit vnstat config.

**Comment by EZarnosky** [comment]
I'm all about clutter... I hate it in my interfaces :P

I'll look into filtering it out, then updating the wiki. might be a couple days, my TODO list is huge.

**Comment by Hellowlol** [comment]
Np, I'm happy for all the help I can get

**Comment by Hellowlol** [comment]
fix https://github.com/Hellowlol/HTPC-Manager/blob/master2/modules/vnstat.py#L37

**Comment by Hellowlol** [comment]
@EZarnosky Can you test if the filter works now?

**Comment by Hellowlol** [comment]
Should work now, feel free to reopen if that isnt true
