### ISSUE TITLE
Sick* request - TV Show Tab Filtering

### ISSUE THREAD

**Issue by EZarnosky** [Hellowlol/HTPC-Manager#233]
Allow/enable filtering on the TV Shows tab.

Example Not Show/Show Status = Ended/Continuing.
Example Not Show/Show Network = NBC/CBS/etc. (Multi-select network)
Example Not Show/Show Quality = SD/720p/etc. (Multi-select quality)

**Comment by Hellowlol** [comment]
Btw, you know you can sort the table?

**Comment by Hellowlol** [comment]
I'm a bit pressed for time so it might take some day until this is done. 
In short pretty much every table in htpc manager will be filter/searchable. 

I'm done with sickrage and sonarr. I'm sure there many bugs regarding this so I'll just push it when the worst are fixed and we have to fix other issues as they come

**Comment by EZarnosky** [comment]
That sounds great. Thanks for giving attention to te features I keep pingign you with.

i fully understand about being pressed for time. I have been doing an 84 hour work week for the last 2 weeks and another 2 weeks to go... I hate site migrations, but I hate multisite migrations more.

**Comment by Hellowlol** [comment]
@EZarnosky @raysguy Would you mind testing the latest update and let me know if there are are errors regarding sorting? (im sure there are shitloads :P)

**Comment by EZarnosky** [comment]
It will take a few days, I don't have a day off until Sunday :(

Which branch should I use? Or did you just add these to the default Master2 branch?

**Comment by Hellowlol** [comment]
It's in the master2 branch already :P
