### ISSUE TITLE
Password Cleartext in Logs

### ISSUE THREAD

**Issue by kars85** [Hellowlol/HTPC-Manager#236]
I'm running the latest master2 branch and was going through the logs to troubleshoot a separate issue with Deluge.

However, I noticed that the logs capture the password in clear text if the authentication to the WebUI failed.  Is this by design? 

![2015-07-01_08-51-15](https://cloud.githubusercontent.com/assets/6616548/8456142/106bee9c-1fcf-11e5-9b9c-766caaea7877.jpg)

**Comment by Hellowlol** [comment]
Yes, this is intended. I wanted to see what username and password a person attempted (check if any is trying to login to the site. typical used if htpc-manager is exposed to www)

In this case the username is masked too so i guess that is listed in one of the passwords fields. This only happens on failed attempts.

**Comment by kars85** [comment]
OK sounds good!  Thanks!

**Comment by Hellowlol** [comment]
You can find the code here: https://github.com/Hellowlol/HTPC-Manager/blob/master2/libs/cherrypy/lib/auth2.py#L28
