### ISSUE TITLE
vnstat doesn't display graphs

### ISSUE THREAD

**Issue by jarlave** [Hellowlol/HTPC-Manager#237]
I enabled vnstat but it only shows the stats down in the table, no graphs above.
Here is the screenshot from the vnstat tab and the about page
![2015-07-02_21-38-09](https://cloud.githubusercontent.com/assets/3617501/8486627/30024b74-2106-11e5-9dbf-f448abc0e2b3.png)
![2015-07-02_21-59-44](https://cloud.githubusercontent.com/assets/3617501/8486682/9a185a12-2106-11e5-806a-f28efd870712.png)

My browser is Google Chrome Version 43.0.2357.130 m (64-bit)
Here is the log: http://pastebin.com/7tLeVnWe
vnstat dumpdb: http://pastebin.com/UWgHEVja

**Comment by Hellowlol** [comment]
So where did you grab the dumpdb? Its in the wrong format. Can you grab it from your http://yourip:yourport/vnstat/dumpdb

what vnstat version do you have?

**Comment by jarlave** [comment]
http://pastebin.com/4w2LngPS

hope this is now the right dump.

now it seams to work but it shows the wrong dates
![2015-07-03_09-58-43](https://cloud.githubusercontent.com/assets/3617501/8494981/215a599a-216a-11e5-8b84-41b162513e99.png)

In germany it is now 10:00 am 03.07.2015

**Comment by Hellowlol** [comment]
Can you force rehresh browser cache on that page? And see if it works?

**Comment by jarlave** [comment]
nothing changed after force refresh

Tried it on Firefox and Opera (both portable) too, the same problem.

**Comment by Hellowlol** [comment]
Ok, the problem is that there isn't enough data. I was under the impression that days returned 30 days with 0 in usage. It does not :(, Ill think i saw a config option about that, it it isnt ill just check how many dayes and feed it trash like we do with months

**Comment by Hellowlol** [comment]
http://humdi.net/vnstat/man/vnstat.conf.html

TrafficlessDays
Log days without any traffic to daily list. 1 = enabled, 0 = disabled. (vnstat and vnstatd only)

**Comment by Hellowlol** [comment]
Im gonna close this as you can fix this your self by using the link. Set TrafficlessDays to 1 in the config.

**Comment by jarlave** [comment]
it is already enabled

**Comment by Hellowlol** [comment]
What version do you use?

**Comment by jarlave** [comment]
vnstat 1.11

**Comment by Hellowlol** [comment]
Thats old. Try to update it and see if that option works then. If not make a issue on https://github.com/vergoh/vnstat. If it doesnt get fixed ill make a work around.

**Comment by Hellowlol** [comment]
Fuckit, it's a easy fix, I'll do it shortly.

**Comment by Hellowlol** [comment]
@areon  Can you update, clear browser cache and try again?

**Comment by jarlave** [comment]
Great!
now it look like this
![2015-07-03_15-15-33](https://cloud.githubusercontent.com/assets/3617501/8499775/707aa666-2196-11e5-823e-5fa5a3a17139.png)

is it normal for the month that it starts in August?

**Comment by Hellowlol** [comment]
Yes. the graps is like this:
| last 12 months from current month | last 30 days from current day | last 24 hours from current hour

**Comment by jarlave** [comment]
Ok, thanks for your help :)

**Comment by Hellowlol** [comment]
Im happy to help!

**Comment by Mcpoowl** [comment]
So what was the update that fixed the graphs? I'm running into the same problem. Running vnstat version 1.12, but apt-get doesn't know of any newer versions.

**Comment by Hellowlol** [comment]
@Mcpoowl please open a new issue. This Issue was related to a old vnstat version (the commands had changed)

**Comment by Mcpoowl** [comment]
I'm sorry. Came to the conclusion my setup was wrong. Seems fixed now!
