### ISSUE TITLE
FreeBSD init script?

### ISSUE THREAD

**Issue by thejrose1984** [Hellowlol/HTPC-Manager#238]
Any chance you can add a folder called `init` with the code that houses the init scripts available? Also, I'm working on a script for FreeBSD/FreeNAS and wondering if it can be added to your code once finished and tested?

**Comment by Hellowlol** [comment]
can do. But can't you need when send the or regarding FreeBSD?

**Comment by thejrose1984** [comment]
But can't you need when send the or regarding FreeBSD???

**Comment by Hellowlol** [comment]
Haha. Sorry. Yes it can be added. Just make folder and move the init scripts  there when you add the Freebsd script.

**Comment by Hellowlol** [comment]
Im gonna close this as you can make the folder when/if you send a pr regarding the init script.

**Comment by Hellowlol** [comment]
@thejrose1984 Have you made a init script for your freenas? If so can you make a pr or dump it somewhere i can grab it.

**Comment by thejrose1984** [comment]
Haven't had time tbh...too much shenanigans afoot! :)

**Comment by Hellowlol** [comment]
Ok! I added a init folder ^^

**Comment by thejrose1984** [comment]
Found something that the HTPC init script can be based on:
https://github.com/RuudBurger/CouchPotatoServer/blob/master/init/freebsd

**Comment by thejrose1984** [comment]
Got a working init script for FreeBSD/FreeNAS but unable to upload...

**Comment by Hellowlol** [comment]
Thats fine. Can you just past it to a gist or something?

**Comment by thejrose1984** [comment]
Filename = initd.freebsd
http://pastebin.com/Q8njF2jY

**Comment by Hellowlol** [comment]
Thanks. I'll add it later today
