### ISSUE TITLE
misc stuff

### ISSUE THREAD

**Issue by Hellowlol** [Hellowlol/HTPC-Manager#245]
fix wrong comments like 24 h disable cache
sonar view add Downloaded to green make quality pretty, naming is HD-720p and HDTV-720p
newnab: default to pubdate if age is missing
dockerfile: correct psutil version

**Comment by thatbritguy** [comment]
Just FYI I’ve prettified and corrected quality labels as part of the theming :)

**Comment by Hellowlol** [comment]
Thanks!

**Comment by Hellowlol** [comment]
all clicks on menu link opens new page...
