### ISSUE TITLE
sqlite erro

### ISSUE THREAD

**Issue by blindpet** [Hellowlol/HTPC-Manager#246]
Updating to systemd scripts and getting this error

`select, keepConnection=False)
 File "/opt/HTPCManager/libs/sqlobject/dbconnection.py", line 717, in __init__
self.dbconn._executeRetry(self.rawconn, self.cursor, self.query)
File "/opt/HTPCManager/libs/sqlobject/sqlite/sqliteconnection.py", line 210, in _executeRetry
etry
raise OperationalError(ErrorMessage(e))
sqlobject.dberrors.OperationalError: no such table: newznab_indexers`

**Comment by Hellowlol** [comment]
That table should exist. Is this a old db that you have used with styxit version. Tried with a clean install. Fair warning I know nothing about init/system scripts. That table is created the same way as the other :(

**Comment by f-society** [comment]
I am getting the same error :( I can't get it to work! But I can use styxit version...

**Comment by blindpet** [comment]
I am using a fresh install and have only used your repo. The systemd script I'm using looks like this

``` [Unit]
Description=HTPCManager Daemon

[Service]
User=orangepi
Group=orangepi

Type=forking
GuessMainPID=no
ExecStart=/usr/bin/python /opt/HTPCManager/Htpc.py --daemon

[Install]
WantedBy=multi-user.target
```

**Comment by blindpet** [comment]
When I run it manually it's the same issue

`Traceback (most recent call last):
  File "Htpc.py", line 254, in <module>
    main()
  File "Htpc.py", line 166, in main
    htpc.settings = Settings()
  File "/opt/HTPCManager/htpc/settings.py", line 31, in __init__
    self.updatebl()
  File "/opt/HTPCManager/htpc/settings.py", line 77, in updatebl
    for ii in nab:
  File "/opt/HTPCManager/libs/sqlobject/sresults.py", line 181, in __iter__
    return iter(list(self.lazyIter()))
  File "/opt/HTPCManager/libs/sqlobject/sresults.py", line 189, in lazyIter
    return conn.iterSelect(self)
  File "/opt/HTPCManager/libs/sqlobject/dbconnection.py", line 472, in iterSelect
    select, keepConnection=False)
  File "/opt/HTPCManager/libs/sqlobject/dbconnection.py", line 717, in __init__
    self.dbconn._executeRetry(self.rawconn, self.cursor, self.query)
  File "/opt/HTPCManager/libs/sqlobject/sqlite/sqliteconnection.py", line 210, in _executeRetry
    raise OperationalError(ErrorMessage(e))
sqlobject.dberrors.OperationalError: no such table: newznab_indexers`

**Comment by Hellowlol** [comment]
@f-society have you been using my fork successfully in the past? @blindpet was this working before? Or did it fail on a clean install?

I have a sneaking fealing that it might be related to my fix for nzb apikey in the log..

**Comment by f-society** [comment]
I had it running on Ubuntu Server just fine then switched it over to Windows 8.1 64bit

**Comment by blindpet** [comment]
I have only ever used your repo for testing and always use a clean install. 

I have never seen this error before and no users have mentioned it in my comments section.

Not sure how old that commit you made is that you suspect but hope you can fix it soon :)

**Comment by Hellowlol** [comment]
@blindpet can you clone and test again? I hope I didn't break anything, I'm out walking the dog. If this doesn't do it I don't have time until tomorrow.

**Comment by Hellowlol** [comment]
Ah crap, it will not work.. Wrong class lol. Tomorrow then, in the mean time you can create the table your self :)

**Comment by Hellowlol** [comment]
Ok, its works now, its more hackish then id like but it will have to do for now. Im off to bed

**Comment by Hellowlol** [comment]
@blindpet @f-society can you confirm that it works now?

**Comment by f-society** [comment]
It is working beautifully now! Thanks

**Comment by Hellowlol** [comment]
Np, if you break it you fix it :P

**Comment by blindpet** [comment]
confirmed working here too, thanks
