### ISSUE TITLE
CDN Checkbox - all JS breaks - cant disable it after

### ISSUE THREAD

**Issue by fma965** [Hellowlol/HTPC-Manager#247]
Enable CDN checkbox doesn't uncheck once checked and when checked all hell breaks loose and all JS stops working, basically making it impossible to revert the change. all menu links go etc.

**Comment by thatbritguy** [comment]
What setup are you running HTPC on and which branch are you using?

The CDN option works flawlessly here.  Can be enabled or disabled without any ill effects.

**Comment by fma965** [comment]
Master2
http://remote.cyanlabs.net/htpc (reverse proxy via nginx)
Windows Server 2012 R2

**Comment by fma965** [comment]
Can i manually disable the CDN value? I tried with SQLite browser but it didn't disable it.

**Comment by Hellowlol** [comment]
Does it work directly without the reverse proxy? (just test that it hasn't cached something)

**Comment by Hellowlol** [comment]
Yes you can edit it manually.

**Comment by thatbritguy** [comment]
If you can copy the logfile contents and dump them onto pastebin I’m sure @Hellowlol will be able to figure out the problem for you.

**Comment by fma965** [comment]
HellowLol how do i edit it manually? editing the database didn't work.

Getting logs

**Comment by fma965** [comment]
not much to show... http://pastie.org/private/sybhv8c9mcgpobg5lgkwng

**Comment by Hellowlol** [comment]
I use a program used sqlite browser set key to 0

**Comment by fma965** [comment]
Yeah changing that to 0 worked, everything has come back now.

Here look, http://remote.cyanlabs.net/htpc - username: test / password: test123

then once you seen it all working, let me know and i will renable CDN and restart my windows service then you can see everything is broken.

**Comment by fma965** [comment]
just realised i should enable debug logging, didn't notice. Let me know if/when your done seeing it for yourself then i will enable debug and get a log if you want.

**Comment by Hellowlol** [comment]
The cnd option will be broken until I have fix it. Leave it disabled for now, I'll ping you when it's fixed.

**Comment by fma965** [comment]
OK no worries, i'm ok with it not working for now, I code stuff myself but not python so i know how annoying bugs are when not reported :).

I've been thinking this has been related to my reverse proxy for ages but then finally noticed it was the CDN option and am relieved as it makes my life easier :)

**Comment by Hellowlol** [comment]
http://cdnjs.com/libraries/jquery.tablesorter
Remove tablesorter from js folder should only be in libs

**Comment by Hellowlol** [comment]
@raysguy @Fma965 Can any confirm that it works now? (with cnd option enabled)

**Comment by fma965** [comment]
hi i can check for you, give me 5mins

**Comment by fma965** [comment]
Hi yes it's working now :)

**Comment by Hellowlol** [comment]
Thank you for confirming that.
