### ISSUE TITLE
Various ideas

### ISSUE THREAD

**Issue by fma965** [Hellowlol/HTPC-Manager#248]
I currently have 1 custom link for ArgusTV and i was thinking it would be cool to make it load in a iframe inside the "content" area of HTPC Manager interface like where sonarr etc shows it's content this way it can keep the navigation bar at the top of the page.

I think AJAX would have issues so iframe seems best.

I would make it my self but i really don't know python, any hints or tips on where i could begin? 

---

Any chance we can have a "latest music" look like the "Latest Movies" maybe with the album art to the left then text to the right? what files would this use? i can work on a idea and maybe send a PR if it's good enough.

**Comment by Hellowlol** [comment]
1. And add a function inside the root.py file that returns the HTML add a parameter that so the href can be set as source on page load. You would also need to make a function that prevent that page from opened and that calls the function inside root.py. Does this make sense? I can post some code for you later. This I frame thing should be a option and off by default.  https://github.com/Hellowlol/HTPC-Manager/issues/90
2. Latest music from what? Plex or kodi? You need to check the size of the original image first. If it look ok you can pretty much  copy the entire latest movie. I think this was suggested before or someone did make a mock up of it. I'll see if I can't find that.

PRS are very welcome ;) I help you if needed.

**Comment by Hellowlol** [comment]
@Fma965 Its up to you to finish this one: https://github.com/Hellowlol/HTPC-Manager/tree/iframe ;) just (css work and deleting one print statement)

**Comment by Hellowlol** [comment]
@kooimens Is the iframe thing something your still interested in?

**Comment by l-t-k** [comment]
Thanks for the ping! Tbh, yes. I would like to load Owncloud within HTPCManager, so iframes would be great!

**Comment by Hellowlol** [comment]
Maybe you wanna checkout the iframe branch and see if that was what you had in mind.
Remember to active it in the general tab as its off by default (since i dont like i frames)

**Comment by l-t-k** [comment]
Nice, I will give it a try tomorrow.

**Comment by fma965** [comment]
I'll get the HTML/CSS sorted for iframe branch then PR you the changes.

**Comment by fma965** [comment]
Not to be a pain but can any 1 give me a simple "how to make PR's" step by step, starting from cloning your repo/branch. if not i will try and figure it out

**Comment by fma965** [comment]
![image](https://cloud.githubusercontent.com/assets/1707290/8679606/7a2fe62e-2a53-11e5-97b6-a763e6a0de77.png)

**Comment by fma965** [comment]
Iframe PR Request https://github.com/Hellowlol/HTPC-Manager/pull/250

**Comment by Hellowlol** [comment]
@kooimens what you think about the screenshot?

**Comment by Hellowlol** [comment]
Btw I liked that the search field on your site always was available even in mobile view. I'll have to do that or move the search field to the top.

**Comment by fma965** [comment]
Stupid question but what does the search even do on HTPC Manager? also i'll work on the other things suggested in the first post shortly

**Comment by Hellowlol** [comment]
It depends on what module your in from the dashboard you will search your newznab indexers, from the torrent page it will search for torrents, in xbmc, plex, sr, qbittorrent module it will filter current window. So say you have 1000 movies and don't want to scroll down to x you can just start typing the movie name.

**Comment by fma965** [comment]
Ahh that explains it, i don't use usenet so haven't actually been able to test it on dashboard and never thought to try it on other pages.

**Comment by l-t-k** [comment]
How do I enable this? In the general tab I enabled iframes (allow iframe). And that's it? I can´t see other options and the links aren´t opened within the iframe.
I think it should be useful to at least select for each ''Other app"  whether it should be opened in the iframe or not. 

I´m running latest version of master2 branche

**Comment by Hellowlol** [comment]
Tried force refreshing browser cache?

**Comment by fma965** [comment]
you may need to remove the apps then re-add them, not sure why but that seemed to fix it for me, i wonder if maybe that just made the browser force a refresh?

Press CTRL + R or CTRL + F5 to force refresh

**Comment by l-t-k** [comment]
All tried, nothing worked. I took a clean fresh empty install op master2. Removed all cookies and tried several times, without any luck.

**Comment by Hellowlol** [comment]
If it still don't work I'm sure I messed it up when I tried to fix the normal links. (Wrong selector)

**Comment by fma965** [comment]
yeah he's right it is broke again :( @Hellowlol why you break it :P only joking..

but yeah it's not working no more, just normal link instead of iframe.

**Comment by Hellowlol** [comment]
@kooimens Works now :P

**Comment by l-t-k** [comment]
Tested. Perfect! However, it would still be nice to set this option for each ''other apps'' link individually.

**Comment by fma965** [comment]
it would be cool to make it so a middle click (which is open in new tab) still opened in a new tab rather than being overridden with the JS code.

**Comment by fma965** [comment]
I got a way with a few lines of code change in JS will git pull latest then send a PR request.

**Comment by fma965** [comment]
I agree with @kooimens but i will only be making PR requests for HTML/CSS/JS as i have no clue about python so either @kooimens or @Hellowlol  or someone who knows python will have to sort that it out :)

**Comment by Hellowlol** [comment]
No Python is required for this one. Or atleat very little. Every Python line you need is already on the settings.html

**Comment by Hellowlol** [comment]
See https://github.com/Hellowlol/HTPC-Manager/blob/master2/interfaces/default/html/form.html#L27 and line 28. Replace field with link and add it to settings.html

**Comment by fma965** [comment]
nope you've completely lost me :(

**Comment by fma965** [comment]
Hey again, Here is a preview of the layouts, i added it as a new dash module so the old layout is still an option.

![image](https://cloud.githubusercontent.com/assets/1707290/8707790/d6ef1ace-2b2f-11e5-92e7-e3962669e72c.png)

**Comment by Hellowlol** [comment]
Nice

**Comment by fma965** [comment]
I guess this can be closed now then since both the original ideas are now implemented.

**Comment by Hellowlol** [comment]
Yeah, thanks a lot!
