### ISSUE TITLE
No wanted movies and no wanted albums if empty on dash

### ISSUE THREAD

**Issue by l-t-k** [Hellowlol/HTPC-Manager#253]
It looks like this atm:
![1](https://cloud.githubusercontent.com/assets/3150962/8686101/99b2b0b4-2a83-11e5-92b9-e74f44f875e2.jpg)

I think it's better to use the thing you use(d) no episode found or something if there no shows with upcoming air dates.

CP, for example comes up with:
![2](https://cloud.githubusercontent.com/assets/3150962/8686142/ec0c09d2-2a83-11e5-98d3-b858c73c53b8.jpg)

**Comment by Hellowlol** [comment]
@kooimens is this plex or kodi?

**Comment by l-t-k** [comment]
CP

**Comment by Hellowlol** [comment]
Hehe, i can see that from the image. I was talking about the blank images. What modules in the dashboard do you want changed, plex or kodi?

**Comment by Hellowlol** [comment]
@kooimens Tried the iframe feature btw?

**Comment by l-t-k** [comment]
I'm sorry, I should clearify my request;). It'is not about plex or kodi, but about the wanted movies (CP) and wanted albums (headphones) on my dash. If there are no wanted albums/movies, they should not be just blank (1st screen), but should show something as 'no wanted movies found', or for example use the CP module text 'no active movies found' (2nd screen)

**Comment by l-t-k** [comment]
Not yet, my server is a complete mess atm. Fixing that first, then I will certainly try the iframe branche;)

**Comment by l-t-k** [comment]
I refered to the sick dash module, because I do remember there is already something in place for this module when no next episodes are found

**Comment by Hellowlol** [comment]
@kooimens iframe is merged in master2 btw

**Comment by rudyvarner** [comment]
The Headphones dash "Wanted Albums" is empty for me as well.

**Comment by Hellowlol** [comment]
@rudyvarner and you have albums that are wanted? Or are you just agreeing with kookiness that this should be changed.

**Comment by rudyvarner** [comment]
Yes.  And if I choose Headphones from the top menu and go to Wanted they are all displayed correctly.

**Comment by Hellowlol** [comment]
Ok, can you open a new issue?

**Comment by l-t-k** [comment]
Oh yeahhhhhhhhh kookiness :+1: I like cookies! :D

**Comment by l-t-k** [comment]
Same goes for the plex module. right now, my music directory is empty and therefore plex is having no music. This is ugly:
![1](https://cloud.githubusercontent.com/assets/3150962/8713906/6ce62e5c-2b6f-11e5-8961-f2e6f0c39df5.jpg)

Ideally, it should contain something. Like, for example when empty = "No music in library".

**Comment by fma965** [comment]
or just not show it? wouldn't it be better to just hide it completely if nothing is in it.

**Comment by Hellowlol** [comment]
I'll rather let the user know that nothing was found, you can be sure some will make a issue if not..

**Comment by fma965** [comment]
Hmm yeah fair point :)

**Comment by fma965** [comment]
@Hellowlol i've just fixed this for couchpotato

**Comment by fma965** [comment]
i can't test Plex but will work on headphones later

**Comment by Fma965** [comment]
I would test it on headphones but 
2015-07-16 12:15:22 :: modules.headphones :: ERROR :: Error calling api http://1
27.0.0.1:8181/api?apikey=********************************&cmd=getWanted: ('Conne
ction aborted.', error(10061, 'No connection could be made because the target ma
chine actively refused it'))

and i'm not quite sure why.

**Comment by l-t-k** [comment]
![1](https://cloud.githubusercontent.com/assets/3150962/8997851/9ca5dc38-3726-11e5-91f2-5526c1f40cb3.jpg)

Nice! Same should be in place for wanted album and next aired.

**Comment by fma965** [comment]
Yeah i can't test plex... and i thought tv shows already did?

**Comment by l-t-k** [comment]
Maybe, the SickBeard and NZBDrone do. I use SickRage, it's not working for that one. I will test plex today

**Comment by Hellowlol** [comment]
@kooimens can you give me the response from http://ip:port/sickrage/GetNextAired in a gist/pastebin?

**Comment by l-t-k** [comment]
http://pastebin.com/s1FgXQb5

ip and port = HTPC Manager, right? Hmm, you probably need output where there are no next aired shows?

**Comment by Hellowlol** [comment]
Yes please. Something is always next in this house.. :p

**Comment by l-t-k** [comment]
Same here... I noticed it when installing new apps. 

Hmm, something isn't ok here. I installed new fresh htpc and sickrage. Added two empty series to sickrage, api is enable. Don't know why the hell i'm getting dutch log output?:

http://pastebin.com/ER5Rwnxp

**Comment by Hellowlol** [comment]
I assume your using Dutch browser settings. This is the console errors that your browser passes. I do nothing except from gabbing what the browser reports. Console errors doesn't really mean anything, some of them are quite normal.

**Comment by l-t-k** [comment]
Hmm, working fine now. Dunno, what the problem was. Finally the json output of an empty SR next aired tab:
`{"message": "", "data": {"later": [], "missed": [], "today": [], "soon": []}, "result": "success"}`

**Comment by l-t-k** [comment]
To be clear, the SR itself is correct:
![1](https://cloud.githubusercontent.com/assets/3150962/9018395/ecd4a58c-37de-11e5-9be5-a3e1137c3048.jpg)

The SR dash module not:
![Uploading 3.jpg…]()

**Comment by l-t-k** [comment]
![1](https://cloud.githubusercontent.com/assets/3150962/9220846/c34d9be6-40e5-11e5-98ee-7cc9c544b0e6.jpg)

After the last updates I got this. It's almost there I think:D

**Comment by l-t-k** [comment]
![foto](https://cloud.githubusercontent.com/assets/3150962/9221369/1982f426-40ea-11e5-82cd-7ffda989ef45.PNG)

Mobile view. Too much white space to be honest. One row of 'no wanted albums' is enough.

**Comment by Hellowlol** [comment]
Hmm i was sure i had fixed this. Dunno why the h3 is missing from your first example but it works on your cell. Was the first ss from IE?

**Comment by l-t-k** [comment]
Indeed IE problem. Fucked up. Chrome and Firefox are fine.

Offtopic, any idea how to specify the webroot in the init.d file as a deamon_opts? tried webroot=/htpc, but that's not working. I'm asking because I want to run two instances of htpc with the same database. I can change one to my own needs (and serve it to my users) and use the other as 'management' htpc.

**Comment by Hellowlol** [comment]
Nope, know nothing about that stuff. Just out of queriosity why do you need two? The hole idea behind the "Manager users" is just use one (in addition to keep the bad guy away)

**Comment by l-t-k** [comment]
I'm using an ldap backend for my users/passwords. All my apps, apache front page login, owncloud, mail etc. are connected to the ldap. Every user can login everywhere with one username and one password. In apache I can authorise users to use the manage htpc and/or the home htpc. So in my environment I can't use the 'users' thing since there is no ability for ldap.

And I know it's just to much overkill (the ldap shit), but it's just fun;)

**Comment by l-t-k** [comment]
However, I manage to solve the problem. Now running two instances of htpc. One with port 8085 and webdir = /manage and one with port 8086 and webdir = /home. Both are using the same .db file so changes in /manage are directly implemented to /home. The /home is from my own github page where I will disable the settings and other options and implement a logout button that redirects to my apache logout page.

**Comment by Hellowlol** [comment]
Slightly overkill... :D, haha, cool.

**Comment by Hellowlol** [comment]
Okei, im gonna close this, the function i wrote it generic but i to lazy to fix it for other module. If you see any other issued you can fix it you self by calling it the same way that the hp modole does. Ill remove the extra blank lines.

**Comment by Hellowlol** [comment]
@kooimens You should consider making a kiosk mode as i did for pytunes. It must be much easier then what your doing now :P See https://github.com/Hellowlol/PyTunes/commit/a8f4e054cd8821cb5c0f5a2d4f02f007825e9a2a#diff-98bc9d7319bb5d2c43d9ed101d5eb87b
