### ISSUE TITLE
TOP menu

### ISSUE THREAD

**Issue by Hellowlol** [Hellowlol/HTPC-Manager#254]
Hi @wmariz ! I dont know if you still using htpc manager but since you authored several awesome additions i thought i id ask anyway.

The menu nav bar  is "blinking" when you press a link, is there a way we can speed this up. Or do i make the menu server side? (like it was before but with sorting :P)

**Comment by wmariz** [comment]
What do you mean by "blinking"? I cannot reproduce that

**Comment by Hellowlol** [comment]
If you press any of the modules in the nav bar you can see everybody except from other links disappear then get added. It doesn't happen every time, but often. at least with many modules active

**Comment by Hellowlol** [comment]
Closing this as i havnt notice this for while. If it pops up ill solve this in the template. Thanks anyway!
