### ISSUE TITLE
CSS / layout problems

### ISSUE THREAD

**Issue by l-t-k** [Hellowlol/HTPC-Manager#255]
I use a fresh new install of master2 and run it with an init script or directly with the settings page to use webroot /htpc. After start, all is well up to this part: (debug logs)
part 1 log: http://pastebin.com/QYTVhmhv
Working fine on:
IE 11.0.9600.17843
Chrome Version 43.0.2357.134 m
Safari, dunno exactly running iOS 8.3 on ipad2

It takes some time (about 5 minutes) to load the second part of the log (something got to do with the auto discovery of plex servers):
part 2 log: http://pastebin.com/GrdZHmvk

From then, it's messed up. When I delete cookies and history in each browser mentioned, all I can see on the main page is this:
![1](https://cloud.githubusercontent.com/assets/3150962/8698814/5e94c570-2b01-11e5-8894-2170dc41d1d8.jpg)

When disabling webroot, this problem does not occur, except for IE (same behavior as above).

**Comment by Hellowlol** [comment]
Im not really sure i get this. The error happens on every browser if webroot is set. except from IE as the browser sucks as usual?

**Comment by Hellowlol** [comment]
Seems to work fine here
chrome: 
![image](https://cloud.githubusercontent.com/assets/1214134/8700486/5552bcb4-2b0c-11e5-8fba-7375bf6ab117.png)
IE:
![image](https://cloud.githubusercontent.com/assets/1214134/8700498/686300f2-2b0c-11e5-9172-934178c227de.png)

**Comment by Hellowlol** [comment]
Heres a ss from ifram btw:

![image](https://cloud.githubusercontent.com/assets/1214134/8700551/b1adc54e-2b0c-11e5-8252-423d8a2ac3c3.png)

**Comment by l-t-k** [comment]
On every browser (including IE) the problem occurs with webroot after around 5 minutes (see log and first part of my first post). The problem also occurs (but only in IE) with webroot turned off after 5 minutes.

**Comment by l-t-k** [comment]
![3](https://cloud.githubusercontent.com/assets/3150962/8702276/25335218-2b17-11e5-9c22-1d4097a53243.jpg)

Hmm, maybe you can repeat the exact same steps I did we a clean install? Strange, above a screenshot of the end of the homepage...

**Comment by fma965** [comment]
i had this, when i had a clean install when i was making the iframe PR, i just ctrl+r it a few times then everything loaded correctly

**Comment by l-t-k** [comment]
Yeah a refresh of the browser fixes this if you're working with Chrome. It's not fixed if you use IE or Safari;)

**Comment by Hellowlol** [comment]
I don't care if it works in ie or not. Special hacks for ie is over.. Is this iOS Safari or on a Mac?

**Comment by l-t-k** [comment]
I agree about IE, it sucks, but this is not a specific IE problem. Although the problems are bigger in IE it occurs in chrome and safari as well. Refreshing the page sometimes fixes this, but not always. And a refresh shouldn't be (of course) the correct way to fix this. Maybe, you can try to follow the exact same steps I covered in my OP to reproduce this? With a clean fresh install.

Safari is iOS 8.3 (Ipad2), info is in OP as well.

**Comment by Hellowlol** [comment]
Ok, I'll see what I can do.

**Comment by Hellowlol** [comment]
I couldnt reproduce your issues in chrome or ie with or without a webdir. I did find a fix for (i think for safari.) Can you try again?

**Comment by l-t-k** [comment]
I have seen it in the last couple of hours only a few times in chrome (it less than last night). For safari it seems to be fixed! IE isn't loading properly at all (even after pressing F5 several times). Strange, because I didn't update for a while and this issues occurred after updating or running a fresh install.

**Comment by Hellowlol** [comment]
Btw this is related to disable cache after update in the general settings page (it's on by default)

**Comment by Hellowlol** [comment]
Still problems with ie?

**Comment by l-t-k** [comment]
Unfortunately yes, I tested with the option you mentioned disabled and enabled, no luck. Same goes for firefox (sometimes). It seems like it occurs more often when accessing htpc with reverse proxy.

But I still think it's weird that when starting htpc all is ok from the beginning (with cookies cleaned of course) and then after a certain amount of time the problems appear?

**Comment by Hellowlol** [comment]
I agree thats strange. There are no change in the way htpc manager servers static content except from the force disabled cache. So you have any console errors (in your browser when this happens)

**Comment by Hellowlol** [comment]
@kooimens Can you see if the latest update fixes the issue?

**Comment by Hellowlol** [comment]
assumed fixed

**Comment by l-t-k** [comment]
Seems to be working now. Tested for a couple of weeks. No problems!
