### ISSUE TITLE
[Suggestion/Feature Request]

### ISSUE THREAD

**Issue by lisim** [Hellowlol/HTPC-Manager#26]
I would love a way to tell the vnstat module to check either all interfaces or to tell it what interfaces to monitor

this is just a way of life improvement as it only seems to monitor the speed of eth0 which is an almost unused interface on our HTPC 

the feature would just be showing the results of wither vnstat -tr -i "interface" or better yet vnstat -l -i "interface"

**Comment by Hellowlol** [comment]
Hi! By default vnstat should monitor all interfaces everything except from bandwidth.

**Comment by Hellowlol** [comment]
Let me know if you still want a option regarding that, it's a easy request :p

**Comment by lisim** [comment]
I mean it would still be nice but maybe the issue might be our end as it seems the vnstat page isnt updating at all anymore Oo ill look into it

**Comment by lisim** [comment]
for instance what we see when runnign vnstat 
http://puu.sh/fIWJp/d35aaed6ef.png

what htpc shows 
http://puu.sh/fIWLB/1f9f2d9cd5.png

**Comment by Hellowlol** [comment]
Yeah until there is a option regarding interface you need to set the correct default interface in vnstat

**Comment by Hellowlol** [comment]
@lisim With the last update you should be able to choose what interface you want to monitor the speed on.
