### ISSUE TITLE
Plex Reverse Proxy Link is wrong

### ISSUE THREAD

**Issue by trickybitch** [Hellowlol/HTPC-Manager#262]
I have HTPC Manager running and working on my local server however I have an issue with the reverse proxy link within plex.

Plex Settings: 
![plex](https://cloud.githubusercontent.com/assets/13413136/8771062/2f464926-2efb-11e5-9376-c32df982cc5b.png)

Plex within HTPC Manager works fine however when click on the 'Plex' title it takes me to:
https://www.domain.com/htpc/plex/webinterface

This page just contains the text of my Plex install:
https://www.domain.com/plex 
And nothing else.
I believe the Plex 'title' should link to that URL instead of a page containing it. The reverse proxy link for Sabnzbd, sickbeard and couchpotato are all working fine and are setup the same way. If I click on the title it takes me to the correct url (https://domain.com/sabnzbd for example)

Cheers.

**Comment by Hellowlol** [comment]
Should be fixed now.
