### ISSUE TITLE
Plex TV shows not opening

### ISSUE THREAD

**Issue by thatbritguy** [Hellowlol/HTPC-Manager#263]
Noticed an issue with the Plex module in the latest master2 version (could have been present before but I'm not sure).  Basically on the TV tab all the shows load correctly and the thumbnails load, but no matter which I click on it just gives a blank page instead of loading the show info and episodes.  Also the video controls no longer appear for me in the now playing well.  I'm on OSX 10.10 and issue is present on latest version of both Chrome and Safari.  Debug logs are showing nothing at all that is related.  Don't know if this is something others are experiencing.

**Comment by Hellowlol** [comment]
Any console errors in the browser? I'm gonna need the log aswell. This makes no sense to me. Its all good here :/

**Comment by thatbritguy** [comment]
http://pastebin.com/rb0wBGdr http://pastebin.com/rb0wBGdr

Here’s a pastern of the console errors

**Comment by Hellowlol** [comment]
Can you try to manually type in this url and paste the response:
GET http://localhost:4465/plex/GetEpisodes?start=0&end=50&hidewatched=0&tvshowid=3412

**Comment by thatbritguy** [comment]
'{"episodes": [{"plot": "Carrie-Louise and her third husband Lewis Serrocold run a correctional facility for young men on their estate, Stonygates, where they also house a rag-tag of family and step-family.\n\nAfter a fire tears through Carrie Louise's office, her sister, Ruth Van Rydock, urges their old - and somewhat less glamorous - friend, Miss Marple (Julia McKenzie), to visit the blithely unsuspecting philanthropist.", "episode": 3, "rating": "9.0", "season": 4, "label": "4x3. They Do It with Mirrors", "thumbnail": "/library/metadata/3414/thumb/1436259837", "playcount": 0, "id": 3414, "showtitle": "Agatha Christie's Marple"}], "limits": {"start": 0, "total": 1, "end": 1}}
'

**Comment by Hellowlol** [comment]
Ok thanks, the url fucks it up :P, thanks

**Comment by Hellowlol** [comment]
Should be fixed now, let me know if you still have issues
