### ISSUE TITLE
Kodi server password visible in logs

### ISSUE THREAD

**Issue by thatbritguy** [Hellowlol/HTPC-Manager#264]
Just wanted to give you a heads up that the password for the kodi server is shown in the url in the logs.  Not sure if that's intended or not.

**Comment by Hellowlol** [comment]
Thank you for the heads up. I was salready award off it, but I haven't bothered fixing it as kodi is a local service and I don't think many has exposed it to the web. But I'll mask this aswell

**Comment by Hellowlol** [comment]
Should be fixed in the latest commit
