### ISSUE TITLE
Sickrage/HP: Hit enter bar should search

### ISSUE THREAD

**Issue by l-t-k** [Hellowlol/HTPC-Manager#272]
When using CP, I can search a movie by typing the name in the search field and hit enter. However, for Sickrage and Headphones I have click on the search button with my mouse in order to start the search. Hitting enter is not working. Just a minor bug...

**Comment by Hellowlol** [comment]
It's not a bug, it's not implemented:p

**Comment by Hellowlol** [comment]
added support for this

**Comment by l-t-k** [comment]
Working like a charm!
