### ISSUE TITLE
'Other apps' delete button not working

### ISSUE THREAD

**Issue by l-t-k** [Hellowlol/HTPC-Manager#273]
If I click on it, nothing happens.
![1](https://cloud.githubusercontent.com/assets/3150962/9021580/83f6d808-3849-11e5-9718-3dffd8838f54.jpg)

**Comment by l-t-k** [comment]
Debug logging:
http://pastebin.com/e825dfuz

**Comment by thatbritguy** [comment]
Just created a PR #274 which fixes the button so that it now deletes as expected.  Sorry, that was my error, I accidentally removed the crucial class.

**Comment by l-t-k** [comment]
Nice! No problem of course. I'm glad to see people actually committing PR's, where I only notice and report bugs;)
