### ISSUE TITLE
Plex dash, year unknown = undefined

### ISSUE THREAD

**Issue by l-t-k** [Hellowlol/HTPC-Manager#275]
![1](https://cloud.githubusercontent.com/assets/3150962/9022100/18bb7ec2-3867-11e5-9433-0c40e3b541c7.jpg)

I have some albums where Plex can't determine the release year. I'll find an ugly (undefined) on my plex music dash. The main plex app (through HTPC) isn't showing the release year at all, so no problems occur in that area.

**Comment by Hellowlol** [comment]
I dont have hp installed anymore, can you check if this is fixed?

**Comment by l-t-k** [comment]
I can't test this atm, because of #282. However, this is not related to HP. My screen is from the PLEX recently added music module;)

**Comment by Hellowlol** [comment]
Well then i have to fix it later. I just pushed a fix for the dash. It got late yesterday:P

**Comment by l-t-k** [comment]
The PLEX recently added music module is only showed on dash, so I think you're right about that. I only said that it's got nothing to do with HP;)

**Comment by Hellowlol** [comment]
Didn't the ignore section fix the double items?

**Comment by l-t-k** [comment]
Oeps, you're correct. Changed it.

**Comment by Hellowlol** [comment]
Should have fixed it now.
