### ISSUE TITLE
bring back the slate theme.

### ISSUE THREAD

**Issue by fma965** [Hellowlol/HTPC-Manager#277]
as the title says, please bring back the slate theme as its the only dark theme i can find.

i mean the screenshot on the readme.md file is even the slate theme.... i like dark themes.

**Comment by fma965** [comment]
also this doesn't look normal to me
![image](https://cloud.githubusercontent.com/assets/1707290/9022473/95e25c3e-386e-11e5-8f78-c579c1c100db.png)
![image](https://cloud.githubusercontent.com/assets/1707290/9022476/a7749d68-386e-11e5-9206-324bc547dcef.png)

also the gamer theme doens't even work.

**Comment by Hellowlol** [comment]
What do you mean by not work? 

![image](https://cloud.githubusercontent.com/assets/1214134/9022519/197815ee-3878-11e5-9d50-e50656dcd7b4.png)

**Comment by Hellowlol** [comment]
onyx is dark btw

**Comment by fma965** [comment]
ok after restarting i can select gamer... onyx looks bad compared to slate though, and most of these themes have font issues as can be seen in my screenshot.

**Comment by Hellowlol** [comment]
What font issues?

**Comment by fma965** [comment]
can you not see them in the screenshot? they are all pixelated and look terrible on the colored backgrounds.

**Comment by Hellowlol** [comment]
Nope, what theme are you talking about specifically?

**Comment by fma965** [comment]
amethyst and which ever one is red and black... i'm not sure why you cant see it from the screenshot though

EDIT: Ruby

**Comment by Hellowlol** [comment]
Slate isnt comming back unless someone sends a pr for it. :)

**Comment by fma965** [comment]
i don't really see why you even needed to delete the old themes tbh but ok.

**Comment by Hellowlol** [comment]
![image](https://cloud.githubusercontent.com/assets/1214134/9022727/d70011c2-3880-11e5-93f8-fd7cadccf180.png)

Thats why

**Comment by fma965** [comment]
not sure what thats meant to be showing

**Comment by Hellowlol** [comment]
Thats slate:)

**Comment by Hellowlol** [comment]
@raysguy any chance you can make a new theme like slate?

**Comment by fma965** [comment]
tbh onyx is ok although the white outline on textboxes makes it looks really dated.

**Comment by Fma965** [comment]
also the menu button on the top right cud prob be 2em rather than 3em.

.navbar .fa-bars {
    font-size: 2em!important;
}

**Comment by fma965** [comment]
also the menu button on the top right cud prob be 2em rather than 3em.

.navbar .fa-bars {
font-size: 2em!important;
}

so it looks like this ![new](http://i.imgur.com/NyJ4Xbv.png)

rather than this ![old](http://i.imgur.com/xPJBuok.png)

but this is just a small nitpick

**Comment by thatbritguy** [comment]
3em was a deliberate design choice :)

**Comment by fma965** [comment]
a bad one in my opinion, the button is way too big like that.

EDIT: to be fair it's not a major issue and onyx is growing on me but those white lines look terrible on textboxes, the 1990's used to have them on everything :D

**Comment by Hellowlol** [comment]
@Fma965 Feel free to send a pr without them, tried to add one based on onyx with a smaller icon and remove the shit. But im just awefull at css. And i dont have the patience to check every browser and every viewport... @raysguy The themes must have been a lot of work. :) Thanks again!

**Comment by thatbritguy** [comment]
@Hellowlol yes they sure were!  Especially trying to cover such a wide variety of styles and color schemes.  One little change to one thing would look fine until I went to a different page and realised it had screwed something else up! Hahaha.  Must have been a lot easier than all the work you put into coding though!  Half the time I'm looking at python or js files I may as well be reading greek for all the sense they make to me!

@Fma965 All I remember of the 90s is how unapologetically gray everything was.  Still have an Atari ST and Citizen ribbon printer in a cupboard somewhere!!!  ;) If all you're looking for is a more grey theme have you tried Moonlight?  Onyx was designed as a dark version of Obsidian and the white highlights were for contrast, Moonlight is what I'd consider a successor to Slate - it is all just various shades of grey and slate.  Check out some of the others too - there are 9 dark themes in total.  I'm not too big on dark ones myself but I know quite a few HTPC users seemed to like them so I tried to make sure they'd got a similar amount of choice to those of us who use regular themes (that being said sublime really grew on me as I was putting it together and I now use that a lot!).

**Comment by thatbritguy** [comment]
Btw @Hellowlol I think you need to update the screenshot in the readme page! ;)

**Comment by Hellowlol** [comment]
Yeah, thanks for reminding me. I should probably redo the entire readme, I like headphones readme. I don't like any markdown :(.

**Comment by thatbritguy** [comment]
Yeah that readme does look good.  I hate markdown too.  When I get some time I was going to look at putting together a lightweight site using html with github pages.  My next project I think will be to put together a bespoke icon font set with a small footprint using the Fonticons service.

**Comment by fma965** [comment]
Hmm i didn't know there was that many dark themes, i went through the themes but half weren't working (i restarted htpc manager then they started working but couldn't be assed to go through them all again :D) i will try the other dark themes and see if they suit me better :)

Don't get me wrong though you have done a great job @raysguy i'm ok at PHP/HTML/JS but i'm not very good with CSS as i can't design for s**t.

**Comment by thatbritguy** [comment]
Yeah, 22 themes and a variety of styles - tried to create something for everyone. Yeah if the update hadn’t completed correctly they wouldn’t have loaded properly at all.  Saw someone else post about it but screenshot was just of one of the old themes but broken! :)

I’m learning CSS as I go along really.  Did start the theming project over at one point as it was driving me mad, so second time I used LESS to compile them.

**Comment by Hellowlol** [comment]
Its broken in the source updater as it currently doesnt removes old files/folders. it just overwrite the ones that already exist. So in short old themes are not removed.
