### ISSUE TITLE
newznab ssl option not working

### ISSUE THREAD

**Issue by l-t-k** [Hellowlol/HTPC-Manager#278]
If I enable the ssl option in the newznab module and then go back to settings page, the module is set back to non-ssl. Furthermore, if I enter api url https://www.index.com, the api url is changed to www.index.com after saving.

**Comment by Hellowlol** [comment]
It work, its just a visual bug after the "sliders" was added. As for the removal of http/https, thats intented. There are some code in htpc manager to fix common user errors.

**Comment by Hellowlol** [comment]
fixed
