### ISSUE TITLE
Headphones issues

### ISSUE THREAD

**Issue by kooimens** [Hellowlol/HTPC-Manager#28]
Working great! I've found some little bugs in de master version.

1. When on an artist or album tab the links to Home / Headphones Module / Artist are without the webroot. 
![1](https://cloud.githubusercontent.com/assets/3150962/6134496/2f6edd76-b162-11e4-8f8c-74db7e7e5548.jpg)

2. I think an album on the wanted page shouldn't have an icon to set it as wanted;)

3. Don't know if you are aware of the stretched artist pics. (On artist-tab and on artist-page)  Album pics are looking great. Just a reminder;)

4. 'Action' would be better, then 'Search' (Artist/Album tab).
![2](https://cloud.githubusercontent.com/assets/3150962/6134606/e2ddd7f4-b162-11e4-97e6-69b145dc8774.jpg)

**Comment by Hellowlol** [comment]
Thanks for reporting our issues.
Regarding: 
1. What webroot? Htpc managers or hp basepath?
2. Its so you can enable and disable it on the same page.
3. The entire thing with images are a pain, the api is dog shit. Ill see if i cant get the correct ratio
4. Agreed

**Comment by kooimens** [comment]
1. htpc webroot
2. If I disable it (set skipped), I'm not able to set it as wanted again. And I think that's not weird, because when skipping it, the album will disappear instantly from the wanted list.

**Comment by Hellowlol** [comment]
1. Fixed
2. Gonna leave it for now, i do see your point. Prob gonna remove this in a later commit
3. The images return from the api is different size, its hard to get this right. Does the last update help?
4. Fixed

**Comment by Hellowlol** [comment]
Note to self: Possible bug in https://github.com/Hellowlol/HTPC-Manager/commit/0693df9cd9bc04ef9226aaba0312e0d6db09ad1b#diff-0947407744ffbad910292a422539babbR12 and https://github.com/Hellowlol/HTPC-Manager/commit/0693df9cd9bc04ef9226aaba0312e0d6db09ad1b#diff-0947407744ffbad910292a422539babbR13
Check if this still works if not add a ?

**Comment by kooimens** [comment]
That helped! Looking great now.
