### ISSUE TITLE
Problems with sabnzbd module

### ISSUE THREAD

**Issue by l-t-k** [Hellowlol/HTPC-Manager#280]
I have to keep pressing F5 to get it refreshed, even when I've been waiting a minute of 5. Just stay in the htpc app and browsing through the different modules and then back to the sab module isn't refreshing anything.

I'm on IE right now, but noticed the same on chrome.

**Comment by Hellowlol** [comment]
Log? works fine here

**Comment by l-t-k** [comment]
Nothing in there atm. I'll keep an eye on it.

**Comment by Hellowlol** [comment]
any console errors (no all of them are logged)?

**Comment by l-t-k** [comment]
No console errors. What I did noticed is that the problem seems to be related to the history tab. I have to F5 that one to grab recent info.

**Comment by l-t-k** [comment]
Damn it. And of course, fucked up IE. Did some tests, chrome, firefox and safari, all working great, refreshing auto on around 3-4-5 seconds on average. IE doesn't do any refreshing at all.Even when I switch to, for example my CP module (within HTPC) and switch back to my sab module (within HTPC) I still don't see the nzb I've added a several minutes ago. Same goes for the history tab (as I mentioned before).

**Comment by Hellowlol** [comment]
What ie version?

**Comment by l-t-k** [comment]
![default](https://cloud.githubusercontent.com/assets/3150962/9026924/9921a156-3941-11e5-8862-409df5686d67.jpg)

Windows 8.1
