### ISSUE TITLE
Sickrage 'add show' should be green instead of black

### ISSUE THREAD

**Issue by l-t-k** [Hellowlol/HTPC-Manager#283]
![1](https://cloud.githubusercontent.com/assets/3150962/9025878/77611ad4-3918-11e5-9cf8-7a55e387d5b6.jpg)

**Comment by Hellowlol** [comment]
You can fix this yourself. It's a typo in btn-succmess.

**Comment by l-t-k** [comment]
Ah ok. I will take a look at it.
