### ISSUE TITLE
Headphones: set albumpage as default artist view

### ISSUE THREAD

**Issue by l-t-k** [Hellowlol/HTPC-Manager#284]
The `Info` tab is the default landing page for each artist. The info looks cool, but the albums are of more value of course. The `Albums` tab next to it should be the default landing page when viewing an artist.

![5](https://cloud.githubusercontent.com/assets/3150962/9025940/02233768-391b-11e5-9ed6-7ca8352b9892.jpg)

**Comment by Hellowlol** [comment]
If you want to fix this yourself you can remove the class from #info and add it to #albums. An add active to .nav-tabs li

**Comment by l-t-k** [comment]
I'll give it a shot!
