### ISSUE TITLE
Plex dash, do not show new items if "show on dashboard" is unchecked in PLEX main app

### ISSUE THREAD

**Issue by l-t-k** [Hellowlol/HTPC-Manager#287]
![1](https://cloud.githubusercontent.com/assets/3150962/9026273/9d3826c4-3929-11e5-83d8-ad677b486255.jpg)

Plex libraries have an option to disable the content of that particular library to show up on dashboard or recently added (All in the main plex app, not HTPC).

If that's the case (if that option is uncheck, see screen) HTPC Manager should no show this items in recently added movies, show or music.

**Comment by Hellowlol** [comment]
Tried adding that sections n to ignore section?

**Comment by l-t-k** [comment]
That did the trick!
