### ISSUE TITLE
Request - Sonarr view default to season 1

### ISSUE THREAD

**Issue by thatbritguy** [Hellowlol/HTPC-Manager#290]
Have a request similar to #288 but couldn't work out how to implement myself.  Basically on sonar_view could you make it so that the Season tab defaults to Season 1 instead of Specials?  In my experience Specials listings cover loads of random stuff I'd never download and hate defaulting to a page full of "Missing" labels!

**Comment by Hellowlol** [comment]
Ok. Can you take a look as https://github.com/Hellowlol/HTPC-Manager/issues/291 ?

**Comment by Hellowlol** [comment]
Would it be better if it open the last season instead?

**Comment by thatbritguy** [comment]
How about latest season if show is flagged as “continuing” and season 1 for shows that are flagged as “ended”.  Is that possible to implement?  If not then yeah just go with latest season.

**Comment by Hellowlol** [comment]
Hmm, ill try.

**Comment by thatbritguy** [comment]
Awesome thanks, works like a charm! :)
