### ISSUE TITLE
Theme issues: onyx 

### ISSUE THREAD

**Issue by Hellowlol** [Hellowlol/HTPC-Manager#291]
I have only notice this on onyx but it might be related to more themes.
- navbar menu button is misalign compared to the htpc manager icon (iPhone 5s)
- season buttons is sonarr is impossibleto see.

**Comment by thatbritguy** [comment]
What do you mean by not responsive?  Tested on my iPhone 6 Plus and it is responsive in both landscape and portrait mode.  Btw is the login screen cached by HTPC?  No matter which theme I switch to the login screen is always showing as sublime (on any browser/device) which i know is impossible from the CSS files.  Clearing browser cache doesn't fix it.

Yeah I knew about the misaligned icons on mobile view - that was one of issues I mentioned in first demo.  Tried everything but couldn't figure out why it is fine in normal view but not mobile.  When I tried to fix for mobile it would screw up main view.

Try this for season buttons - in line 63 of sonarr_view.html change `<ul class="nav nav-pills" id="season-list"></ul>` to `<ul class="nav nav-pills breadcrumb" id="season-list"></ul>` and see what you think to that.

**Comment by Hellowlol** [comment]
No it's not cached. I forgot to change the key used by the db. Should be app_theme_mig. I'll try to fix the icon by using max width :)

**Comment by Hellowlol** [comment]
Bah, i really need to fix my proxy so i can access htpc-manager from work :/

**Comment by Hellowlol** [comment]
Did you ever got around to fix the font to vnstat?

**Comment by thatbritguy** [comment]
I tried using the example you gave but after trying quite a few things I never managed to affect the font, so I gave up so it didn’t delay me getting the themes finished.

**Comment by Hellowlol** [comment]
Ok

**Comment by Hellowlol** [comment]
@raysguy Login screen is after the _mig fix.

**Comment by Hellowlol** [comment]
@raysguy have you tried something like this `@media screen and (max-width: 979px) {
  .navbar .rg-htpc {
    padding: 7px 0 5px 12px!important;
    margin-top: 5px!important;
  }
  .navbar .btn {
    margin-top: 0px !important;
  }`
Its far from perfect but i think its a little better atleast. Bah, the brand button gets to far from the edge, but you get the idea at least.

**Comment by Hellowlol** [comment]
The progress bar sees to be to high
![image](https://cloud.githubusercontent.com/assets/1214134/9049264/630af69e-3a40-11e5-8ff7-c93aa59fcf19.png)

set .progress margin-bottom 0px; module css

**Comment by Hellowlol** [comment]
![image](https://cloud.githubusercontent.com/assets/1214134/9049303/d4725bd8-3a40-11e5-924e-28bfcfa18df1.png)
nzbget image seems chopped

**Comment by thatbritguy** [comment]
Cool I'll play around with those values and try to get them aligned on mobile view.

Thanks for figuring out the progress bar issue - you've no idea how many hours I wasted trying to figure that out!

Weird about the download button image, I thought I'd sorted that whilst I was on them.  I don't think the icon is chopped, I think it's actually mis-aligned.  I probably tweaked something on the rg-icons side and forgot that the download icon is font-awesome.  I'll have a play around and fix that though.   That should all be easier to manage in future once I create the new icon font.

**Comment by thatbritguy** [comment]
Btw what browser are you using?  How do you manage to have all your form dropdowns, eg the category and indexer selectors perfectly square with no border-radius?!  I really want it to look like that for me but both chrome and safari impose rounded ones.

**Comment by Hellowlol** [comment]
Im using chrome, ill find the version number later. Btw chromes
Box model is awesome for figuring out stuff like that as the margin etc get colored around a object.

**Comment by Hellowlol** [comment]
Btw the season buttons was much easier to see after the last update, as the season that was open wasnt toggled as open. (no active class)

**Comment by thatbritguy** [comment]
Yeah that looks much better.  Couldn’t understand why it wasn’t behaving the same as other tabs.
