### ISSUE TITLE
Fix - Sonarr download status for unaired series

### ISSUE THREAD

**Issue by thatbritguy** [Hellowlol/HTPC-Manager#292]
In the show list of the Sonarr module if a show hasn't yet aired, i.e. Sonar has no episode info, under the download column that item will have an empty progress bar with the label saying "undefined / undefined".  Looks odd.  Is there any way you could set it so that if Sonarr doesn't return any episode info it shows a "full" progress bar with the 'warning' class and the label reading "Unaired series", or "Not yet aired" or something along those lines?

**Comment by thatbritguy** [comment]
<img width="1280" alt="sonarr unaired" src="https://cloud.githubusercontent.com/assets/10825337/9053257/91fc0392-3a6a-11e5-9b1f-142129f3a818.png">

**Comment by thatbritguy** [comment]
Actually whilst I'm thinking about it, would there be a way to make all the labels/badges a fixed width on a certain module?  Always looks odd to me with the "continuing" / "ended" ones being different sizes.  Same with the quality labels to.  Be great if they were all a fixed width like the download bar with the text label centered.

**Comment by Hellowlol** [comment]
Hmm, i thought i already have a warning of that. Do you have a screenshot of it? And just to be clear im sure i can remove the undefined's atleast. I remember i thought the progress bars where a pain. What show has does this?

Edit: I just noticed that i check for unaired episodes, but not for missing info. I can fix that, just give me name of a show that is messed up :P

Regarding the labels i have no i idea if its possible to set a fixed width. You just have to play around and see how it goes.

**Comment by Hellowlol** [comment]
Labels: http://jsfiddle.net/4yq8xL6z/

**Comment by thatbritguy** [comment]
On the screenshot above the two unaired shows are "The Guide To Surviving Life" and "Hot & Bothered".  That's how they appear in the Sonarr module.

**Comment by thatbritguy** [comment]
Awesome i'll play around with the labels.  Looks like it will be much simpler than I thought!

**Comment by Hellowlol** [comment]
Oh, lol, i cant believe i missed it. It looks awefull.

**Comment by thatbritguy** [comment]
This is the page view for an unaired show btw.  Maybe for shows that aren't scheduled the "Airs" section could display "TBC" instead of being blank.

<img width="1279" alt="sonarr_view unaired" src="https://cloud.githubusercontent.com/assets/10825337/9055069/30fcaa78-3a7f-11e5-9272-03fa2727cda9.png">

Don't know if it's a viable solution but I'm thinking maybe when Sonarr returns no episode info for a show we could also append a short "info" class label to the end of the series title saying "[fa-star]New![fa-star]"?

**Comment by thatbritguy** [comment]
Lol yeah although to be fair it stands out a lot more on dark themes (probably why I never noticed it before as I've always used light ones.

**Comment by Hellowlol** [comment]
What does TBC short for wouldnt "TBA" To Be Announced be better? I can simply remove the airs field if there is not airdate.

**Comment by thatbritguy** [comment]
To Be Confirmed, but yeah TBA is better anyway I think.

**Comment by Hellowlol** [comment]
Ok, TBA it is then. =)

**Comment by Hellowlol** [comment]
Btw, your missing the from second screenshot since your using auth on sonarr(?)

**Comment by thatbritguy** [comment]
What's missing in the second screenshot?  I have the "(Forms) Login page" option set in Sonarr.

**Comment by Hellowlol** [comment]
There should be a banner image there. But you cant see it because of the login form. It only works without auth. Disable auth in sonarr and you will see what i mean.

**Comment by thatbritguy** [comment]
I've always wondered why there isn't an image there!!!! Is it the banner image?

Unfortunately I have to have the auth active as my server is available outside of my home network.  Is there a workaround at all? Used to use an iPhone app when I was jailbroken called NZBUnity and that had banner image for each show.  Maybe it was grabbing them externally.  Would it be possible to say grab the tvdbid from the Sonarr api and then use that to grab the banner for the series directly from tvdb?

**Comment by Hellowlol** [comment]
Disable auth remove sonarr from www and use htpc manager? It is what htpc manager is meant for :P Any features thats missing preventing you from using it?

Hmm, maybe i havnt look into that. Im sure its possible. I have commented on a issue at sonarr and i hope they allows to access that endpoint if apikey exist.  If not we have some options, add username and password to sonarr settings so it can access the image, grab it from tvdb (havnt look into that), disable auth.

Yes its the banner image. I havnt notice this before since i have no auth on sonarr.

**Comment by thatbritguy** [comment]
The problem is it's installed on my headless server which is internet accessible for remote access, so I have all software secured (I bought my own SSL certificates to make it more secure but I've never been able to figure out how to get that to work on anything!!!).  I use HTPC for the day to day stuff but for admin tasks like updating the software, toggling monitored status, changing folder paths, checking the wanted list, I need to be able to access it as sometimes I'm away for a few weeks and if any issues arise I need to be able to troubleshoot.  Same with the other modules really, I access them directly for admin tasks.

I'm surprised they don't allow access to that with the api key.  Adding username and password to Sonarr settings might be the best solution as it saves you having to engineer anything extra to grab stuff from tvdb.

I've always noticed it and almost submitted a request for it once but saw your comment at L303 of the sonarr_view.js file that said it wasn't in use at the moment so figured it was on the roadmap for the future! :)

**Comment by Hellowlol** [comment]
Yeah, its just the function that isnt used. Its called directly from the other functions. see https://github.com/Hellowlol/HTPC-Manager/blob/master2/interfaces/default/js/sonarr_view.js#L43 for a example. 

I can do that but i still need to support both basic auth and form login as its not done the same way. Its no biggie, but it would be better if this was supported in sonarr. https://github.com/Sonarr/Sonarr/issues/291

**Comment by thatbritguy** [comment]
Yeah it's crazy that they don't allow that access.

**Comment by Hellowlol** [comment]
Can you update to the latest and see if thats good enogh?

**Comment by thatbritguy** [comment]
Yeah that looks much better than before :)
