### ISSUE TITLE
Bug - Searching fails for various newznab indexers

### ISSUE THREAD

**Issue by thatbritguy** [Hellowlol/HTPC-Manager#294]
I have five newznab indexers set up in HTPC for searching and realised today I only ever get results for two of them (dognzb and althub).  Ran some tests and PFMonkey, oznzb and nzb.su fail.  Two of them give errors in the logs one doesn't appear to.

Pulled the logs from the tests:  http://pastebin.com/9abfbKV9

**Comment by Hellowlol** [comment]
Oznzb will not work. It's not the same api, use the search URL of each for the providers (you can see it in the log directly in your browser and copy to content to a pastebin (one for each provider) also is this the debug log? Can you wipe the log search again and give me the entire thing?

**Comment by thatbritguy** [comment]
Well nzb.su is easy - that returns a page that says "403 Forbidden nginx".  Here's the link for PFMonkey: http://pastebin.com/YWnPRFTG

**Comment by thatbritguy** [comment]
nzb.su - full clean log - http://pastebin.com/i0rWxxRX

PFMonkey - full clean log - http://pastebin.com/WzG1SGdc

**Comment by Hellowlol** [comment]
And the responses when you try the same URLs in your browser?

**Comment by thatbritguy** [comment]
That's the first of my last two comments.  When I try the nzb.su one I get the 403 Forbidden nginx message and with PFMonkey I get this http://pastebin.com/YWnPRFTG

**Comment by Hellowlol** [comment]
Ah okei.

**Comment by Hellowlol** [comment]
Well they are not really giving us much to work with here :P 

Regarding nzb su your sure its the correct api url and that the apikey is correct? 

pfmonkey doesnt return anything usefull :( Can yoy try searching on something you know exist like game of thrones or something? just wanna check the response from pf again.

**Comment by thatbritguy** [comment]
Yeah the nzb.su details are correct.  Exactly same ones as in Sonarr and that is  working okay at the moment.

Retried the PFMonkey test on Game of Thrones but the result was identical to the last one.

**Comment by Hellowlol** [comment]
@raysguy Is nzb.su invite only?

**Comment by Hellowlol** [comment]
@raysguy you pf url is wrong, you need to use ssl or you will get that response. Write https://www.pfmonkey.com

![image](https://cloud.githubusercontent.com/assets/1214134/9072134/b8d0b5dc-3af9-11e5-8667-d9efb79d57e1.png)

**Comment by thatbritguy** [comment]
Ah crap, not sure how that happened as I copied and pasted from sonarr settings and it's correct in there.  That cleared that up!

Yeah nzb.su is invite only

**Comment by Hellowlol** [comment]
Ok, Ill try to add another header. It that doesnt work it will be broken until i have nzb.su account  :)

**Comment by thatbritguy** [comment]
Well if you need an invite for testing purposes just let me know :)

**Comment by Hellowlol** [comment]
Can you update and try nzb.su again?

**Comment by Hellowlol** [comment]
Yeah, i might take you up on that if this doesnt work.

**Comment by Hellowlol** [comment]
@raysguy did it work?

**Comment by thatbritguy** [comment]
Oops sorry, got distracted playing around with the font stuff on my test build :D 

Just tried it on latest commit but still returning same error as before.

**Comment by Hellowlol** [comment]
Ok can you send me a inv to hellowlol1@gmail.com?

**Comment by thatbritguy** [comment]
Sent :)

**Comment by Hellowlol** [comment]
Thanks, I'll see if I can't fix this tomorrow.

**Comment by thatbritguy** [comment]
Awesome, thanks

**Comment by Hellowlol** [comment]
It works when i test now. I was missing a - from the header..

**Comment by thatbritguy** [comment]
Still getting identical error message to before for nzb.su.

**Comment by Hellowlol** [comment]
Hmm, strange. Can you try the url manually in your browser, check the reponse. Then login to the site. Use htpc manager to search, it that doesnt work try the url manually again. Do it in that order plx.
