### ISSUE TITLE
rTorrent Support

### ISSUE THREAD

**Issue by DylanGore** [Hellowlol/HTPC-Manager#298]
The only thing that this is missing for me is support for the rTorrent client, any chance that support might be added in the future?

**Comment by Hellowlol** [comment]
Only if someone sends a pr. :)

https://github.com/cjlucas/rtorrent-python

**Comment by DylanGore** [comment]
I'd do it myself but I wouldn't know where to begin

**Comment by Hellowlol** [comment]
You can start here: https://github.com/Hellowlol/HTPC-Manager/wiki/How-to-make-your-own-module
Its not done. But it should get you started. Feel free ask for help

**Comment by Hellowlol** [comment]
Ill finished the guide if you want to.

**Comment by DylanGore** [comment]
Thanks, I'll defiantly give it a go!

**Comment by Hellowlol** [comment]
You should. A guide like that was how i got started (the guide was much better then the mine :P)

**Comment by Hellowlol** [comment]
@DylanGore I have updated the guide so it works.

**Comment by warplayer** [comment]
I would love to see some rTorrent support, too. It's the one thing that is missing now that you have SickRage and Plex in here. Also, that link to how to make your own module doesn't appear to be working for me.

**Comment by Hellowlol** [comment]
Hi! The correct link is https://github.com/Hellowlol/HTPC-Manager/wiki/How-to-make-your-own-module

**Comment by tymanthius** [comment]
Just dropping in my vote for rtorrent support.  :)

**Comment by JigSawFr** [comment]
:+1: could be great :)

**Comment by CaptInsano** [comment]
Another vote here!!

**Comment by mattberther** [comment]
I submitted a PR for this at #490 - please comment on the PR with any other features you might like to see prior to merging.

**Comment by Hellowlol** [comment]
@DylanGore @JigSawFr @tymanthius I rtorrent support has been merged.

Thanks @mattberther
