### ISSUE TITLE
Newznab search feature request NZB button (and little bug)

### ISSUE THREAD

**Issue by kooimens** [Hellowlol/HTPC-Manager#30]
The newznab search is still showing an NZBget button when I click an NZB, even if i haven't enabled NZBget. 
![1](https://cloud.githubusercontent.com/assets/3150962/6146986/009e885c-b1f3-11e4-8b57-7603bc7b049b.jpg)

Furthermore, I have some users who only want the to download the NZB. Is that possible?

**Comment by Hellowlol** [comment]
Ah, crap i forgot that one... :P
