### ISSUE TITLE
Revert back to e85be0b

### ISSUE THREAD

**Issue by fma965** [Hellowlol/HTPC-Manager#304]
Everything breaks after this commit, the active nav was clearly not tested very well and results in sonarr/couchpotato and everything not working.

**Comment by fma965** [comment]
#303

**Comment by Hellowlol** [comment]
Done

**Comment by fma965** [comment]
Great, thanks :)

**Comment by bakman2** [comment]
What didnt work in sonarr ?

**Comment by fma965** [comment]
everything... it wouldn't load cuz js error

**Comment by bakman2** [comment]
Ah ok. I have a fix.
