### ISSUE TITLE
No titles in Mylar history

### ISSUE THREAD

**Issue by rudyvarner** [Hellowlol/HTPC-Manager#309]
Looks like the Title field in the Mylar - History tab is not populating.  Using the Sable theme if it is relevant.

![image](https://cloud.githubusercontent.com/assets/5005529/9136054/5e7c8478-3ce1-11e5-951f-217d56af7001.png)

Log:

2015-08-07 08:52:34 modules.mylar   DEBUG   calling api @ http://localhost:8087/mylar/api?apikey=*******************************_&cmd=getIndex
2015-08-07 08:52:34 modules.mylar   DEBUG   calling api @ http://localhost:8087/mylar/api?apikey=**_****************************_&cmd=getWanted
2015-08-07 08:52:34 modules.mylar   DEBUG   calling api @ http://localhost:8087/mylar/api?apikey=**_*****************************&cmd=getHistory

**Comment by Hellowlol** [comment]
Can you call http://ip:port/mylar/GetHistoryList and give me the response? (i dont have mylar installed anymore)

**Comment by rudyvarner** [comment]
Here is a portion of it.  Was way too long to past the whole thing.

[{"Status": "Downloaded", "ComicName": "Detective Comics", "IssueID": "496857", "FolderName": null, "Issue_Number": "43", "Provider": null, "Size": null, "DateAdded": "2015-08-07 08:44:59", "ComicID": "42594"}, {"Status": "Snatched", "ComicName": "Detective Comics", "IssueID": "496857", "FolderName": null, "Issue_Number": "43", "Provider": "experimental", "Size": null, "DateAdded": "2015-08-07 08:42:57", "ComicID": "42594"}, {"Status": "Snatched", "ComicName": "Detective Comics", "IssueID": "496857", "FolderName": null, "Issue_Number": "43", "Provider": "KAT", "Size": null, "DateAdded": "2015-08-07 08:42:23", "ComicID": "42594"}, {"Status": "Downloaded", "ComicName": "Star Trek", "IssueID": "496909", "FolderName": null, "Issue_Number": "48", "Provider": null, "Size": null, "DateAdded": "2015-08-05 15:50:29", "ComicID": "42972"}, {"Status": "Snatched", "ComicName": "Star Trek", "IssueID": "496909", "FolderName": null, "Issue_Number": "48", "Provider": "experimental", "Size": null, "DateAdded": "2015-08-05 15:42:57", "ComicID": "42972"}, {"Status": "Downloaded", "ComicName": "Star Wars", "IssueID": "496399", "FolderName": null, "Issue_Number": "7", "Provider": null, "Size": null, "DateAdded": "2015-07-31 09:22:34", "ComicID": "79398"}, {"Status": "Snatched", "ComicName": "Star Wars", "IssueID": "496399", "FolderName": null, "Issue_Number": "7", "Provider": "experimental", "Size": null, "DateAdded": "2015-07-31 09:16:25", "ComicID": "79398"}, {"Status": "Snatched", "ComicName": "Star Wars", "IssueID": "496399", "FolderName": null, "Issue_Number": "7", "Provider": "KAT", "Size": null, "DateAdded": "2015-07-30 15:32:45", "ComicID": "79398"}, {"Status": "Snatched", "ComicName": "Five Ghosts", "IssueID": "495843", "FolderName": null, "Issue_Number": "17", "Provider": "KAT", "Size": null, "DateAdded": "2015-07-28 18:37:15", "ComicID": "59223"}, {"Status": "Downloaded", "ComicName": "Star Trek", "IssueID": "495829", "FolderName": null, "Issue_Number": "47", "Provider": null, "Size": null, "DateAdded": "2015-07-28 16:02:38", "ComicID": "42972"}, {"Status": "Downloaded", "ComicName": "Green Arrow", "IssueID": "493757", "FolderName": null, "Issue_Number": "42", "Provider": null, "Size": null, "DateAdded": "2015-07-28 15:57:25", "ComicID": "42598"}, {"Status": "Downloaded", "ComicName": "Uncanny X-Men", "IssueID": "495810", "FolderName": null, "Issue_Number": "35", "Provider": null, "Size": null, "DateAdded": "2015-07-28 15:51:49", "ComicID": "57181"}, {"Status": "Downloaded", "ComicName": "Gotham by Midnight", "IssueID": "495778", "FolderName": null, "Issue_Number": "7", "Provider": null, "Size": null, "DateAdded": "2015-07-28 15:44:37", "ComicID": "78325"}, {"Status": "Snatched", "ComicName": "Star Trek", "IssueID": "495829", "FolderName": null, "Issue_Number": "47", "Provider": "experimental", "Size": null, "DateAdded": "2015-07-28 15:40:26", "ComicID": "42972"}, {"Status": "Snatched", "ComicName": "Green Arrow", "IssueID": "493757", "FolderName": null, "Issue_Number": "42", "Provider": "experimental", "Size": null, "DateAdded": "2015-07-28 15:40:24", "ComicID": "42598"}, {"Status": "Snatched", "ComicName": "Uncanny X-Men", "IssueID": "495810", "FolderName": null, "Issue_Number": "35", "Provider": "newznab", "Size": null, "DateAdded": "2015-07-28 15:40:23", "ComicID": "57181"}, {"Status": "Snatched", "ComicName": "Gotham by Midnight", "IssueID": "495778", "FolderName": null, "Issue_Number": "7", "Provider": "experimental", "Size": null, "DateAdded": "2015-07-28 15:38:38", "ComicID": "78325"}, {"Status": "Snatched", "ComicName": "Uncanny X-Men", "IssueID": "495810", "FolderName": null, "Issue_Number": "35", "Provider": "experimental", "Size": null, "DateAdded": "2015-07-22 23:03:48", "ComicID": "57181"}, {"Status": "Post-Processed", "ComicName": "The Amazing Spider-Man", "IssueID": "493788", "FolderName": null, "Issue_Number": "19.1", "Provider": null, "Size": null, "DateAdded": "2015-07-01 17:08:11", "ComicID": "73420"}, {"Status": "Snatched", "ComicName": "The Amazing Spider-Man", "IssueID": "493788", "FolderName": null, "Issue_Number": "19.1", "Provider": "KAT", "Size": null, "DateAdded": "2015-07-01 16:57:25", "ComicID": "73420"}, {"Status": "Post-Processed", "ComicName": "Detective Comics", "IssueID": "493756", "FolderName": null, "Issue_Number": "42", "Provider": null, "Size": null, "DateAdded": "2015-07-01 13:08:01", "ComicID": "42594"}, {"Status": "Snatched", "ComicName": "Detective Comics", "IssueID": "493756", "FolderName": null, "Issue_Number": "42", "Provider": "KAT", "Size": null, "DateAdded": "2015-07-01 09:57:16", "ComicID": "42594"}, {"Status": "Downloaded", "ComicName": "Gotham by Midnight", "IssueID": "493002", "FolderName": null, "Issue_Number": "6", "Provider": null, "Size": null, "DateAdded": "2015-06-25 02:22:54", "ComicID": "78325"}, {"Status": "Snatched", "ComicName": "Gotham by Midnight", "IssueID": "493002", "FolderName": null, "Issue_Number": "6", "Provider": "experimental", "Size": null, "DateAdded": "2015-06-25 02:17:16", "ComicID": "78325"}, {"Status": "Post-Processed", "ComicName": "Green Arrow", "IssueID": "471920", "FolderName": null, "Issue_Number": "37", "Provider": null, "Size": null, "DateAdded": "2015-06-18 10:19:46", "ComicID": "42598"}, {"Status": "Snatched", "ComicName": "Green Arrow", "IssueID": "471920", "FolderName": null, "Issue_Number": "37", "Provider": "KAT", "Size": null, "DateAdded": "2015-06-18 10:07:16", "ComicID": "42598"}, {"Status": "Downloaded", "ComicName": "Star Trek", "IssueID": "492245", "FolderName": null, "Issue_Number": "46", "Provider": null, "Size": null, "DateAdded": "2015-06-17 13:31:57", "ComicID": "42972"}, {"Status": "Snatched", "ComicName": "Star Trek", "IssueID": "492245", "FolderName": null, "Issue_Number": "46", "Provider": "experimental", "Size": null, "DateAdded": "2015-06-17 13:26:14", "ComicID": "42972"}, {"Status": "Post-Processed", "ComicName": "Star Trek", "IssueID": "480705", "FolderName": null, "Issue_Number": "42", "Provider": null, "Size": null, "DateAdded": "2015-06-12 10:57:02", "ComicID": "42972"}, {"Status": "Post-Processed", "ComicName": "Star Trek", "IssueID": "482185", "FolderName": null, "Issue_Number": "43", "Provider": null, "Size": null, "DateAdded": "2015-06-12 10:48:19", "ComicID": "42972"}, {"Status": "Post-Processed", "ComicName": "Star Trek", "IssueID": "488683", "FolderName": null, "Issue_Number": "45", "Provider": null, "Size": null, "DateAdded": "2015-06-12 10:46:57", "ComicID": "42972"}, {"Status": "Snatched", "ComicName": "Star Trek", "IssueID": "488683", "FolderName": null, "Issue_Number": "45", "Provider": "experimental", "Size": null, "DateAdded": "2015-06-12 10:46:51", "ComicID": "42972"}, {"Status": "Post-Processed", "ComicName": "Star Trek", "IssueID": "486178", "FolderName": null, "Issue_Number": "44", "Provider": null, "Size": null, "DateAdded": "2015-06-12 10:46:47", "ComicID": "42972"}, {"Status": "Snatched", "ComicName": "Star Trek", "IssueID": "486178", "FolderName": null, "Issue_Number": "44", "Provider": "experimental", "Size": null, "DateAdded": "2015-06-12 10:46:46", "ComicID": "42972"}, {"Status": "Snatched", "ComicName": "Star Trek", "IssueID": "480705", "FolderName": null, "Issue_Number": "42", "Provider": "KAT", "Size": null, "DateAdded": "2015-06-12 10:46:36", "ComicID": "42972"}, {"Status": "Downloaded", "ComicName": "Ultimate Spider-Man", "IssueID": "139384", "FolderName": null, "Issue_Number": "126", "Provider": null, "Size": null, "DateAdded": "2015-06-12 10:05:21", "ComicID": "7257"}, {"Status": "Downloaded", "ComicName": "Ultimate Spider-Man", "IssueID": "152792", "FolderName": null, "Issue_Number": "131", "Provider": null, "Size": null, "DateAdded": "2015-06-12 09:56:55", "ComicID": "7257"}, {"Status": "Snatched", "ComicName": "Ultimate Spider-Man", "IssueID": "152792", "FolderName": null, "Issue_Number": "131", "Provider": "newznab", "Size": null, "DateAdded": "2015-06-12 09:48:13", "ComicID": "7257"}, {"Status": "Snatched", "ComicName": "Ultimate Spider-Man", "IssueID": "139384", "FolderName": null, "Issue_Number": "126", "Provider": "experimental", "Size": null, "DateAdded": "2015-06-12 09:47:04", "ComicID": "7257"}, {"Status": "Snatched", "ComicName": "Ultimate Spider-Man", "IssueID": "152792", "FolderName": null, "Issue_Number": "131", "Provider": "experimental", "Size": null, "DateAdded": "2015-06-12 09:47:01", "ComicID": "7257"}, {"Status": "Post-Processed", "ComicName": "Ultimate Spider-Man", "IssueID": "125977", "FolderName": null, "Issue_Number": "120", "Provider": null, "Size": null, "DateAdded": "2015-06-12 09:24:45", "ComicID": "7257"}, {"Status": "Post-Processed", "ComicName": "Ultimate Spider-Man", "IssueID": "122064", "FolderName": null, "Issue_Number": "118", "Provider": null, "Size": null, "DateAdded": "2015-06-12 09:24:33", "ComicID": "7257"}, {"Status": "Post-Processed", "ComicName": "Ultimate Spider-Man", "IssueID": "106363", "FolderName": null, "Issue_Number": "105", "Provider": null, "Size": null, "DateAdded": "2015-06-12 09:24:22", "ComicID": "7257"}, {"Status": "Post-Processed", "ComicName": "Ultimate Spider-Man", "IssueID": "106252", "FolderName": null, "Issue_Number": "104", "Provider": null, "Size": null, "DateAdded": "2015-06-12 09:22:24", "ComicID": "7257"}, {"Status": "Post-Processed", "ComicName": "Ultimate Spider-Man", "IssueID": "113592", "FolderName": null, "Issue_Number": "90", "Provider": null, "Size": null, "DateAdded": "2015-06-12 09:22:10", "ComicID": "7257"}, {"Status": "Post-Processed", "ComicName": "Ultimate Spider-Man", "IssueID": "157043", "FolderName": null, "Issue_Number": "132", "Provider": null, "Size": null, "DateAdded": "2015-06-12 09:04:10", "ComicID": "7257"}, {"Status": "Post-Processed", "ComicName": "Ultimate Spider-Man", "IssueID": "150690", "FolderName": null, "Issue_Number": "130", "Provider": null, "Size": null, "DateAdded": "2015-0

**Comment by Hellowlol** [comment]
Did it work before? If it did they have changed the api and its easy fix.

**Comment by rudyvarner** [comment]
Actually I don't recall if it ever worked.  I just noticed it now.

**Comment by Hellowlol** [comment]
OK, ill fix it later today.
