### ISSUE TITLE
Sickrage dash issues 

### ISSUE THREAD

**Issue by kooimens** [Hellowlol/HTPC-Manager#31]
The dash module of sickrage isn't showing Next Aired episodes if the airdate is today. Like today:
![1](https://cloud.githubusercontent.com/assets/3150962/6167671/1449794a-b2be-11e4-96a5-2b5a34ed0be3.jpg)
![2](https://cloud.githubusercontent.com/assets/3150962/6167673/17997366-b2be-11e4-8e2b-2c4f60839332.jpg)
Left one is sickbeard, right is sickrage.
Furthermore, maybe it should show the same as sickbeard if no next show can be found.

**Comment by Hellowlol** [comment]
Yeah, i remember i did some hacky go get that part right, and as usual i forgot to update the damn dash.

**Comment by Hellowlol** [comment]
When ever i got some time to do some real work ill redesign the entire dash. I would love to have no extra space and the ability to choose the placement of the "modules", it sucks atm

**Comment by kooimens** [comment]
You're right! Was on my mind as well. Especially, determining the sequence of view on dash would be great.

**Comment by Hellowlol** [comment]
Should be fixed in the last commit

**Comment by kooimens** [comment]
Ok. My Next aired ep is 02-19. Will be able to confirm on that date

**Comment by Hellowlol** [comment]
Oki, i also included missing tvshows in next aired (just like it is i sr)

**Comment by kooimens** [comment]
Nice!
