### ISSUE TITLE
iframe not working behind apache reverse proxy

### ISSUE THREAD

**Issue by l-t-k** [Hellowlol/HTPC-Manager#313]
I'm using 'other apps' like this:
![1](https://cloud.githubusercontent.com/assets/3150962/9225645/e39bb106-410a-11e5-90ab-eb36c3a22647.jpg)

Working fine, if I hit the link I'm redirected to www.example.com/autosub. However, if I enable the iframe, it's not working:
![2](https://cloud.githubusercontent.com/assets/3150962/9225877/1aa3fab8-410c-11e5-8a79-2f066454bc76.jpg)

If i'm using the full url in the 'other apps' settings page, iframe's still do not work:
![3](https://cloud.githubusercontent.com/assets/3150962/9225894/3171f344-410c-11e5-8ca0-8b2691b3ae94.jpg)

**Comment by Hellowlol** [comment]
And if you remove extra / ? Use the full URL

**Comment by l-t-k** [comment]
Without slash, (autosub):
![4](https://cloud.githubusercontent.com/assets/3150962/9230043/6c45f09c-4120-11e5-8f8c-4b29c756aecd.jpg)

I already tried full url, see above

**Comment by l-t-k** [comment]
Without slash htpc goes to www.example.com/home/iframe/autosub. /home is my webdir for htpc.

**Comment by Hellowlol** [comment]
Ok. Can to manually test the URL /iframe?link=someurl.com

**Comment by l-t-k** [comment]
`https://www.mydomain.com/home/iframe?link=https://www.mydomain.com/autosub`

Is working!

**Comment by Hellowlol** [comment]
I expected that. Im i little busy so if you can send a pr about this ill merge it right away. If not ill do do it later. Just add ?link= to the js in default.js
