### ISSUE TITLE
Problems with CP suggestions / charts artwork

### ISSUE THREAD

**Issue by l-t-k** [Hellowlol/HTPC-Manager#315]
For some movies the artwork isn't loaded, but if I click on it, the larger art does show up. It's also correctly loaded in CP. I haven't installed PIL atm, because everything else work fine without it. Can you confirm this is PIL related?

Example 1:
![1](https://cloud.githubusercontent.com/assets/3150962/9247860/0222ad62-41b7-11e5-9ddd-14bb78a58b08.jpg)
![2](https://cloud.githubusercontent.com/assets/3150962/9247862/055b65f0-41b7-11e5-8a6a-388e9eedacba.jpg)

Example 2:
![3](https://cloud.githubusercontent.com/assets/3150962/9247864/0d8171de-41b7-11e5-917d-18175a5c1b68.jpg)
![4](https://cloud.githubusercontent.com/assets/3150962/9247866/0ffd6242-41b7-11e5-8c4c-1aec204835ba.jpg)

**Comment by Hellowlol** [comment]
And if you right click the missing image and manually paste the url htpc manager returns the image correctly? (and you browser isnt ie?). I dont think this is related to pil :/

**Comment by l-t-k** [comment]
I can't click the missing image. This is the only link i get:
http://192.168.0.120:8086/webdir/couchpotato/#

Problem is not IE related this time;). Same happens on Firefox, Chrome or Safari (mobile)

**Comment by Hellowlol** [comment]
Sorry, my bad. Can you try the image source manually?

**Comment by l-t-k** [comment]
I'm not sure what you mean. Some links that work in CP, but NOT in htpc:
http://ia.media-imdb.com/images/M/MV5BMTUwODUyNDM3NV5BMl5BanBnXkFtZTgwNzk0MzA2NTE@._V1_SX300.jpg
http://ia.media-imdb.com/images/M/MV5BMTkxMjgwMDM4Ml5BMl5BanBnXkFtZTgwMTk3NTIwNDE@._V1_.jpg

A link that work in both:
https://image.tmdb.org/t/p/w154/kJjXTVQ0yP6Ns5pd7YiyCYCdS3X.jpg
And HTPC link for same image:
https://mydomain.com/home/couchpotato/GetImage?w=100&h=150&url=https://image.tmdb.org/t/p/w154/kJjXTVQ0yP6Ns5pd7YiyCYCdS3X.jpg

Prob related to the @._V1_?

**Comment by l-t-k** [comment]
Ohh wait. In HTPC they do show up in the large view, but not in the small (poster view). Example link in HTPC (large view link):
https://mydomain.com/home/couchpotato/GetImage?w=154&h=231&url=http://ia.media-imdb.com/images/M/MV5BMTkxMjgwMDM4Ml5BMl5BanBnXkFtZTgwMTk3NTIwNDE@._V1_.jpg

**Comment by l-t-k** [comment]
That last one is the Kingsman movie example

**Comment by Hellowlol** [comment]
Ok. Find the small thumb images scr (the one that does not work) copy it. Delete the all the images in the cache folder, clear the log. Then paste the URL in your browser. Check if that image is ok by opening it in a image program and dump the log here.

**Comment by Hellowlol** [comment]
What was the suggestion you mention n in the title? :)

**Comment by l-t-k** [comment]
Log: http://pastebin.com/9cCNLr7W

The link for the small thumb image is the same as the large one, with one exception (the size)? I don't know how to get the small image link if I it's not loaded, so I took the large one and adjusted the size for the small one in the link(just like all the other small ones). That link is correct and gives me the image (although it's pretty big, not the size I specified in the link).

**Comment by Hellowlol** [comment]
How can you be sure if you can't load it. Just right click that image in your browser, press inspect item. And you should see it there (chrome), yeah all the images are just cached if pil isn't installed. You should install pil, it's faster to serve a 7k thumb the a 1 Mb thumb

**Comment by l-t-k** [comment]
Installed pill. Maybe, this one is useful:

http://pastebin.com/Evnh28sM

**Comment by l-t-k** [comment]
Ok, I really don't get it. Tried inspecting the element. Can't see a link to an image
![1](https://cloud.githubusercontent.com/assets/3150962/9254257/d229d0b4-41e2-11e5-9f0b-52f78006bdfd.jpg)

**Comment by l-t-k** [comment]
This is for the large image (that does work):
![3](https://cloud.githubusercontent.com/assets/3150962/9254326/39e43bcc-41e3-11e5-911c-2dbef226f505.jpg)

**Comment by Hellowlol** [comment]
Ok, good. It's likly that the image we use doesn't on exist. Copy the response from /couchpotato/Suggestion

**Comment by Hellowlol** [comment]
Why I have choosen that a img exist then pick another one is beyond me :p

**Comment by Hellowlol** [comment]
Im closing this as there is nothing i can do to fix this. The links exists, but they dont work. Problem is if i change it, the problem will spread to other movies because now they have a link that dont work.

**Comment by l-t-k** [comment]
@Hellowlol you still need the /couchpotato/suggestion response? Anything I can do to help you out?

**Comment by Hellowlol** [comment]
Nope. The only way to fix this for each movie to request all images. 
hash every image, check the images folder i that hash exist, if it does pass that url to the get_image function. If doesnt, loop all images and verify that the image can be downloaded and is ok. If ok, break the loop and pass that url to get_image. If No image is ok, return a placeholder.

Keep in mind that this is only for one movie....

**Comment by l-t-k** [comment]
Damn it, that seems a to be a lot of work. But it's weird that the larger image does show up and the smaller one does not?

**Comment by Hellowlol** [comment]
Its not alot of work, but it will make the cp module much slower, and honestly i dont want that. It isnt strange, the small image uses another url then the big one. I tried to change that, by using the same url both places, but then some other movies was missing images. (that previously worked)

**Comment by l-t-k** [comment]
Ok clear. It's not an option to only implement the slow method for suggestions/charts tab?

**Comment by Hellowlol** [comment]
No, no really, but ill see if i cant add a placeholder so i doesnt look that ugly. That will help anywhere in the the cp module.

**Comment by Hellowlol** [comment]
i made a branch that tries every image, you can test it here https://github.com/Hellowlol/HTPC-Manager/tree/cpimages

**Comment by l-t-k** [comment]
Lol, I was on my way to clone the branche and then I got error 'branche not found':D. You just merged it. I will test it in master;)

**Comment by Hellowlol** [comment]
Yeah, while the initial load is slow. After that its ok enough, if we want to speed up load we need to limit the data we pull from the api.

**Comment by Hellowlol** [comment]
I cant remember if i did the modals, but im sure you will report any errors ;)

**Comment by l-t-k** [comment]
Damn, works great. I'm testing all of it behind a apache reverse proxy (which is alway a bit slower then facing HTPC manager directly) but speeds are perfect. All images are loaded correctly and fast!

**Comment by Hellowlol** [comment]
Haha, try without any images cached ;) Took like 3 minutes or so. But no missing images now ^^. Or there are but then cp doesnt have any images. I had like 50-60 missing images. I think this was much prettier ^^

**Comment by Hellowlol** [comment]
If you still have any half sized images you need to clean you cache (was files has no content)
