### ISSUE TITLE
Can't start HTPC-Manager anymore

### ISSUE THREAD

**Issue by l-t-k** [Hellowlol/HTPC-Manager#316]
After a new and clean git clone and started with `python Htpc.py`:

`/opt/htpcmanage/libs/ndg/httpsclient/subj_alt_name.py:22: UserWarning: Error imp      orting pyasn1, subjectAltName check for SSL peer verification will be disabled.        Import error is: No module named pyasn1.type
  warnings.warn(import_error_msg)
/opt/htpcmanage/libs/ndg/httpsclient/ssl_peer_verification.py:25: UserWarning: S      ubjectAltName support is disabled - check pyasn1 package installation to enable
  warnings.warn(SUBJ_ALT_NAME_SUPPORT_MSG)
/opt/htpcmanage/libs/ndg/httpsclient/subj_alt_name.py:22: UserWarning: Error imp      orting pyasn1, subjectAltName check for SSL peer verification will be disabled.        Import error is: No module named pyasn1.type
  warnings.warn(import_error_msg)
Traceback (most recent call last):
  File "Htpc.py", line 254, in <module>
    main()
  File "Htpc.py", line 166, in main
    htpc.settings = Settings()
  File "/opt/htpcmanage/htpc/settings.py", line 31, in __init__
    self.updatebl()
  File "/opt/htpcmanage/htpc/settings.py", line 70, in updatebl
    from modules.newznab import NewznabIndexers
  File "/opt/htpcmanage/modules/newznab.py", line 6, in <module>
    from htpc.helpers import get_image
  File "/opt/htpcmanage/htpc/helpers.py", line 20, in <module>
    import workerpool
ImportError: No module named workerpool`

**Comment by Hellowlol** [comment]
update again, i just reverted the commit. I forgot some libs

**Comment by l-t-k** [comment]
Lol, too damn fast:D

**Comment by Hellowlol** [comment]
Damn untracked folders I just checked in explorer. But they was there as I have added them in another branch
