### ISSUE TITLE
Optimize iFrame

### ISSUE THREAD

**Issue by l-t-k** [Hellowlol/HTPC-Manager#317]
I'm using the Iframe for some days now and I really like it. However, to my view some things can be better.
1. Scroll bar should be outlined to the right, just like HTPC does with his own apps.
   Iframe example:
   ![1](https://cloud.githubusercontent.com/assets/3150962/9250940/cc481744-41d0-11e5-8ecd-c4e4b747aec3.jpg)

HTPC app example (correct one):
![2](https://cloud.githubusercontent.com/assets/3150962/9250954/de66af3a-41d0-11e5-8d2f-99de70ee8051.jpg)
1. Use full wide, instead of ugly empty white space on left and right. Especially, when on a mobile device this is really needed:

![unnamed](https://cloud.githubusercontent.com/assets/3150962/9251064/990c673a-41d1-11e5-9100-dd206777a444.png)

![3](https://cloud.githubusercontent.com/assets/3150962/9251103/c9e6f186-41d1-11e5-8343-fd7ec9412867.jpg)
1. The iframe should start, directly underneath the top bar. Right now i'm having some little white space between the top bar and the iframe. This is only visible when using a non-dark theme.
   ![4](https://cloud.githubusercontent.com/assets/3150962/9251158/1611b4f6-41d2-11e5-9f00-0b566baa9956.jpg)

**Comment by l-t-k** [comment]
If you can support me a little, like where to look, I will give a try to fix some things myself

**Comment by Hellowlol** [comment]
Your on your own regarding this. Maybe @raysguy can help you out. Iframes are pita. I'm not good with css, I don't know where to start.

**Comment by fma965** [comment]
all of it would be done in CSS per each theme so thats where you would start. and it actually depends on the theme already, i'm pretty sure none of those issues apart from the scroll bar one existed on the old theme code.

**Comment by Hellowlol** [comment]
I dont think it its, the scroll bar would have been there anyway as we try to resize the iframe to the htpc managers viewport. But i might be wrong :D

**Comment by fma965** [comment]
what? i don't get what your saying.

**Comment by fma965** [comment]
i'll fix it for 1 theme later tonight (onyx) then people can copy the code to the other themes

**Comment by thatbritguy** [comment]
Not really sure what you're trying to achieve here...

**Comment by Hellowlol** [comment]
@raysguy What, who? :P

**Comment by fma965** [comment]
@raysguy put simply in 3 words... "full width iframe"

**Comment by thatbritguy** [comment]
That's not something that needs to be done on a theme by theme basis.  They all share a same core design, so if you need to change anything just add what is necessary to base.css

**Comment by fma965** [comment]
@raysguy oh yeah, i forgot about the base.css :D

**Comment by thatbritguy** [comment]
I'm not sure it's possible to make the iframe full width though as it appears to be functioning correctly at present, e.g. it fills the main content area the same as everything else in HTPC.

**Comment by Hellowlol** [comment]
Iframes and responsive design ftw

**Comment by fma965** [comment]
i reckon i can get it sorted, i had it like it before when i first added the iframe css

**Comment by l-t-k** [comment]
@Fma965 maybe you can have a look at the bottom page of the iframe as well. I'm having an ugly white bar at the bottom of the iframe on each browser I tested (IE, chrome, firefox, safari). So besides full width, full height would be really awesome as well.

**Comment by fma965** [comment]
full height by definition would go over the top nav aswell but yeah full height - navigation etc would be good, can u screenshot this issue

**Comment by l-t-k** [comment]
![1](https://cloud.githubusercontent.com/assets/3150962/9275874/8b59ac90-42a0-11e5-884d-c152952d761b.jpg)

**Comment by fma965** [comment]
it's cuz its full size (width and height) of the content area, this was by design but maybe not the best design choice (for mobiles) my bad

**Comment by Hellowlol** [comment]
@kooimens what device is this on? @Fma965 Add support for resize when the viewport changes?

**Comment by fma965** [comment]
@kooimens old CSS

#webpage {
    width: 100%;
    border: none;
    margin: 0px;
}

New CSS

#webpage {
    width: 100%;
    border: none;
    margin: 0px;
    position: absolute;
    left: 0px;
    right: 0px;
}

Now i just need to fix the bottom gap :)

**Comment by fma965** [comment]
![image](https://cloud.githubusercontent.com/assets/1707290/9277181/5e219846-42a0-11e5-8f3f-99c5b1207103.png)

**Comment by l-t-k** [comment]
Nice! Will give it a try

**Comment by fma965** [comment]
#331 and #332 and !['example'](http://i.imgur.com/svisSVd.png)
!['mobile view'](http://i.imgur.com/OK0L0qx.png)
