### ISSUE TITLE
CSS fixes

### ISSUE THREAD

**Issue by Hellowlol** [Hellowlol/HTPC-Manager#319]
- Fixup general alignment issues
  mostly in mobile view where there are posters. 
- Make tables inside tabs scrollable (fuckups mobile)
- Mobile log alignment
- Kodi movie modal.

**Comment by Hellowlol** [comment]
Any want to help out regarding this please do! :)

**Comment by Hellowlol** [comment]
@raysguy Can you take a look on this branch. https://github.com/Hellowlol/HTPC-Manager/tree/cssstuff
I have started but im really awefull at this...

**Comment by thatbritguy** [comment]
Yeah will do.  What are you trying to change with the thumbnails?  I know for desktop/regular view I baked the CSS into the theme files for the new layout.

I feel your pain.  Mobile view is a PITA in CSS as changes to regular CSS always seem to mess up the responsive!

**Comment by Hellowlol** [comment]
I'm trying to make they look pretty on mobile. It's ok as long as you use a max width, but it's still a pain in the ass. I think I got most of it done, I'm not sure is was done in a good way...
