### ISSUE TITLE
Headphones dash LOOKING AWESOME, but a little bug;)

### ISSUE THREAD

**Issue by kooimens** [Hellowlol/HTPC-Manager#32]
The headphones dash is looking really slick:D. Thanks for that.

One issue found, I have got four wanted albums, but the dash only shows two of them (the first two of the albums wanted list).

**Comment by Hellowlol** [comment]
Im not sure its a bug, if ArtworkURL is missing from the api response, it doesnt show. I made like the intentionally, but i can replace it with the "missing image image" if you prefer that.

**Comment by kooimens** [comment]
Ok! Replacing with the missing image would be better, I think. At least, it shows the whole 'picture' in that case.

**Comment by Hellowlol** [comment]
Allright, ill change it :)

**Comment by Hellowlol** [comment]
I have changed so the image is now added. Regarding the option, that wont happen anytime soon. Ill do that as the same time as redesign of the dash

**Comment by Hellowlol** [comment]
@kooimens Unfortunately the reason why the images have been looking really good is that its a bug when the image is supposed to be resized thus the original image is returned. That isnt a viable option as the thumbs are 300 kb from kodi/plex etc. It works great on the same computer running htpc-manager but access outside your network will be very slow. This needs to get fixed. Ill try to get the images a good as possible.

**Comment by kooimens** [comment]
Can confirm that the dash is showing all my wanted albums now. Great!

Make sense. Give it a low prio anyway. All is working fine now, regarding the HP module.
