### ISSUE TITLE
HTPC Manager Redirects to 127.0.0.1 When Using Reverse Proxy

### ISSUE THREAD

**Issue by brando56894** [Hellowlol/HTPC-Manager#322]
I'm having a strange issue where no matter what external link I use, HTPC-Manager grabs it and then tries to connect to [b]http://127.0.0.1:8085/htpc/auth/login[/b]. What makes this even more odd is that I specifically have it configured to use [b]http://192.168.1.100:8085/htpc[/b], when I start HTPC manager it says "you can connect to HTPC-Manager by accessing http://127.0.0.1:8085" even when I specify an address to listen, I've always assumed that this was just a coding error now I'm starting to think differently.

As seen above, I'm using Nginx on FreeBSD 9.3 to hide all my usenet related apps behind a reverse proxy, with HTPC-Manager being the root page. I had this working before but I've been setting up so many different things, something must've changed because it kept doing this, after pulling my hair out for a few hours trying to figure out WTF the problem was I deleted the jail and started over, which included cloning a new copy of HTPC-Manager since it was crashing due to problems with my SSL config (I'm skipping SSL for now). It's back to doing it again and I have no idea what the problem is since I'm relatively new to Nginx and self hosting.

There are no errors in my Nginx logs relating to this, this is the only thing in my access log: [b] [IP Address] - - [17/Aug/2015:14:59:57 -0400] "GET / HTTP/1.1" 302 108 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0"[/b]

Here's my HTPC-Manager log, which doesn't tell much..

```
2015-08-15 19:39:12 :: root :: INFO :: Welcome to Hellowlol's HTPC Manager fork
2015-08-15 19:39:12 :: root :: INFO :: Loglevel set to info
2015-08-15 19:39:12 :: htpc.updater :: INFO :: Using GitUpdater engine
2015-08-15 19:39:13 :: apscheduler.scheduler :: INFO :: Added job "Updater.update_needed" to job store "default"
2015-08-15 19:39:13 :: modules.kodi :: WARNING :: No configured kodi-Servers.
2015-08-15 19:39:13 :: modules.newznab :: WARNING :: No configured Indexers.
2015-08-15 19:39:13 :: modules.stats :: ERROR :: 'FreeBSD'
2015-08-15 19:39:13 :: htpc.server :: INFO :: Starting up webserver
2015-08-15 19:39:13 :: cherrypy.error :: INFO :: [15/Aug/2015:19:39:13] ENGINE Listening for SIGHUP.
2015-08-15 19:39:13 :: cherrypy.error :: INFO :: [15/Aug/2015:19:39:13] ENGINE Listening for SIGTERM.
2015-08-15 19:39:13 :: cherrypy.error :: INFO :: [15/Aug/2015:19:39:13] ENGINE Listening for SIGUSR1.
2015-08-15 19:39:13 :: cherrypy.error :: INFO :: [15/Aug/2015:19:39:13] ENGINE Bus STARTING
2015-08-15 19:39:13 :: cherrypy.error :: WARNING :: [15/Aug/2015:19:39:13] ENGINE There are [<_MainThread(MainThread, started 34389128192)>, <Thread(APScheduler, started daemon 34512749568)>] active threads. Daemonizing now may cause strange failures.
2015-08-15 19:39:13 :: cherrypy.error :: INFO :: [15/Aug/2015:19:39:13] ENGINE Forking once.
2015-08-15 19:39:13 :: cherrypy.error :: INFO :: [15/Aug/2015:19:39:13] ENGINE Forking twice.
2015-08-15 19:39:13 :: cherrypy.error :: INFO :: [15/Aug/2015:19:39:13] ENGINE Daemonized to PID: 8128
2015-08-15 19:39:13 :: cherrypy.error :: INFO :: [15/Aug/2015:19:39:13] ENGINE Started monitor thread '_TimeoutMonitor'.
2015-08-15 19:39:13 :: cherrypy.error :: INFO :: [15/Aug/2015:19:39:13] ENGINE PID 8128 written to '/var/run/htpc-manager/htpc-manager.pid'.
2015-08-15 19:39:13 :: cherrypy.error :: INFO :: [15/Aug/2015:19:39:13] ENGINE Serving on 192.168.1.100:8085
2015-08-15 19:39:13 :: cherrypy.error :: INFO :: [15/Aug/2015:19:39:13] ENGINE Bus STARTED
2015-08-15 22:26:27 :: cherrypy.error :: INFO :: [15/Aug/2015:22:26:27] ENGINE Started monitor thread 'Session cleanup'.
```

Here's the relevant section of my nginx.conf

```
server {
    listen                  192.168.1.103:80 default_server;
    server_name             mysite.us, femp;
    error_log               logs/error/reverse-proxy.log info;
    access_log              logs/access/reverse-proxy.log;

    location / {
       proxy_pass           http://192.168.1.100:8085/htpc;
    }
```

**Comment by Hellowlol** [comment]
So if you use any external links (like mydomain.com) the "other links" dont work?
Can you take a screenshot of you general settings tabs.

Startup message is hardcoded. See https://github.com/Hellowlol/HTPC-Manager/blob/master2/htpc/server.py#L191

**Comment by Hellowlol** [comment]
Is the iframe option set?. This seems very strange. other links only opens the url via javascript

**Comment by Hellowlol** [comment]
@thejrose1984 Do you use a reverse proxy and have the same issues?

**Comment by thejrose1984** [comment]
@Hellowlol No proxy used in my setup, which looks to be the only difference between my setup and what @brando56894 noted above (unless I'm mistaken).

I do however use HTPC Manager as a frontend (hence the SSL issues) while the usenet web apps are protected behind the my firewall. But I don't have any external apps configured (hence the requests for modules in the past - e.g. LazyLibrarian).

But at least I'm not alone with the issues with this setup :)
After all, misery loves company!

**Comment by thejrose1984** [comment]
@brando56894 is there any particular reason why you need/want a reverse proxy? Have multiple web apps trying to use port 80 or 443?

**Comment by brando56894** [comment]
It was actually happening on internal links also, so out of pure frustration I deleted all of my settings and started over to see if I could replicate it and trace it down better. I just reconfigured things and I think the issues lies within "use rev proxy headers". All the above settings are the same.

Here's an nginx debug log for my reverse-proxies vhost (sanitized to remove my current company's domain and my domain): http://hastebin.com/turatuvawa.sm   

While looking through there it looks like your reverse proxy headers are hardcoded for http://127.0.0.1:8085/htpc/auth/login since this shows up in the last third of the log: 
http proxy header: "Location: http://127.0.0.1:8085/htpc/auth/login"

edit: I had opened port 8085 about an hour ago just to test this directly so that I could see if HTPC-Manager was the issue or if it was Nginx, before I switched on "use rev proxy headers" it worked perfectly if I accessed http://mydomain.us:8085/htpc now after enabling that flag it immediately redirects to http://127.0.0.1:8085/htpc/auth/login  This is a HUGE problem for someone like me who isn't running HTPC-Manager locally since it's neigh impossible to access it after this, the only way to access the site would be to install X11 and a DE/WM then VNC in and access the local site. The only other option would to be to open the settings database and change the status of the flag (I really hate that it uses a database and not a text file like everything else, since it makes editing config settings outside of the site a pain in the ass, not your decision I'm sure).

**Comment by brando56894** [comment]
@thejrose1984 yea I have a bunch of things running and I'd like to open as few ports as possible. I currently have HTPC-Manager (which I would like to be the index/root page of my domain) and then all of the following, which should only be accessible via reverse proxies in HTPC-Manager or directly via sub-domains: CouchPotato, SickRage, HeadPhones and Transmission. I will also be running other sites in other vhosts such as Pydio, PhpMyAdmin, and NewzNab (if I ever get it fully working lol)

**Comment by Hellowlol** [comment]
If it works without reverse proxy headers you turn it off. There is no need for it. I have been using reverse proxy for quite some time and every tine I have skipped the reverse proxy headers. It's also not included in many of the guide (see htpcguides.com) it only there for really obscure stuff, I don't think anybody will ever need it :p

**Comment by Hellowlol** [comment]
@thejrose1984 Ssl should work now. Have you tested? The reason it didn't work was that I had swapped place on key and cert when it was generated....

**Comment by brando56894** [comment]
So that option is pretty much pointless? Why is it there then? It could screw up a bunch of people that thinks it works as it should....

**Comment by thejrose1984** [comment]
SSL worked, then an update broke it lol
Now I have a fresh install on my TODO list...

**Comment by Hellowlol** [comment]
lol what update? :P

**Comment by thejrose1984** [comment]
You tell me lol
I checked one day it said I was 7 versions behind.
Next thing I know SSL didn't work

**Comment by Hellowlol** [comment]
@brando56894 It isnt pointless there might be cases where its needed. However if you enabled it you have to set up correctly.. I would have figure this along time ago if you posted a screenshot of you general settings page as i asked you about ;)

**Comment by brando56894** [comment]
Haha I like to figure out my own issues as much as possible, I've been beating my head against the wall trying to figure out why this is happening and now I know why. I tried to find some info regarding the reverse proxy headers and the config field below it but I could find no information regarding it anywhere. Any chance you could add some info about it somewhere and make a note above the switch or in the info bubble that says it's only needed in certain situations so other people don't end up bugging you with the same issue somewhere down the road? Or so I don't enable it months from now and end up with the same issue hahaha  :)

**Comment by Hellowlol** [comment]
Yeah, i added a bubble to the input field but your right, i should have added something to checkbox as well.

**Comment by Hellowlol** [comment]
So everything is all good now? we can close this issue?

**Comment by brando56894** [comment]
yea everything should be good now, won't really have time to test it out until later.

**Comment by brando56894** [comment]
I don't think this is an issue with HTPC (maybe it is, idk) but maybe you can help: whenever I use my local (http://femp) or external domain name the URI rewrites itself to //auth/login. Here's a debug log from nginx: http://hastebin.com/ovuteparot.sm
