### ISSUE TITLE
UTorrent Progress bars incorrect

### ISSUE THREAD

**Issue by Morphy99** [Hellowlol/HTPC-Manager#323]
All the Progress bars are shown as 100% even when new download. Would be nice to have different colours for finished and errored status as per original web GUI.

**Comment by Hellowlol** [comment]
Can you make a ss of a new download? Regarding the colors it isnt something i will use time on, i dont use that module.

**Comment by Morphy99** [comment]
This is how the Q looks in web gui:
![image](https://cloud.githubusercontent.com/assets/5853979/9414423/5113fa5a-4830-11e5-96c4-b6d43f9db243.png)
This is how it looks in HTPCM:
![image](https://cloud.githubusercontent.com/assets/5853979/9414475/9aadf968-4830-11e5-98a8-e3cf1591aa2b.png)

**Comment by Hellowlol** [comment]
Thanks for the screenshot. I notice we need to reduce the margin bottom on the progress bars. What theme is this? (Don't think it's related to the theme)

**Comment by Morphy99** [comment]
If you notice the downloading torrent bar is green in the not complete % and a more turquoise for the completed %. Hence I think the colours need adjusting.
Its obsidian theme.

**Comment by Hellowlol** [comment]
Yeah I see it. Dunno I care enough to change it. I really, really don't like utorrent.

**Comment by Hellowlol** [comment]
fixed

**Comment by Morphy99** [comment]
I'm not a massive fan of it either but I'm using a winowz machine atm and transmission was a pain on that.

**Comment by Morphy99** [comment]
Looked fixed until something downloaded and it went green again?

**Comment by Hellowlol** [comment]
That intended. I wanted a finished download to have a different color.

**Comment by Hellowlol** [comment]
Try qbittorrent.

**Comment by Hellowlol** [comment]
I'm no fan of the green color. I should have choosen a blue one.

**Comment by Morphy99** [comment]
No, I mean it's white until it starts to download then it goes all green. It's not supposed to do this surely?

**Comment by Hellowlol** [comment]
No it's suppose to be like this:
0 % download bar is all white
50 % downloaded bar is 50 % green/white
100 % downloaded different shade of green the entire bar.

What utorrent version are you using?

**Comment by Hellowlol** [comment]
Oh lol.. I forgot to push it to github.
