### ISSUE TITLE
Make hddbar red after x % used storage

### ISSUE THREAD

**Issue by Morphy99** [Hellowlol/HTPC-Manager#326]
A full disk isn't obvious to the user as the bar is coloured blue. A red colour for under a certain % of free space would be more intuitive.

**Comment by Hellowlol** [comment]
I think it is. The current color scheme is blue: used, green: free. There are no threshold atm., when i made the stats module (my first real contribution to htpc-manager) i wanted to add that. But i couldn't get it to work i just wanted it merged.  

Ill make the used bar red on 90% used space. The js in that module need some housecleaning anyway. Its loads of unused stuff there.

**Comment by Morphy99** [comment]
Great, thanks.

**Comment by Hellowlol** [comment]
done
