### ISSUE TITLE
Links to Couchpotato etc. not formatted correctly

### ISSUE THREAD

**Issue by Outcats** [Hellowlol/HTPC-Manager#328]
Hi,

I've set up the newest version of HTPC manager, but noticed that when I select the "Wanted Movies" option it loads Couchpotato, but the address is formatted incorrectly and as such doesn't loan anything.

Screenshot below:

![couchpotato](https://cloud.githubusercontent.com/assets/11628565/9409152/2f945368-4810-11e5-8108-01a1579e94ef.png)

This seems to happen with any link following through. I have HTPC behind a reverse proxy, under /media/ as seen, and Couchpotato under /couchpotato/ but it is keeping the media part. If I select any link from that page removes the /media/ part and loads as normal. Is there something wrong with my set up:

![settings](https://cloud.githubusercontent.com/assets/11628565/9409218/b9ad3c18-4810-11e5-83df-7a7960c2361e.png)

As you can see, every one I have added (Bar Plex) fails the test, but the link still loads through, I assume this is because they are all on a reverse proxy (Bar Plex) and something needs to be set up?

I've tried putting "Couchpotato" (Without the quotes) in the Basepath entry as well, rebooted HTPC Manager but it has made no difference.

Just to confirm, this is for all of the links added, for the most part everything works still, but links like the "Wanted movies" Doesn't load data, and the dashboard doesn't show any data from the programs (Presumably because the test fails?). Any help in this matter?

**Comment by Hellowlol** [comment]
Hi! I believe you have some issue with your settings/.conf.

If you have htpc manger behind /media/ it should have loaded htpc manager not, couchpotatos interface.

Are you using the reverse prody header option in the general tab? Can you take a screenshot of the general settings page?

**Comment by Outcats** [comment]
Ah no sorry, Loading %Address%/Media will load the HTPC manager interface without issue, when I select any link that loads through to Couchpotato or Sabnzbd or Sonarr etc, it should go from %Address%/media to %address%/couchpotato or %Address%/sonarr, but instead it goes to %Address%/Media/Couchpotato or %Address%/media/Sonarr.

I have couchpotato's Wanted movies on the dashboard, so instead of that link opening %address%/couchpotato/wanted, it opens %address%/media/couchpotato/wanted which loads just the couchpotato interface with nothing in the list. If I then click any links on that page it loads from %address%/media/couchpotato/wanted to %address%/couchpotato/&Whatever_I_Clicked%

**Comment by Hellowlol** [comment]
Can you post a screenshot of your general settings page?

**Comment by Outcats** [comment]
Hear you go:

![image](https://cloud.githubusercontent.com/assets/11628565/9410233/0ca7d9e0-4817-11e5-9c5e-fe8cf5797c7f.png)

![image](https://cloud.githubusercontent.com/assets/11628565/9410238/0fc301f4-4817-11e5-9615-01d26d6b1e4a.png)

**Comment by Hellowlol** [comment]
Try to set the general settings webdir to media. If that dosent work post you reverse proxy config.

**Comment by fma965** [comment]
i'm using a reverse proxy with mine and it works fine, i can maybe help but will need more information. like your proxy config

Why haven't you put anything in reverse proxy link? 

This is how i got mine setup... domainname is obviously not actually domainname but instead a domain name set up with the reverse proxy (ip would work to i guess)

Vhost settings

```
server {
        listen       80;
        server_name  domainname;
        access_log  /var/www/access.log;

        location / {
                rewrite  ^/$  /htpc  permanent;
        }

        location /htpc {
                proxy_pass http://192.168.2.3:8085;
                include proxy.conf;
        }

        location /deluge/ {
                proxy_pass http://192.168.2.3:8112/;
                proxy_set_header  X-Deluge-Base "/deluge/";
                include proxy.conf;
        }

        location /couchpotato {
                proxy_pass http://192.168.2.3:5050;
                include proxy.conf;
        }

        location /sonarr {
                proxy_pass http://192.168.2.3:8989;
                include proxy.conf;
        }

        location /kodi {
                proxy_pass http://127.0.0.1:8080;
                include proxy.conf;
        }

        location /headphones {
                proxy_pass http://192.168.2.3:8181;
                include proxy.conf;
        }
}
```

proxy.conf 

```
proxy_redirect default;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
client_max_body_size 10m;
client_body_buffer_size 128k;
proxy_connect_timeout 90;
proxy_send_timeout 90;
proxy_read_timeout 90;
proxy_buffers 32 4k;
```

This is using Nginx, i then just have the following set up in htpc manager
!['htpc manager'](http://i.imgur.com/afe6WP1.png)

**Comment by Hellowlol** [comment]
Im gonna closed this this isnt a problem with htpc manager but you conf or settings. Post you config and we will try to help you out!

@Fma965 Thanks for posting your conf, im sure it will help (might write a little explanation regarding the rewrite)

**Comment by Outcats** [comment]
My web server is IIS, hosted on Windows Server. my config file doesn't show any details about reverse proxy, it's all set up via the GUI. Would you still need it?

**Comment by fma965** [comment]
No Idea at all for IIS sorry.

**Comment by Hellowlol** [comment]
Totally blank here..

**Comment by Hellowlol** [comment]
@Outcats did you set the webdir in the general settings page as i suggested?

**Comment by Outcats** [comment]
Yeah, I set it:

![image](https://cloud.githubusercontent.com/assets/11628565/9436757/83c4bc80-4a49-11e5-898e-db949db4c33c.png)

(Sorry about not replying over the weekend, had a busy one)

**Comment by Hellowlol** [comment]
Np, im sorry i cant assist you anymore. Try some iss forum or stackoverflow. I use a rpi (nginx) as a reverse proxy as im a windows user

**Comment by Outcats** [comment]
Not a problem, It isn't a major issue, the links still go through to the individual programs, it mostly functions without issue, only some of the links semi break, if I can't get it fully fixed then it won't be a major issue.

**Comment by Hellowlol** [comment]
You should try to specify reverse proxy links, if you don't it will try to open http//:localhost:5050/couchpotato etc

**Comment by Outcats** [comment]
From HTPC Manager, or IIS?

**Comment by Hellowlol** [comment]
In htpc manager. It only changes the link in the html. So the browser should handle that. It will still fuck up if the reverse proxy if configure wrong. But its worth a try.
