### ISSUE TITLE
Plex not saving or connecting

### ISSUE THREAD

**Issue by KrunchMuffin** [Hellowlol/HTPC-Manager#329]
I have a ' in my Plex name and it put it as ASCII in the menu, I thought that was the issue why it wouldn't work, so I took it out but it still doesn't work. After I save the settings, the dropdown does not keep the value. If I test before saving, there is an error also. Windows 10. Plex on same box.

**Comment by Hellowlol** [comment]
Do you mean your plex name as the module name, or "myplex name". Can you post a screenshot of your plex settings?

The ASCII is because we try to protect any users against xss attacks.

**Comment by Hellowlol** [comment]
Logs?

**Comment by KrunchMuffin** [comment]
here is the gist of the error. My plex friendly name was D's Plex. When saved, the menu at the top of HTPC had D&#39;s Plex

```
2015-08-21 11:47:34 :: modules.plex :: INFO :: Sending discovery message: M-SEARCH * HTTP/1.0
2015-08-21 11:47:35 :: modules.plex :: INFO :: GDM: Servers discovered: 1
2015-08-21 11:47:35 :: modules.plex :: ERROR :: Unable to contact Plex via http://192.168.0.31:32400 error HTTP Error 401: Unauthorized
```

**Comment by Hellowlol** [comment]
Do you use plex home? Or has activated plex home in pms settings ? If so you need to add the username and password

**Comment by KrunchMuffin** [comment]
If you mean PHT then yes, but different machine

**Comment by Hellowlol** [comment]
I meant Plex Media Server. "Plex Home" is a feature that have they have. Add a username and password :)

**Comment by KrunchMuffin** [comment]
Yes, PMS is on same server and I did add username/pwd

**Comment by KrunchMuffin** [comment]
![image](https://cloud.githubusercontent.com/assets/1037197/9413901/d7a365ca-4802-11e5-8afb-04305e3bb1b1.png)

**Comment by Hellowlol** [comment]
Strange. Clear your log. Shut down htpc manager start it with --loglevel debug. Access the plex modele directly. Then paste the entire log here.

**Comment by KrunchMuffin** [comment]
ok, so it worked this time. This is what I _think_ may be the issue. I first setup the plex settings in htpc w/o a username/pwd, saved tested etc, then came back and added and possibly there was some caching issue that didn't take the newly entered login info? Just a thought. Thanks for the help.

**Comment by Hellowlol** [comment]
Ok. I'm glad you got it working.

**Comment by warplayer** [comment]
Hello, I just set up HTPC-Manager earlier today and I'm really loving it. I am having the exact same issue KrunchMuffin detailed in this post. I shut down htpc manager and turned on --loglevel debut like you suggested. Unfortunately it did not fix my issue like Krunch. Here is my log: http://pastebin.com/JqeFu5SA

Thanks in advance for taking a look.

**Comment by Hellowlol** [comment]
Log says unauthorized. Are you using plex home? Ssl?

**Comment by warplayer** [comment]
Yes, is that not supported?
