### ISSUE TITLE
Newznab search, NZB manual download: not working and mouseover text is missing

### ISSUE THREAD

**Issue by kooimens** [Hellowlol/HTPC-Manager#33]
The manual download button doesn't do anything if I hit it. 
Some mouseover text is missing as well. Like: 'Manual download NZB' or something

**Comment by Hellowlol** [comment]
Looks fine and works here. What browser are you using? Can your try with chrome?

**Comment by Hellowlol** [comment]
@kooimens Can you update and try again?

**Comment by kooimens** [comment]
Tried with IE, chrome and FF. All working after the latest commit. Except for the blue big button (after hitting the NZB). That one isn't working in any browser.

**Comment by kooimens** [comment]
@Hellowlol You noticed my comment about the mouseover?

**Comment by Hellowlol** [comment]
Not really :P Did you want a mouse over on the icon? The big blue button do you mean the modal? I forgot to test that one..

**Comment by kooimens** [comment]
It's not really a matter of 'wanting' it, but more a way to stay consistent, because the sabnzbd button does show a mouseover. 

I mean this one:
![1](https://cloud.githubusercontent.com/assets/3150962/6192275/86b54dd6-b3b0-11e4-8098-0fbf6dac0a3f.jpg)
