### ISSUE TITLE
Search functionality for CP

### ISSUE THREAD

**Issue by l-t-k** [Hellowlol/HTPC-Manager#335]
I'm using the 'Search Table' function very often since I discovered it:). To be honest, it's a really powerful tool within HTPC-Manager. At the moment, the search function is not yet implemented for the CP and PLEX module. Would be great to have a search function for this modules as well.

**Comment by Hellowlol** [comment]
The plex module is the most advanced one. It should work there :), it does not work in cp (no table to search)

**Comment by l-t-k** [comment]
You're right the plex module is working. However, the placeholder name (Default 'Search') changes to 'Search table' if a search is possible. For the plex module, the name does not change.

Furthermore, for HP and sickrage I can hit enter, but nothing happens (correct behaviour, because i'm just searching the table in that case). For plex it brings me to the newznab search module if I hit enter (not correct I think?).

**Comment by Hellowlol** [comment]
It will show search table is there is a table in that module and I have activated it. For other modules it might not change (plex, kodi)

You can also do stuff like genre=action in the plex module. Pressing enter should not search for nzbs.

**Comment by l-t-k** [comment]
Unfortunately, hitting enter does search for nzbs...

I tried, genre=action and genre=comedy, but both returns me with zero results, although I'm 100% sure I have some movies of this type of genre in my lib.

**Comment by Hellowlol** [comment]
Fixed the enter thing, hm it works here :(

**Comment by Hellowlol** [comment]
@kooimens try hitting enter after the last char.

**Comment by l-t-k** [comment]
Thanks, working. Although, if I hit enter once it will show the result again. Hitting the enter bar several times ends up with this: :D

![1](https://cloud.githubusercontent.com/assets/3150962/9567615/eae33dd6-4f32-11e5-8827-60e5fce72ae9.jpg)

**Comment by Hellowlol** [comment]
And why would you spam enter? :p I just tapped in to the functions, seems removable off old content is protected by some funky shit.

**Comment by Hellowlol** [comment]
Anyway I can fix that, what I meant was test the genre. Remember that old content isn't removed and there also a protection against the search function to crap out if it contains =!<>. Best way to test before I fix the issue with old content is to copy paste genre=action into the search field.

**Comment by Hellowlol** [comment]
Regarding you request for cp, I don't think it's supported by the api, but I'll try to hack something together, if it's fast enough I'll merge it.

**Comment by l-t-k** [comment]
Hitting enter just sounds awesome:D. Hmm, tried copy paste genre=action, but no change in results. I use dutch language in the plex module, maybe that's the problem?

**Comment by Hellowlol** [comment]
dunno, i didnt think so.

**Comment by Hellowlol** [comment]
I have added search for wanted and library. 
You can do:
16 blocks
genres=action
plot=cake
if the value your looking for you have to use logical operators
rating<=9
year!=2010
etc

**Comment by Hellowlol** [comment]
I also fix the enter thing

**Comment by l-t-k** [comment]
Nice! My findings after some tests:
1. PLEX - music. The 'enter thing' is still there when searching artists.
2. PLEX - music. Search is not working when searching songs.
3. PLEX - all. Noticed a new 'enter thing', but now it occurs when spamming backspace. Doing a search and then bringing back the search field to null with backspace is working, every next backspace hit returns the full table (without a search) again, resulting in multiple copies of the same table.
4. PLEX - all. The name of the search placeholder is 'Search'

**Comment by Hellowlol** [comment]
1. Dont use music so that slippes my mind
2. Dunno if i cba with fixing it
3. I don't get it. can you take a ss
4. Forgot that

**Comment by l-t-k** [comment]
![1](https://cloud.githubusercontent.com/assets/3150962/9682013/f6d0a72c-5302-11e5-89d8-8fcd71d8e4b1.jpg)
1. As you can see, all the movies are there twice. When I hit the print-screen button, all the movies where there tripled. Another hit after that would bring up four identical versions of each movie, and so on...
