### ISSUE TITLE
Make search-bar placeholder variable to use active tab-name.

### ISSUE THREAD

**Issue by l-t-k** [Hellowlol/HTPC-Manager#336]
All of my users, including myself, were not aware of the search functionality. One of the reasons, I think, is related to the search bar placeholder. Is it possible to use the active module tab-name instead of 'table'. E.g. for headphones it will be like, 'Search Artists' if on artists tab and 'Search Wanted' if on wanted tab. Somewhere here:

https://github.com/Hellowlol/HTPC-Manager/blob/master2/interfaces/default/js/default.js#L94

**Comment by thatbritguy** [comment]
Maybe it doesn't need to be as specific as every tab of every module.  How about when on the Plex module it says "Search Plex Library", on HP "Search Headphones" etc?

**Comment by l-t-k** [comment]
Agreed. In that case, the 'menu name' (user defined) would be the best option?

**Comment by Hellowlol** [comment]
Hmm, I'll see if I can't find a way to solve this, I will not go with a generic one as it only searches current table. I only added the search table as a hit so ppl should discover the feature. Seems it failed :D

**Comment by Hellowlol** [comment]
What I have now is:

If the module has tabs and a table that is sortable use that tabs name,

if active tabs table isn't sortable set default (search)

If a module has sortable table but no tabs, try to get the name from the interface link, if it isn't grab module name from the h1 tag.

In any other cases it should just be "search"

**Comment by l-t-k** [comment]
Perfect! Works for HP, sickrage, sabnzbd. 
1. For plex, the name is still 'Search', although search functionality is working.
2. If a table isn't sortable or if on dash the search functionality can be used to search for NZB's and torrents right? No more? If that's the case, why not changing the default Search to Search NZB/Torrent, or eventually 'Search NZB' if only the newznab module is enabled and 'Search Torrent' if only the torrent search is enabled. 'Search NZB/Torrent' if they are both enabled?

**Comment by Hellowlol** [comment]
1. Yeah, i havnt done that yet, ill do that later
2. JS dont have direct access to the db (for obvious reasons), ill leave it like search for now. There isnt any torrent search from that input field, it has been replaced by a form, that field will no filter the torrents results after the search is done.
