### ISSUE TITLE
Improvements/bugs with plex music

### ISSUE THREAD

**Issue by l-t-k** [Hellowlol/HTPC-Manager#337]
1. On dash, you can always see the five last added music albums. A click on a certain new album on dash will bring you to the PLEX module / Music / Albums tab. A redirect to the plex module showing the album you clicked (and the music numbers belonging to it) will be better.
2. Clicking an album on PLEX / Music / Albums tab should return the songs belonging to that particular album and all the songs in my library (related to 1.)
3. The Plex module / Music / Songs tab isn't working correctly. When I scroll down the page, the app immediately brings me back to the top of the page. Strange behaviour and it occurs on every browser I tested (Chrome, IE, Firefox).

**Comment by Hellowlol** [comment]
1. Rejected
2. Rejected
3. done

While 1 and 2 seems like a easy request, well it isn't.. :p 
I think the benefit is far less the effort I have to put in to make that work.
