### ISSUE TITLE
Improvements/bugs with wanted albums

### ISSUE THREAD

**Issue by l-t-k** [Hellowlol/HTPC-Manager#338]
I'm not sure if you're aware of this issues. If so, then it is just a reminder;)
The dash wanted albums module should only be as large as there are wanted albums. If no wanted albums exist, the module should be of only one row (the one that says 'no wanted albums'). If there are three wanted albums, only three rows. The sabnzbd and sickrage module are working correct. This is not related to a certain browser. Examples:
![2](https://cloud.githubusercontent.com/assets/3150962/9521641/4d8c68e6-4cd0-11e5-9b7d-039cee0dd944.jpg)
![3](https://cloud.githubusercontent.com/assets/3150962/9521645/527d6c1a-4cd0-11e5-871c-aacf2bb132eb.jpg)

Bug with IE and wanted albums:
![1](https://cloud.githubusercontent.com/assets/3150962/9521650/5fe8aac2-4cd0-11e5-8009-759707fecfd8.jpg)

**Comment by l-t-k** [comment]
Maybe, it's an idea to just change the way HTPC-Manager shows the wanted albums? Make it the same way as Next Aired? Just a table with artist - album - release date. That would probably fix the IE bug, and make the wanted albums dash more consistend with the other 'wanted' dash modules. Furthermore, I'm having many 'stretched' and 'ugly' album covers for my wanted albums module that would be fixed as well.

**Comment by Hellowlol** [comment]
I have no interest is rewriting it as I don't use it :p, I will accept
A pr tho. As for the error handler you can probably fix that your self. (Only need so edit some HTML in the error handler)

The images are really tricky as we have to choose between a cropped or stretched image.

**Comment by l-t-k** [comment]
Will give it a try!

**Comment by Hellowlol** [comment]
Fixed in a unpushed branch.

**Comment by l-t-k** [comment]
I think your comment is just a reminder for yourself? If you're referring to a branche in my repo: that one is far from fixed;). I'm trying to get a bit more familiar with the sublime text editor and the javascript language. I can give it a shot tomorrow.

If you're pointing to a branche of yourself: what branche exactly? So I can test it.

**Comment by Hellowlol** [comment]
Ah sorry, it was fixed in the lastest update :P But i welcome all contributions.

**Comment by l-t-k** [comment]
Thanks!
