### ISSUE TITLE
Sonarr not pulling info

### ISSUE THREAD

**Issue by mraneri** [Hellowlol/HTPC-Manager#34]
Sonarr test comes back green, but does not pull any information. 

2015-02-12 11:46:50	cherrypy.error.24964064	ERROR	[12/Feb/2015:11:46:50] HTTP Traceback (most recent call last):
2015-02-12 11:46:50	modules.sonarr	ERROR	Failed to fetch path=Calendar?end=2015-02-19 error No JSON object could be decoded
2015-02-12 11:41:07	cherrypy.error.24964064	ERROR	[12/Feb/2015:11:41:07] HTTP Traceback (most recent call last):
2015-02-12 11:41:07	modules.sonarr	ERROR	Failed to fetch path=Calendar?end=2015-02-19 error No JSON object could be decoded

**Comment by Hellowlol** [comment]
Thanks for reporting this. Dunno why it doesn't  work. I'll see if I can't fix it.

**Comment by Hellowlol** [comment]
This seem to work here:

![image](https://cloud.githubusercontent.com/assets/1214134/6175509/a5f064a6-b2f7-11e4-900f-18bc220929bc.png)

What info do you get back when you call the api command manually?

**Comment by mraneri** [comment]
What command should I use to call it manually?
I ended up deleting everything and starting over this morning. Still the same error.

**Comment by Hellowlol** [comment]
Call http://ip:port/api/Calendar?end=2015-02-20 with a X-Api-Key header. There are some chome addons that can do this for you. If you cant to it ill make a simple script you can run when the kids are in bed

**Comment by Hellowlol** [comment]
Try this script:
https://gist.github.com/Hellowlol/49ac918aace8f31f617b

In cmd: python test_calendar.py > calendar.txt
Copy the content inside calendar txt and upload it to pastebin. Give me the link ;)

**Comment by mraneri** [comment]
http://pastebin.com/Wj8SxLrz

hope this helps

**Comment by Hellowlol** [comment]
Do you have a show with the letter é (0xe9) in? If thats the case what is the name?

**Comment by mraneri** [comment]
No, the only non-letter characters are @midnight, Key & Peele, M.A.S.K., Bob's Burgers, and a few with years like Archer (2009) or Conan (2010)

**Comment by Hellowlol** [comment]
Honestly have i no idea how to fix it. Do the other parts of the module or is it only the calendar?

**Comment by mraneri** [comment]
I don't see anything from Sonarr

**Comment by mraneri** [comment]
OK, by pure accident I figured it out.
For basepath I had it set to the default of '/sonarr'. I accidentally
clicked the Sonarr title taking me to localhost:8989/sonarr which returned
a 404.
Setting the basepath to just '/' made everything work.

All of the other modules worked fine with the default basepaths, Sonarr was
the oddball.

**Comment by Hellowlol** [comment]
The code should be exactly the same. So that's strange, I'm happy you got it sorted!
