### ISSUE TITLE
No HDD or System info showing 

### ISSUE THREAD

**Issue by ScouseTS** [Hellowlol/HTPC-Manager#340]
First of all this is an excellent project.

I've got it up and running on my windows server 2008 r2 box but for some reason it doesn't show any HDD or System info stats. S.m.a.r.t works fine.

"Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\HTPC-Manager-master2\libs\cherrypy_cpreq
uest.py", line 670, in respond
    response.body = self.handler()
  File "C:\Users\Administrator\Desktop\HTPC-Manager-master2\libs\cherrypy\lib\en
coding.py", line 217, in **call**
    self.body = self.oldhandler(_args, *_kwargs)
  File "C:\Users\Administrator\Desktop\HTPC-Manager-master2\libs\cherrypy\lib\js
ontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(_args, *_kwargs)
  File "C:\Users\Administrator\Desktop\HTPC-Manager-master2\libs\cherrypy_cpdis
patch.py", line 61, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "C:\Users\Administrator\Desktop\HTPC-Manager-master2\modules\stats.py", l
ine 213, in sysinfodash
    cpu = psutil.cpu_times_percent(interval=0.1, percpu=False)
NameError: global name 'psutil' is not defined
2015-08-28 18:23:59 :: modules.sonarr :: ERROR :: Failed to fetch url=https://:/
api/Calendar?end=2015-09-04 path=Calendar?end=2015-09-04 error Invalid URL u'htt
ps://:/api/Calendar?end=2015-09-04': No host supplied
2015-08-28 18:23:59 :: modules.stats :: ERROR :: Could not get disk info global
name 'psutil' is not defined"

I have a sneaky feeling it's to do with this :-)

**Comment by Hellowlol** [comment]
Thanks! Your right, you don't have psutil installed on your computer. Download it from here https://pypi.python.org/pypi?:action=display&name=psutil#downloads
Remember to add a host name and port to sonarr settings as well (just noticed that error in the log)

**Comment by ScouseTS** [comment]
Thanks working fine now.

Much appreciated. :+1:

**Comment by Hellowlol** [comment]
Good, let Me know if you have any other issues.

**Comment by ScouseTS** [comment]
Is it possible to add a remote plex server? I am running this on a server I have network mounted to my plex server for additional storage.

Tried putting the ip/port with my plex creds but not connecting.

**Comment by Hellowlol** [comment]
Remote as not connected to your local network? I don't know I have never tried that, but don't think if should be a issue if you use a raw ip and a port.

**Comment by ScouseTS** [comment]
Yeah it's a different dedicated server.

I've tried raw ip/port with my plex account creds, says failed.

**Comment by Hellowlol** [comment]
Don't trust the test button. Just open the module and see if it works there.

**Comment by Hellowlol** [comment]
Check the log to see why it failed :)

**Comment by ScouseTS** [comment]
Saying it's unauthorised when it's accessing my server:32400.

I've put plex credentials and can't find any seperate credential options within plex. Guess it just doesn't work.

**Comment by ScouseTS** [comment]
I will just leave the install on the server plex is installed on and connect the sonarr and couchpotato to the server I use for storage :+1:

**Comment by ScouseTS** [comment]
Any idea what this means?

Just noticed the system stats are:

CPU 
User: 100.0%System: 0.0%Idle: 0.0%
MEM 
Used: 7.1 MBFree: 8.6 MB

Server had 16GB RAM and CPU is only at 13%
2015-08-28 23:08:46 :: htpc.helpers :: ERROR :: Can't resize when PIL is missing
 on system!

**Comment by Hellowlol** [comment]
Was that on the dashboard or in the stats module? Are you using the latest it? You need to install pil or pillow if you want htpc manager to manipulate images.

Check if there is any updates for htpc manager.

See https://github.com/Hellowlol/HTPC-Manager/blob/master2/requirements.txt for a full list of "requirements"
