### ISSUE TITLE
ERROR :: Required package 'smartmontools' is not installed, or 'smartctl'

### ISSUE THREAD

**Issue by brando56894** [Hellowlol/HTPC-Manager#341]
It's definitely installed but I can't get it to detect it

 root@Usenet:/usenet/htpc-manager# find /usr -name smartctl
/usr/bin/smartctl
/usr/sbin/smartctl
/usr/local/sbin/smartctl

I'm using FreeBSD 9.3

**Comment by Hellowlol** [comment]
What smartmontools version is installed? I don't know why it doesn't work as pysmart should work on FreeBSD. Is this free nas? I emailed the author here the other day and he say he wanted to add support for OS X and get some code changes from the guys that requested FreeBSD support.

**Comment by brando56894** [comment]
smartmontools v6.4_1

Yes this is on FreeNAS, it's inside of a standard FreeBSD 9.3 jail.

**Comment by Hellowlol** [comment]
does it work when you call it manually?

**Comment by Hellowlol** [comment]
We just have to wait for until the changes from https://github.com/freenas/py-SMART are added to upstream

**Comment by brando56894** [comment]
Ah ok, I'm switching all of my apps to an Arch Linux VM inside of FreeNAS, BSD is pissing my off hahaha

Thanks!
