### ISSUE TITLE
Sonarr Enhancement 

### ISSUE THREAD

**Issue by edcaruso** [Hellowlol/HTPC-Manager#343]
By default through the API, Sonarr adds a new TV Show and will search for "all" and sometimes results in multiple seasons being downloaded. In sonarr itself, you have the option to select "All, future only, past etc." It would be nice to see that option added. Or even change the default from "All"

HTPC Manager interface options
![screen shot 2015-09-08 at 10 51 49 pm](https://cloud.githubusercontent.com/assets/8314846/9752291/504f86ac-567c-11e5-8e52-4b634954ff9f.png)

Sonarr Interface options:

![screen shot 2015-09-08 at 10 52 16 pm](https://cloud.githubusercontent.com/assets/8314846/9752301/6e2dff82-567c-11e5-906f-22c4c067fe1d.png)

**Comment by Hellowlol** [comment]
Is this something that was added lately? i cant remember i have seen that option before (i belive you could choose season to start)

**Comment by Hellowlol** [comment]
https://github.com/Sonarr/Sonarr/commit/32dd545ef96af604ebd421fe45d0023b71c5d302#diff-c522769d0fe8e83d667bf82a253dc88eR173
no api docs

**Comment by edcaruso** [comment]
Thanks for getting back so quick. I'm not sure if it was just added recently or not. I think the default behavior was always future episodes but it looks now the default is set to All. Maybe it's just my config but I don't think so. 
When you change it in sonarr to future or whatever you choose, it remembers your choice for the future series you add. 
Sent from Outlook

```
_____________________________
```

**Comment by Hellowlol** [comment]
Ok, i dont believe that option was there when i made the sonarr module, but it doesnt matter. Im sure i can add support for this. The api docs are lacking and i dont have alot of spare time atm, but ill get it done. It just gonna take a while.

**Comment by edcaruso** [comment]
No worries! If I get a chance I'll dive in and see if I can figure it out but no promises. Not that great at code lol. They must of recently added this option. 
Take your time :) thanks again! 
Sent from Outlook

On Wed, Sep 9, 2015 at 5:43 AM -0700, "Hellowlol" notifications@github.com wrote:

Ok, i dont believe that option was there when i made the sonarr module, but it doesnt matter. Im sure i can add support for this. The api docs are lacking and i dont have alot of spare time atm, but ill get it done. It just gonna take a while.

**Comment by Hellowlol** [comment]
Can you test your request in the latest update?

**Comment by edcaruso** [comment]
that works awesome. I verified it with a few shows and different qualities and such and no issues to report. What happened to not having the time :D ? Thanks a bunch. Hope this helps out a bunch of other folks too. It was pretty cool seeing your edits via GitHub. Cheers!!!

**Comment by Hellowlol** [comment]
My gf got called to work, so ours plans when to shit :P
