### ISSUE TITLE
Suggestion: Sonarr Series Type

### ISSUE THREAD

**Issue by Kussie** [Hellowlol/HTPC-Manager#345]
I just noticed in the latest update you added support for The Search type when adding a TV Show via Sonarr.  

One last thing missing from there that i have noticed is the Series Type option, would it be at all possible to add that to the list as well?

This is how it looks in Sonarr: (The options are Standard, Daily and Anime)
![image](https://cloud.githubusercontent.com/assets/4960791/9786558/4c4f0cb6-57fe-11e5-88a6-bb8e1fe172d9.png)

**Comment by Hellowlol** [comment]
It that a option that i widely used?  Im just asking since i watch 0 anime and 0 daily shows. I can add it if the "menu" doesnt wrap

**Comment by Kussie** [comment]
Personally i use both options, Anime more then daily, but still.

**Comment by Hellowlol** [comment]
Ok

**Comment by Hellowlol** [comment]
@Kussie Can you update to the latest version and see if it works as you expected?

**Comment by Kussie** [comment]
Perfect!

Awesome work mate :D
