### ISSUE TITLE
System Info whitelist doesnt work

### ISSUE THREAD

**Issue by ezar** [Hellowlol/HTPC-Manager#346]
BRANCH  master2
Current commit  e8b28f3cc32368499ce91ce3ce87117012011da2

I cannot use whitelist in system info for filter Mountpoint

**Comment by Hellowlol** [comment]
Have you set the file system?

**Comment by ezar** [comment]
Yes.
I put /mnt/usb

**Comment by Hellowlol** [comment]
When its a white list you to set filesystem AND mountpoint.

**Comment by ezar** [comment]
Oh yeah!
Thanks
