### ISSUE TITLE
Updates are wiping my settings

### ISSUE THREAD

**Issue by edru** [Hellowlol/HTPC-Manager#35]
Everytime I check for updates, then update, all my settings go back to default.

**Comment by Hellowlol** [comment]
Is this when installed from source?

**Comment by edru** [comment]
yeah. Today i had 5 updates available, and after restart it was all
default. I just reconfiged everything and did 2 more updates and it stayed.

**Comment by Hellowlol** [comment]
Is it the sourceupdater of git updater your using? And if its git. Are the git clean checked in settings?

**Comment by edru** [comment]
i synced it from source via git. Yean git clean was checked. I guess that
would do it huh? Damnit, facepalm. Figured that wouldnt have purged
settings.

**Comment by Hellowlol** [comment]
Well the idea was to keep it save.
  # Note to self rtfm before you run git commands, just wiped the data dir...
 # This command removes all untracked files and files and the files in .gitignore
# except from the content of htpc.DATADIR and VERSION.txt
 self.git_exec(self.git, 'clean -d -fx -e %s -e VERSION.txt' % htpc.DATADIR)

**Comment by Hellowlol** [comment]
Can you make a backup of your db and try  git clean -d -fx -e VERSION.txt - e userdata/ and see it the db is still here after the command i runned

**Comment by edru** [comment]
edru@HK-Drone:~/ServerApps/HTPCManager/userdata$ ls
database1.db  database.db  htpcmanager.log  images
edru@HK-Drone:~/ServerApps/HTPCManager/userdata$ cd ..
edru@HK-Drone:~/ServerApps/HTPCManager$ git clean -d -fx -e VERSION.txt - e
userdata/
Removing userdata/
edru@HK-Drone:~/ServerApps/HTPCManager$ ls
Dockerfile        htpcmanager.pid  initd.fedora  LICENSE    requirements.txt
htpc              Htpc.py          interfaces    modules
HTPC-Manager.bat  initd            libs          README.md


looks like it removed the enitre folder all together.

**Comment by Hellowlol** [comment]
Ok, leave it unchecked for now.
