### ISSUE TITLE
Feature request plexpy

### ISSUE THREAD

**Issue by Hellowlol** [Hellowlol/HTPC-Manager#350]

**Comment by henkjanvries** [comment]
i was just discussion this with a friend of mine to get stats torso on the home of htpc, but now ill let it to you!

**Comment by Hellowlol** [comment]
What is stat torso? ;p

**Comment by henkjanvries** [comment]
sorry i meant" stats or something like that"

**Comment by tymanthius** [comment]
I would LOVE for this type of functionality to be added, esp. if it could support emby as well.

**Comment by hpbrad** [comment]
+1

**Comment by antoinesylvia** [comment]
+1

**Comment by gostlund** [comment]
+1

**Comment by jodfie** [comment]
+1 PlexPy

**Comment by NeskireDK** [comment]
+1
