### ISSUE TITLE
iPad dashboard view

### ISSUE THREAD

**Issue by phairplay** [Hellowlol/HTPC-Manager#352]
Hi,
Great app it just what I was looking for

I mainly control my htpc via my iPad would it be possible to have the dashboard mobile friendly?

**Comment by Hellowlol** [comment]
It should be that already. If not post a screenshot

**Comment by phairplay** [comment]
Just looked on my android phone and it good 
Yet iPad looks cramped 
![image](https://cloud.githubusercontent.com/assets/9025847/10204696/274b8590-67b5-11e5-9ece-2fff6fc685b9.jpg)

**Comment by Hellowlol** [comment]
Have you used the orginal htpc manager on that ipad before? If have you need to delete the "log and webpage data" in safari settings. 

See 
![image](https://cloud.githubusercontent.com/assets/1214134/10204915/b8d5675c-67be-11e5-8fed-93d4505418af.png) for how it should look. (i dont have access on my ipad now, but it looks good, only thing i isnt happy with is stats module in the dashboard)

**Comment by phairplay** [comment]
No I haven't but I'll clear the log and give it a try

I've done something stupid how do I reset the user and password (sorry)

Oh and thanks for responding so quickly

**Comment by Hellowlol** [comment]
LOL, i have done the same. thats why you can fix it with `python htpc.py --resetauth`

**Comment by phairplay** [comment]
Sorry where do I execute this

**Comment by Hellowlol** [comment]
In the console. Shutdown htpc manager, and start it again with python htpc.py --resetauth in the commandline

**Comment by phairplay** [comment]
And stupid of the week goes too...me 

Regarding the iPad I've cleared the web cache ect and its more to do with sonarr next air it looks quashed, would it be able to add the ability to stretch it out?

Cheers again great app

**Comment by Hellowlol** [comment]
Hmm, can you add a screenshot?

**Comment by phairplay** [comment]
It's in my first screenshot

**Comment by Hellowlol** [comment]
Well the entire screen shot seems off, anyway if there isnt enoght space the text will be shorted. I dont have a better way to solve this yet. :(

**Comment by phairplay** [comment]
Okay it was worth asking it's not a deal breaker as it looks good on my android
