### ISSUE TITLE
Suggestion: Sonarr - Add + Search, instead of standard Add

### ISSUE THREAD

**Issue by CJICantLie** [Hellowlol/HTPC-Manager#353]
Currently, if a user adds a show to Sonarr through HTPC Manager, it is only "Adding" the show, which defaults in Sonarr to waiting on releases in Rss feeds.  

If you add a show directly in Sonarr, you have the "Add" option, and the "Add + Search" option.  

I recommend that HTPC Manager's Add feature send the "Add + Search" command instead of the standard "Add".  

Or give the option of either way.  

I would like to use HTPC Manager as a way for friends/family to add shows to Sonarr, without having direct access to Sonarr. With it doing the Add only, they will never get the backlog of episodes for a show, without me going into Sonarr myself to tell it to search.  Preferably, it should start grabbing the backlog for them when they add it, so they can start watching soon on Plex.

**Comment by Hellowlol** [comment]
I believe its possible to do that already, I dont have access to sonarr now but i think it kicks off a https://github.com/Sonarr/Sonarr/wiki/Command#seriessearch. You can invoke that manually by selecting the show, then pick that option from the dropdown button.

If get requested many times i can add that call to the add show..

**Comment by blindpet** [comment]
I'd like to see this too. I believe Add+Search is somewhat new and having it be a selectable option makes sense

**Comment by Hellowlol** [comment]
Ok

**Comment by Hellowlol** [comment]
its now on by default
