### ISSUE TITLE
Viewing HTPC Manager in Portrait Mode

### ISSUE THREAD

**Issue by brando56894** [Hellowlol/HTPC-Manager#356]
I have some viewing issues when viewing HTPC-Manager in portrait mode on various devices, I'm not a web dev but I would imagine that the CSS is a little off for this orientation. When viewing the site in portrait mode on a 24" monitor the reverse proxy links in the top of the desired application page (ex. click on CouchPotato which directs you to domain.com/couchpotato, then there is the CouchPotato link that is clickable and directs you to the actual CouchPotato page) don't display at all even though there is physically enough space for it.

Also when displaying filesystem mount points on the main page the bars cut off the mount point and the freespace text which is on either side of the bar, would it be possible to shrink the size of the bar to completely display these values?

**Comment by Hellowlol** [comment]
Im not a web dev so I struggle with css.. Can you take a screenshot of what you talking about. (Don't have a 24 size screen to test with)

**Comment by brando56894** [comment]
![screenshot_2015-10-09-20-56-25-01](https://cloud.githubusercontent.com/assets/572116/10408335/aeaa01e6-6ec8-11e5-8b07-598450f18e4b.jpeg)

I can't show you the hidden reverse proxy links because I only have 24" portraits at work. The above screenshot is from my phone which displays the same behavior for the squashed text.

**Comment by brando56894** [comment]
Here's an example of the hidden links
![screenshot-htpc manager - mozilla firefox](https://cloud.githubusercontent.com/assets/572116/10439114/d1e95dd4-7105-11e5-8725-8658feb395b6.png)

**Comment by Hellowlol** [comment]
There is nothing i can do to prevent the menu from wrapping. :( Shorten the name of your programs is the "fix"

**Comment by brando56894** [comment]
Ah that's what I figured, I remember having this issue on StyxIts's version where the search bar and layout were getting thrown off by what I had in my menu list. Thanks!
