### ISSUE TITLE
VnStat: Disable ip6 graphs

### ISSUE THREAD

**Issue by brando56894** [Hellowlol/HTPC-Manager#357]
Is there a way to disable the IPv6 graphs in vnstat? I told it to only list for eth0, which works but I have empty graphs for ipv6 that are just taking up space since they don't display anything.

**Comment by Hellowlol** [comment]
I dont know, can you post a screenshot of it and paste the content of vnstst/dumpdb?

**Comment by brando56894** [comment]
version;3
active;1
interface;eth0
nick;eth0
created;1443973516
updated;1444437562
totalrx;202703
totaltx;185824
currx;2337814566
curtx;1513709603
totalrxk;360
totaltxk;508
btime;1444174360
d;0;1444363208;20048;18515;17;62;1
d;1;1444276809;40828;36993;916;874;1
d;2;1444190400;78253;71789;993;663;1
d;3;1444104002;51740;48304;959;934;1
d;4;1444053928;11362;10009;765;948;1
d;5;1444003213;386;186;849;576;1
d;6;1443973516;81;24;981;547;1
d;7;0;0;0;0;0;0
d;8;0;0;0;0;0;0
d;9;0;0;0;0;0;0
d;10;0;0;0;0;0;0
d;11;0;0;0;0;0;0
d;12;0;0;0;0;0;0
d;13;0;0;0;0;0;0
d;14;0;0;0;0;0;0
d;15;0;0;0;0;0;0
d;16;0;0;0;0;0;0
d;17;0;0;0;0;0;0
d;18;0;0;0;0;0;0
d;19;0;0;0;0;0;0
d;20;0;0;0;0;0;0
d;21;0;0;0;0;0;0
d;22;0;0;0;0;0;0
d;23;0;0;0;0;0;0
d;24;0;0;0;0;0;0
d;25;0;0;0;0;0;0
d;26;0;0;0;0;0;0
d;27;0;0;0;0;0;0
d;28;0;0;0;0;0;0
d;29;0;0;0;0;0;0
m;0;1443973516;202703;185824;360;508;1
m;1;0;0;0;0;0;0
m;2;0;0;0;0;0;0
m;3;0;0;0;0;0;0
m;4;0;0;0;0;0;0
m;5;0;0;0;0;0;0
m;6;0;0;0;0;0;0
m;7;0;0;0;0;0;0
m;8;0;0;0;0;0;0
m;9;0;0;0;0;0;0
m;10;0;0;0;0;0;0
m;11;0;0;0;0;0;0
t;0;1444190400;78253;71789;993;663;1
t;1;1444104002;51740;48304;959;934;1
t;2;1444276809;40828;36993;916;874;1
t;3;1444053928;11362;10009;765;948;1
t;4;1444003213;386;186;849;576;1
t;5;1443973516;81;24;981;547;1
t;6;0;0;0;0;0;0
t;7;0;0;0;0;0;0
t;8;0;0;0;0;0;0
t;9;0;0;0;0;0;0
h;0;1444366799;48016;27422
h;1;1444370390;4383;2215
h;2;1444373991;5856;2655
h;3;1444377593;292989;154215
h;4;1444381194;5256;2332
h;5;1444384795;48006;27424
h;6;1444388396;4246;2235
h;7;1444391997;5055;2237
h;8;1444395598;4235;2197
h;9;1444399190;1562065;1433499
h;10;1444402791;10184000;9599271
h;11;1444406392;51205;30900
h;12;1444409993;6572;4057
h;13;1444413594;7555;3657
h;14;1444417196;236948;96901
h;15;1444420797;51813;29243
h;16;1444424398;49904;28555
h;17;1444427999;5991;3140
h;18;1444431590;5785;3078
h;19;1444435192;5803;3076
h;20;1444437562;7943486;7501113
h;21;1444355996;13864743;13073710
h;22;1444359597;8511;6200
h;23;1444363198;48851;27429

![vnstat](https://cloud.githubusercontent.com/assets/572116/10408241/6201cde4-6ec6-11e5-821c-1a72dfdf7496.png)

**Comment by brando56894** [comment]
Also my upload stats are way off, maybe my download stats are off too. I'm definitely not uploading anything right now.

**Comment by brando56894** [comment]
Linux odroid 3.10.82-39 #1 SMP PREEMPT Fri Jul 10 17:47:37 BRT 2015 armv7l armv7l armv7l GNU/Linux

**Comment by Hellowlol** [comment]
Currently the interface is only used for the speed. The description field is wrong, I must have forgotten to add support for it. I'll see if I can't fix it like I intended. Regarding speed I you can try vnstat --tr in the console and see I that matches with what's reported by htpc manager.

I'm sorry I wasn't very very clear when I said vnstat/dumpdb, you need to http://htpc manager ip:port/vnstat/dumpdb

**Comment by brando56894** [comment]
htpc-manager's web interface and vnstat -tr don't seem to match, but they don't seem to be wildly off they're both less than 1 kb/sec, so maybe 0.5 kb/sec off?

{"vnstat": {"@version": "1.12", "@xmlversion": "1", "interface": [{"@id": "ip6tnl0", "id": "ip6tnl0", "nick": "ip6tnl0", "created": {"date": {"year": "2015", "month": "10", "day": "04"}}, "updated": {"date": {"year": "2015", "month": "10", "day": "10"}, "time": {"hour": "09", "minute": "54"}}, "traffic": {"total": {"rx": "0", "tx": "0"}, "days": {"day": [{"@id": "0", "date": {"year": "2015", "month": "10", "day": "10"}, "rx": "0", "tx": "0"}, {"@id": "1", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "0", "tx": "0"}, {"@id": "2", "date": {"year": "2015", "month": "10", "day": "08"}, "rx": "0", "tx": "0"}, {"@id": "3", "date": {"year": "2015", "month": "10", "day": "07"}, "rx": "0", "tx": "0"}, {"@id": "4", "date": {"year": "2015", "month": "10", "day": "06"}, "rx": "0", "tx": "0"}, {"@id": "5", "date": {"year": "2015", "month": "10", "day": "05"}, "rx": "0", "tx": "0"}, {"@id": "6", "date": {"year": "2015", "month": "10", "day": "04"}, "rx": "0", "tx": "0"}, {"@id": "7", "date": {"year": "2015", "month": "10", "day": "04"}, "rx": "0", "tx": "0"}]}, "months": {"month": {"@id": "0", "date": {"year": "2015", "month": "10"}, "rx": "0", "tx": "0"}}, "tops": null, "hours": {"hour": [{"@id": "0", "date": {"year": "2015", "month": "10", "day": "10"}, "rx": "0", "tx": "0"}, {"@id": "1", "date": {"year": "2015", "month": "10", "day": "10"}, "rx": "0", "tx": "0"}, {"@id": "2", "date": {"year": "2015", "month": "10", "day": "10"}, "rx": "0", "tx": "0"}, {"@id": "3", "date": {"year": "2015", "month": "10", "day": "10"}, "rx": "0", "tx": "0"}, {"@id": "4", "date": {"year": "2015", "month": "10", "day": "10"}, "rx": "0", "tx": "0"}, {"@id": "5", "date": {"year": "2015", "month": "10", "day": "10"}, "rx": "0", "tx": "0"}, {"@id": "6", "date": {"year": "2015", "month": "10", "day": "10"}, "rx": "0", "tx": "0"}, {"@id": "7", "date": {"year": "2015", "month": "10", "day": "10"}, "rx": "0", "tx": "0"}, {"@id": "8", "date": {"year": "2015", "month": "10", "day": "10"}, "rx": "0", "tx": "0"}, {"@id": "9", "date": {"year": "2015", "month": "10", "day": "10"}, "rx": "0", "tx": "0"}, {"@id": "10", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "0", "tx": "0"}, {"@id": "11", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "0", "tx": "0"}, {"@id": "12", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "0", "tx": "0"}, {"@id": "13", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "0", "tx": "0"}, {"@id": "14", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "0", "tx": "0"}, {"@id": "15", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "0", "tx": "0"}, {"@id": "16", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "0", "tx": "0"}, {"@id": "17", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "0", "tx": "0"}, {"@id": "18", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "0", "tx": "0"}, {"@id": "19", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "0", "tx": "0"}, {"@id": "20", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "0", "tx": "0"}, {"@id": "21", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "0", "tx": "0"}, {"@id": "22", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "0", "tx": "0"}, {"@id": "23", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "0", "tx": "0"}]}}}, {"@id": "eth0", "id": "eth0", "nick": "eth0", "created": {"date": {"year": "2015", "month": "10", "day": "04"}}, "updated": {"date": {"year": "2015", "month": "10", "day": "10"}, "time": {"hour": "09", "minute": "54"}}, "traffic": {"total": {"rx": "242311631", "tx": "217591200"}, "days": {"day": [{"@id": "0", "date": {"year": "2015", "month": "10", "day": "10"}, "rx": "2290292", "tx": "1987941"}, {"@id": "1", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "52982276", "tx": "44278397"}, {"@id": "2", "date": {"year": "2015", "month": "10", "day": "08"}, "rx": "41808788", "tx": "37881706"}, {"@id": "3", "date": {"year": "2015", "month": "10", "day": "07"}, "rx": "80132065", "tx": "73512599"}, {"@id": "4", "date": {"year": "2015", "month": "10", "day": "06"}, "rx": "52982719", "tx": "49464230"}, {"@id": "5", "date": {"year": "2015", "month": "10", "day": "05"}, "rx": "11635453", "tx": "10250164"}, {"@id": "6", "date": {"year": "2015", "month": "10", "day": "04"}, "rx": "396113", "tx": "191040"}, {"@id": "7", "date": {"year": "2015", "month": "10", "day": "04"}, "rx": "83925", "tx": "25123"}]}, "months": {"month": {"@id": "0", "date": {"year": "2015", "month": "10"}, "rx": "242311631", "tx": "217591200"}}, "tops": {"top": [{"@id": "0", "date": {"year": "2015", "month": "10", "day": "07"}, "time": {"hour": "00", "minute": "00"}, "rx": "80132065", "tx": "73512599"}, {"@id": "1", "date": {"year": "2015", "month": "10", "day": "06"}, "time": {"hour": "00", "minute": "00"}, "rx": "52982719", "tx": "49464230"}, {"@id": "2", "date": {"year": "2015", "month": "10", "day": "09"}, "time": {"hour": "00", "minute": "00"}, "rx": "52982276", "tx": "44278397"}, {"@id": "3", "date": {"year": "2015", "month": "10", "day": "08"}, "time": {"hour": "00", "minute": "00"}, "rx": "41808788", "tx": "37881706"}, {"@id": "4", "date": {"year": "2015", "month": "10", "day": "05"}, "time": {"hour": "10", "minute": "05"}, "rx": "11635453", "tx": "10250164"}, {"@id": "5", "date": {"year": "2015", "month": "10", "day": "04"}, "time": {"hour": "20", "minute": "00"}, "rx": "396113", "tx": "191040"}, {"@id": "6", "date": {"year": "2015", "month": "10", "day": "04"}, "time": {"hour": "11", "minute": "45"}, "rx": "83925", "tx": "25123"}]}, "hours": {"hour": [{"@id": "0", "date": {"year": "2015", "month": "10", "day": "10"}, "rx": "1368749", "tx": "1230909"}, {"@id": "1", "date": {"year": "2015", "month": "10", "day": "10"}, "rx": "605712", "tx": "577703"}, {"@id": "2", "date": {"year": "2015", "month": "10", "day": "10"}, "rx": "2624", "tx": "1865"}, {"@id": "3", "date": {"year": "2015", "month": "10", "day": "10"}, "rx": "249297", "tx": "129957"}, {"@id": "4", "date": {"year": "2015", "month": "10", "day": "10"}, "rx": "22132", "tx": "21725"}, {"@id": "5", "date": {"year": "2015", "month": "10", "day": "10"}, "rx": "25575", "tx": "15216"}, {"@id": "6", "date": {"year": "2015", "month": "10", "day": "10"}, "rx": "2635", "tx": "1896"}, {"@id": "7", "date": {"year": "2015", "month": "10", "day": "10"}, "rx": "3035", "tx": "3116"}, {"@id": "8", "date": {"year": "2015", "month": "10", "day": "10"}, "rx": "3847", "tx": "2920"}, {"@id": "9", "date": {"year": "2015", "month": "10", "day": "10"}, "rx": "6686", "tx": "2634"}, {"@id": "10", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "10184000", "tx": "9599271"}, {"@id": "11", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "51205", "tx": "30900"}, {"@id": "12", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "6572", "tx": "4057"}, {"@id": "13", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "7555", "tx": "3657"}, {"@id": "14", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "236948", "tx": "96901"}, {"@id": "15", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "51813", "tx": "29243"}, {"@id": "16", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "49904", "tx": "28555"}, {"@id": "17", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "5991", "tx": "3140"}, {"@id": "18", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "5785", "tx": "3078"}, {"@id": "19", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "5803", "tx": "3076"}, {"@id": "20", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "22527095", "tx": "19286843"}, {"@id": "21", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "17682002", "tx": "13380940"}, {"@id": "22", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "7814", "tx": "6543"}, {"@id": "23", "date": {"year": "2015", "month": "10", "day": "09"}, "rx": "179682", "tx": "145762"}]}}}]}}

**Comment by Hellowlol** [comment]
Ok, it correct then. With that small difference rounding and timing of the tests might be the issue. Thanks for the json data

**Comment by brando56894** [comment]
Awesome! No problem buddy, thanks for fixing it!

**Comment by Hellowlol** [comment]
I've got a backlog on what i want to do so it might take some time until you can specify that interface you want to use. In the mean time your can edit vnstat.conf to exlude those numbers.

**Comment by Hellowlol** [comment]
Can you try the latest update and see if that works. I havnt tested the vnstat interface parameter ;O
