### ISSUE TITLE
When clicking on Torrent Search I get a 404 error

### ISSUE THREAD

**Issue by 15bitgames** [Hellowlol/HTPC-Manager#361]
I re-installed htpc manager today and noticed that when I click on Torrent Search in the dash menu once I've activated it.  I get the following error.

404 - No Such Resource
No such child resource.

There was in nothing in the log files to even help find the issue.

**Comment by Hellowlol** [comment]
It's working fine here. Seems strange. Tried restarting hm? Is this behind a proxy?

**Comment by 15bitgames** [comment]
You've just explained why it isn't working. Interesting that its only the torrentsearch url that seems to be playing weird with my nginx reverse proxy.  Every other link works including newznab search.  Do you have any recommended nginx reverse proxy settings specifically for HTPC Manager?

**Comment by Hellowlol** [comment]
I only used something like this http://www.htpcguides.com/configure-htpc-manager-reverse-proxy-nginx-windows/

Can you post your .conf?

**Comment by Hellowlol** [comment]
Closing this as it's not related to htpc manager.
