### ISSUE TITLE
Newznab module: send category to sab

### ISSUE THREAD

**Issue by l-t-k** [Hellowlol/HTPC-Manager#365]
Right now the newznab module seems to only send the nzb to sab (the category is missing). Therefore, my Sabnzbd isn't able to recognise the category.

**Comment by Hellowlol** [comment]
Can you provide a log when when you try to add a nzb from the newznab module?

Can you also take a sceenshot of the nzb you tro send to sab (just hover over it)?

**Comment by l-t-k** [comment]
Log: http://pastebin.com/eEBG8sV4

The log shows category "audio" (last line)

Screenshot 1:
![1](https://cloud.githubusercontent.com/assets/3150962/10638397/0f24865e-780b-11e5-942e-6b450da9ce87.jpg)

Screenshot 2: (sab categories)
![2](https://cloud.githubusercontent.com/assets/3150962/10638436/34e214d8-780b-11e5-9b0b-f9e40057db74.jpg)

**Comment by l-t-k** [comment]
Hmm weird, tried with a movie. That one just received the correct category within sab:
`2015-10-21 15:51:54 :: modules.sabnzbd :: DEBUG :: Adding nzb from url
2015-10-21 15:51:54 :: modules.sabnzbd :: DEBUG :: https%3A//www.usenet-crawler.com/getnzb/9ed8153530efdd3c6aefca628689dbdb.nzb%26i%3D25567%26r%3D******************************** movies Minions.2015.720p.BluRay.x264-GECKOS`

![3](https://cloud.githubusercontent.com/assets/3150962/10638729/94392ad8-780c-11e5-8842-d63168f5fec7.jpg)

**Comment by l-t-k** [comment]
Category, PC. Also not working.
`2015-10-21 16:01:06 :: modules.sabnzbd :: DEBUG :: Adding nzb from url
2015-10-21 16:01:06 :: modules.sabnzbd :: DEBUG :: https%3A//www.usenet-crawler.com/getnzb/1f1765b150f96610e0b1dc5198fc559c.nzb%26i%3D25567%26r%3D******************************** pc Windows.7.X86.X64.12in1.ESD.en-US.Oct.2015l`

![4](https://cloud.githubusercontent.com/assets/3150962/10638828/3506af94-780d-11e5-8628-2ae2c53352f5.jpg)

**Comment by Hellowlol** [comment]
Ah, i get it. the module attempt to get the fetch the first in movie > hd or audio > mp3. I dont know if its possible to add a indexer tag while adding a nzb. worst case ill have to make that configureable

**Comment by l-t-k** [comment]
Hmm I was assuming the module just pushed some kind of group / indexer tag to sab and sab would translate it into the correct category. Now I get it as well:). According to the api docs, sab isn't able to receive a usenet group.

I think the default behaviour of HTPC-Manager is correct: send the main category of the newznab category as "category"  to sab. However, some indexers (spotweb, of course) don't use the newznab main categories. For example, newznab main category "audio" is called "sound" within spotweb. I want "audio" and "sound" to be send as "music" to sab.

Furthermore, I found music in newznab category "other > MP3". For this example it would be great to translate "other > mp3" to music as category for sab.

I can think of more examples, like console/games/pc which are all different across each indexer.

In conlusion, in to my view, the module category sending behaviour should be like this:
1. Translate "main > sub" to preferred sab cat if found.
2. Translate "main" to preferred sab cat if found and no translation for "main > sub" is found.
3. Default = send nzb with found cat from newznab to sab, if no translation in 1 or 2 is found.

**Comment by l-t-k** [comment]
![1](https://cloud.githubusercontent.com/assets/3150962/11411400/fe42c9e6-93cf-11e5-81e9-fec4b87216dc.jpg)

I've enabled one newznab website only in this example: spotweb. Spotweb uses it's own build-in main cats: image, sound, games and applications. As you can see in the screen, the correct categories are loaded as for the filters. However, when performing a search, the build-in spotweb category is used (on the right side of the screen, "sound" in this case). In the end this 'wrong' category is used to send to sab. If I look at the spotweb newznabapi.php here: https://github.com/spotweb/spotweb/blob/master/lib/page/SpotPage_newznabapi.php#L779 it seems like it should be possible to pull the correct category?

**Comment by l-t-k** [comment]
The translation category, spotweb --> newznab, starts here:
https://github.com/spotweb/spotweb/blob/master/lib/page/SpotPage_newznabapi.php#L825

**Comment by Hellowlol** [comment]
Im not gonna fix this just for spotweb. It too much work for something i will not use and i bet your the only one :P If you wish to fix this your can add the "wrong" category in the nzb client.

**Comment by l-t-k** [comment]
Ok. Thanks for the response. I'll add them to sab.
