### ISSUE TITLE
500 internal server error when viewing settings

### ISSUE THREAD

**Issue by chenks** [Hellowlol/HTPC-Manager#366]
just installed HTPC manager on my pi2.
it installed OK, but when i go to settings i get a "500 internal server error".
dashboard and logs load ok though via webui.

any thoughts?

**Comment by Hellowlol** [comment]
Is this with a fresh db? Or have you used the db with Styxit version before. Can you provide a log?

**Comment by chenks** [comment]
brand new clean install, never used HTPC Manager before.
i managed to get into settings once to try to configure sonarr, every since then it's been a 500 internal server error.

basically i've installed it and that's about it.
there is nothing in the logs in any of the sections apart from 

"Failed to fetch url=https://:/api/Calendar?end=2015-10-28 path=Calendar?end=2015-10-28 error Invalid URL u'https://:/api/Calendar?end=2015-10-28': No host supplied"

**Comment by Hellowlol** [comment]
Dunno what happend then. its probably a error with mako but I havnt added any checks for that.
Shutdown htpc manager delete the db in the userdata folder and start it again.

**Comment by chenks** [comment]
what's the full path to where the db file is ?

**Comment by chenks** [comment]
will do that and give it a try

**Comment by Hellowlol** [comment]
Does it work now?

**Comment by chenks** [comment]
so far, yes
