### ISSUE TITLE
Trouble adding utorrent

### ISSUE THREAD

**Issue by phairplay** [Hellowlol/HTPC-Manager#369]
Hi I'm having trouble adding uTorrent
I've opened up the web ui and I'm able to access it yet I can't seem to get it to connect with htpc 
What am I doing wrong?

**Comment by Hellowlol** [comment]
Hard to say, what utorrent version? You provide a debug log? (See the readme.md on how to enable it)

**Comment by phairplay** [comment]
It just says
2015-10-24 08:59:23 modules.utorrent    DEBUG   Trying to contact uTorrent via http://myip/gui/

I'm using version 3.4.5

**Comment by Hellowlol** [comment]
There should be a exception if a call failed. I don't know if the module is compatible with any version above 2.2.1 (anything version higher is shit anyway and usually not allowed on private trackers).

**Comment by phairplay** [comment]
Okay I'll grab a copy of 2.2.1 cheers for the quick response

**Comment by Hellowlol** [comment]
I'm gonna assume it works on 2.2.1, if not feel free to reopen

**Comment by phairplay** [comment]
Hi sorry 
I've just got around to retrying this and it still doesn't work with 2.2.1

**Comment by Hellowlol** [comment]
Ok. Read and do what is listed here https://github.com/Hellowlol/HTPC-Manager#so-you-found-a-bug-great

**Comment by phairplay** [comment]
http://pastebin.com/YTmVPMKK

**Comment by Hellowlol** [comment]
Was this the entire log? If not post it all. Didn't seems like it,as there was some calls missing. Are you using a username and password?

**Comment by phairplay** [comment]
http://pastebin.com/RxxzC3Zh

sorry I thought you only wanted it after I enabled the debug this is the entire log

yes I am

**Comment by Hellowlol** [comment]
Can you delete the log and go directly to the utorrent module, then refresh the page a couple of times. Then post the log.

**Comment by phairplay** [comment]
http://pastebin.com/psMz4HCZ

**Comment by Hellowlol** [comment]
Ok, I don't see any console errors, exceptions and it now has a token as it should. Still doesn't work? If so any console errors in your browser?

**Comment by phairplay** [comment]
I don't see any errors I can add a torrent but I can't track it

**Comment by Hellowlol** [comment]
Ok, ill check it out

**Comment by Hellowlol** [comment]
Can you update to the latest version and try again?

**Comment by phairplay** [comment]
Still no joy 
No difference

**Comment by Hellowlol** [comment]
Can I have the log again?

**Comment by Hellowlol** [comment]
And your utorrent build number

**Comment by phairplay** [comment]
Sorry for late reply 
I've moved back to v3 as I had issues with 2.2.1 also it seemed to be kicking out the same error

The build I'm on now it torrentpro 3.4.5 build 41162 32bit
