### ISSUE TITLE
Can't connect to plex 

### ISSUE THREAD

**Issue by Hellowlol** [Hellowlol/HTPC-Manager#372]
https://github.com/Hellowlol/HTPC-Manager/issues/329#issuecomment-151374681

@warplayer Let finish the discussion here so the other user don't get spammed.

**Comment by warplayer** [comment]
Apologies, I didn't see this thread before I responded in the other. Yes, I'm using Plex Home. Is that not supported?

**Comment by Hellowlol** [comment]
Plex home is supported, but you need to enter your plex username and password. Did you do that? You didnt see since it didnt exist. I made it so we can spam this one without the other dude getting notified.

**Comment by Hellowlol** [comment]
SSL is not supported. If you wish to use ssl, you can set the settings to prefered (in the plex server page, not htpc-manager settings.)

**Comment by warplayer** [comment]
I did enter my Plex username and password. Quite a few times, just to make sure I had it correct. I double checked my Plex Server settings, and the "Secure Connections" option is set to Preferred. 

Is there any chance it could be because I'm using a slightly long password for Plex? It has 21 characters, 2 are special characters. Just throwing an idea out there.

**Comment by Hellowlol** [comment]
any foreign chars like øæå? What happens if you click the test button?

**Comment by Hellowlol** [comment]
Can you manually try with http:htpcip:port/plex/myPlexSignin/yourusername/yourpassword and dump the log here?

**Comment by Hellowlol** [comment]
Dont bother anymore, it seems to be broken when i test now. Dunno why, but ill try to fix it later today.
Edit not broken, it helps to write the correct username and password :P

**Comment by warplayer** [comment]
I tried the URL you listed here. It just said 401 Unauthorized in my browser. I'm not sure which log you wanted me to dump.

**Comment by warplayer** [comment]
I just noticed that while http://192.168.0.13:32400 still says 401 Unauthorized, if I go to http://192.168.0.13:32400/web I get a login page. Is there something to that?

**Comment by Hellowlol** [comment]
htpc managers log file, i asked before but i didnt get a response any foreign chars like øæå?

**Comment by warplayer** [comment]
No foreign characters like that. I'm sorry, but how do I manually try the http:htpcip:port/plex/myPlexSignin/yourusername/yourpassword URL from within HTPC Manager? Do you want me to edit the plex.py module?

**Comment by Hellowlol** [comment]
replace htpcip with the the ip htpc manager is using, replace yourusername with your myplex username, and so on. Paste that url in your browser

**Comment by warplayer** [comment]
Sorry about that, I was totally overthinking what you were asking.

Here's the log: http://pastebin.com/rDFdwnh1

The behavior on my end was... started htpc manager with debug, pasted URL you gave me (replaced with my user info). Then I saw the HTPC Manager login screen, so I typed in my credentials, and it took me to the dashboard of HTPC Manager. I then pasted the URL again, and received the 401 unauthorized error, but it looked a little different this time. 

In the browser, the message said: "Failed to login to myPlex: HTTP Error 401: Unauthorized"
Instead of just "401 Unauthorized"

**Comment by Hellowlol** [comment]
Dunno why it fails then, can you try to setup https://github.com/styxit/HTPC-Manager and see if you can connect there?

**Comment by warplayer** [comment]
Wow, it fails there too.

On Tue, Oct 27, 2015 at 3:54 PM, Hellowlol notifications@github.com wrote:

> Dunno why it fails then, can you try to setup
> https://github.com/styxit/HTPC-Manager and see if you can connect there?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Hellowlol/HTPC-Manager/issues/372#issuecomment-151668601
> .

## 

OUTATIME,

Nick Austad

**Comment by warplayer** [comment]
I just tried a new password and that didn't fix it either.

Edit: Come to think of it, the logs never say anything about incorrect password so I doubt the connection even gets that far in the process where it tries the username/password.

On Tue, Oct 27, 2015 at 4:01 PM, Nick Austad warplayer0@gmail.com wrote:

> Wow, it fails there too.
> 
> On Tue, Oct 27, 2015 at 3:54 PM, Hellowlol notifications@github.com
> wrote:
> 
> > Dunno why it fails then, can you try to setup
> > https://github.com/styxit/HTPC-Manager and see if you can connect there?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/Hellowlol/HTPC-Manager/issues/372#issuecomment-151668601
> > .
> 
> ## 
> 
> OUTATIME,
> 
> Nick Austad

## 

OUTATIME,

Nick Austad

**Comment by Hellowlol** [comment]
I activated plexhome and set the password to asdfghjklpoiuytrewqzx###- and it still works. Can you check you db and see if you have a value in plex_authtoken (its in the setting table)? I usually use http://sqlitebrowser.org/ for simple stuff like that.

**Comment by Hellowlol** [comment]
It has to check because it only contacts plex.tv if the username and password supplied and there is a http call that says unauthorized.

**Comment by warplayer** [comment]
Sorry, I got busy for a bit and couldn't respond. I really appreciate the help.

I installed that program (really useful, thanks for that) and in the Settings table, I saw that it was storing the password I set for HTPC Manager as my plex_password. So I updated the value to the correct password, wrote the change to the db, and it worked!

Thank you very much for the help. No clue why it stored that password. I never entered it in the Plex area as I've never used that password for Plex.

**Comment by Hellowlol** [comment]
Ah, I get it. Same has happened with me. Chrome was entering the password I set it to remember in the wrong place. Happy you got it working!

**Comment by JigSawFr** [comment]
@Hellowlol it's strange, i've just setup plex config in HTPC manager and test failed but when saving i can see the popup "myPlex" with my token.

I've this error:
`Unable to contact Plex via http://www.xxxxx:911 error HTTP Error 401: Unauthorized`

Thanks you.

Plex home enabled with PIN
Plex security set to Prefered.

**Comment by Hellowlol** [comment]
@JigSawFr Can you add the log to gist? Where is the popup btw? In htpc manager?

**Comment by JigSawFr** [comment]
@Hellowlol sorry for disturbing you, i've missed to add unsecure URL to my Plex Discovery (Settings -> Network -> Custom server access URLs in Plex Settings) Now it's working.

An possibility to add secure access ?

Thanks you ! :)
