### ISSUE TITLE
Sickrage show poster/banner disappears after refresh

### ISSUE THREAD

**Issue by l-t-k** [Hellowlol/HTPC-Manager#376]
The SickRage module loads the poster correct. But after a refresh (F5, or switching between module in HTPC and return back to the same show) the poster isn't there anymore.

`2015-10-28 13:02:54 :: modules.sickrage :: ERROR :: http://localhost:8081/sickrage/api/********************************/?cmd=show.getbanner&indexerid=247897
2015-10-28 13:02:54 :: modules.sickrage :: ERROR :: ([], 304)`

Tried with Chrome, FireFox and IE

**Comment by Hellowlol** [comment]
should be fixed

**Comment by l-t-k** [comment]
Nope, unfortunately it isn't. Log file:
http://pastebin.com/6kjNQb1t

I refreshed my browser at 10:24:14.

**Comment by Hellowlol** [comment]
Sure its refreshed? I double checked and it works as expected here. If your using the source updater you need to manually restart sometimes.

**Comment by l-t-k** [comment]
I'm sure. Removed cookies, updated sickrage & HTPC-Manager. Removed cached images.

**Comment by Hellowlol** [comment]
Restarted htpc manager? Hmm can you inspect the image (with dev tools or something similar) that would be there and link the url to that image that fails?
