### ISSUE TITLE
More Detailed NZBGet Info

### ISSUE THREAD

**Issue by slamanna212** [Hellowlol/HTPC-Manager#379]
As it stands, if an item in NZBget is doing anything but downloading, it just says paused. More detailed info would be amazing

**Comment by Hellowlol** [comment]
Status (string)- Status of the group:
QUEUED - queued for download;
PAUSED - paused;
DOWNLOADING - item is being downloaded;
FETCHING - nzb-file is being fetched from URL (Kind=URL);
PP_QUEUED - queued for post-processing (completely downloaded);
LOADING_PARS - stage of par-check;
VERIFYING_SOURCES - stage of par-check;
REPAIRING - stage of par-check;
VERIFYING_REPAIRED - stage of par-check;
RENAMING - processed by par-renamer;
UNPACKING - being unpacked;
MOVING - moving files from intermediate directory into destination directory;
EXECUTING_SCRIPT - executing post-processing script;
PP_FINISHED - post-processing is finished, the item is about to be moved to history.

**Comment by Hellowlol** [comment]
I'm a little pressed for time this week, but it's a very easy request so I will get it done

**Comment by Hellowlol** [comment]
@slamanna212 Was this latest changed enough info for you?

**Comment by slamanna212** [comment]
Much better! Thanks a ton!
