### ISSUE TITLE
HTPC Manager stops working with hostname instead of IP

### ISSUE THREAD

**Issue by robertward** [Hellowlol/HTPC-Manager#38]
HTPC manager works fine until I update the IP/Host section to use a hostname instead of 0.0.0.0

After I update the field and attempt to restart HTPC manager, it crashes.

**Comment by Hellowlol** [comment]
Any log or traceback? 

This is from cherrypy doc:

The hostname or IP address on which to listen for connections.

Host values may be any IPv4 or IPv6 address, or any valid hostname. The string ‘localhost’ is a synonym for ‘127.0.0.1’ (or ‘::1’, if your hosts file prefers IPv6). The string ‘0.0.0.0’ is a special IPv4 entry meaning “any active interface” (INADDR_ANY), and ‘::’ is the similar IN6ADDR_ANY for IPv6. The empty string or None are not allowed.

**Comment by Hellowlol** [comment]
Seems like cherrypy has problem resolving your host name.
