### ISSUE TITLE
SqueezeBox Not working

### ISSUE THREAD

**Issue by DrJeff** [Hellowlol/HTPC-Manager#385]
In the squeezebox.py file line 37:

```
 port = htp.settings.get('squeezebox_ip')
```

Should read:

```
        port = htpc.settings.get('squeezebox_ip')
```

That made it work! It was missing the "c"

**Comment by Hellowlol** [comment]
Thanks for finding my typo! Do you use the squeezebox module? if you do would you mind taking a screenshot off it? I have never seen it... :P

**Comment by DrJeff** [comment]
Sure here you go.

There is one problem the scrub bar(progress bar) doesn't update unless you pause. It Looks like it isn't being polled?

![screenshot 2015-11-09 08 48 43](https://cloud.githubusercontent.com/assets/1709631/11040029/3685a440-86bf-11e5-8cfb-de65e47ad54f.png)
![screenshot 2015-11-09 08 48 32](https://cloud.githubusercontent.com/assets/1709631/11040027/367d1aa0-86bf-11e5-971d-0472eb22cdf4.png)
![screenshot 2015-11-09 08 40 38](https://cloud.githubusercontent.com/assets/1709631/11040028/3681689e-86bf-11e5-978e-dfd34a9f0b09.png)

**Comment by Hellowlol** [comment]
Ok, i remember that i remove jquery cookie. That might be the reason. Ill check it out (and give me a excuse to dust off the squeezebox)

**Comment by Hellowlol** [comment]
Can you try the lastest commit?

**Comment by DrJeff** [comment]
Awesome! It works great now.
