### ISSUE TITLE
Enabling auth, drops connection or becomes slow.

### ISSUE THREAD

**Issue by armss001** [Hellowlol/HTPC-Manager#387]
After adding a user/password to the interface, access to the page will intermittently drop or become extremely slow, I.E. taking over 5 minutes to load a page. If I restart the service it is fixed but happens again later. Removing the username/password and restarting solves this issue 100%.

**Comment by Hellowlol** [comment]
Are you talking about the main username/password in the settings page or the users settings tab?

**Comment by armss001** [comment]
This would be on the main username/password in the settings page. But I adding and removing other users did not make a difference

**Comment by Hellowlol** [comment]
I cant recreate this at all. When i try this now (from work to my home via a reverse proxy) it takes 0,700 to load the html. There are some js calls that take way longer but it does not lock the interface. What browser is this? can you take a print screen of the about page?

**Comment by armss001** [comment]
![image](https://cloud.githubusercontent.com/assets/8210710/11143593/938fd040-89f6-11e5-8ac9-da51c1431b2d.png)
This is Chrome, I haven't tried an alternate browser as everyone in the house also uses chrome.

**Comment by armss001** [comment]
I should be clear that it doesn't always lock out but the server restarts every 24 hours with it been windows and still locks out in the day if I am using it alot

**Comment by Hellowlol** [comment]
why is --daemon there on windows? Ok, i havnt noticed that. ill keep an eye regarding it.

**Comment by armss001** [comment]
Thats just me copy and pasting from a Linux tutorial and then adapting commands etc, just a bit I had forgotten to remove it. corrected now. I hope the auth can be fixed as at the moment I can't open mine up to outside access.

**Comment by Hellowlol** [comment]
Ok, remove that one. You can find a install guide for windows here: http://www.htpcguides.com/install-htpc-manager-windows/

**Comment by Hellowlol** [comment]
When you add a username and password the general settings page you need to restart htpc manager for it to work. When you say locked, do you mean locked out completely or that the interface is locket for xx sec?

**Comment by armss001** [comment]
Thats the exact process I took, :) I am a actually an IT tech, but my network infrastructure is my main area, so I am impresses I got it right :P and that guide says I should include --daemon?? As for the interface, what happens is sometimes while using the interface pages will stop loading and time-out. some times this lasts for a few minutes then fixes itself. Other times it doesn't fix until the service is restarted.

**Comment by Hellowlol** [comment]
Ah i see. It might be needed if your using a service to run htpc manager, i have never tried that my computers are always on. Electricity is cheap in Norway ^^^. 

Regarding the "lockup" the only thing im aware is issues if you entering a module that does not work. Authors of modules (read me..) are lazy and have not set a timeout for the http call to the different apis so say it tried to contact sonar api but sonar is not running it will timeout after 30 sec, but the interface request new data ever 10 sec, filling the que.

**Comment by armss001** [comment]
I am currently running the service without it and not having any issues. And so would the fact that the test button was reporting a fail for uTorrent have caused me an issue before? Even though the actual page had been working?

**Comment by armss001** [comment]
I am not 100% sure on what you mean, I apologise if thats a stupid and unrelated question. and my server is on all the time, it just has a reboot at 4am everyday. so its easier to run everything as a service in case the windows auto log in process fails.

**Comment by Hellowlol** [comment]
Nope the test button would be unrelated in this case. There are no stupid questions. I don't know to to explain it another way then I already did but it's easy to test. Enable a module say qbittorrent, write some random ip and port. Open the module in a different tab. Then try to use htpc manager as normal in a different tab.

**Comment by armss001** [comment]
I think I get what your saying but I don't get how that would be only an issue with the auth enabled?

**Comment by Hellowlol** [comment]
Lol, im just talking from my ass... Its unrelated to the auth issue. :P

**Comment by armss001** [comment]
So its an issue, but one that doesn't relate but gives similar symptoms?

I am going to re-enable the auth and hope to recreate the issue so I can seen screenshot and logs

**Comment by Hellowlol** [comment]
Yes. It would be awesome with some logs since i dont have that issue. Fixing problems that you cant see if hard :( Thanks for the help!

**Comment by Hellowlol** [comment]
@armss001 is this still a issue?

**Comment by armss001** [comment]
Nope, seems stable. Sorry I am working ins ship atm so difficult to reply. I do seem to have an issue with the connection between htpc and sick beard but don't have access to the logs. When adding a show it shows an error.

**Comment by Hellowlol** [comment]
How come? you know you can download the log from the logs interface? :P sickbeard hasnt gotten alot of some from me, the project seems to be dead. Its better to switch to sickrage or sonarr imo

**Comment by armss001** [comment]
I am only on an iPhone and at $20 for 500MB of data this ship is costing me a fortune already :P hence replying via email and not opening a new thread.

**Comment by Hellowlol** [comment]
Hehe. That sounds awefull :(
