### ISSUE TITLE
Disk Space overview on Dashboard

### ISSUE THREAD

**Issue by Morphy99** [Hellowlol/HTPC-Manager#39]
Would be great to have some form of disk space view for all drives on a system, viewable from dashboard.
Additionally a file manager as well but might be a bit more complicated.

**Comment by Hellowlol** [comment]
I agree :)

**Comment by Hellowlol** [comment]
@Morphy99 Added it now :)

**Comment by Morphy99** [comment]
Cool thanks! Can only see HDD in dashboard no info or bar? Works if I go into system info

**Comment by Hellowlol** [comment]
Clear browser cache, make sure that you have enabled it as well

**Comment by Morphy99** [comment]
Yep clearing cache did it! Thanks :)
