### ISSUE TITLE
Sickrage not showing TV Shows in TV Shows tab, rest works

### ISSUE THREAD

**Issue by Darkcloud1987** [Hellowlol/HTPC-Manager#390]
![ruyenrg](https://cloud.githubusercontent.com/assets/3299458/11447927/edf90d90-954e-11e5-84e0-477617c7f9fe.png)
I did set up Sickrage under the Sickrage settings, tried both 127.0.0.1 and the local ip of my Raspberry pi 2 where HTPC Manager is running and clicking on testíng in both cases shows as successful but TV shows are not listed under the TV shows tab. 
I tried it both in Chrome 46.0.2490.86 m (64-bit) and Firefox 42.0. 
![bgsytpm](https://cloud.githubusercontent.com/assets/3299458/11447949/3ea2cde4-954f-11e5-9786-145b9a8fc18c.png)

The error that may be connected to it shows up in line 5:
http://pastebin.com/1gpqKpyc

**Comment by Hellowlol** [comment]
Delete the log change logging to debug and open the module again. I need a debug log :)

**Comment by Darkcloud1987** [comment]
here is the debug log, I am not sure if the error actually shows up in the log but I went to the tv shows page twice before pasting the log
http://pastebin.com/5Ju0z5Q6

**Comment by Hellowlol** [comment]
I can't see any errors or exceptions regarding sickrage. Can you grab the log again? Maybe it was pasted before any exceptions happend. Double check your setting too

**Comment by Darkcloud1987** [comment]
tried it again and checked the settings. 
http://pastebin.com/xXmarekq

**Comment by Hellowlol** [comment]
Hmm, since there are no errors in the log, im wondering if this doesnt work and because of a js error. Can you see if there is some console errors? Can you go to http://htpcip:htpcport/sickrage/GetShowList and parse the response to a gist?

**Comment by Darkcloud1987** [comment]
It just shows a white page with "An error occured" but strangely it also lists the shows on the main page (I think Sickrage updated recently though).

**Comment by Hellowlol** [comment]
I didn't get that. Can you post a screenshot and dump the log? Should be error there now

**Comment by Darkcloud1987** [comment]
thats what the page shows now:
http://pastebin.com/uCv9vxsr
and that is the log now after accessing the page:
http://pastebin.com/qUnvLWRD
though for some reason it also shows the shows for me now. Maybe because of the last sickrage update.

**Comment by Hellowlol** [comment]
Ok. So it work as it should now?

**Comment by Darkcloud1987** [comment]
Yeah it works now for some reason.
