### ISSUE TITLE
plex js error

### ISSUE THREAD

**Issue by Hellowlol** [Hellowlol/HTPC-Manager#392]
Fix l324.

(typeof(options.f) != "undefined" && options.f.length)

same goes for albums etc.

**Comment by l-t-k** [comment]
Is this bug causing missing images?
![1](https://cloud.githubusercontent.com/assets/3150962/11568255/6c66e9e0-99eb-11e5-9dea-97f3f9e9b6e6.jpg)

**Comment by Hellowlol** [comment]
No, i dont think so but ill check later
