### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by nickisagod** [Hellowlol/HTPC-Manager#394]
Apologies if this is an obvious fix but i cannot install even though HTPC has previously installed fine. I get the error 

c:\HTPCManager>python htpc.py
Traceback (most recent call last):
  File "htpc.py", line 263, in <module>
    main()
  File "htpc.py", line 145, in main
    ssl._create_default_https_context = ssl._create_unverified_context
AttributeError: 'module' object has no attribute '_create_unverified_context'

Any advice would be great, Thanks in advance I am sure it is something stupid i am doing.

**Comment by Hellowlol** [comment]
Hi. I think you need to upgrade to Python 2.7.9. I'll fix this later

**Comment by nickisagod** [comment]
Hi, Thanks for the getting back to me, I am actually on 2.7.10 could that be the issue

**Comment by nickisagod** [comment]
Hi, I have upgraded to 2.7.11 and that sorted it feel free to close this down, Thanks

**Comment by Hellowlol** [comment]
Sweet!
