### ISSUE TITLE
Toggle Switches Not Displaying Correctly

### ISSUE THREAD

**Issue by slamanna212** [Hellowlol/HTPC-Manager#396]
On chrome , all toggle boxes display like this when turned on: https://i.imgur.com/ECz0OCo.png

When they are toggled off, they look normal

This issue does not occur in firefox

cleared cache/cookies

it happens on all computers i have with chrome on them

**Comment by Hellowlol** [comment]
Works fine here. Any console errors in your browser? what is the version/build number?

**Comment by slamanna212** [comment]
not sure how to check for errors in my browser, sorry

just updated it to the latest on the master2 branch about 5 minutes ago

**Comment by Hellowlol** [comment]
Press f12, click the console "tab". Oh, sorry i was refering to the chromeversion.

**Comment by slamanna212** [comment]
https://i.imgur.com/CFMqp66.png

**Comment by Hellowlol** [comment]
Was this a fresh install or have you using styxit branch before? I cant recreate the issue. Ill see if i cant download the same build has your using.

**Comment by Hellowlol** [comment]
Closed because of inactivity and that I can't reproduce the error
