### ISSUE TITLE
load HTPC-Manager in iframe

### ISSUE THREAD

**Issue by phairplay** [Hellowlol/HTPC-Manager#401]
Hi,
Tenzinn3 from reddit took a codyhouse html and customized it to use with his usenet sites. allowing you to view the main sites on one page.

https://github.com/Tenzinn3/Managethis

i've added this to my system to allow me to go directly to my main domain. Yet when I add mydomain.com/htpc it doesn't load. I found an option within google chrome which showed the following error

Refused to display 'https://mydomain.com/htpc/' in a frame because it set 'X-Frame-Options' to 'DENY'.

I mainly use HTPC-Manager for the stat (system) page to monitor my pc and exacute custom scripts.

I would really like to add this to Managethis, could you please help with this? :)

**Comment by Hellowlol** [comment]
Oh, i thought it was a issue rendering iframes inside htpc manager not the other way around. It was never my intension that htpc manager should be allowed to be iframed, Anyway you can fork the project and comment out https://github.com/Hellowlol/HTPC-Manager/blob/master2/htpc/server.py#L41

**Comment by phairplay** [comment]
Hi,
I totally understand and I know this is a cheeky request, but I'd really appreciate if you could help me achieve this.
when I removed the comment I get the following error when trying to load HTPC manager back up

500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.
Powered by CherryPy 3.8.0

**Comment by Hellowlol** [comment]
Oops. I think you need to comment out https://github.com/Hellowlol/HTPC-Manager/blob/master2/htpc/server.py#L140 aswell.

**Comment by Hellowlol** [comment]
I can make that option configure able also

**Comment by phairplay** [comment]
Hi 
Removing
headers['X-Frame-Options'] = 'DENY'
Did the trick 
(:

**Comment by Hellowlol** [comment]
With the latest update you can disable secure headers (to allow htpc manager to be iframed)
