### ISSUE TITLE
Request: Upload subs or files

### ISSUE THREAD

**Issue by nockstarr** [Hellowlol/HTPC-Manager#408]
After going away for x-mas I missed a simple module for uploading subs.

Would be nice to upload subs or files to a directory available for the HTPC Manager like a mounted share or a local directory (have to specify a directory in the module settings like "/media/plex").
Lets say a directory where all your movies and tv-shows exist. You can browse and search in that specific dir+subdir and then upload subs. A super easy way to add subs on the run or at home.

Restriction could also be added to auth leves like, admin can create sub folders and upload files.
Other users can only upload files with subtile extensions.

If this is even possible would be super nice! :)

**Comment by Hellowlol** [comment]
This out of scope of the project. You can use something like ftp own cloud etc
