### ISSUE TITLE
Computer Stats on multiple systems

### ISSUE THREAD

**Issue by Hat3Mondays** [Hellowlol/HTPC-Manager#41]
Would be great to see the Computer Stats on a separate system as well as the one HTPC-Manager runs on.

For example I run HTPC-Manager on a VPS alongside Sonarr and Couchpotato but host Plex on a seperate server.

Would be nice to be able to see the plex servers stats on the same page

**Comment by Hellowlol** [comment]
That isnt possible atm. Psutil is used for grabbing info about your system and it can only check what its installed on. 

For this to be doable it need to be something you can grap from a webapi. I dont know if webmin or similar have something you can use. 

This isnt something i will add as everything is install on a windows 7 except from nginx reverse proxy. I will however accept a pr regarding if anybody is willing to do the work.

**Comment by madclicker** [comment]
All you have to do is mount an NFS share. Of course this means you have to use real operating systems.

**Comment by Hellowlol** [comment]
@Hat3Mondays you can use the ohm tab for that now btw.

**Comment by Hellowlol** [comment]
Closing this as its out of scope. As i mentioned you can use the ohm tab or a project like psdash.
