### ISSUE TITLE
Incorrect redirect

### ISSUE THREAD

**Issue by ezar** [Hellowlol/HTPC-Manager#412]
Hi,
I configure nginx:

```
location ~ ^/htpc($|./*) {
        proxy_pass http://127.0.0.1:8085;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
}
```

But I use diferent port for SSL: 7777

I access to https://xxx.xxx.xxx:7777/htpc but system redirect to https://xxx.xxx.xxx/htpc and doesnt works!
Same configuration for sickrage works perfectly.

Regards,

**Comment by Hellowlol** [comment]
Have you checked anything regarding proxy in htpc manager settings? If it is turn it off. See the reverse proxy guide for htpc manager on htpcguides.com

**Comment by ezar** [comment]
I configure it using this guide: http://www.htpcguides.com/configure-htpc-manager-reverse-proxy-nginx-windows/

Problem with port.
I access to https://xxx.xxx.xxx:7777/htpc but system redirect to https://xxx.xxx.xxx/htpc and doesnt works!

Cesar.

**Comment by ezar** [comment]
location /htpc {
                proxy_pass http://127.0.0.1:8085;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

**Comment by Hellowlol** [comment]
Where does this redirect happen? Right after login? Have you activated anything related to reverse proxy inside htpc manager?

**Comment by ezar** [comment]
Nothing activate inside htpc manager.

Fails before login.
1. Access to https://xxxxxxxxxxx:7777/headphones
2. Next url appears: http://xxxxxxxxxx/headphones/

Removed port and https 

I configure same for sickrage and couchpotato, and works perfectly.

Thanks!

**Comment by ezar** [comment]
If I use 80 for http or 443 for https works fine. 
When I use a different port fails.
Regards,

**Comment by Hellowlol** [comment]
Why anybody would use a non default port i beyond me :D, ill change my reverse proxy and see if i cant find a way to handle this. (i think you can fix it by editing the reverse proxy settings in the general settings tab)

**Comment by ezar** [comment]
Thanks you!

**Comment by Hellowlol** [comment]
Try setting $http_host instead of $host in the reverse proxy settings

**Comment by ezar** [comment]
Doesnt works.

**Comment by Hellowlol** [comment]
It will always fail with that. you would need to use https://xxxx.port/htpc/headphones

**Comment by Hellowlol** [comment]
remove the proxy_set_header Host $host; and you should good to go.

**Comment by ezar** [comment]
Its true! works!
Thanks
