### ISSUE TITLE
Allow 'rg-htpc brand' to be modifiable (local branding)

### ISSUE THREAD

**Issue by brianbuquoi** [Hellowlol/HTPC-Manager#413]
I would like to be able to easily change out this image with either the word Home or with another image.

I can't find a way to do this currently (at least not easily).

Could this be modifiable via settings or a config?

**Comment by Hellowlol** [comment]
It could, but I can't a setting for everything. Have you tried replacing that image with the one you want? I that doesn't work you will have to edit base.html. Just remember that your changes will break any updates so you would have to do it manually after each update.

**Comment by Hellowlol** [comment]
Edit https://github.com/Hellowlol/HTPC-Manager/blob/master2/interfaces/default/html/base.html#L69
