### ISSUE TITLE
Issue with specifying an interface in vnstat module

### ISSUE THREAD

**Issue by ghost** [Hellowlol/HTPC-Manager#415]
Hello, I am running HTPC manager inside of a docker container, linuxserver.io's container build. I cannot specify an interface via the vnstat settings. I am given the error:

Failed to run vnstat -tr -i eno2 from shell output Error: Unable to get interface "bond0" statistics.

I have confirmed that the container has access to the directory and have also tried giving the container root permissions. The command when tested in terminal does produce results without running as root or sudo. This could be an error with the container itself but I have hit a dead end. Thank you for a great application!

**Comment by Hellowlol** [comment]
Can post a screenshot of your vnstat settings. Seems strange that it says the command was something else then what it found.

**Comment by ghost** [comment]
Here are screen shots of the configuration as well as the error, I have tried this with specifying the database directory as well and still no luck.

<img width="1027" alt="screen shot 2016-01-13 at 6 58 33 pm" src="https://cloud.githubusercontent.com/assets/5766531/12310624/b41bb8b8-ba27-11e5-8bf7-f78c31f8796a.png">
<img width="520" alt="screen shot 2016-01-13 at 6 58 07 pm" src="https://cloud.githubusercontent.com/assets/5766531/12310625/b431b74e-ba27-11e5-9ec2-b4a4816295c5.png">

**Comment by Hellowlol** [comment]
I dont think its a issue directly with htpc manager. If you dont write any interface you should see them all. There is no bond0, atlest not on mine. :( i also checked via the dockers bash.

the vnstat modules isnt really that interesting, atleast not for the docker and since its the dockers data usage it reports. A better option would be to install vnstat on your router and use the ssh option so you can get some real data about your usage

**Comment by ghost** [comment]
Oh, now that makes much more sense! I was specifying an interface on the host machine and wondering where the default eth0 interface came from. I will look into using the ssh command to grab a more useful interface.

**Comment by Hellowlol** [comment]
Great, im closing this as its not a htpc manager issue but a consequence of installing it on a isolated environment like a docker.
