### ISSUE TITLE
Sonarr calendar on main page is blank. Calendar in sonarr tab is fine.

### ISSUE THREAD

**Issue by famewolf** [Hellowlol/HTPC-Manager#417]
Log:  http://pastebin.com/MnkAuW5U    I see nothing in the log that refers to sonarr in any way.  It would also help if you add in your instructions where the log file is since the average user (or at least me) would be looking in /var/log.

Screenshots: 
![hm1](https://cloud.githubusercontent.com/assets/4558832/12401122/6a919cd4-bdf2-11e5-92b7-92b9ae95647c.png)
![hm2](https://cloud.githubusercontent.com/assets/4558832/12401124/6a9636ae-bdf2-11e5-96e7-abb311cb154e.png)
![hm3](https://cloud.githubusercontent.com/assets/4558832/12401123/6a95d452-bdf2-11e5-958e-9874a9854ef5.png)
![hm5](https://cloud.githubusercontent.com/assets/4558832/12401125/6a9be388-bdf2-11e5-9299-179e5edb27e1.png)

Description of bug:   

The sonarr "tab" displays shows as it should while the htpcmanager main page shows a blank calendar for day, week and month (week and month screenshots included).

Browsers:  Firefox and qupzilla under Linux Mint 17.3 (ubuntu 14.04).  Another user in the gitchat indicated they had the same issue using chrome.

htpcmanager and sonarr are each running in their own jail on a freenas server.  Sickrage (192.168.3.100) was shut down during this time so that's the reason for those errors.

**Comment by Hellowlol** [comment]
Can you update and try again? The is in htpc manager data folder. You can download the log for the log interface

**Comment by famewolf** [comment]
Updating solved the issue however I had to check for update 3 times before it finally told me there was an update and it had not prompted me that an update was available.  Now on current commit:  6a78741eb94aa9cf74fb404a2da68336f119a73a
