### ISSUE TITLE
Sonarr calendar no longer working ( dash calendar or full calendar )

### ISSUE THREAD

**Issue by Flippage** [Hellowlol/HTPC-Manager#420]
I just did an update to commit: 782c29eda282af2a0165c33c7128a0c1e8142bc8 , and the calendar for sonarr is now broken completely (nothing shows up).

Using the default skin, and calendar was working fine on both pages immediately before doing the update.

Screenshots of the issue:
http://imgur.com/a/hPwkD

**Comment by Hellowlol** [comment]
Sorry about that. Its fixed in the latest commit.
