### ISSUE TITLE
remove wiki page about freenas

### ISSUE THREAD

**Issue by josh4trunks** [Hellowlol/HTPC-Manager#421]
this page should be removed
https://github.com/Hellowlol/HTPC-Manager/wiki/Convert-HTPC-Manager-FreeNAS-Plugin-to-Hellowlol's-Fork

the freenas plugin already uses this fork
https://github.com/josh4trunks/freenas-plugins/commit/72e6641be31b35727c8db75928b300830e54796e

**Comment by Hellowlol** [comment]
Thanks :)
