### ISSUE TITLE
Wiki page deleted?

### ISSUE THREAD

**Issue by famewolf** [Hellowlol/HTPC-Manager#422]
Can someone provide an archived copy of https://github.com/Hellowlol/HTPC-Manager/wiki/Convert-HTPC-Manager-FreeNAS-Plugin-to-Hellowlol's-Fork?    It apparently has been deleted.  I need the git clone info for use with another plugin and didn't save the page as I was unaware it was going to be deleted.

**Comment by Hellowlol** [comment]
I deleted it since the user can choose my fork in the plugin. I dont know a way to get it back and i dont remember what it said, i wasnt the author. Ask for help on the freenas forum?

**Comment by famewolf** [comment]
Yes but the instructions were a perfect example of how to go into a jail and do a git clone of any project.  I was trying to use it to set up Jackett.   In the meantime I managed to do it without the tutorial  Thanks for following up.
