### ISSUE TITLE
Mylar - Not working

### ISSUE THREAD

**Issue by PREngineer** [Hellowlol/HTPC-Manager#427]
Hi!

I just encountered a bug where the current version will not connect to Mylar and it produces a 500 error.

I've tried putting "/home" or "/" or just nothing in the "base path" box but it doesn't help.

A weird thing is that it sometimes "passes" the connectivity test.  But almost always fails.

I tried the [getVersion] & [getWanted] URLs / Requests and I got successful replies from Mylar, so, Mylar is not the problem.

![1 - about](https://cloud.githubusercontent.com/assets/6334069/12864695/3324d49a-cc62-11e5-8fb1-6140be3ba9b5.png)

![2 - settings](https://cloud.githubusercontent.com/assets/6334069/12864696/377df396-cc62-11e5-95d4-ce974aed04a3.png)

![3 - failure](https://cloud.githubusercontent.com/assets/6334069/12864698/3a72cde2-cc62-11e5-95c4-7f58f8efdb0e.png)

![4 - log](https://cloud.githubusercontent.com/assets/6334069/12864699/3d52b9fa-cc62-11e5-85fb-d290e093a856.png)

**Comment by Hellowlol** [comment]
I'll have to install Mylar and test it myself. Thanks for the report.

**Comment by Hellowlol** [comment]
I cant recreate your issue. Works fine here. Can you delete your log, enable debug logging. Restart htpc manager. Open the mylar tab then paste the log to a gist?

**Comment by PREngineer** [comment]
Give me a minute and I will do it.  In fact, I'll also restart the PC just to clear everything up too.

Did you test in Windows?  I'm using Windows now.  Uploading the log to Pastebin.  Will post it in a minute.

**Comment by Hellowlol** [comment]
Yeah,i tested on windows

**Comment by PREngineer** [comment]
http://pastebin.com/V6pmznrr

Here's the log... if I'm not mistaken.  I copied the contents of C:\Program Files\HTPCManager\userdata\htpcmanager

**Comment by Hellowlol** [comment]
Ah, crap, i forgot the test the right version.Thanks for the report ill fix it

**Comment by PREngineer** [comment]
No problem!  If I programmed in Python I would have helped... guess I'm going to start learning it.  Not many apps like this are created using PHP, which is the one I use for Web Apps.

Thank you very much!

**Comment by Hellowlol** [comment]
update to the latest version :)

**Comment by PREngineer** [comment]
Awesome!  Thanks.

**Comment by Hellowlol** [comment]
Your welcome!
