### ISSUE TITLE
Can't login after enabling user?

### ISSUE THREAD

**Issue by alexbartisro** [Hellowlol/HTPC-Manager#428]
I've installed it on my server, and enabled login, but now I can't under any circumstance. I know I have the right user/pass as it was saved in my password manager. 

How can I reset it, or where is it saved locally for me to see it?

**Comment by Hellowlol** [comment]
I bet the password manager messed up. It has happen to me to. Shutdown htpc manager and start it with Python htpc.py --resetauth. Change the password/username and shut it down again then start it without --resetauth

**Comment by alexbartisro** [comment]
Worked, thank you!

---

## _"Nu lasa nimic intre tine si visele tale."_

http://www.blog.alexbartis.com

*Alex Bartis, *
iOS Developer @ Fortech

www.alexbartis.com | facebook.com/bartis.alex | twitter.com/alexbartis

**Comment by Hellowlol** [comment]
Your welcome. I just noticed that I didn't answer all your questions. The username and password is stored inside the settings table. You can use a program like SQLite browser to open the db.

**Comment by alexbartisro** [comment]
Yeah, it's no problem. I just needed any way to reset the password, one or the other. Thank you, again! HTPCManager was just what I needed to get a status over my server.
