### ISSUE TITLE
Sonarr & CouchPotato Data Not Displaying on Dashboard

### ISSUE THREAD

**Issue by twitchfidelis** [Hellowlol/HTPC-Manager#433]
I have the correct Sonarr & CouchPotato settings in HTPC Manger even the Test buttons give me a success notification,  but no information is displayed for the Calendar, Wanted Movies or Next Aired. Automatic updates are enabled for Sonarr, CouchPotato, and HTPC Manager and I ran a forced update check just to be sure.

**Comment by Hellowlol** [comment]
Hi. Does it work inside the module? Please provide a debug log :)

**Comment by twitchfidelis** [comment]
No it does not.
[htpcmanager.txt](https://github.com/Hellowlol/HTPC-Manager/files/128814/htpcmanager.txt)

**Comment by twitchfidelis** [comment]
Any idea what the issue is?

**Comment by Hellowlol** [comment]
Im sorry, i forgot about the entire thing :/ Not atm. Seems like it dont return the response the code expects. 

Can you go to go to http://htpcip:htpcport/sonarr/oldCalendar and parse the response?

**Comment by twitchfidelis** [comment]
it shows a 404 not found error.

**Comment by Hellowlol** [comment]
Im sorry, i had some typos in the url. Set loglevel to debug and delete htpc managers log file (it can be done from the log page). Can you switch to the sonar_debug branch?

Open the module page and the url above and parse log to a gist

**Comment by twitchfidelis** [comment]
I changed the HTPC Manager and Sonarr log level to debug and cleared the log. I am hesitant to switch the Sonarr branch since the only reference I can find to a debug branch is here in this thread and I don't want to break Sonarr. I went to the URL you provided and got the same 404 error.

Sonarr Debug Log Gist
https://gist.github.com/twitchfidelis/3b0f2e7382341e6caea4

HTPC Debug Log Gist
https://gist.github.com/twitchfidelis/56cc09600ffaaf92cc87

**Comment by Hellowlol** [comment]
The sonar_debug branch is a branch of htpc manager not sonarr. Full logs please. And I I'm I to assume that you have replaced your the htpc ip etc with your actually ip?

**Comment by Hellowlol** [comment]
Post a screen shot of sonar settings (in htpc manager)

**Comment by twitchfidelis** [comment]
Yes I am replacing http://htpcip:htpcport with my ip and port. I didn't put the /sonar in before but I did this time and this time I got a new page with the Sonarr loading dots going back and forth. I tried changing the update branch to sonar_debug, but after I save it it goes back to master2.

Sonarr Debug Log
https://gist.github.com/twitchfidelis/317593f26babdec13ed5

HTPC Manager Debug Log
https://gist.github.com/twitchfidelis/1cbf6c6df1d44bc0d5ca

<img width="306" alt="2016-02-17 15_33_01-htpc manager" src="https://cloud.githubusercontent.com/assets/3360184/13128605/d3057b7c-d58b-11e5-9f04-fe5279dc3ae6.png">

**Comment by Hellowlol** [comment]
You need to use got to change branch or choose the sonarr_debug click save then force update.

**Comment by Hellowlol** [comment]
Closing this since i havnt gotten any feedback and it works here. If the problem persist feel to reopen after relevant info is added.
