### ISSUE TITLE
"S.M.A.R.T not correctly configured." - smartmontools problem

### ISSUE THREAD

**Issue by ujellyx** [Hellowlol/HTPC-Manager#439]
I followed this guide to setup HTPC Manager but can't seem to get S.M.A.R.T. status to work:
http://www.htpcguides.com/install-htpc-manager-windows/

I installed smartmontools (64bit) and checked to PATH option during installation. I also used that powershell-command, just to make sure. But it still won't work - i always get the following error:

> Required package 'smartmontools' is not installed, or 'smartctl' component is not on the system path. Please install and try again.

I'm on WIndows 10 64bit, latest HTPC Manager, Python 2.7 and latest smartmontools (smartmontools-6.5-0-20160311-r4231.win32-setup).

What am i doing wrong?

**Comment by Hellowlol** [comment]
Im not sure :P what version is installed? you said you installed the 64bit version but later your referring to a 32 bit version.

Are you using nssm or starting htpc manager manually? If you execute the smartctl in cmd what is the response? Remember that you have to start Python from a shell with elevated credentials.

**Comment by ujellyx** [comment]
The installer is named like a 32bit version, yes, but inside the installer one can choose to use/install the 64bit-version of it.
Using smartctl inside cmd works (shows the version, etc.). So i guess the PATH is installed correctly.

I'm using nssm to start HTPCManager as a daemon on startup. How do i do what you're mentioning in your last sentence? Starting Python from a shell with elevated credentials? Right now all my tools start up using nssm.

**Comment by Hellowlol** [comment]
For the last sentance see http://forum.kodi.tv/showthread.php?tid=221715&pid=2113602#pid2113602

Try running htpc manager from source without nssm and see if it works then.

**Comment by Hellowlol** [comment]
Assumed fixed since there was no response.
