### ISSUE TITLE
kickass.to torrent search

### ISSUE THREAD

**Issue by Morphy99** [Hellowlol/HTPC-Manager#44]
Any way to add public torrent sites to search? I dont have access to the two provided.

**Comment by Hellowlol** [comment]
Yeah, but i want to use some site with api. I dont like scraping web pages. I probably gonna add kat, ptp and maybe yifi

**Comment by Morphy99** [comment]
That will do for me :)

**Comment by Hellowlol** [comment]
@Morphy99 I just added kickasstorrents and yts
