### ISSUE TITLE
CouchPotato images not loading?

### ISSUE THREAD

**Issue by ujellyx** [Hellowlol/HTPC-Manager#440]
When i choose the CouchPotato menu none of the images (thumbnails, etc.) are loading properly. When i try to enter the image-url manually (e.g. http://localhost:8085/couchpotato/GetImage?w=154&h=231&url=https://image.tmdb.org/t/p/w154/fYzpM9GmpBlIC893fNjoWCwE24H.jpg) i always get the following error:

> 500 Internal Server Error - The server encountered an unexpected condition which prevented it from fulfilling the request.

Though the image-url itself (from tmdb) is okay.

Here a picture of how it looks:
![unbenannt](https://cloud.githubusercontent.com/assets/17804807/13726052/43fe6720-e8b6-11e5-9678-932208053425.PNG)

Log says:

> 2016-03-13 01:08:45   cherrypy.error.28113936 ERROR   [13/Mar/2016:01:08:45] HTTP

**Comment by Hellowlol** [comment]
Is pil/pillow installed? Can i have the full log please

**Comment by ujellyx** [comment]
@Hellowlol Yeah, i downloaded the "PIL-1.1.7.win-amd64-py2.7.exe" installer from the web and installed it. It is correctly placed in my python installation directory after that. Do i need to do anything else?

[htpcmanager.txt](https://github.com/Hellowlol/HTPC-Manager/files/171018/htpcmanager.txt)

**Comment by Hellowlol** [comment]
I can't seems to open the log, I get a 404 page, it might be because I'm on my phone. 

Are windows version are you using and Python version so I can try to recreate the issue?

**Comment by ujellyx** [comment]
Windows 10 Pro 64 bit and Python 2.7.
Gonna reupload the log when i'm back home.

[htpcmanager.txt](https://github.com/Hellowlol/HTPC-Manager/files/171093/htpcmanager.txt)
If that doesn't work:
http://pastebin.com/2xY5sZcV

And here are the debug-level-logs, if needed:
[htpcmanager (1).txt](https://github.com/Hellowlol/HTPC-Manager/files/171109/htpcmanager.1.txt)

**Comment by Hellowlol** [comment]
Your pil install is broken, uninstall it and install pillow instead. Also the --daemon is useless for windows. See the errors message in the log.

**Comment by ujellyx** [comment]
Great, Pillow instead of PIP did the trick. Thanks!
So i could've left out the --daemon part?

**Comment by Hellowlol** [comment]
Yeah
