### ISSUE TITLE
Cannot connect to headphones

### ISSUE THREAD

**Issue by soehlert** [Hellowlol/HTPC-Manager#444]
I just installed this tonight, and cannot get the test to work in headphones. I see this error in the log. I'm guessing it's due to a missing API key, but I have no clue where to get that from. 

modules.headphones  ERROR   Error calling api http://127.0.0.1:8181/api?apikey=&cmd=getVersion: No JSON object could be decoded

**Comment by Hellowlol** [comment]
You get the apikey from headphones :) check headphones settings page.

**Comment by soehlert** [comment]
Sorry no more late night messing around..works perfectly thanks!
