### ISSUE TITLE
Sickrage module seems not to work with shows from TVRage

### ISSUE THREAD

**Issue by kooimens** [Hellowlol/HTPC-Manager#45]
It can find and add shows from TVRage, but when opening the show from the tv shows tab, it returns this: 
![5](https://cloud.githubusercontent.com/assets/3150962/6384284/ed88dc18-bd5a-11e4-9af8-8567f9dddf28.jpg)

**Comment by Hellowlol** [comment]
Hi, Thanks for reporting this. What show was this and I want htpc manager log :)

**Comment by Hellowlol** [comment]
I think the error is in https://github.com/Hellowlol/HTPC-Manager/blob/master2/modules/sickrage.py#L123 should be a easy fix :)

**Comment by kooimens** [comment]
I tried with a lot of shows, but for example you can try House from the TVRage db.

**Comment by Hellowlol** [comment]
@kooimens Can you try this branch https://github.com/Hellowlol/HTPC-Manager/tree/sr2 ? Im at work so i havnt tested it, but in theory it should work :P

**Comment by Hellowlol** [comment]
Can you update and try again?

**Comment by kooimens** [comment]
Fixed! Thanks again
