### ISSUE TITLE
"Reverse proxy link" input field not available when configuring Transmission client

### ISSUE THREAD

**Issue by WzL** [Hellowlol/HTPC-Manager#452]
When configuring Transmission client, the input field "**Reverse proxy link**" is missing. This causes me not to be able to click on the **Transmission** "Menu Name" on top of the page which would generate an new web browser tab presenting the original transmission web portal. The only option available under Transmission client options is "**Reverse Proxy**" which does not seem to work as I expect.

This option is available for example on the NZBGet configuration page. Setting the option "**Reverse proxy link**" under NZBGet configuration page gives me the option to navigate using **NZBGet**  "Menu Name" on top of the page to the NZBGet web portal (presented as a new web browser tab).

This is the case using the latest HTPCManager GIT master2 branch.

**Comment by Hellowlol** [comment]
I have no idea what the reverse proxy listed there should do :S I thought I added that to all the modules but this one must have slipped.

**Comment by WzL** [comment]
Ok, would be handy if one could add the "**Reverse proxy link**" to the Transmission configuration page, thanks!

**Comment by Hellowlol** [comment]
I will

**Comment by Hellowlol** [comment]
Fixed some time ago.

**Comment by WzL** [comment]
The change does not function as expected. When i specify the Reverse Proxy field within the transmission configuration section of HTPC-Manager for example "https://bilaap.io/transmission" without quotes obviously, the page which opens tries to connect to the following URL: "http://https//bilaap.io/transmission".

Also, the location (this option is the last option printed of every configurable application within HTPC-Manager) of the option and naming convention of this option is not consistent. Within the NZBGet section and everywhere else in the HTPC-Manager configurable applications the input field is called "Reverse proxy link" instead of "Reverse Proxy". Furthermore the input field lacks a question mark icon which is clickable, and when clicked on, it generates an explanation box of what is option actually does.

**Comment by Hellowlol** [comment]
@WzL update htpc manager and the link should work now. Ill update the text and add the question mark etc later.

**Comment by WzL** [comment]
Ok thanks Hellowlol, I updated accordingly and tested. Results are as expected, the functionality works! Thank you for the quick response!
