### ISSUE TITLE
/mnt/ doesn't show in System info

### ISSUE THREAD

**Issue by Mcpoowl** [Hellowlol/HTPC-Manager#454]
Trying to show my HDD usage of my external harddrive, I'm running into the problem that my /mnt/ won't show up.

My external harddrive is mounted to /mnt/extdrive/.

I've tried everything, but the log shows the same error everytime:

"Could not get disk info [Errno 2] No such file or directory: '/_mnt'

Not sure why the extra _ is there.

![image](https://cloud.githubusercontent.com/assets/2244753/14405910/70e5e3ae-fe9a-11e5-901c-bfd2833e9ace.png)

**Comment by Hellowlol** [comment]
Can you take a screenshot of the about page and your computer stats settings page? I have no idea why that happen so i need some more info to debug it.

**Comment by Mcpoowl** [comment]
Ofcourse. I'll add as much screenshots as possible with relevant information:

About:

![image](https://cloud.githubusercontent.com/assets/2244753/14406002/91b0fb62-fe9c-11e5-9c3c-81f13c37a1df.png)

System info settings (I've been trying some different things, so might not be correct atm)

![image](https://cloud.githubusercontent.com/assets/2244753/14406008/ab360168-fe9c-11e5-8b0e-1050ce789e3d.png)

Only thing showing in System info tab is the /run mount point

![image](https://cloud.githubusercontent.com/assets/2244753/14406029/07b8e0ae-fe9d-11e5-8be6-1f57a1ab8b92.png)

**Comment by Hellowlol** [comment]
Thanks, and if you manually execute

```
import psutil
print psutil.disk_partitions(all=True)
```

Whats the response?

**Comment by Mcpoowl** [comment]
![image](https://cloud.githubusercontent.com/assets/2244753/14406143/f750f498-fe9e-11e5-8536-a1c3c0eba680.png)

So it's probably having difficulties with the mmcblk0p1 device?

**Comment by Hellowlol** [comment]
psutil seems to return a invalid mountpoint. Try adding _mnt in the mountpoint in computer stats settings.

**Comment by Mcpoowl** [comment]
Excellent. That did the trick! Thank you very much!

**Comment by Hellowlol** [comment]
No problem! Glad we got it sorted.
