### ISSUE TITLE
modules.stats :: ERROR :: Pulling S.M.A.R.T. data 'usbsunplus'

### ISSUE THREAD

**Issue by jjkakakk** [Hellowlol/HTPC-Manager#455]
I get the error

`modules.stats :: ERROR :: Pulling S.M.A.R.T. data 'usbsunplus'`

in the log, and the httpd always reports 'smart is not correctly configured'. 
Smartmontools is installed (package manager ubuntu, resides /usr/sbin/).
Can execute "smartctl --scan-open" from a shell without error.

**Comment by Hellowlol** [comment]
Usbdrives isnt supported in the wrapper we use for smartctl. Thats why it fails.

**Comment by jjkakakk** [comment]
I don't want it scanning usb drives, just 4 internal sata.

**Comment by Hellowlol** [comment]
Ok, please follow the issue guidelines and I'll see what I can do.

**Comment by Hellowlol** [comment]
Update to the latest version and clear the log then recreate the error and paste the log here/gist/pastebin

**Comment by jjkakakk** [comment]
i've done a git pull - and it seems to be resolved now - I didn't amend any config but git pulled / rebooted, and am now getting (no errors)

> S.M.A.R.T.
> sda   WDC WD40EFRX-68WT0N0    34°    PASS
> sdb   WDC WD40EFRX-68WT0N0    35°    PASS
> sdc   WDC WD40EFRX-68WT0N0    35°    PASS
> sdd   WDC WD40EFRX-68WT0N0    33°    PASS
> sde   Samsung SSD 840 EVO 120GB   0° PASS

unsure what the cause was (can't put in a log as i cleared it before re-running)
thanks for the help though
