### ISSUE TITLE
Unable to connect to Plex. Getting 401 Unauthorized with correct login info.

### ISSUE THREAD

**Issue by hematic** [Hellowlol/HTPC-Manager#459]
- modules.plex  ERROR   Unable to contact Plex via http://192.168.1.8:32400 error HTTP Error 401: Unauthorized
- modules.plex  ERROR   Unable to contact Plex via http://localhost:32400 error HTTP Error 401: Unauthorized
- modules.plex  INFO    GDM: Servers discovered: 1

I have all of the other pieces fine but for some reason i cant get Plex to work. 

Plex needs the following link to open to not get the 401: 

> http://127.0.0.1:32400/web/index.html

I dont know how to append the **/web/index.html** to the connection string.

If i just append it to the PORT string i get:
- modules.plex  ERROR   Unable to contact Plex via http://192.168.1.8:32400/web/index.html error No JSON object could be decoded

**Comment by Hellowlol** [comment]
Hi! It does not need the /web/index etc. It uses the api to get info. Can you post the full log plx. Do you use plex home? Any special/foreign chars in the username/password?

**Comment by hematic** [comment]
Thanks for the prompt response!

Here is the full log : http://pastebin.com/zRjbf9xj
I don't know if im using plex home. Under the users section i dont have an option to LEAVE HOME so im assuming i dont.

Definitely no special characters in the password.

**Comment by Hellowlol** [comment]
Can you check that the ssl option inside plex is set to prefered? it does not work with ssl.

What happens if you go to `http://htpcmanager_ip:htpcmanager_port/plex/myPlexSignin?username=your_username&password=your_password` ?

Have you change password in plex recently?

**Comment by hematic** [comment]
Yes sir!

Secured connections was set to preferred.

When i go to that link i get a value back in quotes, "removed"

I have not changed my password in months,

**Comment by Hellowlol** [comment]
I removed the authtoken from your post since it would allow ppl to use your account. Any change your using a plexpass server? (special releases only available to ppl with plexpass)

**Comment by hematic** [comment]
oops thanks!

I am using PlexPass. Version 0.9.16.5

**Comment by Hellowlol** [comment]
Plex pass versions is unsupported because you cant authenticate :(
