### ISSUE TITLE
Headphones bugs

### ISSUE THREAD

**Issue by kooimens** [Hellowlol/HTPC-Manager#46]
First, If there are no wanted albums, it's better to use the same as couchpotato/sickrage does for the wanted albums on dash.
Secondly, the 'no wanted albums found' is on full width. I think that's correct. Same should be in place for no artists found and history is empty.

![1](https://cloud.githubusercontent.com/assets/3150962/6384288/023791cc-bd5b-11e4-9e7b-1c1d56f9fe83.jpg)
![2](https://cloud.githubusercontent.com/assets/3150962/6384290/02552552-bd5b-11e4-8e1d-2d3b1bcd86f2.jpg)
![3](https://cloud.githubusercontent.com/assets/3150962/6384291/0256e3e2-bd5b-11e4-8691-f9a3bc447507.jpg)
![4](https://cloud.githubusercontent.com/assets/3150962/6384289/0254f406-bd5b-11e4-8082-9db3d71cf34b.jpg)

**Comment by Hellowlol** [comment]
Thanks!

**Comment by Hellowlol** [comment]
So if i get your right image placeholder should be replaced with a table like sr and cp?

**Comment by Hellowlol** [comment]
Im gonna leave the wanted albums carousel as it is atm, as i like the consistency with the other carousels. The other stuff you mention should be fixed

**Comment by kooimens** [comment]
Yeah, that's right. Seems to be fixed now! 

I mean the view on dash if there are no wanted albums is just not that pretty. Maybe, remove the wanted albums dash completely if wanted albums equal zero?

**Comment by Hellowlol** [comment]
I could but i think the user would expect something to be there when its actived in the settings.
