### ISSUE TITLE
Deluge Login Error

### ISSUE THREAD

**Issue by Mdleal** [Hellowlol/HTPC-Manager#461]
Is there suppose to be a server listed here?
![deluge connection](https://cloud.githubusercontent.com/assets/691042/15050695/e967183c-12ba-11e6-88bc-a3828db3a3e7.JPG)

After I select connect. 
![deluge error](https://cloud.githubusercontent.com/assets/691042/15050738/1a7272dc-12bb-11e6-971d-6ee6fe803bed.JPG)

Deluge version: 1.3.10

I am able to connect to the daemon via the Deluge Web UI. 

[http://pastebin.com/pypshzH1](pastbin)

**Comment by Hellowlol** [comment]
The link is broken. Yes it's suppose to be listed. Please read the issue guidelines.

**Comment by Mdleal** [comment]
[http://pastebin.com/pypshzH1](http://pastebin.com/pypshzH1)

**Comment by Hellowlol** [comment]
Port don't seem to be set.

**Comment by Mdleal** [comment]
Does it need to connect to the gui. 8112 or deamon?

**Comment by Hellowlol** [comment]
I cant remember and i cant check now. Just try both

**Comment by Mdleal** [comment]
Web ui. 8112.  Still had the default password deluge set

**Comment by Hellowlol** [comment]
It was the webui port. Anyway please read https://github.com/Hellowlol/HTPC-Manager/blob/master2/ISSUE_TEMPLATE.md and say the version number of deluge an ill look into it. I just tried with 1.3.12 and it works just fine.
