### ISSUE TITLE
Sonarr Calendar- Show All

### ISSUE THREAD

**Issue by Mdleal** [Hellowlol/HTPC-Manager#463]
Can an option be added to show all(unmonitored and monitored) on the calendar? I tried updating the sonarr.py myself but received and error.

episodes = self.fetch('calendar?unmonitored=true%s' % p)

 'title': episode['series']['title'],
TypeError: string indices must be integers

**Comment by Hellowlol** [comment]
It should be:

```
episodes = self.fetch('calendar?unmonitored=true&%s' % p)
```

**Comment by Mdleal** [comment]
perfect. I'm going to try to create a switch in setting.
