### ISSUE TITLE
Plex Challenge

### ISSUE THREAD

**Issue by armss001** [Hellowlol/HTPC-Manager#465]
Is it possible to connect to a plex server that has a login and pin code for the users? I keep getting errors when I try to connect and I am unsure on why. I am in the process of upgrading and switching to Plex over Kodi and loved this feature.

**Comment by Hellowlol** [comment]
Yes, but you need to add the username and password. This module does not support ssl so you need to set pms ssl settings to prefered.

**Comment by armss001** [comment]
Hello, sorry for the slow replied I had a busy few days. I have indeed set this to preferred but it still fails to connect. I am unsure on how to get this working. Attached is an image of the settings on HTPC and Plex if that helps any.. please tell me I am missing something stupid... I just want to see my latest additions. 
![capture](https://cloud.githubusercontent.com/assets/8210710/15206655/180240c0-1821-11e6-9c38-79c1b07453d5.PNG)

**Comment by Hellowlol** [comment]
Try restarting htpc manger and make sure your not using a plex pass release of pms. The settings look fine :)

**Comment by armss001** [comment]
Oh How come I can't use the plex pass version. And will changing the version remove other features?

**Comment by Hellowlol** [comment]
Its simply because authentication fails against a plex pass pms (just as same as it does for plexpy etc)

**Comment by armss001** [comment]
Okay, this is weird, but I just moved the VM onto another host, and even though I haven't changed any settings I.E. it's still on plex pass update channel, it is working.

**Comment by Hellowlol** [comment]
Oh. thats great new. It has been like that for a really long time im glad they got that sorted. So plex works inside htpc manager now?

**Comment by armss001** [comment]
To an extent. I am not pushing anything in it at the moment as the functionality I wanted it now there. I am just happy I can see my recently added. If you want me to poke around some more I will. I just hope the SSL gets sorted so its a bit more secure.

**Comment by Hellowlol** [comment]
Im lazy so i dont think there ever will be a ssl option not aslong as there is a prefred option in plex. htpc manger is intended to be used on a local network, if one of the bad guys are on your local network your pretty much fucked anyway.

Feel free to poke around round, test the dropdown, try search, filter on genre=action year>2010 etc
If i get some time ill try to fix the player controls so you can control players (on your network) for htpc manager

**Comment by Hellowlol** [comment]
ssl has been added to the plex module. closing this.
