### ISSUE TITLE
Sonarr Calendar not showing todays shows unless toggled to Month first

### ISSUE THREAD

**Issue by ShoGinn** [Hellowlol/HTPC-Manager#466]
When using the dashboard to show the calendar for today the shows do not show up until you click on month then back to week or day.

![untitled](https://cloud.githubusercontent.com/assets/2660603/15099376/c363c8ce-1508-11e6-9263-2c84dc097c4f.gif)

**Comment by Hellowlol** [comment]
Works fine here. What browser is this?

**Comment by ShoGinn** [comment]
@Hellowlol I tried it using Safari, Firefox and Chrome as well as IE and MS Edge.

**Comment by ShoGinn** [comment]
It looks like anywhere the calendar is unless I change the month, week day it doesn't show... very odd.

**Comment by Hellowlol** [comment]
Very strange, i just checked with firefox and ie, works fine here. Any console errors?

**Comment by ShoGinn** [comment]
Here are my version info's just in case:

```
Updater Git
BRANCH  master2
Current commit  23ef0fcb5c03455e9dc13301062f933771629176
Auto update True
RUNDIR  /opt/HTPC-Manager
DATADIR /home/htpcm/.config/htpcm/userdata
DB  /home/htpcm/.config/htpcm/userdata/database.db
WEBDIR  /
AUTH    False
LOGLEVEL    info
locale  UTF-8
ARGS    --daemon --datadir /home/htpcm/.config/htpcm/userdata --pid /home/htpcm/.config/htpcm/userdata/htpcmanager.pid
OS  Linux-4.4.6-1-pve-x86_64-with-Ubuntu-16.04-xenial
Python version: 2.7.11+ (default, Apr 17 2016, 14:00:29) [GCC 5.3.1 20160413]

```

**Comment by ShoGinn** [comment]
No console errors of significance, just the gripes about CSS etc. I looked at the code, and in the table there isn't any hidden data, it isn't there at all in the source (I was hoping it was a formatting thing). Until you click then it shows up.

**Comment by Hellowlol** [comment]
On the page load of the dashboard you should be able to a call like this: http://10.0.0.97:8986/htpc/sonarr/Calendar?start=2016-05-09&end=2016-05-10

Can you see it? And if you do does it has any data?

**Comment by ShoGinn** [comment]
I modified that URL to my setup and the data in there looks like the correct info.

If I changed the start and end to 2016-05-08 there is nothing.

just []

**Comment by ShoGinn** [comment]
So the episodes show in the "Next Aired" but the Calendar is not showing the episodes.

As for Sonarr itself, its calendar is functioning perfect (I checked to make sure)

Its not just a dashboard problem from what I can tell, its all Sonarr Calendar functions

**Comment by Hellowlol** [comment]
So just to be clear, the episodes show up on next aired on the dashboard but not in the dash board calendar or the calendar inside the module? 

Only thing that is differed is that the next aired has hardcoded dates and the calendar gets it from the calendar. There is also junkpart of that url. fx &_=1462749552290 what happens if you remove it?

**Comment by ShoGinn** [comment]
I guess I'm confused on how to do all of that.. here is another example
![untitled](https://cloud.githubusercontent.com/assets/2660603/15101064/0917951c-153b-11e6-90e2-94a4b266b6dc.gif)

**Comment by Hellowlol** [comment]
Nvm, i just removed it. Try if the latest update solved the issue.

**Comment by ShoGinn** [comment]
I just tried the update... no change..

**Comment by Hellowlol** [comment]
Ok, can i have to log file? 

Can you use use the chrome dev tools click the network tab, use cntl f5 to refresh the page,  find the request that looks like .../sonarr/Calendar?start=2016-05-09&end=2016-05-10&_=1462749552290  and see if it returns any data.

**Comment by ShoGinn** [comment]
I did this request right now.

09 May 2016 @ 0826L

```
GET /sonarr/Calendar?start=2016-05-09&end=2016-05-10&_=1462807368941 HTTP/1.1
Host: mediaserver:8085
Connection: keep-alive
Cache-Control: max-age=0
Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
Referer: http://mediaserver:8085/
Accept-Encoding: gzip, deflate, such
Accept-Language: en-US,en;q=0.8
```

`[{"all": {"seriesId": 8, "episodeNumber": 3, "seasonNumber": 6, "airDate": "2016-05-08", "airDateUtc": "2016-05-09T01:00:00Z", "overview": "Daenerys meets her future. Bran meets the past. Tommen confronts the High Sparrow. Arya trains to be No One. Varys finds an answer. Ramsay gets a gift.", "absoluteEpisodeNumber": 53, "title": "Oathbreaker", "hasFile": true, "series": {"certification": "TV-MA", "overview": "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and the icy horrors beyond.", "airTime": "21:00", "firstAired": "2011-04-17T00:00:00Z", "tvRageId": 24493, "year": 2011, "images": [{"coverType": "fanart", "url": "http://thetvdb.com/banners/fanart/original/121361-15.jpg"}, {"coverType": "banner", "url": "http://thetvdb.com/banners/graphical/121361-g19.jpg"}, {"coverType": "poster", "url": "http://thetvdb.com/banners/posters/121361-36.jpg"}], "id": 8, "ratings": {"votes": 1542, "value": 9.5}, "genres": ["Adventure", "Drama", "Fantasy"], "monitored": true, "network": "HBO", "title": "Game of Thrones", "lastInfoSync": "2016-05-09T06:49:52.765809Z", "seasonCount": 6, "seriesType": "standard", "status": "continuing", "added": "2015-12-08T03:47:02.913535Z", "tvdbId": 121361, "tags": [], "imdbId": "tt0944947", "seasonFolder": true, "cleanTitle": "gamethrones", "sortTitle": "game thrones", "seasons": [{"monitored": false, "seasonNumber": 0}, {"monitored": false, "seasonNumber": 1}, {"monitored": false, "seasonNumber": 2}, {"monitored": false, "seasonNumber": 3}, {"monitored": false, "seasonNumber": 4}, {"monitored": true, "seasonNumber": 5}, {"monitored": true, "seasonNumber": 6}], "useSceneNumbering": false, "titleSlug": "game-of-thrones", "qualityProfileId": 3, "profileId": 3, "path": "/mnt/media/Videos/TV Shows/Game of Thrones", "runtime": 55, "tvMazeId": 82}, "unverifiedSceneNumbering": false, "monitored": true, "episodeFileId": 494, "id": 1976}, "allDay": false, "episode": 3, "title": "Game of Thrones", "overview": "Daenerys meets her future. Bran meets the past. Tommen confronts the High Sparrow. Arya trains to be No One. Varys finds an answer. Ramsay gets a gift.", "start": "2016-05-09T01:00:00Z", "season": 6}, {"all": {"seriesId": 7, "episodeNumber": 5, "seasonNumber": 2, "airDate": "2016-05-08", "airDateUtc": "2016-05-09T01:00:00Z", "overview": "Alicia works toward reuniting with her family. Travis comes across a familiar face. Madison and Nick try to save their family against all odds.", "title": "Captive", "hasFile": true, "series": {"certification": "TV-MA", "overview": "A horrifying zombiocalypse spin-off series from The Walking Dead, set in the same universe but starting at a far earlier time in Los Angeles. The show follows normal people learning to deal with the rapidly growing collapse of civilization, at the very beginning of a zombie outbreak.\n\nIn Los Angeles, a city where people come to escape, shield secrets, and bury their pasts, we follow this mysterious outbreak as it threatens to disrupt what little stability high school guidance counselor Madison Clark and English teacher Travis Manawa have managed to assemble. \n\nThe pressure of blending two families while dealing with resentful, escapist, and strung out children takes a back seat when society begins to break down. A forced evolution, and survival of the fittest takes hold, as our dysfunctional family finds they must either reinvent themselves or embrace their darker histories.", "airTime": "21:00", "firstAired": "2015-08-23T00:00:00Z", "tvRageId": 48384, "year": 2015, "images": [{"coverType": "fanart", "url": "http://thetvdb.com/banners/fanart/original/290853-20.jpg"}, {"coverType": "banner", "url": "http://thetvdb.com/banners/graphical/290853-g6.jpg"}, {"coverType": "poster", "url": "http://thetvdb.com/banners/posters/290853-8.jpg"}], "id": 7, "ratings": {"votes": 108, "value": 8.2}, "genres": ["Drama", "Horror"], "monitored": true, "network": "AMC", "title": "Fear the Walking Dead", "lastInfoSync": "2016-05-09T06:49:51.41065Z", "seasonCount": 2, "seriesType": "standard", "status": "continuing", "added": "2015-12-08T03:47:00.447543Z", "tvdbId": 290853, "tags": [], "imdbId": "tt3743822", "seasonFolder": true, "cleanTitle": "fearwalkingdead", "sortTitle": "fear walking dead", "seasons": [{"monitored": false, "seasonNumber": 0}, {"monitored": true, "seasonNumber": 1}, {"monitored": true, "seasonNumber": 2}], "useSceneNumbering": false, "titleSlug": "fear-the-walking-dead", "qualityProfileId": 3, "profileId": 3, "path": "/mnt/media/Videos/TV Shows/Fear the Walking Dead", "runtime": 45, "tvMazeId": 1824}, "unverifiedSceneNumbering": false, "monitored": true, "episodeFileId": 496, "id": 2121}, "allDay": false, "episode": 5, "title": "Fear the Walking Dead", "overview": "Alicia works toward reuniting with her family. Travis comes across a familiar face. Madison and Nick try to save their family against all odds.", "start": "2016-05-09T01:00:00Z", "season": 2}, {"all": {"seriesId": 18, "episodeNumber": 17, "seasonNumber": 2, "airDate": "2016-05-08", "airDateUtc": "2016-05-09T01:30:00Z", "overview": "Todd feels left out, as Tandy warms to having his big brother back on Earth. Meanwhile, Mike learns more about Erica than the group has ever uncovered about her.", "title": "Smart and Stupid", "hasFile": true, "series": {"certification": "TV-14", "overview": "The year is 2022, and after an unlikely event, only one man is left on earth: Phil Miller, who used to be just an average guy who loved his family and hated his job at the bank. Now, in his RV, Phil searches the country for other survivors. He has traveled to every city, every town and every outpost in the United States, Mexico and Canada, and has found no one, which leads him to the painful realization that he is almost certainly the last living being on the face of the earth.", "airTime": "21:30", "firstAired": "2015-03-01T00:00:00Z", "tvRageId": 38162, "year": 2015, "images": [{"coverType": "fanart", "url": "http://thetvdb.com/banners/fanart/original/281622-2.jpg"}, {"coverType": "banner", "url": "http://thetvdb.com/banners/graphical/281622-g3.jpg"}, {"coverType": "poster", "url": "http://thetvdb.com/banners/posters/281622-1.jpg"}], "id": 18, "ratings": {"votes": 35, "value": 7.4}, "genres": ["Comedy"], "monitored": true, "network": "FOX (US)", "title": "The Last Man on Earth", "lastInfoSync": "2016-05-09T06:49:56.624794Z", "seasonCount": 2, "seriesType": "standard", "status": "continuing", "added": "2015-12-08T03:47:35.261237Z", "tvdbId": 281622, "tags": [], "imdbId": "tt3230454", "seasonFolder": true, "cleanTitle": "thelastmanonearth", "sortTitle": "last man on earth", "seasons": [{"monitored": false, "seasonNumber": 0}, {"monitored": false, "seasonNumber": 1}, {"monitored": true, "seasonNumber": 2}], "useSceneNumbering": false, "titleSlug": "the-last-man-on-earth", "qualityProfileId": 3, "profileId": 3, "path": "/mnt/media/Videos/TV Shows/The Last Man on Earth", "runtime": 25, "tvMazeId": 620}, "unverifiedSceneNumbering": false, "monitored": true, "episodeFileId": 495, "id": 1970}, "allDay": false, "episode": 17, "title": "The Last Man on Earth", "overview": "Todd feels left out, as Tandy warms to having his big brother back on Earth. Meanwhile, Mike learns more about Erica than the group has ever uncovered about her.", "start": "2016-05-09T01:30:00Z", "season": 2}]`

**Comment by ShoGinn** [comment]
If I step through the days do next Sunday (15th) the request looks like:
Request:

```

GET /sonarr/Calendar?start=2016-05-14&end=2016-05-15&_=1462807676613 HTTP/1.1
Host: mediaserver:8085
Connection: keep-alive
Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
Referer: http://mediaserver:8085/
Accept-Encoding: gzip, deflate, such
Accept-Language: en-US,en;q=0.8

```

Response:

```

HTTP/1.1 200 OK
Content-Length: 22
X-Xss-Protection: 1; mode=block
Content-Encoding: gzip
Vary: Accept-Encoding
Server: CherryPy/3.8.0
Date: Mon, 09 May 2016 15:28:46 GMT
X-Frame-Options: DENY
Content-Type: application/json

[]
```

**Comment by Hellowlol** [comment]
I cant seem to recreate your issue. Sure there are no console errors in your browsers, im gonna need the log in order to attempt to figure out whats wrong.

**Comment by ShoGinn** [comment]
Weird... I checked on multiple browsers under multiple operating systems and they all have the same problem..

Sunday is not being shown on the calendar unless you load the entire month (day and week do not load it)

The console log has the typical CSS errors on Safari and on Firefox I get jquery errors (getPreventDefault() is depreciated.... //@ to indicate sourceMappingURL pragmas is deprecated use //# instead.
