### ISSUE TITLE
Sonarr searches for every episode when new tv show is added.

### ISSUE THREAD

**Issue by chris243** [Hellowlol/HTPC-Manager#468]
Seems that the module is adding and searching for missing episodes instead of just adding. Any way to just add the show? 

Edit: I opened the sonarr.py file and changed  'searchForMissingEpisodes': True} to false and that did the trick. Never mind this question.

**Comment by Hellowlol** [comment]
Hi! I'm glad you found a solution. Just remember you have to do this on each update.
