### ISSUE TITLE
Sabnzbd empty history tab 

### ISSUE THREAD

**Issue by kooimens** [Hellowlol/HTPC-Manager#47]
![1](https://cloud.githubusercontent.com/assets/3150962/6385086/b3beac0a-bd65-11e4-8590-f3b473a258f9.jpg)

Don't know what's happening here. It worked perfectly last days, but now it's just empy. I'v got a pretty large history at the moment, around 70 items.

**Comment by Hellowlol** [comment]
Hi! thanks for reporting this issue. Would you provide me with htpc-manager log. And can you go to http://ip:port/sabnzbd/GetHistory. Does anything turn up there?

**Comment by kooimens** [comment]
http://ip:port/sabnzbd/GetHistory returns "null".

The log is showing two errors regarding sabnzbd:
`modules.sabnzbd ERROR Cannot contact sabnzbd Invalid control character at: line 1 column 380 (char 379)  `
`modules.sabnzbd ERROR Cannot contact sabnzbd Invalid control character at: line 1 column 409 (char 408)  `

**Comment by Hellowlol** [comment]
Okei, is history the only thing that isnt working? can you grab the history data manually from sabnzbd webui and paste that to pastebin?

**Comment by kooimens** [comment]
Indeed, history is the only thing that's not working. 

You've got mail (gmail)

**Comment by Hellowlol** [comment]
what mail was that? i think the one hithub shows is just a fake one, not even sure it exists.. :p

**Comment by kooimens** [comment]
hellowlol1@gmail.com ?

**Comment by Hellowlol** [comment]
ah, thats just a dummy. Do you have a user account on kodi forum or something where i can pm you the real one?

**Comment by Hellowlol** [comment]
nvm... i acctually made that one.... just need to reset it.

**Comment by kooimens** [comment]
A new error in sabnzbd came up. I think the '@' isn't the problem:
`2015-02-27 16:50:31 modules.sabnzbd ERROR Cannot contact sabnzbd Invalid control character at: line 1 column 7536 (char 7535)  `

**Comment by Hellowlol** [comment]
Ok, is a probably invalid characters in the json returned from sabnzbd. I'll try to fix it later tonight.

**Comment by Hellowlol** [comment]
@kooimens Can you update and try again?

**Comment by kooimens** [comment]
Fixed! Many thanks!
