### ISSUE TITLE
Unable to connect to Sonarr

### ISSUE THREAD

**Issue by triantos** [Hellowlol/HTPC-Manager#470]
### Reporting Issues:

To ensure that a I has enough information to work with please include all of the following information.

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**
- [x] Version
  02ce2ba63
- [x] Branch
  master2
- [x] Commit hash
  02ce2ba63
- [x] Operating system
  Ubuntu 14.04 LTS
- [x] Python version
  2.7.6
- [x] What you did?
  Trying to connect to sonarr (running on same host)
- [ ] What happened?
  [code]2016-05-29 22:01:03 :: cherrypy.error.140603774022032 :: ERROR :: [29/May/2016:22:01:03] HTTP 
  Traceback (most recent call last):
  File "/usr/local/src/HTPC-Manager/libs/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/src/HTPC-Manager/libs/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/usr/local/src/HTPC-Manager/libs/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(_args, *_kwargs)
  File "/usr/local/src/HTPC-Manager/libs/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/usr/local/src/HTPC-Manager/modules/sonarr.py", line 116, in Rootfolder
    return [folder['path'] for folder in self.fetch('Rootfolder')]
  TypeError: string indices must be integers[/code]
- [x] What you expected?
  read and display data from sonarr
- [x] How can we reproduce your issue?
  Per hellowlol, I need a non-empty "rootfolder off your shows". None of my subscribed shows have blank folders (all were added via "import existing". My root folder is "/mnt/media/tv" and that does show up in Series -> Add Series -> Import Existing in Sonarr. When I go to Series -> Series Editor and look at the list of shows, they all have paths that are subdirectories of that root folder. Some series have a trailing "/", others don't, and some have parenthesis (e.g. "Xxx show (2010)"), but none are blank.

Sometimes I end up in a situation when htpc-manager shows a spinner on the web page but never completes. Other times, the error gets dumped to the log and then the web page stops updating
- [x] What are your (relevant) settings?
  I'm running in Safari on El Capitan (Mac)
  <img width="664" alt="screen shot 2016-05-31 at 9 34 43 pm" src="https://cloud.githubusercontent.com/assets/374769/15698258/8e052930-2777-11e6-9a01-15024e768967.png">
- [x] Include a link to your **FULL** (not just a few lines!) log file that has the error. Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).
  https://gist.github.com/triantos/a5203d423dbb27a7842fceb49066e599

Close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.

**Comment by Hellowlol** [comment]
What happens if you go to http://htpc-ip:htpc-port/sonarr/test ?

**Comment by Hellowlol** [comment]
I was referring to this place: 
![image](https://cloud.githubusercontent.com/assets/1214134/15711952/9550e24e-2810-11e6-9fe4-8a8a26cbcb33.png)

**Comment by triantos** [comment]
I haven't enabled auth on any internal systems but I get the following:
{"error": "Unauthorized"}

**Comment by Hellowlol** [comment]
That message is from sonarr, doble check your apikey

**Comment by triantos** [comment]
Argh! Pilot error. I hadn't realized I needed the API key. Small suggestion might be to change the description for the "API" field to "API key" in the Sonarr config page. I thought it was a path to the API or something like that and left it blank. Thanks!
