### ISSUE TITLE
[FreeBSD] vnstat: not found 

### ISSUE THREAD

**Issue by T-600** [Hellowlol/HTPC-Manager#471]
### Reporting Issues:

To ensure that a I has enough information to work with please include all of the following information.

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**
- [x] Version
  https://github.com/Hellowlol/HTPC-Manager/commit/02ce2ba6360dc95e64669946383866d1ad347f8d
- [x] Branch
  master2
- [x] Commit hash
  https://github.com/Hellowlol/HTPC-Manager/commit/02ce2ba6360dc95e64669946383866d1ad347f8d
- [x] Operating system
  FreeBSD-10.3-RELEASE-amd64-64bit-ELF
- [x] Python version
  2.7.11
- [x] What you did?
  Installed vnstat & paramiko
- [x] What happened?
  getting vnstat: not found, is working fine in the shell
- [x] What you expected?
  vnstat to work. Is there a way to find out what path it's looking for or to set a manual path like git ?
- [x] How can we reproduce your issue?
  Is a fresh install of freebsd
- [x] What are your (relevant) settings?
  ![untitled-2](https://cloud.githubusercontent.com/assets/19683856/15703980/aadcc7c0-282b-11e6-883f-6a07d9f56271.png)
- [x] Include a link to your **FULL** (not just a few lines!) log file that has the error. Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).

Close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.
#### Link to log:

htpcmanager.log https://gist.github.com/T-600/65a370ba4a8ae6189e391a01715dba3e
vnstat --dumpdb --xml https://gist.github.com/T-600/f456fca188fa96b740070e555e62e5d3

**Comment by Hellowlol** [comment]
in short return ocde 127 means command not found. Have you installed vnstat **inside** your jail?

**Comment by T-600** [comment]
yes and it's working fine from the command line, just not in htpc manager

**Comment by Hellowlol** [comment]
Hmm. Strange, you dont seem to be using paramiko. What happens if you check the use ssh option and enter the ip and port of the freenas computer?

**Comment by T-600** [comment]
paramiko is installed. using ssh is erroring out aswell, this is quite strange.

https://gist.github.com/T-600/8d01f8faf057e39ac7d4e808ddce11e2

**Comment by Hellowlol** [comment]
Can you post a screenshot of your vnstat module settings?

**Comment by T-600** [comment]
![untitled-2](https://cloud.githubusercontent.com/assets/19683856/15713885/8d05fe4e-285b-11e6-82cf-78fc68e0aeec.png)

**Comment by Hellowlol** [comment]
What paramiko version have you installed?

**Comment by T-600** [comment]
paramiko (2.0.0)

**Comment by T-600** [comment]
Seems to be a path issue, if i add the path to the [cmd](https://github.com/Hellowlol/HTPC-Manager/blob/master2/modules/vnstat.py#L66) variable it works fine. /usr/local/bin/ is in the env $PATH so it should work without it but it's not /shrug

**Comment by T-600** [comment]
That's working on my end, i'll wait till it's added thank you.
