### ISSUE TITLE
Ubuntu server 16.04 Questions

### ISSUE THREAD

**Issue by ezspot** [Hellowlol/HTPC-Manager#475]
Is this version tested on Ubuntu server 16.04? and is it approved? 
Maybe someone out there got a insight. I'm considering installing this, but not much info to go on regarding server 16.04.

**Comment by Hellowlol** [comment]
You can install it anywhere python runs.

**Comment by wildedave** [comment]
I'm running on Server 16.04 without issue

**Comment by ezspot** [comment]
@wildedave Thanks, i'll give it a go :)

**Comment by ezspot** [comment]
Would you run this on the same server as the Plex, Sickrage server? Or use another one? @Hellowlol @wildedave

**Comment by Hellowlol** [comment]
I have everything running on the same "server" except my reverse proxy running on a rpi.

**Comment by ezspot** [comment]
Got this error when i installed it: 
http://pastebin.com/abdFq9bY

**Comment by Hellowlol** [comment]
See https://github.com/Hellowlol/HTPC-Manager/issues/477

**Comment by ezspot** [comment]
Version: https://github.com/Hellowlol/HTPC-Manager

Branch: Master

Operating system Ubuntu Server 16.04

Python version: Python 2.7.11+

What you did? Follow the guide, and fresh installed. 

What happened? I got a error message.

What you expected? It to work when I followed the installation process. 

How can we reproduce your issue? Fresh install

Logs:
http://pastebin.com/abdFq9bY

@Hellowlol

**Comment by Hellowlol** [comment]
I broke it revered the merge 1 minute ago. Just do a git pull and it should resolve your issues

**Comment by ezspot** [comment]
Works fine now, but i can't get Plex to get connected. Tips? 
I'm running it on the same server, and tryed picking it from the list, and type in localhost with correct port. Failed both times.

**Comment by Hellowlol** [comment]
Plex in htpc manger does not support ssl or plexpass server versions. Except from that restart htpc manager

**Comment by ezspot** [comment]
So plex is not supported at all or? I still got the "error" when i try to add it again.

**Comment by wildedave** [comment]
Does your Plex Server appear in the dropdown list?
The other thing I had to do was add my username in the appropriate field,
no password. Make sure you can access you Plex Server on the usual web
interface without issue.

Or reboot…..

**Comment by ezspot** [comment]
Thanks for your reply. Yes it appear in the dropdown list, i tryed with and without my username. Still get the same RED "test". You think i need to reboot the hole server?

**Comment by ezspot** [comment]
Just tryed a reboot, nothing changed.

**Comment by ezspot** [comment]
Deluge, Sickrage works.

**Comment by wildedave** [comment]
There is a htpc.log (from memory) in the userdata directory. See if there
is anything logged. No access to my server at the moment

On Tuesday, 14 June 2016, spot88 notifications@github.com wrote:

> Deluge, Sickrage works.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/Hellowlol/HTPC-Manager/issues/475#issuecomment-225732326,
> or mute the thread
> https://github.com/notifications/unsubscribe/AS9vOuDyjyFSoCw8stS9_-mXkkM4vyuTks5qLd8agaJpZM4IznpS
> .

## 

Sent from Gmail Mobile

**Comment by Hellowlol** [comment]
Try try http://ip:port/plex/myPlexSignin?username=xxx&password=xxx manually in your browser this should return the authtoken from plex TV or raise a exception.

**Comment by ezspot** [comment]
htpc.log - http://pastebin.com/y36QLJb1
Where can i change the port directly in the config? It won't start with what i have saved in settings.

**Comment by Hellowlol** [comment]
Have you tried reading the log? It clearly states the issue. You can't change it as there is no config file. You have to stop what ever runs on that port or manually edit the db.

**Comment by wildedave** [comment]
Looks as if you are going around in circles. Here is what I would do…

Delete what you have done -

sudo rm -rf /opt/HTPCManager
sudo updatedb
sudo locate -i htpc and delete any leftover files as displayed

stop anything running on port 8085
if you don’t know what that is (if anything) try sudo lsof -i :8085

Follow this guide -
http://www.htpcguides.com/install-htpc-manager-ubuntu-linux/

Choose the init.d option to autostart as upstart is deprecated in 16.04

If you want to change the port once you have htpc running goto the settings
page and change the port there. Restart, check connectivity on new port
then restart original service on 8085.

**Comment by ezspot** [comment]
@Hellowlol: Yes. 
http://192.168.1.164:32400/web/index.html - Works fine! 
2016-06-14 11:21:16 modules.plex    ERROR   Unable to contact Plex via http://192.168.1.164:32400 error HTTP Error 401: Unauthorized
2016-06-14 11:21:13 modules.plex    ERROR   Unable to contact Plex via http://192.168.1.164:32400 error HTTP Error 401: Unauthorized

**Comment by ezspot** [comment]
Fresh installed it now, and it works now, thanks @wildedave 
No i only struggle with plex :p

**Comment by wildedave** [comment]
I can’t replicate that error. Removed the username from my config and still
its OK…

2016-06-14 20:27:55 :: modules.plex :: INFO :: Connected to the _Plex_
Media Server mediaserver at http://10.0.1.101:32400

2016-06-14 20:28:08 :: modules.plex :: INFO :: Connected to the _Plex_
Media Server mediaserver at http://10.0.1.101:32400

**Comment by Hellowlol** [comment]
@spot88 please answer the questions you are asked, if not you just wasting my time:

1: First delete the log file from the log page.
2: Manuall enter http://ip:port/plex/myPlexSignin?username=xxx&password=xxx in your browser replace xxx with you username or you password.

This should return a auth token that we used to verify you plex account.
It it does not return a auth token post the log to a gist.

If it dont work:
- Any spescial chars in the password?
- Is plex home active?
- Is the server you using a plexpass version or a regular?
- ssl has to be set to prefered in pms settings

**Comment by ezspot** [comment]
1. Deleted both logs plex and HTPC
2. 401 Unauthorized - Witch log do you want*
- Yes, i use %
- No
- Regular
- https://gyazo.com/111bbb8a152f2e63a61a56f581b0d032

**Comment by ezspot** [comment]
assume you wanted HTPC:
http://pastebin.com/62SCfjds

**Comment by Hellowlol** [comment]
I guess it does not handle the % correctly. Try to change your password in plex.tv, enter the new password in htpc manager and restart it.

**Comment by ezspot** [comment]
Changed password, to something without a special character, but i still get the same error. 
http://pastebin.com/LDRUMk2S

**Comment by Hellowlol** [comment]
Dunno what it could be then. I would use a tool like sqlbrowser to verify that the username and password in the db is correct. Plex works fine here

**Comment by ezspot** [comment]
Okay, thanks anyway.

**Comment by ezspot** [comment]
Still can't get Plex to work, everything else works fine.

**Comment by wildedave** [comment]
Time to reinstall Plex

On Monday, 20 June 2016, spot88 notifications@github.com wrote:

> Still can't get Plex to work, everything else works fine.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/Hellowlol/HTPC-Manager/issues/475#issuecomment-227088438,
> or mute the thread
> https://github.com/notifications/unsubscribe/AS9vOrrp-1tTcyHh6-JD10JEgYH7dg10ks5qNlg-gaJpZM4IznpS
> .

## 

Sent from Gmail Mobile

**Comment by ezspot** [comment]
@wildedave - hehe, that i'm not gonna risk :p everything else works perfectly, so guess ill just drop it.

**Comment by l-t-k** [comment]
I've the same problem as @spot88. http://ip:port/plex/myPlexSignin?username=xxx&password=xxx returns an authtoken. However, the token is different in comparison to the token I manually looked up on plex.tv?
