### ISSUE TITLE
vnstat date/time issue

### ISSUE THREAD

**Issue by wildedave** [Hellowlol/HTPC-Manager#476]
I'm having an issue with vnstat....

The graphs on the vnstat tab work well however the time is 7 hours behind.
My system date/time and locale are correct. 
Running vnstat from the command line shows the correct (system) time.

Is this a pearl thing??

![screen shot 2016-06-12 at 17 16 15](https://cloud.githubusercontent.com/assets/19885882/15989684/6e98678a-30c1-11e6-80ed-8f42f95c7732.png)
![screen shot 2016-06-12 at 17 15 52](https://cloud.githubusercontent.com/assets/19885882/15989685/6f1f365c-30c1-11e6-8bf8-f3a0594f0cd3.png)

**Comment by Hellowlol** [comment]
I'm sure it isn't a pearl thing ;p htpc manager is written in Python. The charts etc are from JavaScript. What way are they off?

**Comment by wildedave** [comment]
Whoops. I meant Python, not Pearl.
At any rate I seem to have solved this. As per the screenshots, vnstat via the command line was showing the correct time, i.e. 17:08. The vnstat Tab in HTPC Manager was showing the time as being 7 hours behind.
Whilst checking everything I noticed that the time and date of the attached switch was incorrect, although not by 7 hours. After correcting the switch, its working correctly this morning.
Go figure....
