### ISSUE TITLE
Problem with latest Comitt

### ISSUE THREAD

**Issue by karanveer1982** [Hellowlol/HTPC-Manager#477]
Hi your latest commit gives the following error.

Indentation error in Line 162 Sonarr.py under modules
### Reporting Issues:

To ensure that a I has enough information to work with please include all of the following information.

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**
- [ ] Version
- [ ] Branch
- [ ] Commit hash
- [ ] Operating system
- [ ] Python version
- [ ] What you did?
- [ ] What happened?
- [ ] What you expected?
- [ ] How can we reproduce your issue?
- [ ] What are your (relevant) settings?
- [ ] Include a link to your **FULL** (not just a few lines!) log file that has the error. Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).

Close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.

**Comment by Hellowlol** [comment]
Thanks, im a moron...

**Comment by Hellowlol** [comment]
I cant fix this until i have access to my computer and i didnt find a revert button on the github page, i was sure i have seen i before. Anyway in the meantime you need to revert this your self.

**Comment by karanveer1982** [comment]
ive replaced it with older modules of sonarr.py and that did the job for now ..thanks

**Comment by Hellowlol** [comment]
git reset --hard
git pull
