### ISSUE TITLE
vnstat not working over ssh

### ISSUE THREAD

**Issue by mme89** [Hellowlol/HTPC-Manager#482]
- Version
  f8c499a
- Branch
  Master2
- Commit hash
  f8c499a
- Operating system
  Linux-3.10.77-x86_64-with-Ubuntu-14.04-trusty
- Python version
  2.7.11
- What you did?
  On the local machine vnstat works without a problem, but I can't get it working over SSH.
  Vnstat also working without any problems on the computer i like to access. Also I can reach
  the computer when using SSH in the terminal or ping.
- What happened?
  Always get the same error as you can see in the LOG file.
- What you expected?
  any ideas are welcome, couldn't find a similar case so far.
- What are your (relevant) settings?
  <img width="745" alt="bildschirmfoto 2016-06-21 um 02 36 09" src="https://cloud.githubusercontent.com/assets/20055295/16214475/f229648a-3758-11e6-9524-3c7519728a92.png">
- http://pastebin.com/FPRvN6Kc

**Comment by Hellowlol** [comment]
Hi! What version of paramiko are you using?

**Comment by mme89** [comment]
Client:

<img width="355" alt="bildschirmfoto 2016-06-23 um 19 54 25" src="https://cloud.githubusercontent.com/assets/20055295/16314096/9544a0b0-397c-11e6-9689-0c93bea1a13f.png">

Server:
<img width="650" alt="bildschirmfoto 2016-06-23 um 19 54 37" src="https://cloud.githubusercontent.com/assets/20055295/16314098/990a5c58-397c-11e6-9ca0-3e14e9a93235.png">

**Comment by mme89** [comment]
anyone?

**Comment by Hellowlol** [comment]
Sorry, i forgot about the entre issue. Try downgrading paramiko to the latest in 1.9.x version

**Comment by mme89** [comment]
No problem. 
Downgrading doesn't make any change. Maybe I will just make a fresh install and see if its working.

**Comment by Hellowlol** [comment]
try

pip install -U setuptools
pin install -U paramiko

http://stackoverflow.com/questions/38251099/paramiko-script-with-error

**Comment by mme89** [comment]
no change. thanks for your help.
I will try reinstall when i got time.

**Comment by Hellowlol** [comment]
did you find a solution?
