### ISSUE TITLE
HTPC Manager doesn't work with Plex Media Server 1.1.0

### ISSUE THREAD

**Issue by mfrelink** [Hellowlol/HTPC-Manager#488]
Hi,

just giving you a heads up that the current version of HTPC Manager doesn't work with the new authentication scheme of Plex Media Server 1.1.0 (Plex Pass right now). So all PMS integration ceased to function.

**Comment by Hellowlol** [comment]
Thanks

**Comment by geolaw** [comment]
I can confirm - I can provide my PMS logs if that will help track down the issue.

I was previously using a version of Maraschino with plex support and it broke at the same time.  So I tried HTPC Manager and I am liking it ... I have had to put my plex web into the "other apps" area.

**Comment by Hellowlol** [comment]
I haven't had time to investigate the issue as I'm busy with other projects. I'll see if I can't get it fixed this weekend.

**Comment by mgmaik** [comment]
Plex update 1.1.3.2700 still doesn't work on HTPC Manager. Please let me know how I could help to fix this issue.

Little more info, I have plex pass and home enabled.

**Comment by Hellowlol** [comment]
Im sorry, i havnt had time to fix it. I havnt forgotten it, i promise :P

**Comment by bafplus** [comment]
Any news on this issue?

**Comment by Hellowlol** [comment]
No, sorry. I havnt had time to work on it.  I have this weekend off so i plan to fix sonarr and plex.

**Comment by geolaw** [comment]
This all started working fine for me ... I am running the following

HTPC :
Updater: Source
BRANCH : master2
Current commit : a7ffcdce698e61202fb25a5fd1d476e55ce47afc

Plex :
Version 1.1.4.2757

​

**Comment by Hellowlol** [comment]
@geolaw Where you running a plexpass version before?

**Comment by geolaw** [comment]
Yes, I think I have installed 2 updates to plex since I reported the problem

-rwxrw-rw- 1 glaw users 100490872 Aug 21 14:47
plexmediaserver_1.1.0.2611-ba905d2_amd64.deb
-rwxrw-rw- 1 glaw users 100597892 Sep  6 17:21
plexmediaserver_1.1.3.2700-6f64a8d_amd64.deb
-rwxrw-rw- 1 glaw users 101088776 Sep 14 16:56
plexmediaserver_1.1.4.2757-24ffd60_amd64.deb

Maybe they reverted something in their API?

**Comment by bafplus** [comment]
At first it didnt work. The settings page says its not working and the 
page stays blank.
But when i just opend it it magicly worked!

Op 22-09-16 om 13:39 schreef geolaw:

**Comment by Hellowlol** [comment]
Awesome stuff.

**Comment by ezar** [comment]
+1 doesn't works

I'm using PLEX 1.1.4

Logs:

> 2016-09-25 07:27:37   modules.plex    INFO    GDM: Servers discovered: 1
> 2016-09-25 07:27:36   modules.plex    INFO    Sending discovery message: M-SEARCH \* HTTP/1.0
> 2016-09-25 07:27:24   modules.plex    ERROR   Unable to fetch all movies! Exception: HTTP Error 401: Unauthorized
> 2016-09-25 07:27:21   modules.plex    ERROR   Unable to fetch recent movies! Exception: HTTP Error 401: Unauthorized
> 2016-09-25 07:27:21   modules.plex    ERROR   Unable to fetch albums! Exception: HTTP Error 401: Unauthorized
> 2016-09-25 07:27:21   modules.plex    ERROR   Unable to fetch episodes! Exception: HTTP Error 401: Unauthorized

**Comment by Hellowlol** [comment]
@ezar that wasnt really helpfull. What version of plex are you using?
