### ISSUE TITLE
HTPC manager for synology doesnt include Sonarr

### ISSUE THREAD

**Issue by henkjanvries** [Hellowlol/HTPC-Manager#489]
- [ ] Version
  htpc manager vs:20160105-2
  synology vs: DSM 6.0.1-7393
- [ ] Python version
  2.7
- [ ] What you did?
  i installed the package and and tried to add my sonarr
- [ ] What happened?
  nothing, it wasnt there
- [ ] What you expected?
  that it was there
- [ ] How can we reproduce your issue?
  Install it from packages.synocommunity.com on a synology with dsm 6
- [ ] What are your (relevant) settings?
  none so far

**Comment by Hellowlol** [comment]
Are you sure you selected my fork?
