### ISSUE TITLE
Sickrage error no shows loading

### ISSUE THREAD

**Issue by gl3nni3** [Hellowlol/HTPC-Manager#491]
### Reporting Issues:

To ensure that a I has enough information to work with please include all of the following information.

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**
- [ ] Version
  current
- [ ] Branch
  master2
- [ ] Commit hash
  f8c499a78557ea85566a40fad097854d6a92a176
- [ ] Operating system
  Unraid docker
- [ ] Python version
  2.7.12 
- [ ] What you did?
  Tried to load a random show of sickrage
- [ ] What happened?
  got an error show not found. Note it does show the banner just not the episodes
- [ ] What you expected?
  Showed all my shows
- [ ] How can we reproduce your issue?
  Add sickrage without ssl with api key to htpc. try to load a randoms how
- [ ] What are your (relevant) settings?
  just the default settings with name password and api
- [ ] Include a link to your **FULL** (not just a few lines!) log file that has the error. Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).

Close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.
#### Link to log:

http://pastebin.com/fAR5cbXg

edit: log with debug on http://pastebin.com/eqvdWAED

**Comment by Hellowlol** [comment]
Delete the log. Set log level to debug, restart and reproduce the error. There isn't enough info in the logs.

**Comment by Hellowlol** [comment]
Bah, there is a error in the exception block...

**Comment by gl3nni3** [comment]
Owh i was already trying to get an error in the log but it didn't want to show. This explains a lot XD

**Comment by Hellowlol** [comment]
update and try again, it should get logged now

**Comment by gl3nni3** [comment]
Nope still can't get debug log to work. It only shows level error while i set the setting to debug in general settings.

**Comment by Hellowlol** [comment]
Did you click save and restart htpc manger?

**Comment by gl3nni3** [comment]
You have to be kidding me _face palm_. Here is the log:http://pastebin.com/eqvdWAED i will also edit the main post to reflect the new log

**Comment by Hellowlol** [comment]
Dunno why the error isnt logged. Any way if you manually type http://10.0.0.3:8081/api/********************************/?cmd=show&indexerid=267440 (replace the xx with apikey).
What is the response on that webpage?

**Comment by gl3nni3** [comment]
{"data": {"args": [], "error_msg": "error 512", "kwargs": {"indexerid": "267440"}}, "message": "SickRage encountered an internal error! Please report to the Devs", "result": "fatal"}

wtf well it isn't a problem on your side i will go and pester the sickrage devs :p thanks for your help!

**Comment by Hellowlol** [comment]
Ok, then its nothing i can do :P. It simply fails since there isnt a proper response. Ill make htpc manager raise a sickrage error message in the future so we know why it failed
