### ISSUE TITLE
Add support for DobyTang app LazyLibrarian similar to CP/Sickrage/Headphones etc.

### ISSUE THREAD

**Issue by famewolf** [Hellowlol/HTPC-Manager#497]
![lazylibrarian_image1](https://cloud.githubusercontent.com/assets/4558832/19181044/5a313074-8c38-11e6-8dbf-b7295128f19a.png)
Please add support for LazyLibrarian.  It's being actively developed and does for ebooks what Headphones, Couch potato and Sickrage do for their associated media.   The project is at:  https://github.com/DobyTang/LazyLibrarian  and was updated as recently as 19 hours ago.  If not for Lazy Librarian specifically perhaps a general category similar to how you did with newsnab where a user could plug in the requirements to access the service and have the program access the app via it's api.

**Comment by Hellowlol** [comment]
See https://github.com/Hellowlol/HTPC-Manager/pull/443
