### ISSUE TITLE
How to add spotweb and nzedb in?  The main page readme says they are supported.

### ISSUE THREAD

**Issue by famewolf** [Hellowlol/HTPC-Manager#498]
The main page states under improvements:  Usenet (Multi search indexers, support nzedb and spotweb in addition to newznab)

So I see how to add a newsnab search to the app.  How does one go about adding a spotweb or nzedb or am I misreading it?

**Comment by Hellowlol** [comment]
There is nothing special to it. Just add them as a indexer in the newznab module

**Comment by Hellowlol** [comment]
There is nothing special to it. Just add them as a indexer in the newznab module
