### ISSUE TITLE
Clicking on name in newsnab page does not take you to server like CP, Sickrage etc Pages.

### ISSUE THREAD

**Issue by famewolf** [Hellowlol/HTPC-Manager#500]
In the interest of having a consistent UI, (and because I run my own local newsnab server which would make this convenient), it would be nice if clicking on the name of the Newsnab entry took you to the actual server:port in the same manner it does on pretty much all the other pages.  When on the couchpotato page clicking on "CouchPotato" takes you to the actual server so you can access special features not integrated into htpcmanager.   As a specific example I have nzbhydra running locally which combines all my various indexers into one and provides some additional features (search history, indexer stats etc) and currently I have to maintain a link for it under "Other servers" to workaround the issue. [This specific screenshot was taken on cybercorey's fork with lazylibrarian support but the issue is the same in both].

![nzbhydra3](https://cloud.githubusercontent.com/assets/4558832/19407232/94bb0b52-9269-11e6-9f10-a00a334995a8.png)

**Comment by Hellowlol** [comment]
This is deliberate as you can add many indexers.I think you can click on a link in the search results
