### ISSUE TITLE
htpc.helpers :: ERROR :: Failed to open image

### ISSUE THREAD

**Issue by mando414** [Hellowlol/HTPC-Manager#502]
### Reporting Issues:

To ensure that a I has enough information to work with please include all of the following information.

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**
- [ 234457927b155517cecf9bcb6bf3fda5034e440c] Version

- [ master2] Branch

- [x] Commit hash

- [ Windows 10 Pro x64] Operating system

- [2.7 ] Python version

- [ pip install --upgrade pil
      pip uninstall pil
       pip install pillow] What you did?

- [ Images for Plex connection no longer show, HTPC displays the following errors in the log: Failed to open image C:\HTPCManager\userdata\images/530b887f91870308f4f93c53a66f6404 dest C:\HTPCManager\userdata\images/530b887f91870308f4f93c53a66f6404_w430_h240_o_100.0_None cannot identify image file 'C:\\HTPCManager\\userdata\\images/530b887f91870308f4f93c53a66f6404'   ] What happened?

- [ pil has been deprecated, pillow should now be used ] What you expected?

- [uninstall pil, install pillow  ] How can we reproduce your issue?

- [ ] What are your (relevant) settings?

- [ https://gist.github.com/mando414/1cbe9a14c38b2cd73b02e8ec9ef0f6f5] Include a link to your **FULL** (not just a few lines!) log file that has the error. Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).

Close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.

#### Link to log: https://gist.github.com/mando414/1cbe9a14c38b2cd73b02e8ec9ef0f6f5

**Comment by Hellowlol** [comment]
pip/pillow install seems to be broken. Uninstall and download the correct exe from here http://www.lfd.uci.edu/~gohlke/pythonlibs/#pil

**Comment by mando414** [comment]
I uninstalled both PIL and Pillow and installed the version of pillow from http://www.lfd.uci.edu/%7Egohlke/pythonlibs/#pil for python2.7.

I am still receiving:

Failed to open image C:\HTPCManager\userdata\images/530b887f91870308f4f93c53a66f6404 dest C:\HTPCManager\userdata\images/530b887f91870308f4f93c53a66f6404_w430_h240_o_100.0_None cannot identify image file 'C:\HTPCManager\userdata\images/530b887f91870308f4f93c53a66f6404'

**Comment by Hellowlol** [comment]
If you check C:\HTPCManager\userdata\images/530b887f91870308f4f93c53a66f6404 does the image work? 
Can you upload that image?

**Comment by mando414** [comment]
Yes the image opens.  I cannot upload it, GitHub won't let me because it has no file extension.

**Comment by mando414** [comment]
I disabled image resize in the HTPC Manager setting and it appears to be working correctly, i will close this issue.

**Comment by Hellowlol** [comment]
Can you give it a jpg extension and upload the image? I just want to test it

**Comment by mando414** [comment]
![530b887f91870308f4f93c53a66f6404](https://cloud.githubusercontent.com/assets/4461890/19943322/e1757820-a104-11e6-89cd-8da8e379605f.jpg)
