### ISSUE TITLE
Plex content retrieval error

### ISSUE THREAD

**Issue by blackley** [Hellowlol/HTPC-Manager#509]
G'day all, having a problem with HTPC manager and Plex - error in log is as follows. "Unable to fetch episodes! Exception: '_children'" I get the same error with movies also. Any ideas?

Updater	Git
BRANCH	master2
Current commit	2b8e5fd0f19b1d75c90e0ecbe4f1892c8ea0d0a9
Auto update	True
RUNDIR	/opt/HTPCManager
DATADIR	/opt/HTPCManager/userdata
DB	/opt/HTPCManager/userdata/database.db
WEBDIR	/
AUTH	True
LOGLEVEL	info
locale	UTF-8
ARGS	
OS	Linux-4.8.0-27-generic-x86_64-with-Ubuntu-16.10-yakkety
Python version:	2.7.12+ (default, Sep 17 2016, 12:08:02) [GCC 6.2.0 20160914]

- Configured linked to Plex and validated - tested OK!

Nothing showing in Dash from Plex content.  Checked the log and found the error message above. No content (only headings) when you click on the plex link.

#### Link to log: http://pastebin.com/hj6nDQH1

**Comment by Hellowlol** [comment]
Tried restarting htpc manger? 
Are you using plex home? A plexpass pms instance?

**Comment by blackley** [comment]
Yes i have restarted a number of times and also restarted the server a number of times.  Yes i am using Plex Home and yes a PlexPass pms instance

**Comment by blackley** [comment]
Hi
Any progress on this issue as yet?

**Comment by Hellowlol** [comment]
Ye, this isn't going to fixed before pms version 1.3 is available to everyone. Plex has changed  some json responses I wanna see what else they intend to break before fixing it.
