### ISSUE TITLE
Unable to contact Plex via http://xxxx:32400 error HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by ajkis** [Hellowlol/HTPC-Manager#511]
### Reporting Issues:

To ensure that a I has enough information to work with please include all of the following information.

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**
- [ ] Version
Todays git

- [ ] Branch

- [ ] Commit hash

- [ ] Operating system
Ubuntu 16.04

- [ ] Python version
Python 2.7.12
- [ ] What you did?
Tried accessing Plex server ( running on another machine )

- [ ] What happened?
Cant connect 

- [ ] What you expected?

- [ ] How can we reproduce your issue?

- [ ] What are your (relevant) settings?

- [ ] Include a link to your **FULL** (not just a few lines!) log file that has the error. Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).

Close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.

#### Link to log:

**Comment by Hellowlol** [comment]
tried restart of htpc manger?

**Comment by ajkis** [comment]
Yes couple of time, is there anything i should set in plex, i mean there is not token, and it seems username and pass is just for Plex Home .
I have Plex Pass and running Plex Media Server Version 1.3.0.3059

Also tryed adding Htpc server IP to plex List of IP addresses and networks that are allowed without auth , but same problem.

**Comment by flixajki** [comment]
omfg lol solved i removed http:// for host. 
my bad

**Comment by ajkis** [comment]
UPDATE 
I removed http:// for host and now TEST connection works, I restarted htpc after but when i try to access plex this is the error in log: 

```
(2016-11-28 22:46:41	modules.plex	ERROR	Unable to fetch currently playing information! Exception: '_children'
2016-11-28 22:46:41	modules.plex	ERROR	http://144.76.35.13:32400
2016-11-28 22:46:37	modules.plex	ERROR	Unable to fetch all movies! Exception: '_children')
```

**If i do TEST** 

```
2016-11-28 22:47:17	modules.plex	INFO	Connected to the Plex Media Server None at http://144.76.35.13:32400
2016-11-28 22:47:15	modules.plex	INFO	GDM: No servers discovered
2016-11-28 22:47:14	modules.plex	INFO	Sending discovery message: M-SEARCH * HTTP/1.0
```

**Comment by Hellowlol** [comment]
Thanks, ill look into it. I guess they changed something.

**Comment by ajkis** [comment]
Anyone else with same issue.

**Comment by Hellowlol** [comment]
I have the same error after I updated to 1.3

**Comment by duecedriver** [comment]
me too... strangely it was working with 1.3 until it autoupdated htpc manager today...



Date
Module
Level
Message
2016-11-30 18:52:26	modules.plex	ERROR	Unable to fetch currently playing information! Exception: '_children'
2016-11-30 18:52:26	modules.plex	ERROR	http://localhost:32400
2016-11-30 18:52:22	modules.plex	ERROR	Unable to fetch all movies! Exception: '_children'
2016-11-30 18:52:18	modules.plex	ERROR	Unable to fetch albums! Exception: '_children'
2016-11-30 18:52:18	modules.plex	ERROR	Unable to fetch recent movies! Exception: '_children'
2016-11-30 18:52:18	modules.plex	ERROR	Unable to fetch episodes! Exception: '_children'
2016-11-30 18:52:15	modules.plex	INFO	Connected to the Plex Media Server None at http://localhost:32400
2016-11-30 18:52:15	modules.plex	INFO	Connected to the Plex Media Server None at http://localhost:32400
2016-11-30 18:52:14	modules.plex	INFO	GDM: Servers discovered: 2
2016-11-30 18:52:13	modules.plex	INFO	Sending discovery message: M-SEARCH * HTTP/1.0
2016-11-30 18:51:43	modules.plex	INFO	Connected to the Plex Media Server None at http://192.168.0.12:32400
2016-11-30 18:51:06	modules.plex	INFO	GDM: Servers discovered: 2

**Comment by Hellowlol** [comment]
I already have a fix but I have hold off since a pita to support both json responses and I want to fix the plex remote controls.

**Comment by strikerjjb** [comment]
Is this because we maybe running a plex pass version that has newer json? So you want to wait until the plex pass version comes out as a general release?

**Comment by Hellowlol** [comment]
Yes, because supporting both version would require more work then im willing to do :P, or rewrite to the xml api. Thats out of question.

**Comment by mattvperry** [comment]
This JSON api change has made it out of plexpass versions I believe

**Comment by corephx** [comment]
Same issue here with _children error and Plex pass.

**Comment by ajkis** [comment]
@Hellowlol r u pushing out the update ?

**Comment by Hellowlol** [comment]
https://github.com/Hellowlol/HTPC-Manager/issues/516

**Comment by blackley** [comment]
@Hellowlol any idea when the update will be released - this issue is driving me nuts as i use the manager on a daily basis and at the moment i have to still look in plex to see what i happening...

**Comment by Hellowlol** [comment]
Dunno, I'll see if I have anytime today. Been busy, sorry.

**Comment by Hellowlol** [comment]
Plex module should be better now. Still controls are still broken.

**Comment by duecedriver** [comment]
a git pull shows no update.. how do I try it out?

**Comment by duecedriver** [comment]
never mind...
just sudo nano copied the module text over and restarted...

get info under plex now.. put no movies show content shows up on the main landing page...

**Comment by Hellowlol** [comment]
Crap, forgot the landing page.

**Comment by duecedriver** [comment]
Doh!!!!  hehe.. just kidding...

happy new year.. thanks for your work here!

**Comment by Hellowlol** [comment]
https://github.com/Hellowlol/HTPC-Manager/issues/509

**Comment by Hellowlol** [comment]
https://github.com/Hellowlol/HTPC-Manager/issues/488

**Comment by strikerjjb** [comment]
Is the code for this in a particular branch? I still get the following from the logs. @Hellowlol 
>2017-01-06 09:28:02	modules.plex	ERROR	Unable to fetch albums! Exception: 'Plex' object has no attribute 'jloadr'
>2017-01-06 09:28:02	modules.plex	ERROR	Unable to fetch recent movies! Exception: '_children'
>2017-01-06 09:28:02	modules.plex	ERROR	Unable to fetch episodes! Exception: Invalid URL '/library/sections': No schema supplied. Perhaps you meant http:///library/sections?`

**Comment by Hellowlol** [comment]
The first is a typo, second is a oversight :p I don't use plex in the dashboard. I'll fix it later today

**Comment by Hellowlol** [comment]
@strikerjjb Should work now.

**Comment by duecedriver** [comment]
upgrade path?

**Comment by Hellowlol** [comment]
I'm not sure I understand your question.

**Comment by duecedriver** [comment]
forget it.. figured it out.. just updated the plex.py fie right?  so I copied that over and it is now good.

does htpcmanager cache these images at all?  with lots of content in my plex library. it takes forever to generate thumbnails each time I go to the plex movie page..

**Comment by Hellowlol** [comment]
Don't manually copy the file over. Just click update and htpc manager will handle this for you. All images are cached and resized. But only as far as you have scrolled down the movie page.

**Comment by duecedriver** [comment]
that didnt work with your last update.. it just opened a green box after clicking update saying I had the latest... didnt try it again this time.

as for caching.. mine appears to reload each time I go into movies and moving down the page takes seconds as it reloads thumbs.....

**Comment by Hellowlol** [comment]
I'm gonna close this because this issue was changes plex did to the json responses. Open a new one issue if you still have problems.
