### ISSUE TITLE
Is this project dead ?

### ISSUE THREAD

**Issue by ajkis** [Hellowlol/HTPC-Manager#515]
Just wonder since its over two weeks of public PMS release with changed json for Plex integration. 
https://github.com/Hellowlol/HTPC-Manager/issues/511

The Hellowlol's htpc was most complete/functioning fork of HTPC i found so far, but if development is stopped then its plan to move on.

**Comment by Hellowlol** [comment]
I'm just lazy. Since this is out of beta I'll see if I can't fix it.
