### ISSUE TITLE
Plex Not Working: Unable to fetch currently playing information! Exception: '_children'

### ISSUE THREAD

**Issue by SlackMaster** [Hellowlol/HTPC-Manager#516]
**- [ ] Version** lastest version from Master 2 as of 12/26/2016
**- [ ] Branch** = Master2
**- [ ] Commit hash** = 868dfc0a5b6f912a0ab1a3e1cd565ea9085f08b2
**- [ ] Operating system** = Windows 10 / Mac Sierra
**- [ ] Python version** = 2.7

**- [ ] What happened?**
I had successfully installed HTPCManager on a Windows 10 NUC I had in my basement. I had it grabbing Plex info from another Mac mini I had running the latest version of Plex. Everything was running smoothly until about two weeks ago and I noticed it not grabbing the info anymore and giving the error in the title:

**- [ ] What you did?**
I did the usual, restarting of server and HTPC manager process and machine. Then I tried a fresh install of HTPCManager to the same Plex installation on the Mac. Then I tried HTPCManager running on another Mac I had, no luck. Then I tried both of the HTPC managers (windows and Mac) and tried connecting it to a different Plex installation running on a Mac, no luck. Then I tried a fresh install of Plex on a different Mac (tried both the plexpass and main version). No combination of any of these things worked, still always getting the error above.

Perhaps Plex made a change in a recent update?

Willing to try and test whatever you'd like me to test.

**- [ ] Pastebin**
[http://pastebin.com/kGznDfGP](http://pastebin.com/kGznDfGP)

**Comment by Hellowlol** [comment]
closing as this is a dupe. I hope to fix this some time after chrismas.

**Comment by SlackMaster** [comment]
I saw the 401 thread, but I didn't realize my issue was related. Thanks, have a good Christmas!
