### ISSUE TITLE
[Feature Request] Support for Kodi v17 (Krypton)

### ISSUE THREAD

**Issue by jpiscaer** [Hellowlol/HTPC-Manager#517]
I've moved my Raspberry Pi's running Kodi to LibreElec v8 preview (based on v17.0-beta7 codename Krypton), and after the upgrade I cannot control Kodi via the keyboard on the HTPC-Manager page. I used to be able to do so with older Kodi versions.

I'm guessing, since Kodi v17 uses a new (and vastly improved) website, work needs to be done to support the new remote control website. Is this something on the roadmap?

I'm running the newest HTPC-Manager commit (master2 branch, commit 7256761094919decea52c0a4e9fbb4826b625427).

**Comment by jpiscaer** [comment]
Nevermind; it works.

**Comment by Hellowlol** [comment]
Awesome. I'm still using kodi 15 so I wouldn't have noticed any breaking changes.
