### ISSUE TITLE
[Request] Torrent Search support for Cardigann/Jackett

### ISSUE THREAD

**Issue by dvdgorila** [Hellowlol/HTPC-Manager#518]
Hi, 

Would it be possible to add support for searching Cardigann/Jackett in the torrent search module? Adding this feature would allow searching multiple providers, similar to the nzb search module. 

Thanks!

**Comment by Hellowlol** [comment]
I had never heard about cardigann before. The torrent search needs a cleanup anyway,

**Comment by dvdgorila** [comment]
Its inspired by Jackett, more info here https://github.com/cardigann/cardigann . Anything that supports Torznab can use either to search multiple providers i.e. CouchPotato, sickrage, nzbhydra etc

**Comment by Hellowlol** [comment]
Can we get a json response or it just xml?

https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer

**Comment by dvdgorila** [comment]
Unfortunately i'm not a programmer so I couldn't tell you. Here is the search module nzbhydra uses https://github.com/theotherp/nzbhydra/blob/master/nzbhydra/searchmodules/jackett.py

**Comment by Hellowlol** [comment]
https://github.com/Hellowlol/HTPC-Manager/tree/cardigan I'll try to finish it today.

**Comment by dvdgorila** [comment]
Awesome! I'll test it once its ready.

**Comment by dvdgorila** [comment]
@Hellowlol have you made any progress on this?

**Comment by Hellowlol** [comment]
Not really, i have made some half asses work getting support for jackett as well but isnt ready yet. I have no eta.

**Comment by antdesca** [comment]
this feature would be great for me as well !

**Comment by dvdgorila** [comment]
@Hellowlol thanks for the update.

**Comment by Hellowlol** [comment]
Jackett is now supported.

**Comment by vampywiz17** [comment]
Hello there,

i try to add Jackett but not found it the left-side menu. How to add it?

**Comment by Hellowlol** [comment]
Its a part of torrents search

**Comment by goku-son** [comment]
@hellowlol I added jackett via settings—>torrents however where do I go to actually see jackett within HTPC Manager?
