### ISSUE TITLE
Plex 

### ISSUE THREAD

**Issue by fma965** [Hellowlol/HTPC-Manager#520]
Plex unable to connect, (PS good to see this project is still going, not sure you remember me or not)

- [x] Version
???

- [x] Branch
master2

- [x] Commit hash
4e2cd8477f3df01ef894801470cf7360c0e6fbe6

- [x] Operating system
UnRAID Docker
Linux-4.4.30-unRAID-x86_64-with

- [x] Python version
2.7.12 (default, Jun 29 2016, 08:57:23) [GCC 5.3.0]

- [x] What you did?
add plex server

- [x] What happened?
`2017-01-08 22:32:13	modules.plex	ERROR	Unable to contact Plex via http://192.168.1.3:32400 error No JSON object could be decoded`

- [x] What you expected?
Plex to work?

- [x] How can we reproduce your issue?
not sure, maybe by doing what i've done but i dunno.

- [x] What are your (relevant) settings?
nothing relevant really, non ssl, standard ip and port.

Plex web version 2.12.5, which i believe is PMS 1.3.3??

**Comment by fma965** [comment]
nevermind restarting pms and htpcmanger fixed it.

**Comment by Hellowlol** [comment]
Ofc i do. You where the tvheadend guy ^^. Nice to see you.

**Comment by fma965** [comment]
Haha, suprised you remember me :) any way yeah as you can see this solved it self haha, great to see this project is still active though :)

**Comment by Hellowlol** [comment]
I wouldn't call it active. I'd love to rewrite the entire thing but it works for me so it isn't worth the hassle.
