### ISSUE TITLE
Plex integration not working - Unable to contact Plex - error No JSON object could be decoded

### ISSUE THREAD

**Issue by ghost** [Hellowlol/HTPC-Manager#522]
### Reporting Issues:

Updater	Git
BRANCH	master2
Current commit	4e2cd8477f3df01ef894801470cf7360c0e6fbe6
Auto update	True
RUNDIR	/app/htpcmanager
DATADIR	/config
DB	/config/database.db
WEBDIR	/
AUTH	True
LOGLEVEL	debug
locale	UTF-8
ARGS	--datadir /config
OS	Linux-4.4.30-unRAID-x86_64-with
Python version:	2.7.12 (default, Jun 29 2016, 08:57:23) [GCC 5.3.0]

- [ ] What you did?
I run unRAID v 6.2.4
I run separate dockers for things like SABnzbd, Sonarr, Deluge, Sickrage, Couchpotato, Plex etc
All other dockers are working fine, and can communicate with each other
I installed HTPC in its own docker, and running the latest from linuxserver
Docker details below
htpcmanager
Container ID: eb5fc727943d
By: linuxserver/htpcmanager:latest

- [ ] What happened?
In HTPC manager I have configured SABnzbd, Couchpotato, Deluge, Sickrage and Sonarr, which are all working fine.
I then tried to set up Plex the same way, however it doesn't work. I get the below error:
Unable to contact Plex via http://192.168.2.195:32400 error No JSON object could be decoded

- [ ] What you expected?
I expected Plex to work just like all the other apps I have configured in HTPC manager
I have also tried with and without different Plex username and password combinations.

- [ ] How can we reproduce your issue?
Plex in a docker, configured with IP 192.168.2.195:32400
HTPC in a docker configured with IP 192.168.2.195:8097
Try and communicate between HTPC and Plex

- [ ] What are your (relevant) settings?
see above.

#### Link to log:
[htpcmanager-2.txt](https://github.com/Hellowlol/HTPC-Manager/files/696254/htpcmanager-2.txt)

**Comment by Hellowlol** [comment]
The link to the log return 404. Please fix it.

**Comment by derrickmehaffy** [comment]
I too am having this issue, which log are you looking for the one under userdata/htpcmanager.log

**Comment by derrickmehaffy** [comment]
Link to htpcmanager.log under userdata
http://pastebin.com/j5ePPhp5

Also attached file:

[htpcmanager.txt](https://github.com/Hellowlol/HTPC-Manager/files/697104/htpcmanager.txt)

**Comment by fma965** [comment]
@Hellowlol this is the issue i had last night or whenever it was, fixed it by restarting HTPC manager and plex after adding the server to htpc-manager, obviously its still an issue but just letting you know.

**Comment by ghost** [comment]
@Fma965 I have tried restarting Plex and HTPC manager many times, unfortunately it doesn't fix it

**Comment by ghost** [comment]
@Hellowlol sorry about that, I'm not sure why my log didn't attach properly.
uploaded to pastebin now.

http://pastebin.com/QSmie6x1

**Comment by ghost** [comment]
@Hellowlol also I'm running the latest Plex, version 1.3.3.3148

**Comment by fma965** [comment]
I also added my unraid server ip to the plex server settings under I belive
the network section, the allowed ip address section. Not sure this solves
it or not.

**Comment by fma965** [comment]
http://i.imgur.com/30CFQfs.jpg

No idea if this is needed or not but that an restarting were only thing I did on unraid 6.2.4

**Comment by ghost** [comment]
@Fma965 yeah I have already added my whole internal network (192.168.2.0/24) into "List of IP addresses and networks that are allowed without auth" and disabled secure connections in Plex settings. Unfortunately still no go.

**Comment by fma965** [comment]
Hmm well I'm not a dev for this, I've done a few contributions etc...  Just
suggesting the things I've done previously, just to confirm which unraid
plex docker are you using?

**Comment by ghost** [comment]
@Fma965 

On your unRAID, which Plex docker are you using?
I'm using the one from Linuxserver. 

Are you using 'Host' or 'Bridge' for your network?
I'm using 'Host' as 'Bridge' doesn't allow me to enable remote connections, as it doesn't recognise the IP address properly for some reason. I think that is a known issue. If I use 'Bridge' instead of getting 192.168.2.195 for my Plex IP, I get an IP address from the Docker internal network of 172.17.0.1, and Plex doesn't even function.

**Comment by fma965** [comment]
Im using Linuxserverio, my friend whos server I have completely configured for him is using plex by limetech both work fine with htpc manager, in fact my friends is literally a fresh plex install with ip whitefish and it works with htpc manager.

Can I get a screenshot of your plex server settings on htpc manager?  I'm sure it's all correct just curious. 

Sorry for lack of grammar etc using my phone

**Comment by fma965** [comment]
Just realised I never answered, yes I'm using host aswell as bridge is known as not working

**Comment by ghost** [comment]
<img width="483" alt="htpc plex settings" src="https://cloud.githubusercontent.com/assets/19606551/21831009/785dbcd4-d7ec-11e6-84b2-b14a35877719.png">

**Comment by ghost** [comment]
@Fma965 also as I stated above, I have tried with and without my Plex username and password.

**Comment by fma965** [comment]
Yeah as expected that's fine, if you test it I presume it just errors? Not sure what else to suggest to be honest

**Comment by ghost** [comment]
yeah just gives the same error over and over ..... one thing also is that when I use the 'Existing Server' dropdown box, instead of populating the IP with 192.168.2.195, it populates it with the what I think is the docker container IP address of 172.17.0.1. It shouldn't be an issue as I'm putting in my 192. address, but just noticed it.

Yeah I'm at a loss too as to what to do now .... I really appreciate you helping me though, thanks so much!

Hopefully Hellowlol can come up with something.

**Comment by fma965** [comment]
Good luck...  I'll look in to it tomorrow after work but it's 1am now and I should be asleep haha,  172 auto populate isn't an issue as mine does this to. Maybe try a second plex docker just as a test, if you set a different config path and don't run them both at same time it shouldn't conflict.

**Comment by ghost** [comment]
already did that, I tried the LimeTech docker, and it did the same thing.

Have a good sleep! :)

**Comment by fma965** [comment]
Have you pressed save and then restarted plex and then htpc manager after and then retested? That's the exact procedure I did but I don't think it will sort your issue.

**Comment by ghost** [comment]
yes, many many times haha

**Comment by ghost** [comment]
go to bed! :)

**Comment by fma965** [comment]
In that exact order....  OK I'm gone ;)

**Comment by Hellowlol** [comment]
I dont know why this isnt working for you. Ill post my my settings. Using brigde i had to manually enter the correct ip in the plex settings page. Click save then restart htpc manger

![image](https://cloud.githubusercontent.com/assets/1214134/21860421/c773f556-d830-11e6-89e9-87d540617cd4.png)

![image](https://cloud.githubusercontent.com/assets/1214134/21860445/e434cdc8-d830-11e6-9e38-2b68f3d0abdb.png)

**Comment by ghost** [comment]
fyi - i have just updated to the latest HTPC manager cb59c05ef3076cfe5d40034f44a6ee599c3f6551
and Plex integration is now working

**Comment by Hellowlol** [comment]
@blade316 thanks for the feedback.
