### ISSUE TITLE
Request: Support for Radarr

### ISSUE THREAD

**Issue by blackley** [Hellowlol/HTPC-Manager#523]
Please include support for Radarr.

Same as Sonarr tho this is for movies -)  https://github.com/Radarr/Radarr

I am guessing here, however, i would think that you could use the sonarr implementation as the template and that this should only require a little modification to the sonarr configuration to allow support for radarr

**Comment by fma965** [comment]
There is currently no documentation for the API for Radarr. i looked in to it briefly but it was too much effort without documentation.

if i did manage to get it working i would have sent a PR of course.

**Comment by mr-fionn** [comment]
Isnt the API same as Sonarr ? as its a fork off Sonarr and looks almost identical with a few name changes and over for movies insted..

**Comment by Hellowlol** [comment]
Im not gonna go digging in the source code to check what what the they guys might have changed. If somebody wants to do it and send a pr I'll accept it :P

**Comment by mr-fionn** [comment]
hehe. wasnt expecting that :P ..

**Comment by falling-fading** [comment]
I'm keen for Radarr integration too, but lack literally all the skills necessary to do it myself. 

The API page on the wiki seems to be updated regularly as the Radarr build progresses, so it might be worth keeping an eye on it: [https://github.com/Radarr/Radarr/wiki/API](url)

**Comment by ghost** [comment]
Please with sugar 1's and 0's on top!

**Comment by 313d44** [comment]
This would be excellent to have. Sonarr integration is top notch, this would be icing on the cake.

**Comment by ahiguero** [comment]
+1 please let me know if you need help testings.

**Comment by Kussie** [comment]
I had a brief look at this today and like Hellowlol there isn't enough documentation around the Radarr API that describes the changes.  In order to do it you would need to dig through the Radarr source code and play with the API manually to figure it out.  Which sadly i don't really have the time for either.

That being said it would be awesome to see this added, as i also recently made the switch from CouchPotato to Radarr

**Comment by Hellowlol** [comment]
Seems to be better now. https://github.com/Radarr/Radarr/wiki/API

**Comment by strikerjjb** [comment]
@Hellowlol This could be the next project for me. I recently setup radarr and it is running alongside couchpotato.  But also don't want to develop to many new things in the old BS 2.3.2 framework if we may venture away fro mit.

**Comment by desimaniac** [comment]
@strikerjjb Even a simple menu link to Radarr would be very helpful, at least to get things started.

**Comment by strikerjjb** [comment]
@desimaniac you could do that under the general settings with the other apps setting (i.e. below pic)
![image](https://cloud.githubusercontent.com/assets/10637609/23834040/e3970e48-0725-11e7-8301-732567722beb.png)

**Comment by Hellowlol** [comment]
@strikerjjb the old bootstrap is gonna be there for ever or until somebody updates it. I have tried in the past it was a pain. I have started playing around with sanic.

**Comment by desimaniac** [comment]
@strikerjjb Oh neat, thanks! 

 I installed HTPCManager for the first time today and did not notice that option at all.

**Comment by Hellowlol** [comment]
@desimaniac there is also a iframe option if you prefers to open things inside htpc manager

**Comment by desimaniac** [comment]
@Hellowlol Neat. That's convenient. I will check that out. 

Update: iframe works nicely!

**Comment by neil-bh** [comment]
+1 over here for Radarr integration.

I've recently switched from CP to Radarr, and have it working a treat on my HTPC.  I'm glad to see all the developers starting to pick up the dev work to support Radarr.

The postscripting script that I use [nzbToMedia](https://github.com/clinton-hall/nzbToMedia) has recently been upgraded to support Radarr too.  It seems the API is now sufficient for other developers to use.  The Radarr "develop" fork is rapidly updating, but it seems the [API](https://github.com/Radarr/Radarr/wiki/API) is fairly solid already.

@Hellowlol I think the API is in a good place now for you to use without having to spend time reverse engineering the Radarr code itself.

I look forward to the new HTPC Manager release :)

**Comment by augusteo** [comment]
Is anyone working on this at the moment?

If not I would like to take a crack at it :)

**Comment by Hellowlol** [comment]
Not that i know of. Go for it @augusteo

**Comment by augusteo** [comment]
ok cool, i'll take it up and submit a PR later. might take a while since i haven't used python in a while 😄 

@Hellowlol can you assign it to me on issues?

**Comment by ahiguero** [comment]
any news amigos?

**Comment by augusteo** [comment]
slowly progressing, got the settings page on, but still need to build the radarr page.

its mostly now copied from sonarr. so need to see what has changed and modify that.

**Comment by ahiguero** [comment]
all i can say is thnak you for your effort victor... keep it up

**Comment by wlsnchrs** [comment]
Second that! Appreciate you taking this on.

**Comment by BzowK** [comment]
+1 - Thanks!

**Comment by Hellowlol** [comment]
Radarr support has just been merged in. Thanks alot @zachnedwich
