### ISSUE TITLE
Bootstrap Switch height issue

### ISSUE THREAD

**Issue by marsderp** [Hellowlol/HTPC-Manager#524]
![image](https://cloud.githubusercontent.com/assets/1872386/21956940/607cf526-dac6-11e6-8d48-1d838637aefc.png)

On Firefox and Chrome, cache-refreshed. I've had this problem since forever.

**Comment by Hellowlol** [comment]
Is this only the moonlight theme or all of them?

**Comment by marsderp** [comment]
It's on every theme.

**Comment by Hellowlol** [comment]
Can I have the version number of chrome and firedfox your using? Does this happen on only this switch box or all of them?

**Comment by marsderp** [comment]
Currently Firefox 50, Chrome 55.

All the switches have the same issue unfortunately. Here's on twilight theme:

![image](https://cloud.githubusercontent.com/assets/1872386/21957359/754e113e-dacf-11e6-8e8f-757067d10202.png)

**Comment by marsderp** [comment]
After a little investigation, it seems like the width of `bootstrap-switch-container` set at 109px is causing my issue. Increasing it by 1px fixes it, alternatively `bootstrap-switch-label`'s width decreased by 1px fixes it too.

**Comment by Hellowlol** [comment]
What screen resolution do you use?

**Comment by marsderp** [comment]
1920x1080

**Comment by Hellowlol** [comment]
Ah, can you send a pr?

**Comment by marsderp** [comment]
Thing is I'm not sure where's the script that's setting this width. 

`default.js` only has `$("[type='checkbox']").bootstrapSwitch();`

**Comment by marsderp** [comment]
I believe I have found the real cause of this issue.

The `border-left` and `border-right` rules in `.bootstrap-switch .bootstrap-switch-label` in `xl.bootstrap.min.css` within all the theme files is set to 1px while the default bootstrap-switch's style does not. Removing the borders should not affect the visuals. 

How should we go about this?

**Comment by fma965** [comment]
Hi this happens to me at 4k when using Windows scaling are you using Windows scaling by any chance?

**Comment by Hellowlol** [comment]
@raysguy Dunno if you still using htpc manager, but we are still using your themes! Any chance you can take a look on this issue?
