### ISSUE TITLE
Malware?

### ISSUE THREAD

**Issue by stayupthetree** [Hellowlol/HTPC-Manager#525]
Something in HTPCManager is trying to access a questionable site. Malwarebytes blocks it, but it makes HTPCManager unusable 

Malwarebytes
www.malwarebytes.com

-Log Details-
Protection Event Date: 12/24/16
Protection Event Time: 1:49 PM
Logfile: 
Administrator: Yes

-Software Information-
Version: 
Components Version: 
Update Package Version: 
License: Premium

-System Information-
OS: Windows 10
CPU: x64
File System: NTFS
User: System

-Blocked Website Details-
Malicious Website: 1
, , Blocked, [-1], [-1],0.0.0

-Website Data-
Domain: imtdtaloqwcz.com
IP Address: 216.21.13.14
Port: [49993]
Type: Outbound

**Comment by Hellowlol** [comment]
Lol. The only questionable site it tries to access is the one you add your self. I assume other links and the modules opens as a iframe inside htpc manager?

**Comment by stayupthetree** [comment]
This is a fresh install. The only thing I've added is NZBGet, SickRage, Sabnzbd, Plex, Smart Info, and System Info

**Comment by stayupthetree** [comment]
Just went through one by one enabling. Whatever is using "System Info" is the culprit

**Comment by stayupthetree** [comment]
Worth noting, that it kicks in when I enable "Show System Info" on the Dashboard sidebar, as it is not enabled on the "System Info" sidebar yet

**Comment by Hellowlol** [comment]
Hm the only external call is to figure out your external up. And one to google dns to figure out the localip

**Comment by AzureDoom** [comment]
Malwarebytes user myself and no such issue with System Info, check your settings in Malwarebytes.
