### ISSUE TITLE
No Pictures after upgrading to Krypton

### ISSUE THREAD

**Issue by GTunney** [Hellowlol/HTPC-Manager#526]
### Reporting Issues:

To ensure that a I has enough information to work with please include all of the following information.

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**
- [ ] Version
4e2cd8477f3df01ef894801470cf7360c0e6fbe6

- [ ] Branch
master2

- [ ] Commit hash
4e2cd8477f3df01ef894801470cf7360c0e6fbe6

- [ ] Operating system
Linux-4.2.8-x86_64-with-glibc2.2.5

- [ ] Python version
	2.7.12 

- [ ] What you did?
Upgraded Kodi to Krypton

- [ ] What happened?
No images displaying from Kodi Movies, Music, Tv Shows or apps

- [ ] What you expected?
Pictures to be shown

Close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.

#### Link to log: http://pastebin.com/RwjxKsKv

**Comment by Hellowlol** [comment]
Can you see if the lastest update fixes it? Dunno if it works but it shouldnt raise a exception now. Im at work so i cant test if this works.

**Comment by GTunney** [comment]
Yup thats fixed it, cheers for the quick fix.
