### ISSUE TITLE
Transmission header link gives 409 error

### ISSUE THREAD

**Issue by efalder413** [Hellowlol/HTPC-Manager#527]
### Reporting Issues:

To ensure that a I has enough information to work with please include all of the following information.

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**
- [ ] Version: installed from `git clone`

- [ ] Branch: master2

- [ ] Commit hash: 4e2cd8477f3df01ef894801470cf7360c0e6fbe6 

- [ ] Operating system: Raspbian: Linux-4.4.21-v7+-armv7l-with-debian-8.0

- [ ] Python version: 2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]

- [ ] What you did?: Connected transmission, then followed link in header

- [ ] What happened?: Link went to 192.168.0.10:9091/transmission/**rpc** and resulted in a 409 conflict error

- [ ] What you expected?: Expected link to go to 192.168.0.10:9091/transmission/**web** and open interface

- [ ] How can we reproduce your issue?: Connect transmission to HTPC, then follow link in header to Transmission web interface. Resulting page should display "409: Conflict Your request had an invalid session-id header."instead of intended interface

- [ ] What are your (relevant) settings? 
![screenshot](https://cloud.githubusercontent.com/assets/6841035/21996667/38fcc06a-dbe0-11e6-8a4e-873f737c966f.png)

- [ ] Log file: No relevant errors displayed in either HTPC or Transmission logs.

**Comment by efalder413** [comment]
confirmed fixed on my end too, tyvm!

**Comment by Hellowlol** [comment]
you welcome.

**Comment by efalder413** [comment]
Actually, I'm still receiving the 409 error. Manually entering the URL (
http://192.168.0.10:9091/transmission/web) into a new tab still results in
the error. Manually entering the URL without the directories (
http://192.168.0.10:9091) redirects to the previous URL and opens the
interface normally. I believe this may be an error in Transmission, and
I'll report it to them as well, but thought I'd update here in case others
are having the same issue.

**Comment by desimaniac** [comment]
@efalder413 It needs the slash '/' after "web" in the url. I created an issue for this a bit ago.

**Comment by efalder413** [comment]
Duplicate of #543
