### ISSUE TITLE
Dash: bugs / improvements / discussion

### ISSUE THREAD

**Issue by kooimens** [Hellowlol/HTPC-Manager#53]
Right now, on the top row of my dash I have got plex latest movies, tv and music. These three are correctly shown in one row, like this: (1680x1050)
![3](https://cloud.githubusercontent.com/assets/3150962/6422843/ca3189b6-bedd-11e4-90b0-85d1490c2848.jpg)

However, my next aired (sickrage), wanted movies, latest downloads (sab) and wanted albums are shown in this way: (1680x1050)
![1](https://cloud.githubusercontent.com/assets/3150962/6422856/f9bbd204-bedd-11e4-8100-ae9aea4dec94.jpg)

Without latest downloads, it looks even worse: (1680x1050)
![2](https://cloud.githubusercontent.com/assets/3150962/6422858/0256c40a-bede-11e4-81bc-d62e9b904a70.jpg)

There is too many white om my dash right now:D. I know that it's on your mind to improve/rebuild the dash and I don't know you should fix this before rebuilding/rethinking the dash. That's up to you;). Maybe, we can start a discussion here to see how other people think about this topic and try to come up with some suggestions together. 

One of the things I would like to see in a new build of the dash is a drag and drop functionality to determine your own custom sequence of each tab on your dash (I think you already mentioned this somewhere).

**Comment by Hellowlol** [comment]
I agree. It doesnt feel unified at all. My goal if to have a drop and drag where the user chooses the location and it gets saved to the db.

**Comment by wmariz** [comment]
I think this could be closed.

**Comment by Hellowlol** [comment]
Yep
