### ISSUE TITLE
Multiple newznab server support

### ISSUE THREAD

**Issue by kooimens** [Hellowlol/HTPC-Manager#54]
Would be great to have an option to add multiple newznab servers for searching NZB's. (Better to have it here, instead of in the dead repo;)

**Comment by Hellowlol** [comment]
I like the idea, but i already have a lot of stuff on my plate. So if anybody is up for the task i id welcome  a pr.

**Comment by raysguy** [comment]
Very excited for this feature.  Will OMGWTFNZB be supported?  I notice on most services it's a separate section to the regular newznab providers so wasn't sure if this is something you were planning to add.

When it's complete would it be possible to add a simple API + key to allow search in HTPC to be used by other clients?  At the moment I use NZBmegasearcH which lets you add multiple newznab accounts and provides an api key you can provide in apps like Sonarr/CP/SickRage to basically use it as a sole newznab provider.  Most apps require you to use an API key instead of a username/password so at the moment it's not possible to add HTPC.  It'd be great to be able to ditch megasearch as HTPC actually has all search categories and is a much better UI.

**Comment by Hellowlol** [comment]
checkout the kodi servers settings tab, it's gonna be like that. It will only support newznab api. I'll add a new dropdown to the seach page where you can choose what provider to use or search on all.

**Comment by Hellowlol** [comment]
@raysguy OMGWTFNZB will not be supported as the api access is for vips only and the response isnt the same :)

**Comment by raysguy** [comment]
Ah I see, that explains why it always appears in its own section.  I've got VIP accounts with loads of newsnab sites though so I'm sure there'll be plenty of search results for me when multiple providers are possible. :)

**Comment by Hellowlol** [comment]
@kooimens @raysguy Does nzbsearch work with dognzb via htpc manager for you guys?

**Comment by thatbritguy** [comment]
Works intermittently for me, but all newznab providers act like that on HTPC Manager.  Seems that if I enter a search term I've previously used then no search results are returned.  When it fails this is the error in the logs:

"Unable to fetch information from: http://api.dognzb.cr/api?o=json&apikey=********************************&t=search&q=Testing&extended=1 ('The read operation timed out',)"

**Comment by Hellowlol** [comment]
Ok, I'll do some digging

**Comment by Hellowlol** [comment]
@raysguy  Ok, im not gonna bother with anything related to dognzb until there are api is fixed. I can search over and over on the same item using usenet-crawler (the only other i have.) Can you test with a different indexer then dognzb?

**Comment by thatbritguy** [comment]
Okay, I use a number of indexers and have been through to check them all.  The only one which works consistently for me is nzb.su.  Of the others althub and nzbgeek exhibit the same behaviour as dognzb, working only intermittently with the logs showing a timeout error.  PFMonkey is the same but there's no error in the logs - it shows the search happened as though there was no issue.  Oznzb fails completely with logs showing Error 61 - connection refused.

**Comment by thatbritguy** [comment]
Also the newznab search link in the nav bar is still not working, not sure if it's supposed to be yet though.

**Comment by Hellowlol** [comment]
Thanks! I'll see if I can sign up on the others to test. Oznzb is got supported as the have a own api. Yeah, the menu link is not suppose to work yet :)

**Comment by thatbritguy** [comment]
Hahaha yeah I signed up to a lot just to ensure coverage.  Probably a little bit of overkill though!  Didn't realise oznzb has a different api - I know on other apps I just insert the details the same as any other newznab provider.  Only one I have which is non-standard is omgwtfnzb so I know that wouldn't work.

**Comment by Hellowlol** [comment]
Ah shit I thought of omgwft when I wrote oznzb

**Comment by Hellowlol** [comment]
@raysguy Where the fuck do you find the apikey to nzbgeek? I have been looking for ages..

**Comment by Hellowlol** [comment]
Edit found nzbgeek apikey. Had to throw some $ at them to get it...

**Comment by Hellowlol** [comment]
- [x] Add/delete/edit indexer
- [x] add search url entry in the db, used to clean the url in setindexer
- [x] rename files
- [x] menu link
- [x] spinner
- [x] html add indexer dropdown
- [x] add search on all
- [x] use requests-futures, add failback from json to xml?
- [ ] add derefer to external links
- [x] search result should be sortable.
- [x] fix image in modal tvrage api http://services.tvrage.com/feeds/full_show_info.php?sid=2930

**Comment by Hellowlol** [comment]
Im gonna try to finish this today, as there will be a couple of weeks until i got time to do some work on htpc manager again. Thanks for the patience, i had forgot about this request.

**Comment by Hellowlol** [comment]
This module will support adding new indexers inside the nebwnab settings page. 
In menu link works now, you can choose what indexer you want to search on and defaults to all indexers. 

Each search is async to each provider. You can see what provider yielded what result and the table should be sortable.

**Comment by Hellowlol** [comment]
@kooimens @raysguy Can you try this branch? https://github.com/Hellowlol/HTPC-Manager/tree/impnewznab and let me know if you find any bugs?

The branch isn't done, but it should be usable

**Comment by thatbritguy** [comment]
Looking good!  Great implementation. Not found any major bugs.  Only minor issue is when searching direct from navbar search form it takes you to newznab search page with search term pre-populated but doesn't automatically search.

**Comment by Hellowlol** [comment]
Thanks for reporting this I'll look into it. Any more issues regarding search on the same thing?

**Comment by thatbritguy** [comment]
I notice in the results that the age of each result is correct for all providers except dognzb which says "N/A".  Is that a peculiarity of their api?  Also the results are listed in blocks of one provider then the next.  Would it be possible to have them listed by age regardless of provider?

Should the spinner show when it is searching?  I see it's ticked off in the list above but I don't see it when searching.

**Comment by Hellowlol** [comment]
Yes it's because of the api. Sorting don't work but I'll fix that. The check was related to the spinner showing regardless if you searched on something or not. I'll fix that too

**Comment by Hellowlol** [comment]
Merged, let me know if there are any bugs. @raysguy I couldnt reproduce your issue regarding nav-search, so if this problem persist please make a proper bug report :)
