### ISSUE TITLE
No Plex Metadata Pulling

### ISSUE THREAD

**Issue by AzureDoom** [Hellowlol/HTPC-Manager#541]
- Version
Latest

- Branch
master2

- Commit hash
7200d387d2c2d4f67de391d86dd105ab9b03bfad

- Operating system
Latest Windows 7 SP1 for Plex and HTPC Manager servers.

- Python version
2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]

- What you did?
Have HTPC manager running another computer and linked to my plex server on another network.

- What happened?
No metadata is appearing in HTPC Manager from my plex server.

- What you expected?
Needed Metadata from Plex to show up.

- How can we reproduce your issue?
Have HTPC manager running another computer and linked to my plex server on another network.

- What are your (relevant) settings?
Added admin user and Plex/Sonarr info. Plex passes settings test button.

#### Link to log:
http://pastebin.com/YP1CQ9Mi

**Comment by AzureDoom** [comment]
Never mind, I'm an idiot and forget to reinstall the Python Image Library

**Comment by Hellowlol** [comment]
:D
