### ISSUE TITLE
Issue with HDD/Filesystem System Info Whitelist

### ISSUE THREAD

**Issue by Kussie** [Hellowlol/HTPC-Manager#542]
Blacklisting drives and file systems in the System Info module works fine.  But when you enable it as a white list, it no longer works correctly and the drives module on the dashboard just returns "null"

**Comment by Hellowlol** [comment]
does the one in the psutil module work?

**Comment by Kussie** [comment]
I haven't actually tested with that one yet.  Will give it a spin when i am home later again.   


For the moment i have working around my issue by blacklisting everything i don't want to show, instead of whitelisting only those i do want to show.

**Comment by Hellowlol** [comment]
Ok. Remember that whitelist will require you to enter both the path and the filesystem type.

**Comment by Kussie** [comment]
Ahhhh i remember that now from my previous install.  Which is what i forgot to do.  I might look at doing a PR that makes this requirement a little more clear inside the interface :)
