### ISSUE TITLE
Menu link to Transmission not valid; needs to have a forward slash at the end. 

### ISSUE THREAD

**Issue by desimaniac** [Hellowlol/HTPC-Manager#543]
### Reporting Issues:

The menu link to Transmission is going to `http://192.168.1.159:9091/transmission/web` instead of `http://192.168.1.159:9091/transmission/web/` which is causing it to not load. Basically, it just needs a forward slash at the end to fix the problem. 

- Version: Latest
- Commit hash: `2a81339b21f97c51de706fb571111f3ce2c188ed`
- Branch: master2
- Operating system: Linux-4.4.43-boot2docker-x86_64-with
- Python version: 2.7.13

**Comment by Hellowlol** [comment]
Seems to depend on transmission version.

**Comment by desimaniac** [comment]
I am using the latest version. Also maybe pertinent is that it's running in a docker on my macOS.

![image](https://cloud.githubusercontent.com/assets/5501908/24813125/79b00904-1b92-11e7-85cc-0381b2de05bb.png)


The error I get when I try without the last slash. 

![image](https://cloud.githubusercontent.com/assets/5501908/24813080/4915c720-1b92-11e7-8276-9e798dc9e142.png)

Can you simply add a slash at the end of the transmission url in your code?
