### ISSUE TITLE
Wiki edit: Synology Install

### ISSUE THREAD

**Issue by desimaniac** [Hellowlol/HTPC-Manager#546]
I edited the Wiki to add instructions to installing on Synology. Hope that was OK to do.

**Comment by Hellowlol** [comment]
Feel free to any changes to wiki. Thanks for helping out! :)

**Comment by desimaniac** [comment]
My pleasure!

 I had tested this setup on docker but wanted a native setup to show my "PC stats" for the Synology NAS vs the Docker VM. 

I will keep an eye out for any further issues. If any permission issues arise (which occurs for Sonarr/Radarr installs), I will post a fix for that as well.

**Comment by jimmykl** [comment]
Thank you so much for the Synology guide @desimaniac ! The first step had stopped me trying the package a while back, now I can enjoy the awesomeness 👍

**Comment by desimaniac** [comment]
You're welcome! 

---

Apparently a lot of those Synocommunity packages require their own username or else the install will fail. You have to find that into the source code for the package since there are no instructions with them.
