### ISSUE TITLE
[REQUEST] Option to have top bar category "Others" not as dropdown but each item as own menu entry like the Plugins

### ISSUE THREAD

**Issue by v1rusnl** [Hellowlol/HTPC-Manager#548]
As the title says, i currently have 2 custom URLs in HTPC Manager. Currently the two links are shown as a dropdown menu in the topbar.

It would be really nice to have an own top menu entry for each item (perhaps optionally) instead of the Entry "Others" with the dropdown menu showing the custom links.

**Comment by jeremysherriff** [comment]
+1 This would be a useful feature.

Implementation could be done via a tick-box per line-item on the Settings/Other Apps page to indicate which apps to include in the main bar (versus which to leave in the Other menu). This tick-box should then help provide the logic for including these lines in the code for the loop that draw the menus.

**Comment by falling-fading** [comment]
I quickly threw this together - Just added a few extra modules for the custom links. I'm 100% sure that there's a better way to do it - But I can't code, and as far as I can tell it does the job. The "navbarlink*.py" files into the "modules" folder.

Screenshot: https://imgur.com/IWKwAaf
Gist: https://gist.github.com/falling-fading/222f1deaa7bf6b814470290a529ca14e
