### ISSUE TITLE
Couchpotato improvements

### ISSUE THREAD

**Issue by kooimens** [Hellowlol/HTPC-Manager#55]
One of the things I'm really missing atm is the option to manually downloads nzb's found by couch before ETA. See here, 2 available releases for Samba:
![2](https://cloud.githubusercontent.com/assets/3150962/6423641/5e5fcb1a-bee9-11e4-85dd-d265f04e21a0.jpg)
![1](https://cloud.githubusercontent.com/assets/3150962/6423693/2b0993a8-beea-11e4-9c24-8b9e304adb9e.jpg)

A tab with `Snatched & Available` would be great, where the user can pick a NZB itself. 

Furthermore, a tab with `Available soon` will be great as well.

A suggestions and charts tab would be really awesome:D

**Comment by Hellowlol** [comment]
There is a option to manually select what release to pick in the modal, but im not sure if movies before eta shows up there. Have you checked?

**Comment by kooimens** [comment]
You mean within the couchpotato module in HTPC? I can't find a manual nzb option at all there...

**Comment by Hellowlol** [comment]
![image](https://cloud.githubusercontent.com/assets/1214134/6423929/8fcb6344-beee-11e4-8cfd-d734ec04d476.png)

**Comment by Hellowlol** [comment]
press the release button in the modal and you get that list up

**Comment by Hellowlol** [comment]
There was a or for a suggestion tab to htpc manager from another person but it didn't get merged, then the api broke

**Comment by Hellowlol** [comment]
@kooimens did you find any releases?

**Comment by kooimens** [comment]
Yes, I can also download movies before ETA on my wanted list! Thanks.

**Comment by Hellowlol** [comment]
added suggestions and charts

**Comment by Hellowlol** [comment]
Ah crap, i noticed you asked for dashboard soon aswell. Oh well some other time.

**Comment by kooimens** [comment]
Wow! This is really awesome, many thanks. 

I have found two small bugs after some testing: 
1. I can remove `ignore` movies from the suggestions/charts tab, but it returns an error. When I refresh the page, it actually removed it from the list.
![1](https://cloud.githubusercontent.com/assets/3150962/6584106/321148d0-c769-11e4-9dc2-4c97c6855ee2.jpg)

2. The button `seen it` isn't doing anything.

**Comment by Hellowlol** [comment]
Yeah, i noticed... it got a little late last night :P fix inc

**Comment by Hellowlol** [comment]
Should be fixed

**Comment by kooimens** [comment]
Nice! One more thing. Is it possible to show on the wanted movies on dashboard (for example with an orange exclamation mark in combination with a mouseover text) that a movie is wanted and snatched (not auto download). This happens many times if a movie is found before ETA. When doing it this way a can easily notify a movie that's snatched and available, but need some further investigation.

**Comment by Hellowlol** [comment]
Please make a separate issue regarding that, but not gonna touch the dash rewritten. And i have forgotten long before that :P
