### ISSUE TITLE
Not so much a programme issue

### ISSUE THREAD

**Issue by Dhop84** [Hellowlol/HTPC-Manager#550]
Hi, forgive me but I have no idea about github so I don't have a clue where to put this but I've tried installing on Windows 10 and all was good until I started htpc manager after installing the Nssm I then tried to start htpc through "my computer, manage and services" and I got a error 2 "cant find file" now I'm sure this is because I've messed up somewhere so I just want to no from someone experienced what is it that I've likely Done wrong? Do I have to copy out the Nssm Argument exactly as it's put on the instructions? And put htpc.py --daemon?

**Comment by Hellowlol** [comment]
the arguments need to be the fullpath to htpc.py you can drop -daemon sinne it does nothing on windows
