### ISSUE TITLE
Noob Questions:  AUTH

### ISSUE THREAD

**Issue by seanvree** [Hellowlol/HTPC-Manager#554]
Is it possible to have two separate dashboard interfaces:  one with "read only / Guest" (I.e. can't access the menu options dashboard with no AUTH required), then ALSO have a dashboard with admin for editing the dashboard?

THANKS!

Great work!

**Comment by Hellowlol** [comment]
Nope this isnt possible. But you can add a restricted user that has access to the dashboard / modules but cant add/change anything. and just share the username/password. like a test account or something

**Comment by seanvree** [comment]
@Hellowlol  - Got it! Thanks.  Any plans to add something like this?  no biggie if not.

**Comment by Hellowlol** [comment]
I have to interest in that type feature but if you want to add support for that you can remove the '''@require()''' decorator from index inside root.py and from the the ajax calls used in dash.js

**Comment by seanvree** [comment]
@Hellowlol  - A bit confused.  Would I change that code after I add the restricted user?

Also, how do i disable authentication completely?
