### ISSUE TITLE
Sabnzbd Pause/Start Individual Files and Pause Sabnzbd for X amount of minutes

### ISSUE THREAD

**Issue by austinbarberrepo** [Hellowlol/HTPC-Manager#558]
### Reporting Issues:

To ensure that a I has enough information to work with please include all of the following information.

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**
- [ ] Version - Could not locate version, but have installed using GIT and said that I was up to date when typing this out.

- [ ] Branch - Master

- [ ] Commit hash - c0ed30551f183437753773e317cacf7c00750f6c

- [ ] Operating system - Win 10

- [ ] Python version - 2.7.13

This is more of a question, than a issue. On the Sabnzbd page within HTPC Manager, is there a way to pause for X amount of minutes/hours? The other question I have is, if I pause individual files with Sabnzbd, I could not find a way to start them within HTPC Manager. I'm possibly just doing something wrong on my side as I have just completed setting everything up. It could be something simple that I am over looking. I glanced over the open and closed issues but couldn't find one related to my question. Let me know if you need any extra information from me or anything else to help out. Thanks!

**Comment by Hellowlol** [comment]
There is a way to pause for x minutes. Enter value in the time input and press the pause button. As for pausing single files i dont thats supported. I never does that. I simple drag and drop to reorder the queue.
