### ISSUE TITLE
500 Internal Server Error, when clicking on Settings

### ISSUE THREAD

**Issue by Thunderlight1** [Hellowlol/HTPC-Manager#559]
### Reporting Issues:

To ensure that a I has enough information to work with please include all of the following information.

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**
- [ ] Version

- [ ] Branch
master2

- [ ] Commit hash
c0ed30551f183437753773e317cacf7c00750f6c

- [ ] Operating system
Linux-4.4.0-87-generic-x86_64-with-Ubuntu-16.04-xenial

- [ ] Python version
2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

- [ ] What you did?
Clicked on Settings to try to configure HTPC Manager.

- [ ] What happened?
Got the following error on the browser:
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

- [ ] What you expected?
Get to the configuration page.

- [ ] How can we reproduce your issue?
Not really sure how to reproduce it.

- [ ] What are your (relevant) settings?
Following options are configured: CouchPotato, Deluge, Torrents, Plex, Sickrage and headphones.

- [ ] Include a link to your **FULL** (not just a few lines!) log file that has the error. Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).

Close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.

#### Link to log: https://pastebin.com/zrP2r9jD

**Comment by Hellowlol** [comment]
The db has a duplicate value of deluge ssl. Delete that or delete the db and set it up again.
