### ISSUE TITLE
Themes bugs

### ISSUE THREAD

**Issue by Hellowlol** [Hellowlol/HTPC-Manager#56]
Flatly

- [ ] --

**Comment by raysguy** [comment]
Spacelab - pages do not load any css styling with this theme selected.  Page is unformatted, unreadable and unusable when that theme is selected.

**Comment by raysguy** [comment]
Excellent, just tested and this is fixed in later revision.  Thanks :)

**Comment by Hellowlol** [comment]
Closing this as its related to old themes
