### ISSUE TITLE
Plex Hide watched Option does not work

### ISSUE THREAD

**Issue by ahiguero** [Hellowlol/HTPC-Manager#563]
### Reporting Issues:

To ensure that a I has enough information to work with please include all of the following information.

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**
- [ ] Version
????

- [ ] Branch
master 2

- [ ] Commit hash

c300bf33db3fd4c15650b853727083c01144fe2e

- [ ] Operating system
Docker container

- [ ] Python version
2.7.13

- [ ] What you did?
hide watch on plex server option

- [ ] What happened?
still shows the watched items on my library

- [ ] What you expected?
to hide the items that i have already watched.

- [ ] How can we reproduce your issue?

- [ ] What are your (relevant) settings?

- [ ] Include a link to your **FULL** (not just a few lines!) log file that has the error. Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).

Close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.

#### Link to log:

**Comment by Hellowlol** [comment]
Thanks!

**Comment by jeremysherriff** [comment]
Can be closed now.

**Comment by jeremysherriff** [comment]
@ahiguero can you close this?
