### ISSUE TITLE
What theme is used on the screenshots?

### ISSUE THREAD

**Issue by joq3** [Hellowlol/HTPC-Manager#568]
Hi,

I can't find which theme gives me this look in HTPC Manager:
https://camo.githubusercontent.com/45156447898bcba8252d13f8fd406b56238e4fa0/687474703a2f2f692e696d6775722e636f6d2f365145575046662e706e67

Went through them all, none looked like that, with the colors and the top bar being "3d-look".

How do I make it look like that?

Is it possible to change the HTPC logo in the top bar without it being replaced in updates?

**Comment by Hellowlol** [comment]
i think that one of the old themes. it has been removed i just havnt updated the images. I think it was this one: https://bootswatch.com/2/slate/

**Comment by joq3** [comment]
Okey, would it be possible to bring it back? I really like the look of it, the progressbars etc looks very good.

**Comment by Hellowlol** [comment]
Not, unless someone makes a PR.

**Comment by joq3** [comment]
What does that mean?

**Comment by Hellowlol** [comment]
Oh, i'm sorry. That means that i'm not willing to do this, but if ill merge a pull request (where somebody has added this the old theme back)
