### ISSUE TITLE
Plexpy not displaying any data

### ISSUE THREAD

**Issue by Kazz3r24** [Hellowlol/HTPC-Manager#576]
### Reporting Issues:

To ensure that a I has enough information to work with please include all of the following information.

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**
- [4b41640c74e14dcdf77e6e0ea0ecc180bfa4e120] Version

- [master2] Branch

- [eda521c1c814cd536961206b41fb201b] Commit hash

- [Linux-4.13.0-32-generic-x86_64-with-Ubuntu-16.04-xenial] Operating system

- [2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609]] Python version

- [Installed as per the wiki] What you did?

- [Everything installed correctly, Plexpy tests ok in settings, but I'm seeing errors in the logs when I try to open the module and no information is displayed] What happened?

- [To see some data return in the module, not sure what it looks like yet.] What you expected?

- [Currently using Tautulli beta branch locally] How can we reproduce your issue?

- [SSL enabled, Tautulli from beta branch, tests OK in settings] What are your (relevant) settings?

- [https://gist.github.com/Kazz3r24/4b02d3017f015e2923b52658fed1d47f] Include a link to your **FULL** (not just a few lines!) log file that has the error. Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).

Close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.

#### Link to log: https://gist.github.com/Kazz3r24/4b02d3017f015e2923b52658fed1d47f

**Comment by Kazz3r24** [comment]
*UPDATE*
A specific error code I've been failing to look up the cause of is 
`cherrypy.error.139761942786128`

**Comment by Hellowlol** [comment]
I think this was caused by a ssl error as requests tries to verify the ssl cert. Anyway i have disabled that now and fixed a typo in the exception handling. Can you update and try again?

**Comment by Kazz3r24** [comment]
Thanks for the swift response, I'll update now and let you know!

**Comment by Kazz3r24** [comment]
Swift and efficient! That worked perfectly thanks very much! If you ever need someone to "beta test", I'd be happy to help out. This project has allowed me to go from having 20 tabs open (slight exaggeration) to a single tab, amazing work! Closing the ticket!

**Comment by samcro1967** [comment]
I am seeing a similar issue on Windows 10.

[Do not see a line for this in the about tab] Version

[master2] Branch

[2f3e2f0fbec46a039e17628bee267cd8602dc2d8] Commit hash

[Windows 10] Operating system

[2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]] Python version

[Installed as per the wiki] What you did?

[Everything installed correctly, Plexpy tests ok in settings, but I'm seeing errors in the logs when I try to open the module and no information is displayed] What happened?

[To see some data return in the module, not sure what it looks like yet.] What you expected?

[Using Tautulli master branch] How can we reproduce your issue?

[SSL disabled, Tautulli from master branch, tests OK in settings] What are your (relevant) settings?

https://gist.github.com/osuhickeys/8cae151288fdb98e434d3733170cf4a9

**Comment by Hellowlol** [comment]
The log says it fails to get the data from the url. What happens if you copy that url into your browser?

**Comment by samcro1967** [comment]
http://192.168.1.105:8181/tautulli/history works fine in a browser.

This link with the correct API key in it just spins.....

http://192.168.1.105:8181/Tautulli/api/v2?apikey=********************************&cmd=get_history&json_data=%7B%22draw%22%3A1%2C%22columns%22%3A%5B%7B%22data%22%3A%22date%22%2C%22name%22%3A%22%22%2C%22searchable%22%3A%22false%22%2C%22orderable%22%3Atrue%2C%22search%22%3A%7B%22value%22%3A%22%22%2C%22regex%22%3Afalse%7D%7D%2C%7B%22data%22%3A%22friendly_name%22%2C%22name%22%3A%22%22%2C%22searchable%22%3Atrue%2C%22orderable%22%3Atrue%2C%22search%22%3A%7B%22value%22%3A%22%22%2C%22regex%22%3Afalse%7D%7D%2C%7B%22data%22%3A%22ip_address%22%2C%22name%22%3A%22%22%2C%22searchable%22%3Atrue%2C%22orderable%22%3Atrue%2C%22search%22%3A%7B%22value%22%3A%22%22%2C%22regex%22%3Afalse%7D%7D%2C%7B%22data%22%3A%22platform%22%2C%22name%22%3A%22%22%2C%22searchable%22%3Atrue%2C%22orderable%22%3Atrue%2C%22search%22%3A%7B%22value%22%3A%22%22%2C%22regex%22%3Afalse%7D%7D%2C%7B%22data%22%3A%22player%22%2C%22name%22%3A%22%22%2C%22searchable%22%3Atrue%2C%22orderable%22%3Atrue%2C%22search%22%3A%7B%22value%22%3A%22%22%2C%22regex%22%3Afalse%7D%7D%2C%7B%22data%22%3A%22full_title%22%2C%22name%22%3A%22%22%2C%22searchable%22%3Atrue%2C%22orderable%22%3Atrue%2C%22search%22%3A%7B%22value%22%3A%22%22%2C%22regex%22%3Afalse%7D%7D%2C%7B%22data%22%3A%22started%22%2C%22name%22%3A%22%22%2C%22searchable%22%3Afalse%2C%22orderable%22%3Atrue%2C%22search%22%3A%7B%22value%22%3A%22%22%2C%22regex%22%3Afalse%7D%7D%2C%7B%22data%22%3A%22paused_counter%22%2C%22name%22%3A%22%22%2C%22searchable%22%3Afalse%2C%22orderable%22%3Atrue%2C%22search%22%3A%7B%22value%22%3A%22%22%2C%22regex%22%3Afalse%7D%7D%2C%7B%22data%22%3A%22stopped%22%2C%22name%22%3A%22%22%2C%22searchable%22%3Afalse%2C%22orderable%22%3Atrue%2C%22search%22%3A%7B%22value%22%3A%22%22%2C%22regex%22%3Afalse%7D%7D%2C%7B%22data%22%3A%22duration%22%2C%22name%22%3A%22%22%2C%22searchable%22%3Afalse%2C%22orderable%22%3Atrue%2C%22search%22%3A%7B%22value%22%3A%22%22%2C%22regex%22%3Afalse%7D%7D%5D%2C%22order%22%3A%5B%7B%22column%22%3A0%2C%22dir%22%3A%22desc%22%7D%5D%2C%22start%22%3A0%2C%22length%22%3A25%2C%22search%22%3A%7B%22value%22%3A%22%22%2C%22regex%22%3Afalse%7D%7D&grouping=false

**Comment by Hellowlol** [comment]
I was referring to the api call that hype manager uses to contact plexpy. Dunno if it matters but I notice you using a large T in tautulli in htpc manger and the link you said works using a small t

**Comment by samcro1967** [comment]
Ah.  http://192.168.1.105:8181/tautulli works just fine.
I changed basepath from "/Tautulli" to "/tautulli" and the history tab is working now.

Thanks.  Appreciate your work.  This is a great product.  You have brought it a long way with this fork.
