### ISSUE TITLE
Feature Request: Display more stream information in PlexPy

### ISSUE THREAD

**Issue by Kazz3r24** [Hellowlol/HTPC-Manager#577]
### Reporting Issues:

To ensure that a I has enough information to work with please include all of the following information.

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**
- [2f3e2f0fbec46a039e17628bee267cd8602dc2d8] Version

- [master2] Branch

- [823791748e5073c1fc19ad42cab55c1f] Commit hash

- [Linux-4.13.0-32-generic-x86_64-with-Ubuntu-16.04-xenial] Operating system

- [2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609]] Python version

- [This is just a feature request, no issue. Is it at all possible to add more stream information? I'll post a screen shot link below for context] What you did?

- [Everything's working great] What happened?

- [Nothing short of what I got, I apologize if I didn't post this feature request properly] What you expected?

- [configure PlexPy module] How can we reproduce your issue?

- [Not applicable] What are your (relevant) settings?

- [] Include a link to your **FULL** (not just a few lines!) log file that has the error. Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).

Close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.
![capture](https://user-images.githubusercontent.com/15070472/36909103-22211a1c-1e0b-11e8-93f1-68001a72b1ea.PNG)

#### Link to log: https://imgur.com/Z9Ca9v1

**Comment by jeremysherriff** [comment]
I'll have a hack at this. Fair warning: my coding is pretty poor, I'm an infrastructure engineer :)

**Comment by jeremysherriff** [comment]
How's this look:
![image](https://user-images.githubusercontent.com/1082213/38168861-44856996-35ad-11e8-9d23-18f2e647f35a.png)

**Comment by Kazz3r24** [comment]
That looks perfect, exactly what I was looking for!

**Comment by jeremysherriff** [comment]
Sweet. Just cleaning up a couple of bits and I'll send a pull request to
Hellowlol

**Comment by jeremysherriff** [comment]
Just realised I didn't include the subtitles line.  I've already submitted the pull request.
But looking at the layout there isn't actually space for the subtitles info..

I'm reasonably confident there'll be at least one bug so assuming that I'll be doing an edit on this soon, I'll collapse the top two lines together and add subtitle info then.

**Comment by jeremysherriff** [comment]
Just submitted a PR with a few bugfixes. @Kazz3r24 can you close this issue if you're happy with it?

**Comment by jeremysherriff** [comment]
![image](https://user-images.githubusercontent.com/1082213/38299644-be7692cc-384e-11e8-860d-403185229d9c.png)
![image](https://user-images.githubusercontent.com/1082213/38299670-d27b7666-384e-11e8-85fb-dc1592215368.png)

**Comment by Kazz3r24** [comment]
It looks pretty much perfect! Exactly what I was looking for. My only issue I'm having, and I'm not sure if it's on my end or where. 

![image](https://user-images.githubusercontent.com/15070472/38437663-316b94be-39a6-11e8-8c00-c70b1a6586e8.png)

The progress bar for media seems to be getting cut off due to large images. So I don't know if it's something I can tweak, or where those settings are.

I did already try clearing my browser cache to see if that would fix it, still nothing so far. I also just restarted the service, issue remains.

**Comment by Kazz3r24** [comment]
Once I get that fixed, I'll be 1000% satisfied and will certainly close the issue. Thanks again for all of your hard work! I'll need to brush up on my various coding languages so I can help out!

**Comment by jeremysherriff** [comment]
Wow, that's not looking right. What resolution is your monitor at?
Can you try taking your browser down to a window instead of full screen, and making it narrower? Does that seem to resize the bars and images?

I noticed when editing the code that some of the sizing is in "%" and some of it is in pixels. I'm guessing you have a screen size that is quite different to any of mine (I think mine are all 1920x1080) and some of the % width stuff is causing the image to stretch taller to compensate for the increased width.

I'll try replicate it but if you could let me know about your screen resolution & whether changing the browser window size helps, that would be great.

**Comment by jeremysherriff** [comment]
PS does it look OK with just one stream playing?

**Comment by Kazz3r24** [comment]
I will have to try it out and see how things look with one stream. My monitor and resolution are 1920x1080 as well. Thanks for looking into this!

**Comment by jeremysherriff** [comment]
@Kazz3r24 fyi I've been able to reproduce your situation. Seems it's totally different in Edge, IE, Chrome and Firefox. Different browser window sizes definitely contribute to it.

...fml..

**Comment by Kazz3r24** [comment]
LOL I'm sorry this has turned into a bit of a nightmare. I was able to get everything looking normal by shrinking my browser window down. Even with one stream going at full screen the issue remains. If there's anything I can do to help I am more than willing and capable.

Thanks for your efforts again!

**Comment by jeremysherriff** [comment]
OK fixed it. Stupid MS Edge is stupid, and I had to rewrite the whole thing to cater for one browser dong tables differently. :)

**Comment by Kazz3r24** [comment]
LOL I could have told your Edge is stupid :P, that's silly... should be standards for that. Either way, I'm going to close this ticket. I believe you've more than exceeded what I asked for and I'll know for sure once the pull request goes through and I update.
Thank you again for all of your efforts! It's so nice having just one tab open!

**Comment by jeremysherriff** [comment]
@Kazz3r24 just fyi the fixes have been merged in, so check for updates.

**Comment by Kazz3r24** [comment]
Perfect! Sure thing, I'll update as soon as I get a chance and get back to you. Thanks again!

**Comment by Kazz3r24** [comment]
Looks absolutely perfect now! Thank you guys so much for your efforts!
