### ISSUE TITLE
Deluge only shows a spinning wheel

### ISSUE THREAD

**Issue by samcro1967** [Hellowlol/HTPC-Manager#578]
### Reporting Issues:

To ensure that a I has enough information to work with please include all of the following information.

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**
- [ ] Version
"2f3e2f0fbec46a039e17628bee267cd8602dc2d8"

- [ ] Branch
master2

- [ ] Commit hash

- [ ] Operating system
Windows 10

- [ ] Python version
Python27

- [ ] What you did?
Added Deluge config.  Test button works successfully

- [ ] What happened?
Deluge tab shows spinning wheel and never loads

- [ ] What you expected?
Deluge tab to populate with current queue

- [ ] How can we reproduce your issue?

- [ ] What are your (relevant) settings?
Provided IP, port, enabled SSL, provided basepath, and password.  WebUI plugin is enabled in Deluge.

- [ ] Include a link to your **FULL** (not just a few lines!) log file that has the error. Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).
https://gist.github.com/osuhickeys/572da18a9d79b07ffffaaf164a982513

**Comment by samcro1967** [comment]
I noticed the test deluge button says successful with the SSL enabled and disabled.  Seems like there is an issue with this tab in general.  One way should work and the other should fail.  I see json errors on the log, but nothing else that jumps out at me.

**Comment by Hellowlol** [comment]
Ill take a look at this in couple of days.

**Comment by terdinglage** [comment]
I just wanted to add that I am experiencing the same issue.  This tab tests out as successful regardless of the settings used.  I thought it was an issue with my reverse proxy setup, until I saw this issue post.  I am using basic auth through a reverse proxy, and my direct URL works (https://username:password@mydomain/deluge) in a web browser, but I cannot get any combination of settings to work, they are result in the spinning wheel.

**Comment by samcro1967** [comment]
bump

**Comment by samcro1967** [comment]
Any update on this issue?

**Comment by Hellowlol** [comment]
I haven’t had time to work in this yet. I’m busy with irl stuff and other projects. If anybody wants to work on this they should.
