### ISSUE TITLE
Sonarr module and reverse proxy

### ISSUE THREAD

**Issue by needo37** [Hellowlol/HTPC-Manager#58]
When HTPC-Manager and Sonarr are configured behind a reverse proxy the Sonarr link on the top of the  HTPC-Manager page does nothing but pull back up the HTPC-Manager homepage.

Next Aired also pulls up the HTPC-Manager homepage.

However clicking on a specific episode under Next Aired does pull up the Sonarr module, but that is the only Sonarr page I can access.

**Comment by needo37** [comment]
Nevermind. I fixed it. It seems you need to set the webdir setting in the app itself not only on the command line.

**Comment by Hellowlol** [comment]
Nice to know! I only tested setting the webdir directly in sonarr webui
