### ISSUE TITLE
Plex Icons are blank

### ISSUE THREAD

**Issue by samcro1967** [Hellowlol/HTPC-Manager#580]
The icons on the Plax tab are not displaying.  Tried to uninstall PIL (via control panel) and installed pillow (pip install pillow).  hptc-manager service would not start.  Reverted back to PIL so the service would start.

[Do not see a line for this in the about tab] Version

[master2] Branch

[2f3e2f0fbec46a039e17628bee267cd8602dc2d8] Commit hash

[Windows 10] Operating system

[2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]] Python version

[Installed as per the wiki] What you did?

[Plex tab does not show icons] What happened?

[] What you expected?

[] How can we reproduce your issue?

[] What are your (relevant) settings?

https://gist.github.com/osuhickeys/a8bb6d11453f020f63ab98c6d551a867

**Comment by Hellowlol** [comment]
Fix your install. You get a import error in your logs.

**Comment by samcro1967** [comment]
The install of Plex, pil, pillow, or htpc-manager?

**Comment by Hellowlol** [comment]
pil / pillow. Pil/pillow isn’t required of the Plex module btw. Just disable it in Plex settings.

**Comment by samcro1967** [comment]
I uninstalled Pil from the control panel this time and installed pillow using "pip install pillow".  I think last time I uninstalled pil vis "pip uninstall pil".  I was able to get htpc manager to work and the icons are now updating.  That made the c module error disappear from the logs.
