### ISSUE TITLE
Radarr API v2 support

### ISSUE THREAD

**Issue by incorpusyehtee** [Hellowlol/HTPC-Manager#587]
### Reporting Issues:

To ensure that a I has enough information to work with please include all of the following information.

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**
- [x] Version
d1b4fe4bd5da3dd76b23a8b6825d217b03b1701b

- [x] Branch
master2

- [x] Commit hash
d1b4fe4bd5da3dd76b23a8b6825d217b03b1701b

- [x] Operating system
Windows-10-10.0.14393

- [x] Python version
2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]

- [x] What happened?
Adding films fails with an error response from `http://localhost:8085/radarr/Lookup/` + search string saying that nothing was found. Dropdown box presents one option: "undefined (undefined)"
- [x] What you did?
Installed the latest Radarr (or any version since ~July of 2017)

- [x] What you expected?
This dropdown should probably have at least one option for a valid film title like "Film Name (2099)".

- [x] How can we reproduce your issue?
Use a recent version of Radarr and enable/configure it in the settings.

- [x] What are your (relevant) settings?
Radarr, no reverse proxy, no alternative base path.

**Comment by islanddog** [comment]
After much Googling I am glad somebody posted this issue. I am utilizing Openflixr which comes pre-bundled with Sonarr, Radarr and HTPC Manager and this issue is apparent only with Radarr.

**Comment by incorpusyehtee** [comment]
I will probably do a PR to fix Radarr API v2 support in this project, I have been learning Python/CherryPy/this project for the last few days so that I can patch it and some other minor things.

**Comment by islanddog** [comment]
Awesome. I have my entire Media Manager working with OpenFlixr with the single exception of Radarr lol. You will be my hero.

**Comment by incorpusyehtee** [comment]
Hi, sorry I forgot about this thread.

The issue with "undefined (undefined)" can be fixed with the following. In `/modules/radarr.py` change this:

    @cherrypy.expose()
    @require()
    @cherrypy.tools.json_out()
    def Lookup(self, q):
        return self.fetch('Movies/lookup?term=%s' % urllib.quote(q))

to:

    @cherrypy.expose()
    @require()
    @cherrypy.tools.json_out()
    def Lookup(self, q):
        return self.fetch('movie/lookup?term=%s' % urllib.quote(q))

And the two functions below it are "addMovie" and "test", change both the `self.fetch('Movies` to `self.fetch('movie`

And close and re-start the HTPC-Manager script. I was/am working on a more complete overhaul of HTPC-Manager to reimplement the Radarr features and try to make them nice like Couchpotato's support was (though CP sucks)

**Comment by jeremysherriff** [comment]
Guys I see this issue was closed without an actual fix in the code (just the examples above).  I can open a pull request with these changes if you want?

**Comment by Hellowlol** [comment]
Feel free
