### ISSUE TITLE
Sickrage improvement: show subtitle language 

### ISSUE THREAD

**Issue by kooimens** [Hellowlol/HTPC-Manager#59]
I'm using dutch (primary) and english (secondary) as subtitles languages. Right now, you can only see if subtitles are available. It does not show the actual language(s).

**Comment by Hellowlol** [comment]
I can't remember if the api returns the language but it should be easy to add if it does

**Comment by kooimens** [comment]
Ok! Any idea where I can find the api docs for sickrage? I can't find it...

**Comment by Hellowlol** [comment]
There isnt any other then /apibuilder or source code.

**Comment by Hellowlol** [comment]
https://github.com/Hellowlol/HTPC-Manager/blob/master2/interfaces/default/js/sickrage_view.js#L162

**Comment by Hellowlol** [comment]
Added a popover to the icon :)

**Comment by kooimens** [comment]
Nice!
