### ISSUE TITLE
Radarr undefined selection

### ISSUE THREAD

**Issue by reaperofpower** [Hellowlol/HTPC-Manager#592]
### Reporting Issues:

To ensure that a I has enough information to work with please include all of the following information.

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**
- [ ] Version
master2

- [ ] Branch
Master2

- [ ] Commit hash

71ae0fae769ac3111841e5b15f9c90a97c1efc95
--

- [ ] Operating system
Linux-4.10.0-30-generic-x86_64-with-Ubuntu-16.04-xenial

- [ ] Python version
2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609]

- [ ] What you did?
added radarr and tested connection (green check) tried to add movie

- [ ] What happened?
movie name came back as undefined
https://i.imgur.com/SyjyLsA.png

- [ ] What you expected?
movie added to radarr

- [ ] How can we reproduce your issue?
add movie name then click add

- [ ] What are your (relevant) settings?
default

- [ ] Include a link to your **FULL** (not just a few lines!) log file that has the error. Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).

Close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.

#### Link to log: https://gist.github.com/reaperofpower/3661e9cf1f6c0ebe17c4ad5fbf5e6210

**Comment by reaperofpower** [comment]
#591

**Comment by jeremysherriff** [comment]
lol sorry i broke #591 while cleaning up my branches.
Resubmitted as part of #590
