### ISSUE TITLE
Ombi module

### ISSUE THREAD

**Issue by jeremysherriff** [Hellowlol/HTPC-Manager#593]
Hey folks, has anyone coded up a custom HTPC module for Ombi v3?

I see Ombi has an API interface so could have it's own top-bar section and custom/themed module page, with functionality pretty similar to the CouchPotato "Movies" page - search/request new content, approving or rejecting requests, forcing refreshes of Plex/Emby content, could even go as far as checking and responding to issues.  The request API call itself has filtering options to tie in with the HTPC global filter field.

If anyone has done (or even just started a basic framework) for this, I'd be keen to get a copy of the files, and collaborate on extending features and merging it into the master HTPC code base on Github so that everyone can benefit.

**Comment by jeremysherriff** [comment]
@Hellowlol I'm having issues with my new module for Ombi.  The 'test' function of the settings page always fails, despite the actual target page working fine.  In fact, it seems like the 'test' is never actually called when the button is pressed.  My best guess is that I need to add the module into another location for the test to succeed (like we add the module into Htpc.py).

I don't even get an entry in the log when I hit 'test' but everything works as expected when I browse to http://localhost:8585/ombi/ping - I get a log message, and I get the expected html displayed.

There's two functions, currently it's set to ombi/ping which will fetch an unauthenticated response.

I can change the test link from 'ombi/ping' to 'radarr/Version' or basically any other endpoint, everything works except my page. Yet the page is absolutely working...

I have pushed through to my repo, would you be able to take a look and see if you spot anything?
It's in 'master3' here: https://github.com/jeremysherriff/HTPC-Manager/blob/master3/modules/ombi.py

Any help would be much appreciated!

**Comment by Hellowlol** [comment]
Dunno why the test button doesnt work. Tried to control f5? You should also use htpc.py --dev to enable debug mode.

**Comment by jeremysherriff** [comment]
Log level is at debug (same same) but it's never writing the debug entries for that endpoint unless I specifically hit it in my browser - just calling it from the test button it never fires. Weird.

I'll carry on, maybe I'll work it out as I develop the other endpoints and action buttons.
Am doing it for a mate despite no on else showing any interest.

**Comment by Hellowlol** [comment]
--dev option enables other things to like traceback in the webui.

**Comment by jeremysherriff** [comment]
Oh cool thanks

On 10/08/2018 7:48 AM, "Hellowlol" <notifications@github.com> wrote:

--dev option enables other things to like traceback in the webui.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Hellowlol/HTPC-Manager/issues/593#issuecomment-411875364>,
or mute the thread

**Comment by jeremysherriff** [comment]
The answer is that the 'test' button calls a POST (I assumed it was a GET) so I have to declare **kwargs in the function definition.  My testing via browser to the url was of course a GET which is why it worked.  It was Chrome's console that eventually exposed my issue :)

**Comment by Kazz3r24** [comment]
If the Ombi module is working, any chance it'll be merged with the current build so I can get my hands on it? It's the only thing I'm missing with my configuration.
Cheers!

**Comment by Hellowlol** [comment]
I would be willing to merge it if I got a pr

**Comment by Kazz3r24** [comment]
I was about to submit one, I just took a quick peek at his repository -  doesn't appear that the module is fully working (or his comments aren't up-to-date. Also specifically states not to merge with yours. I'll leave it in their hands.
[https://github.com/jeremysherriff/HTPC-Manager/tree/master3](url)
It would be an awesome feature to add in though!

**Comment by jeremysherriff** [comment]
Hi guys

I'm not happy enough to call it "working" so I won't be raising a pull
request to the original repo yet. None of the buttons on the Requests page
actually work and there's no TV components yet, but it is actually
functional.

I posted a list of features that are working and not working here:
http://www.openflixr.com/forum/discussion/505/ombi-module-for-htpc#latest

If you're keen to run it as is, then you can change your HTPC repo to my
fork + branch which would then stay up to date as I work through it. Maybe
even help me out a bit with testing and coding?

Just use the master3 branch, the one called Ombi isn't anything and I'll
clean it up soon.

The comment about not pushing to Hellowlol is regarding the one commit for
the updater so that others can use my repo and the auto update feature
without it switching back to the original repo every time. It really just
means I have to cherry pick commits to put in a pull request.

**Comment by jeremysherriff** [comment]
Not sure how well this screenshot will come out as it's a compilation of screenshots in a Word doc and then screenshot again :smile:

I'm getting closer, the Movies content pages are fully functional!
See above post if you want to actually run this on your setup.
I do need testers, ideally someone who has dozens if not hundreds of requests, as I have questions over performance with bigger table loads.
Movies: Suggestions, Search, 'Similar', and Request features all working for Movies
Movies: Requests page functions all complete: Approve, Deny, Remove, Mark Available/Unavailable
The Filter box filters on all Ombi fields (dates, statuses, requesters as well as titles)
Common: Plex and Emby sync functions. Grays-out Emby or Plex sync options if they're not configured in Ombi.
(i) hover with plot summary
Mobile views all work, column sizing re-flows down pretty good.  That is why the release-date/status and request-date/requester columns have been merged (disclaimer: breaks descending-order table sorts for those columns)
Still to-do for first release:
TV Shows: Create using Movies pages as base, fix-up equivalent functions
(TV features may be somewhat reduced - Request feature for TV content is complex!)
Delay table content load until the tab is clicked, or add a easy refresh button that maintains table-sort order for each tab
Longer-term plans:
Add Lidarr/music content support (it's in development in Ombi right now)
Figure out a way to re-enable descending-order sorts on the merged date/text columns
Re-work table framework to use a 2-stage loading process to get richer information, get more accurate 'Available' status (apparently this is how Ombi itself works too) (big performance drop though, hence Ombi's orange progress line at top of page)

![image](https://user-images.githubusercontent.com/1082213/44653405-c6857a80-aa42-11e8-9e59-b65ab8cbf2e6.png)

**Comment by Kazz3r24** [comment]
Forgive me, I literally just woke up to this. I'd be willing to be a guinea pig for you. I literally just had 6 requests come in. I typically have 10 streams going at a time, and I push Ombi on my streamers so they are VERY active lol. Just getting a coffee, then I'll read the above in greater detail.

**Comment by Hellowlol** [comment]
my god, what theme are you using?

**Comment by Kazz3r24** [comment]
It was a little hard to look at after first opening my eyes :P, but all good.  jeremysherriff where would you like feedback to be posted, and issues? I am having one with Ombi, but I don't want to litter this thread as it's technically unrelated (not in his repo).
Cheers!

**Comment by jeremysherriff** [comment]
hah sorry @Kazz3r24 the theme is 'Candy' it's so that I don't mistake my dev environment for my prod environment :smile:
Throw comments and issues into my git, that way I'll be able to reference them as I commit/close etc.
I'll start a 'feedback' thread, start new ones yourself for specific issues.

**Comment by jeremysherriff** [comment]
Am very close, have finally got a TV request to actually work.
I'll likely be raising a PR today some time to include a functional Ombi module into the master2 branch 😄

**Comment by jeremysherriff** [comment]
PR raised: #597 
Bugs etc should be raised over at https://github.com/jeremysherriff/HTPC-Manager/issues for now

**Comment by jeremysherriff** [comment]
This is now in the main `master2` branch and has been through a couple of bugfixes.
Any further bugs should be raised as per normal issues at https://github.com/Hellowlol/HTPC-Manager/issues
