### ISSUE TITLE
Recent Movies Plex Dashboard Not Updating

### ISSUE THREAD

**Issue by goku-son** [Hellowlol/HTPC-Manager#595]
### Reporting Issues:

To ensure that a I has enough information to work with please include all of the following information.

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**
- [ 6734237c2959f5979219510a4d9a206565e037b9] Version

- [ ] Branch
Master2

- [ ] Commit hash

6734237c2959f5979219510a4d9a206565e037b9
- [ ] Operating system

Windows-10-10.0.14393

- [ ] Python version
2.7.12 (v2.7.12:d33e0cf91556

- [ ] What you did?
Trying to view Plex Recent Movies and TV Shows on dashboard. 

- [ ] What happened?
These two sections are not updating and been showing the same recent movies and tv shows for several weeks now. 

- [ ] What you expected?
Expect the recent movies and recent tv shows to display the latest movies and tv shows. 

- [ ] How can we reproduce your issue?
Not sure. Was working fine for months then started to notice the issue. 

- [ ] What are your (relevant) settings?

- [ ] Include a link to your **FULL** (not just a few lines!) log file that has the error. Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).

Close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.

#### Link to log:

**Comment by jeremysherriff** [comment]
Recently Added is a list exposed via the Plex API, not calculated via the DateAdded data directly from the Plex database.
I believe your question needs to be directed to the Plex forums.

**Comment by goku-son** [comment]
Thanks, I can certainly check on the plex forums. The strange thing is that Plex and Tautulli both show current items for recently added movies and shows. It is as if HTPC is out of sync for some reason.

**Comment by goku-son** [comment]
Is there a way I can remove the plex info and reconfig that part? I tried removing and readding to the dash but the issue persists. Does HTPC manager have a DB I can try blowing away in the event that data is cached there?

**Comment by goku-son** [comment]
Checked on Plex forums and the feedback provided was that it is not a Plex issue since recently added movies and tv shows reflect correctly there and in Tautulli. The recently added music appears to be updating correctly in HTPC but not the movies or tv shows. 
Any other suggestions that I can try? Thanks in advance.

**Comment by goku-son** [comment]
I tried blowing away the HTPC database and starting all over.  I started with Plex first and noted the same issue recently added:

Music accurate
Movies not accurate
TV Shows not accurate 

The thing that is confusing to me is that Plex itself and Tautulli both show accurate recently added movies and tv shows. 

Not really sure where to try and look for the cause at this point. Everything else working just fine.

**Comment by jeremysherriff** [comment]
Your talking about the dashboard, right?  With the title 'Latest Movies' and the 5 images that scroll around continuously in the carousel?

**Comment by jeremysherriff** [comment]
The dash code is here: https://github.com/Hellowlol/HTPC-Manager/blob/6734237c2959f5979219510a4d9a206565e037b9/interfaces/default/js/dash.js#L340-L342
You can see it is a web request that pulls data from the HTPC Plex module.

The GetRecentMovies function is here: https://github.com/Hellowlol/HTPC-Manager/blob/6734237c2959f5979219510a4d9a206565e037b9/modules/plex.py#L123-L133
Again you can see it is a web call, this time to the Plex instance itself.

None of this is cached, except by your browser maybe.

Note that the response to the GetRecentMovies module call is affected by your "Show watched" setting for the HTPC Plex settings.  So if you've watched your recent movies and then it will show you the 5 most recent "old" movies.

**Comment by goku-son** [comment]
@jeremysherriff that is exactly what I am referring to thanks for that info. The only plex related dashboard settings  I have are Show Plex recent movies/tv shows/music all set to yes. The strange thing is that the music shows up correctly. Do you happen to know if that is coming from a db table from plex? I guess that may be more of a question in the plex forums. Just a very bizarre issue. Thanks again for the help.

**Comment by jeremysherriff** [comment]
Yes it's coming from somewhere in Plex, but no idea where.  It's a call to the public API, you can craft the same call yourself using curl.

**Comment by goku-son** [comment]
I noticed when looking at the code before the GetRecentMovies function it calls cherrypy.  I am seeing these errors in the log:

2018-09-19 15:50:53	cherrypy.error	ERROR	[19/Sep/2018:15:50:53] ENGINE Set handler for console events.
2018-09-19 11:17:15	cherrypy.error.60820224	ERROR	[19/Sep/2018:11:17:15] HTTP
2018-09-18 10:18:18	cherrypy.error	ERROR	[18/Sep/2018:10:18:18] ENGINE Set handler for console events.
2018-09-17 23:58:48	cherrypy.error.65473280	ERROR	[17/Sep/2018:23:58:48] HTTP
2018-09-17 23:58:43	cherrypy.error.65473280	ERROR	[17/Sep/2018:23:58:43] HTTP
2018-09-17 23:58:35	cherrypy.error.65473280	ERROR	[17/Sep/2018:23:58:35] HTTP
2018-09-17 23:58:30	cherrypy.error.65473280	ERROR	[17/Sep/2018:23:58:30] HTTP
2018-09-17 23:58:28	cherrypy.error.65473280	ERROR	[17/Sep/2018:23:58:28] HTTP
2018-09-16 17:33:06	cherrypy.error	ERROR	[16/Sep/2018:17:33:06] ENGINE Set handler for console events.
2018-09-16 15:59:17	cherrypy.error.61569736	ERROR	[16/Sep/2018:15:59:17] HTTP

Could this be related to the issue I am seeing?

**Comment by goku-son** [comment]
No responses over on the Plex forums. Being that Tautulli pulls the correct recent movies and TV from Plex, is there a way to have HTPC pull that info from Tautulli and use it for its plex dashboard?

**Comment by jeremysherriff** [comment]
Are you SURE that this isn't related to the watched/unwatched filtering?
The setting on the Plex module page affects the content of the carousel on the dashboard.
This one here:
![image](https://user-images.githubusercontent.com/1082213/45924703-d10c3480-bf5a-11e8-8290-487df8314dee.png)

**Comment by goku-son** [comment]
That was exactly the problem!!! Totally overlooked that staring me right in the face!! Thanks for helping me with this issue @jeremysherriff!!

**Comment by jeremysherriff** [comment]
glad we got there in the end :)
