### ISSUE TITLE
No future episodes in Sonarr calendar on dashboard 

### ISSUE THREAD

**Issue by goku-son** [Hellowlol/HTPC-Manager#599]
### Reporting Issues:

To ensure that a I has enough information to work with please include all of the following information.

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**
- [ ] Version

- [ ] Branch
Master2 

- [ ] Commit hash

6734237c2959f5979219510a4d9a206565e037b9
- [ ] Operating system

Windows 10
- [ ] Python version
2.7.12

- [ ] What you did?
Selected Show Sonnar and Show Sonarr calendar in settings so they are displayed on the dashboard. However, even though the Sonarr calendar shows up correctly the Show Sonarr section shows up correctly but after displaying Next Aired it shows the following:

No future episodes in Sonarr calendar

- [ ] What happened?
No future episodes in Sonarr calendar

- [ ] What you expected?
That the message not be shown since I have the Sonarr calendar in the dash. If it must show then display the calendar since if I click on next aired it takes me to the Sonarr module and I can see I have future episodes in my calendar. 

![6e3439bc-6732-4fed-acee-9c31decbcd91](https://user-images.githubusercontent.com/20881936/45932342-2b4bcc00-bf40-11e8-9e2f-5e41e3708069.jpeg)

- [ ] How can we reproduce your issue?
Add Sonarr to the dashboard 

- [ ] What are your (relevant) settings?

- [ ] Include a link to your **FULL** (not just a few lines!) log file that has the error. Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).

Close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.

#### Link to log:

**Comment by jeremysherriff** [comment]
I have the same bug.  Looks like there is an error in code I pushed a few months back (commit 7af168d55eb5cc8302ccf350d35ef1bccdadb6e7 )

I'll see if I can fix it in the next few days.

**Comment by jeremysherriff** [comment]
@goku-son do you have any coding skills?  As you are active, it would be cool if you can also do some edits as there's not many people around that can/do for this project.

**Comment by goku-son** [comment]
@jeremysherriff thanks for the update on the bug. I unfortunately don’t have any coding skills but would be willing to try and learn but I suspect it would take me a while before I can contribute in any meaningful way. If you know of any good resources for a newbie let me know. Thanks!
