### ISSUE TITLE
Sabnzbd improvement: add date to history tab 

### ISSUE THREAD

**Issue by kooimens** [Hellowlol/HTPC-Manager#60]
The sabnzbd module is missing a history field. Will be better if the module shows the date and time of each download, just like all other modules do.

**Comment by Hellowlol** [comment]
What are you talking about? There is a history tab and it's awesome imo. Do you want a timestamp on each history item?

**Comment by kooimens** [comment]
Oeps. Got the first sentence wrong. It should be, the history tab is missing a date field. 
![1](https://cloud.githubusercontent.com/assets/3150962/6546805/61aac254-c5c2-11e4-870b-6532001f2de5.jpg)

All of the modules I use (couch, sickrage, headphones) start with the date of each history item. For consistency and completeness, the same information should be in place for the sab module.

**Comment by Hellowlol** [comment]
I agree, I have never thought about that.. I'll add it

**Comment by Hellowlol** [comment]
Fixed

**Comment by kooimens** [comment]
That's quick, again... Thank you.
