### ISSUE TITLE
Sonarr calendar: Upcoming episodes show up as red

### ISSUE THREAD

**Issue by goku-son** [Hellowlol/HTPC-Manager#601]
### Reporting Issues:

To ensure that a I has enough information to work with please include all of the following information.

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**
- [ ] Version
2a178b3784ba49e0c2d6abe224e09e2a77f559b8

- [ ] Branch

Master2
- [ ] Commit hash
2a178b3784ba49e0c2d6abe224e09e2a77f559b8

- [ ] Operating system
Windows 10

- [ ] Python version
2.7.12

- [ ] What you did?
Viewed the Sonarr calendar on the dashboard.  

- [ ] What happened?

All calendar entries show up red. 
- [ ] What you expected?
Expect the calendar to reflect the same colors as the Sonarr calendar. Based on the Sonarr calendar:
![9f6d19a0-5776-4bb1-abc2-f342922536d0](https://user-images.githubusercontent.com/20881936/45988812-5c122b00-c03e-11e8-8109-923208a9342b.jpeg)

I noticed that future episodes as always listed as red (missing) until they are downloaded at which point they turn green.  They should list as blue (unaired) so as to not mistakenly think that they are missing. It would be nice if all of the colors above matched, but at least fixing future episodes to show blue vs red would be enough.  Not sure if this is a bug or something on my end. 

- [ ] How can we reproduce your issue?

View upcoming episodes on dashboard and/or in Sonarr module. 
- [ ] What are your (relevant) settings?

- [ ] Include a link to your **FULL** (not just a few lines!) log file that has the error. Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).

Close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.

#### Link to log:

**Comment by jeremysherriff** [comment]
There are limitations to the colour names provided by the bootstrap themes.  There is only "default" (blue), "info" (purple), "success" (green), "warning" (orange) and "important" (red) to choose from.
This is not a bug.

**Comment by goku-son** [comment]
Thanks for the insight on the color scheme. 
Should upcoming episodes though show the blue color scheme “default” vs red “danger”? I am seeing red for upcoming and only after they are downloaded do I see them change green.

**Comment by Hellowlol** [comment]
I selected the colors since we have too many themes. Cba with adding a decent color for every theme.
