### ISSUE TITLE
couchpotato: auto fill quality profile if only one profile is available

### ISSUE THREAD

**Issue by kooimens** [Hellowlol/HTPC-Manager#61]
I make use of only one quality profile in couchpotato. It's called `Best`. When I add a movie through the couchpotato module within HTPC-Manager, it doesn't select this quality profile by default, instead the field is left blank.

![1](https://cloud.githubusercontent.com/assets/3150962/6547228/72798fd8-c5d2-11e4-89f9-3ce560a0f70b.jpg)
![2](https://cloud.githubusercontent.com/assets/3150962/6547229/75406ca0-c5d2-11e4-8578-3e1c8e1d9f53.jpg)

**Comment by Hellowlol** [comment]
Works fine here.. Let me guess IE?

**Comment by kooimens** [comment]
That's weird. It's working fine on chrome and safari. Tests with IE and Firefox fail, field is left blank.

**Comment by Hellowlol** [comment]
Okei, i just tested with IE and it works with 11.09600

**Comment by kooimens** [comment]
Damn, I'm using same version here: 11.0.9600.17633

**Comment by Hellowlol** [comment]
I cant seems to get this right, i have been trying for over 3 hours... i just dont care, ff and ie sucks anyway. lol

**Comment by Hellowlol** [comment]
fixed
