### ISSUE TITLE
Don't see SMART data in Dashboard

### ISSUE THREAD

**Issue by PrzemekSkw** [Hellowlol/HTPC-Manager#617]
### Reporting Issues:

To ensure that a I has enough information to work with please include all of the following information.

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**

BRANCH | master2
Current commit | 13f179597fbe0ef6cfdb382bef7204e00737fa10
OS | Dietpi, Linux-5.4.72-v7l+-armv7l-with-debian-10.6
Python version: | 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
- [ ] What you did?
I try to install smartmontools but I have it already and it works.

- [ ] What happened?
I have checked smart data in settings as `YES` but have info in dashboard: `S.M.A.R.T not correctly configured.' There's noting to configure in settings.

- [ ] What you expected?
to see smart data for my external USB HDD. I see it in my serwer:
```
smartctl 6.6 2017-11-05 r4594 [armv7l-linux-5.4.72-v7l+] (local build)
Copyright (C) 2002-17, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Toshiba P300
Device Model:     TOSHIBA HDWD130
Serial Number:    X9CJT9MAS
LU WWN Device Id: 5 000039 fe6f1e7b5
Firmware Version: MX6OACF0
User Capacity:    3 000 592 982 016 bytes [3,00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    7200 rpm
Form Factor:      3.5 inches
Device is:        In smartctl database [for details use: -P show]
ATA Version is:   ATA8-ACS T13/1699-D revision 4
SATA Version is:  SATA 3.0, 6.0 Gb/s (current: 3.0 Gb/s)
Local Time is:    Thu Nov 12 22:58:01 2020 CET
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
```

#### Link to log: [https://paste.gnome.org/p7skvpizd](https://paste.gnome.org/p7skvpizd)

Regards, Przemek.

**Comment by cooperdk** [comment]
This app is outdated. Not much else to say.
It doesn't even support Python 3 (just like the app it's forked from).

**Comment by Hellowlol** [comment]
This app has already been ported to python 3 https://github.com/HTPC-Manager/HTPC-Manager
