### ISSUE TITLE
sab history tab 12h time instead of 24h

### ISSUE THREAD

**Issue by kooimens** [Hellowlol/HTPC-Manager#66]
Sabnzbd history within HTPC-Manager shows this:
![1](https://cloud.githubusercontent.com/assets/3150962/6584511/3adad85c-c76c-11e4-9177-e9b051202660.jpg)

In sab it's like:
![2](https://cloud.githubusercontent.com/assets/3150962/6584524/4a510efa-c76c-11e4-9f76-fba08ff04fa2.jpg)

**Comment by Hellowlol** [comment]
Changed to 24 hours format.

**Comment by kooimens** [comment]
Hmm. The time is now completely different from what sab is showing:
![1](https://cloud.githubusercontent.com/assets/3150962/6586174/cb31469c-c777-11e4-89c9-a4d4f1162325.jpg)
![2](https://cloud.githubusercontent.com/assets/3150962/6586176/cdf3a730-c777-11e4-8ccf-3aceb19af60f.jpg)

**Comment by kooimens** [comment]
It seems to be fixed.
