### ISSUE TITLE
S.M.A.R.T and Temperatures

### ISSUE THREAD

**Issue by wmariz** [Hellowlol/HTPC-Manager#69]
What about retrieving HD's and System temperatures and SMART data?

I'm not a python programer, but I've done some research and found this pages that looks useful.

http://www.stavros.io/posts/monitoring-your-systems-temperatures-python/
https://pypi.python.org/pypi/pySMART/0.2
http://louwrentius.com/tag/smartctl.html

Hope some one could implement this on the stats page.

Thanks and congratulations for the excelent work.

**Comment by Hellowlol** [comment]
Hi. I'm mainly developing for windows (and making sure that's working on other platforms) it isn't likely a mix only feature. I do love your idea!

**Comment by wmariz** [comment]
I would like to help testing on other platforms, but unfortunately I am using windows as well.

I believe that these links may also be useful, especially the last one:

https://pypi.python.org/pypi/PySensors/
https://pypi.python.org/pypi/Glances/
https://github.com/artsalliancemedia/system-monitor (The system temps are also read (Windows: using WMI from Open Hardware Monitor, Linux: using pysensors)

Best regards

**Comment by Hellowlol** [comment]
Thanks for the links, ill check it out.

**Comment by Hellowlol** [comment]
Wow, there is a webserver in that openhardwareinfo. So you you go to http://ip:port/data.json you get all the good stuff there :D

**Comment by wmariz** [comment]
Great! And it works on linux and windows, so could be one unique implementation for both.

Also, smartmontools runs on both platforms, so you can grab SMART data from it.

**Comment by Hellowlol** [comment]
@wmariz Just a little preview. http://i.imgur.com/hw0sV6F.png?1

**Comment by Hellowlol** [comment]
![image](https://cloud.githubusercontent.com/assets/1214134/6648339/dc5b11c4-c9d8-11e4-88a3-5496d2b0a10f.png)

**Comment by wmariz** [comment]
As I said before, I'm not a python program, but this made me try to learn. (i'm actually a lawyer, with some php experience).

I was trying to implement it but, looks like you are way ahead. So, I will start to try something on the S.M.A.R.T side.

Take a look at my pull request, was my first python code.

Best Regards


![hwmon](https://cloud.githubusercontent.com/assets/11435639/6648712/f23ebcc4-c9bb-11e4-9f8e-5d6db5a128e5.png)

**Comment by Hellowlol** [comment]
Yeah, just browsing your code it looks good. I just broke the damn thing so I'm gonna have to fix that first.

**Comment by Hellowlol** [comment]
@Snipees just pinging you as you had a request regarding monitor
