### ISSUE TITLE
newznab password -1 or none?

### ISSUE THREAD

**Issue by kooimens** [Hellowlol/HTPC-Manager#74]
What does the -1 mean? It's prob a password protected nzb, but it should not be shown this way?
![10](https://cloud.githubusercontent.com/assets/3150962/6639467/43afb65c-c990-11e4-9cd4-477b20db2d6a.jpg)
![11](https://cloud.githubusercontent.com/assets/3150962/6639468/43b25c0e-c990-11e4-937e-8899480333c7.jpg)

**Comment by Hellowlol** [comment]
I have no idea, i have only seen noen before.

**Comment by kooimens** [comment]
Ok, I will try to fix it in my newznab age branch
