### ISSUE TITLE
IMPORTANT please read: Bug in updater

### ISSUE THREAD

**Issue by Hellowlol** [Hellowlol/HTPC-Manager#78]
There was a bug in the updater, so pressing check for update would fail no matter what. This issue has now been resolved.

To update to the last commit use one of the following options.
1. Use force update from the settings page
2. Update manually via git
3. Download source manually

**Comment by Hellowlol** [comment]
Has anyone else experienced this?

**Comment by ohbarnes** [comment]
I am seeing the same issue.  Always returns an "Already running the latest version" message despite updates in the master2 branch.  It was working fine a week or 2 back (sorry can't remember exactly when at changed for me).

**Comment by Hellowlol** [comment]
@ohbarnes thanks for confirming this issue.

**Comment by Hellowlol** [comment]
@ohbarnes This issue should now be resolved.

**Comment by ohbarnes** [comment]
Confirmed that latest changes in master2 branch prompted an update via "Check for updates".  Thanks for fixing so quickly.
