### ISSUE TITLE
Torrent Search no results gives no feedback

### ISSUE THREAD

**Issue by Morphy99** [Hellowlol/HTPC-Manager#79]
When searching for a torrent and no results can be found there is just a "working" symbol. It would be much more helpful to display "no results" to the user. Also I get this error in log:
cherrypy.error.55007944	ERROR	[15/Mar/2015:15:59:20] HTTP Traceback (most recent call last):

**Comment by Hellowlol** [comment]
Was that after your searched? Cus it always like that on startup. What provider was this and what did you search for?

**Comment by Morphy99** [comment]
I have KAT and YTS enabled

**Comment by Hellowlol** [comment]
Ok, thanks

**Comment by Morphy99** [comment]
And yes its after a search. I did "this is a test s03e01" for example and waited ten seconds then clicked log

**Comment by Hellowlol** [comment]
Thanks, should be fixed in the last commit
