### ISSUE TITLE
Computer Stats

### ISSUE THREAD

**Issue by Madseason41** [Hellowlol/HTPC-Manager#88]
I can't enable computer stats. I have psutil installed, but the web ui does not allow me to select the enable tic box, it just shows a red circle with line through it. Any idea on how to troubleshoot this?

Running ubuntu 14.10.

Thanks

**Comment by wmariz** [comment]
Try to update to last commit. This was fixed.

**Comment by Hellowlol** [comment]
@Madseason41 does it work after update?

**Comment by Madseason41** [comment]
Latest update seemed to do the trick. Thanks
