### ISSUE TITLE
Load "other apps" in same tab or within htpc

### ISSUE THREAD

**Issue by kooimens** [Hellowlol/HTPC-Manager#90]
As I'm having a lot of other apps (owncloud, subsonic, mail etc.) I would like to have the ability to load these apps in the same tab as my htpc is running at that time or, even better, load the app within htpc. I mean load the base with the custom app underneath it. 

If you like the idea, please let me know. Then I will give this a try. I already tried some things. The use of an iframe will probably do the trick. If you know a better solution, let me know.

**Comment by Hellowlol** [comment]
Im not really a fan of iframes.. I think opening a a new tab is the cleanest approch, however if you find a ok way to do both ill merge it.

**Comment by Hellowlol** [comment]
Closing this and waiting for a pr ;)
