### ISSUE TITLE
Undefined for all links

### ISSUE THREAD

**Issue by Outcats** [Hellowlol/HTPC-Manager#96]
•Branch 
Master2

•Commit hash 
unknown

•Your operating system and python version 
Windows 8.1 / python 2.7.7

•What did you do? 
Add Plex, CouchPotato etc 

•What happened? 
Added and verified without issue, the links at the top state "Undefined" instead of a clickable link. If you add several it just looks like:

"UndefinedUndefinedUndefinedUndefinedUndefinedUndefined" across the top.

•What did you expect to happen? The clickable link to appear like in the master branch (I used the original first, and switched to yours when I found it has more options, the original version worked as intended.)

•If its a visual bug, screenshot or it didnt happen!
![wp_ss_20150324_0001](https://cloud.githubusercontent.com/assets/11628565/6801760/c00e26bc-d222-11e4-89d8-b4e4e0c17966.png)

•What browser, including version 
Internet Explorer 11, but it worked fine in Firefox 36.0.4

•Link to a copy/paste of your logfile with clear debug info of the error on PASTEBIN 
http://pastebin.com/wFKKJC0e

**Comment by Hellowlol** [comment]
Thanks you for making a proper issue! I think your the fist one
I dont know if @wmariz tested reorder Menu on ie. I didn't. 

Honestly I getting tired of doing special things just for IE. 

@wmariz do you have idea what might be the cause of this?

Thanks for reporting this. Until this issue is resolved use a proper browser ;)

**Comment by Hellowlol** [comment]
@Outcats what is the menu_order? You can find it in one of the script tags

**Comment by Outcats** [comment]
script>
    Menu = {}
                 Menus['nav-plex'] = '<li class="nav-menu-item" id="nav-plex"><a href="/plex/>Taylor-FX</a></li>;
    Menu_order = "0";
</script>

**Comment by Hellowlol** [comment]
Tried force refresh the browser? I cant seem to reproduce your error. It works fine here (win 7 ie 11.0.9600.17501)

Can you copy out the entire script tag where you find menu_order?

**Comment by Outcats** [comment]
I can't paste the code into the message box so I put it in a paste bin:

http://pastebin.com/Tn1gVQHC

**Comment by Hellowlol** [comment]
Can you use the force update option in the settings page and try again? just to be sure.

**Comment by Outcats** [comment]
Did a force update from settings, as well as a force refresh, and a restart of IE. I've also restarted HTPC Manager from settings and still "undefinedundefinedundefinedundefinedundefinedundefinedundefined"

**Comment by Hellowlol** [comment]
OK, can have the full version number of your IE, need to fire up a vm..

**Comment by Outcats** [comment]
Version: 11.0.9600.17690

![capture](https://cloud.githubusercontent.com/assets/11628565/6810448/a4be5036-d258-11e4-9dbb-b8d277e60ca6.PNG)

**Comment by wmariz** [comment]
I wasn't able to reproduce that.

**Comment by kooimens** [comment]
Just pulled the new commits. Dash looking good! Great work. I've got the same problem when I use IE. 
![1](https://cloud.githubusercontent.com/assets/3150962/6832368/4ac4747e-d326-11e4-8d0e-18c15e4709d2.jpg)

Let me know if you need more info.

**Comment by Hellowlol** [comment]
@kooimens what os version?

**Comment by kooimens** [comment]
Windows 7 Ultimate SP1 x64 EN-US Oct. 2014

**Comment by wmariz** [comment]
It just happens on new installations, I will try to fix

**Comment by wmariz** [comment]
Is not only on new installations.

I've made a pull request that fix it.

**Comment by Hellowlol** [comment]
@Outcats @kooimens Can you update and comfirm that latest update resolves your issue.

**Comment by Outcats** [comment]
Hi, just did the update and now it displays all my tabs now, thanks!

(I have noticed that if the page isn't full screen they all disappear and it is just a blank black bar though.)

**Comment by Hellowlol** [comment]
screenshot?

**Comment by wmariz** [comment]
I think it is because of the responsive layout for tablets and mobile phones, if the window is below certain width, the menu goes under the drop down menu on the right.

**Comment by Hellowlol** [comment]
Yeah, that was my thought as well :P

**Comment by Outcats** [comment]
Yeah, when I expand the menu it shows in the drop down. As far as I'm concerned this is fine and all issues my end resolved. :)
