### ISSUE TITLE
Torrent search not adding torrent to Deluge with kat

### ISSUE THREAD

**Issue by z1lt0id** [Hellowlol/HTPC-Manager#97]
I've setup torrent search to search through KickAssTorrents but when I click on send to Deluge a message comes up saying "Sending to Deluge" and then I go and check my Deluge torrent queue but nothing appears.  I have it working correctly as I can delete torrents and view them on HTPC but this feature doesn't seem to work.  I checked the logs and couldn't find anything regarding it.

**Comment by Hellowlol** [comment]
Have you tried any of the other providers? 

I just tried to add one now for htpc-manager and it didnt work. I copied that link to the deluge and tried to add it manually from webui. 

That didnt work, i dobled checked with a norbits, and it works fine there.

Seems that deluge webapi have a issue with link for kat (torcache)

**Comment by z1lt0id** [comment]
Ah I see I'll try another provider and see how it goes. Manually adding 
magnet links to the webui of Deluge works though still via KickAss.  
Thanks for the quick response.

**Comment by Hellowlol** [comment]
I havnt tried that but thats cool. The api htpc-manager uses atm does not support magnet links. (magnet addr isnt returned by the json api)

**Comment by Hellowlol** [comment]
Ill see if i can solve this a different way. (Download torrent locally then upload that torrent to deluge)

**Comment by z1lt0id** [comment]
That would work wonderfully if you can get HTPC to do that.

**Comment by Hellowlol** [comment]
Np. Its low priority so it might take some time.

**Comment by Hellowlol** [comment]
https://github.com/Hellowlol/HTPC-Manager/issues/19

**Comment by Hellowlol** [comment]
@z1lt0id 
Deluge works with kat now, i also added support for magnet. There is still some work that has to be done regarding the ui etc (dosnt exist in the module ui). But that have to be for some other time. 

Btw, you should try the new provider i added, i thiknk you will like it.

**Comment by z1lt0id** [comment]
Will do, I'll check it out now :)
